### ISSUE TITLE
Potentially replace the breadcrumb back button 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1002]
with something like this: https://d30y9cdsu7xlg0.cloudfront.net/png/46559-200.png

This actually depends on how @DinisCruz will make the breadcrumbs work (or not :) )

**Comment by romichg** [comment]
related to #955

**Comment by luchia** [comment]
We have an up arrow in the application already -

![screen shot 2015-09-17 at 8 11 01 am](https://cloud.githubusercontent.com/assets/4547737/9920036/4fc818b8-5d14-11e5-87c7-d903a1c2764a.png)

But for the time being, I've removed it so you can't see it (as per yesterdays meeting) -

![screen shot 2015-09-16 at 9 13 28 am](https://cloud.githubusercontent.com/assets/4547737/9892540/35c77d1c-5c53-11e5-8d35-930bf59e194a.png)

**Comment by romichg** [comment]
This will not be done as breadcrumbs are enough for nav.
