### ISSUE TITLE
HTML5 icon no longer shown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1003]
![selection_062](https://cloud.githubusercontent.com/assets/1326120/9925526/9aa5f70e-5cda-11e5-841b-17e858b1635c.png)

**Comment by romichg** [comment]
We seem to have lost it everywhere, in the filters in the gray box and in the metadata.

**Comment by luchia** [comment]
Got it -

![Uploading Screen Shot 2015-09-17 at 9.07.31 am.png…]()
![screen shot 2015-09-17 at 5 38 03 pm](https://cloud.githubusercontent.com/assets/4547737/9927551/e10478be-5d62-11e5-8684-58516be03876.png)

**Comment by romichg** [comment]
This is fixed. HTML5 is back :)
