### ISSUE TITLE
Word are broken into two lines in FF in Guides and full article view

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1008]
![selection_076](https://cloud.githubusercontent.com/assets/1326120/9936355/8e0534ac-5d29-11e5-8143-433a29ff5891.png)
![selection_075](https://cloud.githubusercontent.com/assets/1326120/9936358/9091b8da-5d29-11e5-8da5-2ac6598d7b74.png)

**Comment by luchia** [comment]
PR submitted. Fixed -

![screen shot 2015-09-18 at 7 21 41 am](https://cloud.githubusercontent.com/assets/4547737/9946346/fc3cd0a4-5dd5-11e5-9941-8c6f556f4402.png)

**Comment by romichg** [comment]
Right now we get words carried over in FF. Which is probably not the best solution. It works fine in Chrome.

![selection_005](https://cloud.githubusercontent.com/assets/1326120/10079970/ffbf512c-62ba-11e5-9554-12ef05b90372.png)

**Comment by luchia** [comment]
This has been fixed as well, please take a look.

**Comment by romichg** [comment]
Is there a new version? Seem like it is still doing it... 
![selection_001](https://cloud.githubusercontent.com/assets/1326120/10115913/53bafed2-63e9-11e5-9727-e4bd73024f0b.png)

**Comment by luchia** [comment]
![screen shot 2015-09-26 at 7 05 42 pm](https://cloud.githubusercontent.com/assets/4547737/10116751/e98f20da-6481-11e5-8a29-42c37ba00829.png)

Argh, sorry! I had to force this option (I didn't realise).

**Comment by romichg** [comment]
Yey.. fixed.
