### ISSUE TITLE
Guides articles are not ordered the way they are in the XML file

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1009]

**Comment by michaelhidalgo** [comment]
With Pull Request [https://github.com/TeamMentor/TM_Website/pull/26/files]

**Comment by michaelhidalgo** [comment]
hey @DinisCruz could you please merge this [https://github.com/TeamMentor/TM_Website/pull/26/files]

**Comment by michaelhidalgo** [comment]
This is working now : 

<img width="1439" alt="screen shot 2015-10-01 at 9 37 32" src="https://cloud.githubusercontent.com/assets/1732035/10225601/cf8424cc-6820-11e5-8e74-98ae47bb306c.png">

**Comment by romichg** [comment]
This is fixed.
