### ISSUE TITLE
Top Articles heading is shown twice, once where it shoudlbe the other all the way at the bottom

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1011]
![selection_078](https://cloud.githubusercontent.com/assets/1326120/9943741/465d5e36-5d51-11e5-8aa7-bf4552395e30.png)

**Comment by luchia** [comment]
PR submitted. Fixed -

![screen shot 2015-09-18 at 7 30 33 am](https://cloud.githubusercontent.com/assets/4547737/9946548/521d4002-5dd7-11e5-818f-4e0c08cb33d4.png)

**Comment by romichg** [comment]
This is fixed. We could use some bottom padding on the page though

![selection_008](https://cloud.githubusercontent.com/assets/1326120/10080213/65b3a04a-62bc-11e5-917a-bb82d6eb9a31.png)

**Comment by luchia** [comment]
![screen shot 2015-09-25 at 8 32 04 am](https://cloud.githubusercontent.com/assets/4547737/10088690/ebd6d0a4-635f-11e5-986a-0afe8f0fb7b6.png)

Fixed, in my PR today.

**Comment by romichg** [comment]
Yep done.
