### ISSUE TITLE
404 error for Jade Terms and Conditions

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#1012]
https://beta.teammentor.net/jade/misc/terms-and-conditions

**Comment by BendixSpring** [comment]
This is on the default page:  https://beta.teammentor.net/jade/guest/default.html

**Comment by romichg** [comment]
@BendixSpring are you using IE? Try it with FF or Chrome/Safari

**Comment by michaelhidalgo** [comment]
With Pull Request

**Comment by romichg** [comment]
I am not sure what happened, haven't tested Jade yet, but looks like you broke them on Flare :)

**Comment by michaelhidalgo** [comment]
Hmm. Can you please delete the cache, I just cloned a clean version and it works fine : 

![screen shot 2015-10-06 at 22 13 04](https://cloud.githubusercontent.com/assets/1732035/10328922/8ecb66ce-6c77-11e5-8ad4-7047e6d35867.png)

and here are the submodules , where only TM_Angular, TM_Jade and TM_Static should have been modified.

``````
Michael:Issue_1041 Michael$ git submodule
 4cc3a0c002fad180f86d32ccab22fc74998c675e build/TM_4_0_JSON_Data (4cc3a0c)
 4321dcc3823fd3abc0e5b910a1d8118ac61a215c build/TM_Gulp (heads/master)
 91eb7986387665fd6d3a74f43854233cfde11b17 code/TM_Angular (remotes/origin/Issue_1012_TermsAndConditions)
 967836881bea30fba84a0437ce69381c9e4a457c code/TM_Flare (4.0.3-327-g9678368)
 120056e6043656b86698ad46983041dd5aa89782 code/TM_GraphDB (4.0.1-36-g120056e)
 24de6de2987b4d395dfef318e663d75af5b203a6 code/TM_Jade (heads/Issue_1012_TermsAndConditions)
 c8406320efbbdb8986823fce6935499c0f7ae470 code/TM_Shared (remotes/origin/Dev)
 136af9e4f2286f3719f8856dd485c2ee66f92ae2 code/TM_Static (heads/Issue_1012_TermsAndConditions)
 9a3630c688797993dbe276ebf94eb97b3ffb3fec code/TM_Website (4.0.3-133-g9a3630c)
 7f6f1cad93bd9e6668ef9e0d0a06939df225bf76 config/SiteData_TM (remotes/origin/Dev)
 dd65a11bf320940d515c8e06870616a5ae8a03f1 data/Lib_Docs-json (heads/master)
 256c437c3cc25c33025918bf12d93ae42c011e22 data/Lib_UNO (remotes/origin/Beta)
 95e9f6fc9d672de1d36b4bf3d5026a12158d362a data/Lib_UNO-json (remotes/origin/Beta)
 921ea5e009deca34bc3b34fbd7e54ec746f0fa87 qa/TM_QA (4.0.1-34-g921ea5e)
Michael:Issue_1041 Michael$ ```
``````

**Comment by romichg** [comment]
Cache cleared, but doesn't seem to work. Works fine in Dev 

```
 4cc3a0c002fad180f86d32ccab22fc74998c675e build/TM_4_0_JSON_Data (4cc3a0c)
 4321dcc3823fd3abc0e5b910a1d8118ac61a215c build/TM_Gulp (heads/master)
+91eb7986387665fd6d3a74f43854233cfde11b17 code/TM_Angular (heads/Issue_1012_TermsAndConditions)
+967836881bea30fba84a0437ce69381c9e4a457c code/TM_Flare (4.0.3-327-g9678368)
 120056e6043656b86698ad46983041dd5aa89782 code/TM_GraphDB (4.0.1-36-g120056e)
+24de6de2987b4d395dfef318e663d75af5b203a6 code/TM_Jade (heads/Issue_1012_TermsAndConditions)
 c8406320efbbdb8986823fce6935499c0f7ae470 code/TM_Shared (heads/Dev)
+136af9e4f2286f3719f8856dd485c2ee66f92ae2 code/TM_Static (heads/Issue_1012_TermsAndConditions)
 c47364fe28232dc813c26c0ded0852e5096c5228 code/TM_Website (4.0.3-138-gc47364f)
 7f6f1cad93bd9e6668ef9e0d0a06939df225bf76 config/SiteData_TM (heads/Dev)
 dd65a11bf320940d515c8e06870616a5ae8a03f1 data/Lib_Docs-json (heads/master)
 256c437c3cc25c33025918bf12d93ae42c011e22 data/Lib_UNO (heads/Beta)
 95e9f6fc9d672de1d36b4bf3d5026a12158d362a data/Lib_UNO-json (heads/Beta)
 921ea5e009deca34bc3b34fbd7e54ec746f0fa87 qa/TM_QA (4.0.1-34-g921ea5e)
```

What happens is that I can't click on the terms and conditions link on the footer, and the link on signup page shows a blank page

**Comment by michaelhidalgo** [comment]
That's weird :), ok on Flare Signup, the link should be like this  `<a href="terms-and-conditions">Terms and Conditions</a>`

![screen shot 2015-10-06 at 22 30 01](https://cloud.githubusercontent.com/assets/1732035/10329129/03264dd4-6c7a-11e5-84a4-0a7fb570b0d1.png)

**Comment by michaelhidalgo** [comment]
Could you please do a manual checkout from code/TM_Angular , code/TM_Jade and code/TM_Static ?

**Comment by romichg** [comment]
So, at this point the Jade Terms and conditions, once logged in, still show the logged out nav menu
1. login to jade
2. open an article
3. click on terms and conditions

And an interesting condition happens (404 error) when:
1. login to jade
2. logout of jade
3. click on terms and conditions
this is a lot less importaint, so I am ok if we keep it as a bug for later.

**Comment by romichg** [comment]
this is fixed. Other issues are tracked in #1057 and #1058
