### ISSUE TITLE
Unable to view more than 250 articles

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#1015]
Search for the word "and"
![image](https://cloud.githubusercontent.com/assets/3578332/9946580/1dd638e6-5d62-11e5-8aa2-45f8ceab03d5.png)

I am unable to look at the next 250 results. Add a button that allows user to select the next bunch of articles.

Also for slow systems, it might take a while to load 250 articles.  If everyone could configure their search results (example:  25, 50, 100) (and many other features), it would enhance usability.

**Comment by romichg** [comment]
This is solved in Flare. Closing
