### ISSUE TITLE
Unlinked content makes the tool less helpful

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#1018]
This page has references to other articles that are important for understanding:
https://beta.teammentor.net/jade/article/2142c74362bc/Perform-a-Security-Design-Review

See "Web Application Security Design Inspections Questions". -- this should have links that point to the specific page.

**Comment by romichg** [comment]
This is now tracked https://github.com/TMContent/Lib_UNO/issues/469

Closing
