### ISSUE TITLE
Dropdown isnt styled properly (Safari) from Joe

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1022]
The dropdown isn’t styled properly in Safari. It looks more natural in chrome, so it might just be a safari issue. 

![screenshot 2015-09-17 13 30 21](https://cloud.githubusercontent.com/assets/1326120/9949473/23de4c1a-5d7b-11e5-8283-b466e5905b7b.PNG)

**Comment by luchia** [comment]
Fixed -

![screen shot 2015-09-18 at 11 49 41 am](https://cloud.githubusercontent.com/assets/4547737/9950203/674b54a4-5dfb-11e5-9119-af8ecbeb2a69.png)

**Comment by romichg** [comment]
This is fixed. Joe has confirmed.
