### ISSUE TITLE
Links with querries/serches shoudl redirect to login for non logged in users

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1023]
https://tmdev01-beta.teammentor.net/angular/user/index/query-00e5f2a398d2/query-5090bb51ad10

this should redirect to a login page, and then display the page upon successful login.

**Comment by romichg** [comment]
At the moment this redirects to the main page, so is anything that is under /angular/user/ 
I think the short way of fixing this would be to redirect everything under /angular/user to the login page for non-logged in users. Then redirect to the requested page, upon successful login. 
In an event that the requested page is bad, or doesn't exist we would then follow the current behavior and show an error page or a query not found page. 
Eventually it might be a good idea to validate for the format of a valid request under /angular/user so that requests like http://localhost:12345/angular/user/index/blah would show and error page. this is tracked in issue: #1061 and #1062

**Comment by michaelhidalgo** [comment]
With Pull request https://github.com/TeamMentor/TM_Website/pull/36

**Comment by romichg** [comment]
So two issues.
- [x] localhost:12345/ should not redirect to the login
- [x] after being redirected to the login and then after a successful login, the user should be redirected to the original link.  For example, if I am not logged in and go to http://localhost:12345/angular/user/index/search-xss___query-d43fe5882bcd/query-3e54c333d53a,query-670dbd0c22c7,query-89a417d8ce59 
  I should be redirected to the login, then after I login I should be redirected again to the page I was going for.  At the moment I am just being redirected to the index.

**Comment by michaelhidalgo** [comment]
Two Pull Request : 
1. TM_Angular https://github.com/TeamMentor/TM_Angular/pull/34
2. TM_WebSite https://github.com/TeamMentor/TM_Website/pull/36

**Comment by romichg** [comment]
This id done. Good job!
