### ISSUE TITLE
Looks like we have a nasty issue in IE

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1024]
![selection_001](https://cloud.githubusercontent.com/assets/1326120/9950807/b1497492-5d8c-11e5-8dd5-a871794fd4c0.png)

**Comment by luchia** [comment]
I tested this in both IE11 and IE Edge with no issues. I think this may have been fixed? Can you double check or let me know what browser you were using so I can try to recreate. TY.

**Comment by michaelhidalgo** [comment]
Assigning to me. to do some testing on SauceLabs

**Comment by michaelhidalgo** [comment]
It looks fine on Windows 10 IE 11 

![screen shot 2015-09-29 at 19 35 07](https://cloud.githubusercontent.com/assets/1732035/10182429/408cbf26-66e1-11e5-9552-043a3d1882dd.png)

And this is on Edge:

![screen shot 2015-09-29 at 19 39 52](https://cloud.githubusercontent.com/assets/1732035/10182476/ec622a98-66e1-11e5-959f-c033abbe2b23.png)

**Comment by romichg** [comment]
perfect, thanks closing.
