### ISSUE TITLE
Some versions of FF do not got to Flare

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1025]
Danny had an issue with this user agent 
Mozilla/5.0 (compatible)

**Comment by DinisCruz** [comment]
I will need more than that :)

Can Danny provide the full user agent

**Comment by romichg** [comment]
That is what he provided. Let me check again..
So Danny is using this http://chrispederick.com/work/user-agent-switcher/  and that is why we are not getting the right user agent :).
