### ISSUE TITLE
Clicking on TM logo no longer works in Jade

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1026]
![selection_079](https://cloud.githubusercontent.com/assets/1326120/9952413/3e5ea800-5da3-11e5-8009-f97eed8690f8.png)

looks like route to https://beta.teammentor.net/user/main.html is missing

**Comment by DinisCruz** [comment]
fixed

**Comment by romichg** [comment]
Clicking on It should go to the index page, now it goes to the search page..

**Comment by michaelhidalgo** [comment]
With PR [https://github.com/TeamMentor/TM_Jade/pull/27]

**Comment by romichg** [comment]
This is fixed.
