### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1027]
@luchia I think this one might be yours, if not send it to @DinisCruz to fix first thing in the morning.

![04](https://cloud.githubusercontent.com/assets/1326120/10007980/f33355fe-6097-11e5-94e0-e237003cea4f.png)

**Comment by luchia** [comment]
Template is there, it just needs to be routed. Assigning to Dinis.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_Angular/pull/20

**Comment by romichg** [comment]
Still not working actually @DinisCruz please help out.

**Comment by DinisCruz** [comment]
this should be working now with the small issue that we are doing the redirect to the login page after 2 seconds (where the Jade solution is better since it shows the login page with the 'your pwd was changed ok' message)

**Comment by romichg** [comment]
This is fixed. @michaelhidalgo will open a follow up issue to address the 2 seconds later.
