### ISSUE TITLE
Tables can be shown better

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1029]
https://beta.teammentor.net/angular/user/article/1f8046b8ad9d/Validate-Input-for-Length,-Range,-Format,-And-Type

![selection_001](https://cloud.githubusercontent.com/assets/1326120/10028858/d2c45912-613c-11e5-9fe3-83832ab88499.png)

**Comment by luchia** [comment]
![screen shot 2015-09-23 at 9 10 11 pm](https://cloud.githubusercontent.com/assets/4547737/10043575/8d5e9490-6237-11e5-8304-dd67349e33c5.png)

Do you like this? And more importantly, is there enough contrast on your screen?

**Comment by romichg** [comment]
Yes looks pretty good. The background can be a notch lighter. But overall pretty good!

**Comment by luchia** [comment]
![screen shot 2015-09-24 at 10 19 37 am](https://cloud.githubusercontent.com/assets/4547737/10062419/c82d1c18-62a5-11e5-9e0a-ae84b35d43ea.png)

Fixed

**Comment by romichg** [comment]
Perfect, lets put it in.

**Comment by luchia** [comment]
It is in :)

**Comment by romichg** [comment]
Looks good. closing
