### ISSUE TITLE
Client logos are not evenly spaced on homepage

### ISSUE THREAD

**Issue by yankola** [TeamMentor/TM_4_0_Design#1032]
<img width="745" alt="screen shot 2015-09-23 at 3 58 27 pm" src="https://cloud.githubusercontent.com/assets/12300809/10056996/f849c49a-620b-11e5-92e4-d9322f7ee2a7.png">

**Comment by luchia** [comment]
The new logos -

![screen shot 2015-09-25 at 10 47 05 am](https://cloud.githubusercontent.com/assets/4547737/10090455/fab6fc8a-6372-11e5-8f75-91bc8c67e4f5.png)

And in the browser -

![screen shot 2015-09-25 at 10 48 01 am](https://cloud.githubusercontent.com/assets/4547737/10090456/faba3f58-6372-11e5-8799-9316a804a97c.png)

**Comment by yankola** [comment]
The logos look great! Although they don't seem to be centered below the text "Our clients...". This might be due to the width of the browser and the responsive design? I'm not sure, but I wanted to point it out because I know you're always on point with aligning everything to the grid! :)

**Comment by luchia** [comment]
Good pick up :)

![screen shot 2015-09-25 at 11 27 14 am](https://cloud.githubusercontent.com/assets/4547737/10090910/732be2a2-6378-11e5-9cdc-fd83890b1ff6.png)

This will be in my PR today @roman87.

**Comment by yankola** [comment]
Perfect!

**Comment by romichg** [comment]
Looks good. @yankola can you just make sure it looks good to your eyes. It is on https://tmdev01-beta.teammentor.net (not on the beta site yet)

**Comment by yankola** [comment]
Yup! I approved already. See above ^. :)

**Comment by romichg** [comment]
alright cool.. closing.
