### ISSUE TITLE
SI logo should be complete in footer

### ISSUE THREAD

**Issue by yankola** [TeamMentor/TM_4_0_Design#1033]
I feel that we need to be using the entire SI logo in the footer rather than the solo lock. Not only will this keep our brand consistent, but it will create a stronger balance between both sides of the footer.

<img width="1113" alt="screen shot 2015-09-23 at 4 02 31 pm" src="https://cloud.githubusercontent.com/assets/12300809/10057100/87d8f52c-620c-11e5-92ed-2bacf5f3b62c.png">

**Comment by luchia** [comment]
I agree. I think we should revert back to Jade for this for consistency but also searchable text (SEO reasons). Instead of the logo, I propose text -

![screen shot 2015-09-24 at 9 21 05 am](https://cloud.githubusercontent.com/assets/4547737/10061604/9a3a9f22-629d-11e5-909c-8a192d69e978.png)

**Comment by romichg** [comment]
@yankola  what do you think?

**Comment by yankola** [comment]
I think it would be better to have the actual logo, but if we can't add a tag to it to help with searchable text, this works. I didn't see any mention of Security Innovation on the rest of the site so it might be our only option?

**Comment by luchia** [comment]
Good point :+1: 

![screen shot 2015-09-25 at 2 13 33 pm](https://cloud.githubusercontent.com/assets/4547737/10092951/aa89e926-638f-11e5-8bce-c0099b508e0a.png)

**Comment by yankola** [comment]
Looks great!

**Comment by romichg** [comment]
Done, closing.
