### ISSUE TITLE
Links in Docs are broken

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1037]
None of the links in the Docs are working.

**Comment by michaelhidalgo** [comment]
With Pull Request.

**Comment by romichg** [comment]
This is still not working.. Did clear my .tmCache

![selection_002](https://cloud.githubusercontent.com/assets/1326120/10254916/b153dc5a-6914-11e5-99d3-e261841e44bc.png)

Seems like the code here is not called:
https://github.com/TeamMentor/TM_Website/commit/68adbd00f42037687241c56f837d2fd302c7940b#diff-cf4178f140ff2be1143ea62bee47ef49R74

**Comment by michaelhidalgo** [comment]
I think is because PR are still open :) 

Fixing broken links on Doc pages. TeamMentor/TM_Angular#23
 Open
Fixing broken links on Docs pages. TeamMentor/TM_Flare#64
 Open
Fixing broken links on Docs pages TeamMentor/TM_Website#27
 Open
updating submodules. TeamMentor/TM#41

**Comment by romichg** [comment]
after a couple of small issues this is now all merged and fixed. good work!
Related remaining issues #1046 and #1045
