### ISSUE TITLE
Article per page changes back to default (10) after making another selection

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1042]
For example.
Select 20 articles per page, on the main screen, and then choose "Authentication" now only 10 articles are shown (even though the selector shows 20 articles)

**Comment by michaelhidalgo** [comment]
I see. But if you select another filter, should not you start with the default? otherwise it is more complex because if there are just 9 and the filter was 20?

**Comment by romichg** [comment]
Not sure why is it more complex? isn't it just a matter of showing the number of articles selected? and persisting that?  If there are less articles in the filter than what is selected then we can do what we do now and show all the articles. 
If you think its more complicated than that, then lets discuss.

**Comment by michaelhidalgo** [comment]
Ok let me play with it, I think I got the point :)

2015-10-02 10:27 GMT-06:00 RomichG notifications@github.com:

> Not sure why is it more complex? isn't it just a matter of showing the
> number of articles selected? and persisting that? If there are less
> articles in the filter than what is selected then we can do what we do now
> and show all the articles.
> If you think its more complicated than that, then lets discuss.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamMentor/TM_4_0_Design/issues/1042#issuecomment-145079011
> .

## 

Michael Hidalgo
http://michaelhidalgocr.blogspot.com

_The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer_

**Comment by romichg** [comment]
Worst case if we default back to 10 we should change that back in the UI. But that would be the least favorable resolution :)

**Comment by romichg** [comment]
This is fixed
