### ISSUE TITLE
New users can be created with Weak Passwords

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#105]
Related to: https://github.com/TeamMentor/Master/issues/923

As seen at https://github.com/TeamMentor/TM_4_0_Design/issues/104 at the moment it is possible to create new users with weak passwords (for example using ``jade.user_Sign_Up 'user with', 'weak password', 'good@email.com' ```)

This should be addressed when the new API method that Michael is working on is published

**Comment by michaelhidalgo** [comment]
If TEAM Mentor is configured to not show detailed error messages ( a config setting from the config file), TM backend will return a customized error message in the response, which correspond to the Simple_Error_Message.

The Post_Login_Url is part of the data structure but it is not being used at the moment. I guess it needs to be a configuration settin?

```coffee
it 'Issue 105 - New users cannot be created with Weak Passwords', (done)->
    assert_Weak_Pwd_Fail = (password)->
      randomUser  = 'abc_'.add_5_Random_Letters();
      randomEmail = "#{randomUser}@teammentor.net"
      jade.user_Sign_Up randomUser, password,password, randomEmail, (html , $)->
        html= $('.alert p').html();
        html.assert_Is("Error Signing In : Password must be 8 to 256 character long");
        done();
    @timeout(4000)
    assert_Weak_Pwd_Fail "1223", ->
      done()
```

**Comment by michaelhidalgo** [comment]
This issue should be fixed with https://github.com/TeamMentor/TM_4_0_Design/pull/222

Note that at the moment, the password policy matches exactly what TM 3.5  is using. We will need to use a strong pattern that involves the usage of upper case letters too.

However this fix needs to be done in parallel to be consistent across platforms.

**Comment by roman87** [comment]
Couple of small things:
- [ ] 1. On the error should be "Error: and stat the error" 
![selection_048](https://cloud.githubusercontent.com/assets/1326120/5707900/a335089e-9a5a-11e4-8ad2-6383127beb75.png)

- [ ] 2. For password errors, we should specify the full password specification in all error messages. i.e. we should state "Password must be 8 to 256 char long, contain a letter, number and a special character"

- [ ] 3. It seems like I can create a password with out any numbers.Is this also a case with TM 3.5?

**Comment by michaelhidalgo** [comment]
There are few validations for the password, one of those is password length, the other one is for password complexity:

![screen shot 2015-01-12 at 12 14 21 pm](https://cloud.githubusercontent.com/assets/1732035/5708204/ab02c350-9a54-11e4-8bf7-efb5a85eb2de.png)

In TM 3.5, we do have the same validations in place.

**Comment by roman87** [comment]
I think we should  make the change in 3.6 now then. Lets make sure we use the correct validation regex that check for both upper case and password without numbers. 
But first lets fix 1 and 4 above

**Comment by michaelhidalgo** [comment]
Ok great, doing it right now.

**Comment by michaelhidalgo** [comment]
As per comments above, second and fourth bullet has been addressed : 
https://github.com/TeamMentor/TM_4_0_Design/pull/249/files

**Comment by roman87** [comment]
Created issue #259 to track bullet point 3. The rest is fixed.
