### ISSUE TITLE
Searching for CWE 22 or CWE-22 does not have any search results, while CWE-22 does show result in dropdown but not in results

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1052]
Both the dropdown and the search results should have results for querries
CWE 22
CWE-22
22 CWE

**Comment by romichg** [comment]
I assume the issue here is that the title in the content says CWE-22: 
I think the way to fix this is to treat '-' as space when we generate search words as well as to remove ':' from words. I think this solution will fix not just his but a number of other issues with the search.

**Comment by DinisCruz** [comment]
searching for 'cwe 22' 

![image](https://cloud.githubusercontent.com/assets/656739/10683087/ae42b744-7935-11e5-9ed3-3bc267556171.png)

now returns

![image](https://cloud.githubusercontent.com/assets/656739/10683092/bac659c6-7935-11e5-9898-1a337ca0b851.png)

searching for 'cwe-22' (with a dash) will also give the same result.

for example 'cwe-131'

![image](https://cloud.githubusercontent.com/assets/656739/10683096/dc36283e-7935-11e5-9ff0-d820dd8d5e70.png)

**Comment by DinisCruz** [comment]
the '22 CWE' is actually harder because the 'CWE' keyword was not parsed individually , so for that case let's open a separate issue

I think that the scenario that is working now (i.e. searching for 'cwe 22') is the one most users will hit

**Comment by romichg** [comment]
This is working. The follow up issues are covered in #1079 and #1080.

I am keeping this issue open since issue addressed in the same PR as this one is not resolved. Since they are related, I will close them together when both are fixed.

**Comment by romichg** [comment]
This is done.
