### ISSUE TITLE
IE 11 Signup page is not looking good. Only single column is shown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1054]
![selection_001](https://cloud.githubusercontent.com/assets/1326120/10299108/4767ed48-6bb4-11e5-83f9-55bd14d8a746.png)

**Comment by luchia** [comment]
This has been fixed in my PR today -

![screen shot 2015-10-20 at 12 39 12 pm](https://cloud.githubusercontent.com/assets/4547737/10596440/9e2973d0-7727-11e5-8cef-64b982e8453d.png)

**Comment by romichg** [comment]
This is fixed.
