### ISSUE TITLE
Error when currentUser object is null 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#1060]
![image](https://cloud.githubusercontent.com/assets/656739/10486692/00e71f8a-7288-11e5-95ed-e28f4b872838.png)

here 

![image](https://cloud.githubusercontent.com/assets/656739/10486712/1a9a686a-7288-11e5-81c3-2704b8dfdd33.png)

**Comment by DinisCruz** [comment]
here is the test that confirms the error

``` coffee
it 'currentuser', ()->
    inject ($httpBackend)->


      using tm_API, ->

        @.currentuser (data)->
          data.assert_Is a: '42', InternalUser: false, InternalUserInfo: {}
          tm_API.currentUser.assert_Is data
        $httpBackend.expectGET('/json/user/currentuser').respond null
        $httpBackend.expectGET('/jade/json/tm/config'  ).respond null
        $httpBackend.flush()
```

![image](https://cloud.githubusercontent.com/assets/656739/10487884/0d545ef8-728e-11e5-9edc-c0c270fa90a1.png)

**Comment by michaelhidalgo** [comment]
That's a good catch!. I'll add the safe check for this.

**Comment by DinisCruz** [comment]
This can be fixed with

``` coffee
currentuser: (callback) =>
    url      = "/json/user/currentuser"
    if  @.currentUser? &&  @.currentUser.UserEnabled
      callback  @.currentUser
    else
      @.$http.get(url).success (data)=>
        if not data
          return callback null

        @.currentUser                   = data
        @.currentUser.InternalUser      = ''
        @.currentUser.InternalUserInfo  = {}
```

Here is the test that checks it:

``` coffee
it 'currentuser', ()->
    inject ($httpBackend)->
      using tm_API, ->

        @.currentuser (data)->
          (data is null).assert_Is_True()
        $httpBackend.expectGET('/json/user/currentuser').respond null
        $httpBackend.flush()

        tm_API.currentUser = null

        @.currentuser (data)->
          data.assert_Is a: '42', InternalUser: false, InternalUserInfo: {}
          tm_API.currentUser.assert_Is data

        $httpBackend.expectGET('/json/user/currentuser').respond { a: '42'}
        $httpBackend.expectGET('/jade/json/tm/config'  ).respond { }
        $httpBackend.flush()

        tm_API.currentUser = null
```

**Comment by michaelhidalgo** [comment]
I wonder why the current user returned null or undefined. Since if you are able to access the Index, it's because you are logged In.

I hope this not to be a race condition when reading/accessing the session.

**Comment by DinisCruz** [comment]
yeah it could be a race condition

Here is the test passing

![image](https://cloud.githubusercontent.com/assets/656739/10488387/5e91b336-7290-11e5-9e44-ccca32c05f03.png)

I will send in the fix with the PR for the angular error page (#995)

**Comment by romichg** [comment]
Hmm.. interesting. Looks like this was introduced when we added the cache. Good catch

**Comment by michaelhidalgo** [comment]
This is fixed here https://github.com/TeamMentor/TM_Angular/commit/58819709ce9090826736e8d2b1cc316c02a698f5#diff-8ba36e4f57e14c486e12370faf6b0243R1230

**Comment by romichg** [comment]
This is fixed.
