### ISSUE TITLE
Deny access to everything under /angular/guest/* except for specific white lists

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1062]
This should not happen for non logged in users:
![team mentor 4 0 - chromium_005](https://cloud.githubusercontent.com/assets/1326120/10505075/fd08b2a8-72d6-11e5-8b60-21690a5afab4.png)

Nor should any of this:
![team mentor 4 0 - chromium_004](https://cloud.githubusercontent.com/assets/1326120/10505080/0a0ad922-72d7-11e5-8c64-2816ec64d80e.png)

![team mentor 4 0 - chromium_003](https://cloud.githubusercontent.com/assets/1326120/10505083/13e82e5e-72d7-11e5-83b3-8a5268f97c07.png)
![team mentor 4 0 - chromium_002](https://cloud.githubusercontent.com/assets/1326120/10505085/17c7d2b8-72d7-11e5-84d8-1ded6cb5a5a7.png)

And this should not happen for logged in user:

![team mentor 4 0 - chromium_007](https://cloud.githubusercontent.com/assets/1326120/10505105/6a32294a-72d7-11e5-80b8-6db4fc74f75d.png)

**Comment by michaelhidalgo** [comment]
Good catch!, interestingly those pages are accessed using /guest*

**Comment by michaelhidalgo** [comment]
With pull request https://github.com/TeamMentor/TM_Website/pull/35

**Comment by romichg** [comment]
This is fixed
