### ISSUE TITLE
Remove the "logging in.." and "loggin ok" from the login page

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1063]
According to Jason's comments, this looks like debug messages. Do you think we can remove the messages and only show the error messages?

**Comment by michaelhidalgo** [comment]
I think that for better user experience, we should show a message indicating that something is happening.
What about something like this , otherwise if the login takes few seconds, the user won't know what is happening.

![screen shot 2015-10-19 at 14 41 24](https://cloud.githubusercontent.com/assets/1732035/10590748/a9110dac-766f-11e5-9f0a-ad7b8128b7fe.png)

**Comment by romichg** [comment]
So couple of more things that I realized.  
- [ ] once the user hits sign up on the sign up page, or login on the login page, we should disable the button until we ether get a response from the server, or we display an error message. Without this, the user can keep on hitting login / signup button causing weird conditions (we also should throttle one login/signup request at a time per session on the server, but that is a different issue tracked here #1069)
- [ ] disable the "retrieve password" button once the user hits it until a response comes back from the server.
- [ ] remove the "Info:" from the signup messages. 
- [ ] remove "info:" and "..." from the messages displayed by password reset

**Comment by michaelhidalgo** [comment]
Fixing Issues above, branch name is Issue_1063_LoginMessage

New Pull Request to address this issue : 

1.https://github.com/TeamMentor/TM_Website/pull/37
2.https://github.com/TeamMentor/TM_Angular/pull/33
3.https://github.com/TeamMentor/TM_Flare/pull/71
4.https://github.com/TeamMentor/TM_Static/pull/94

**Comment by romichg** [comment]
This is done.
