### ISSUE TITLE
Multiple search issues 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1064]
Probably all related to: #1052
- [x] searching 04 XSS does not bring up the CWE article in the search results that the dropdown shows. (this is actually the same symptom as #1053) 
- [x] searching for "System Hardening" does not show the System Hardening article (http://localhost:12345/angular/user/guides/article-76824246fdb2) as part of the search result. (same symptom as above and in #1053) 
  _Edit:_ This is actually because of #1090 and will be addressed when it is fixed.
- [x] searching for "cross site scripting" only one article shows up. while when I search for "xss" there are plenty of articles that have the words "cross site scripting"  in  them
  _Edit:_ This has been partially fixed. This will be fully fixed with #1090

**Comment by DinisCruz** [comment]
the reason why searching for xss returns more matches is because there is query (i.e. view) with that name

![image](https://cloud.githubusercontent.com/assets/656739/10683289/43d1bb64-7938-11e5-9b87-dc28805e0018.png)

**Comment by romichg** [comment]
This is not what the issue is about. Regarding the second bullet point above, let me rephrase.
When doing a search for "xss"  a number of articles which contain "cross site scripting" show up. As you can see in the example above, there is an article "how to test for cross site scripting vulnerabilities"  However, when searching for the string "cross site scripting" the same article does NOT come up. This is illustrated below. 
![selection_004](https://cloud.githubusercontent.com/assets/1326120/10684867/531949a6-7920-11e5-8b96-c33641b725e2.png)

**Comment by romichg** [comment]
Assigning to @michaelhidalgo since he is the one working on the latest search issues.

**Comment by romichg** [comment]
This is fixed. Great Job Michael.
