### ISSUE TITLE
Upstream TM server for virtual articles 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1077]
This should mimic the exact functionality we have today in 3.5
CONFIG:
1. There should be an enable/disable switch
2. There should be a configuration of the upstream server (www.teammentor.net usually)

UE:
If the user uses a website that has a subset of our library (like owasp.teammentor.net) and hits on a link inside an article. If the article does not exist on the server AND upstreamserver is enabled in the config, the user should be redirected to the upstream server's article page. So the redirect should be <upstreamServerURL:/<article link user clicked on> 
Note that if the user is not logged in to the upstream server he/she will get a login prompt (or in the future the free article workflow)

**Comment by michaelhidalgo** [comment]
With Pull Request (branch Issue_1077_VirtualArticles)

**Comment by romichg** [comment]
This is done.
