### ISSUE TITLE
On FF and IE The predictive search dropdown has a horizontal scroll bar which is not used

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1081]
![selection_007](https://cloud.githubusercontent.com/assets/1326120/10707018/f561943a-79ba-11e5-80b3-00c18e32431f.png)

This doesn't happen in Chrome, and happens in both in windows and linux on FF.

**Comment by luchia** [comment]
This has been fixed in my PR today -

![screen shot 2015-10-29 at 8 45 23 am](https://cloud.githubusercontent.com/assets/4547737/10804046/70a2ccec-7e19-11e5-9f70-05453d1e9319.png)

**Comment by romichg** [comment]
Looks good, thank you!
