### ISSUE TITLE
"Open an issue" box shows up on the bottom of the left hand side menu when filters are collapsed

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1089]
I think this leads to double scroll bar as well. Credit to @luchia for noticing.

![selection_001](https://cloud.githubusercontent.com/assets/1326120/10809918/df36e2e4-7dd1-11e5-9c98-30a35bbb1c11.png)

![selection_002](https://cloud.githubusercontent.com/assets/1326120/10809924/e62eb194-7dd1-11e5-9861-a3c9ec179a90.png)

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_Angular/pull/38

**Comment by michaelhidalgo** [comment]
branch name is Issue_1089_CollapsedFilters

**Comment by romichg** [comment]
this is fixed.
