### ISSUE TITLE
Search logic should continue searching for titles/words even if exact match is found on the query

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1090]
Currently if the search finds that a search term matches exactly the name of the query(keyword) it will stop processing the search.  This results that if an article title or any other relevant article is not in the query, it is not displayed. 
The logic should be that the search continues, but setting the exact match article scores to be the highest, such that they are shown first. 
This logic should also allow the word scores to add/subtract from the score so that most relevant articles are show up on top. For example:
Search for "System Hardening", which exactly matches a query, should mark all the articles in the query with score of 100, ensuring they end up on top. However the word search should also add + 30 to the score for the article that is titles "System Hardening" making it show up first.

**Comment by michaelhidalgo** [comment]
Working on it!.

**Comment by michaelhidalgo** [comment]
This PR is related https://github.com/TeamMentor/TM_4_0_JSON_Data/pull/5

**Comment by romichg** [comment]
this is fixed.
