### ISSUE TITLE
Articles' "comment" link to private or nonexistent github repo

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#1097]
On the bottom left of an article view (e.g. https://www.teammentor.net/angular/user/article/0000002e3de4/Implement-Code-Integrity-Checks) there is a link with the text "Have a comment about this article? Open an issue here." The link goes to a github issue tracker that is either for a private repository or a bad link giving a 404 error.

**Comment by romichg** [comment]
We should create a public repo for these issues.

**Comment by romichg** [comment]
this is done. public repo is created and link is updated. (to be updated in production shortly)

**Comment by romichg** [comment]
This is fixed.
