### ISSUE TITLE
Create TeamCity deployment script for TM 4.0 Jade

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#110]
Michael, can you start working on a TeamCity script that will deploy the TM 4.0 Jade into a QA/Production server.

There are a couple moving parts to set-up, but the key components are in place

One question: do we want to host the TM 4.0 on Windows or Linux? And on which box?

**Comment by romichg** [comment]
no longer needed. We are not using TC anymore. Scripts run on their own.
