### ISSUE TITLE
Add piwik stats for articles opened through TP

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1100]
- [x] Event sent for article link in TP. Ex of an article 
  https://teammentor.net/teamMentor/open/e72235ce-c86f-481a-a8b0-d2d8ad59bb75#load:ea854894-8e16-46c8-9c61-737ef46d7e82&showFilters:false&showTree:false&centerGuidanceItems:true

So we should use /teamMentor/open as the triger. 
- [ ] Direct TM access from TP by clicking on TM link. Ex link:

https://teammentor.net/teamMentor#load:ea854894-8e16-46c8-9c61-737ef46d7e82

So is it possible to use #load: as a trigger?

**Comment by michaelhidalgo** [comment]
I think option 2 it's not possible because the URL fragment '#' it is not sent to the server. So we don't have way to add a route for /teammentor#load:guid.

> The fragment identifier functions differently than the rest of the URI: namely, its processing is exclusively client-side with no participation from the server — of course the server typically helps to determine the MIME type, and the MIME type determines the processing of fragments. When an agent (such as a Web browser) requests a resource from a Web server, the agent sends the URI to the server, but does not send the fragment. Instead, the agent waits for the server to send the resource, and then the agent processes the resource according to the document type and fragment value.[2]

**Comment by michaelhidalgo** [comment]
With PR https://github.com/TeamMentor/TM_Website/pull/42

**Comment by michaelhidalgo** [comment]
Branch name Issue_1100_Piwik

**Comment by romichg** [comment]
Some small issues
- We get a few events for SSO login. We should get only one.
- We get two events for TP article view. One TP and another regular view
- Seems like we do need to send "action" (populated with some title, perhaps replace '/' with'-' for the url) We also need to send this action for searches and article views as it is not picked up.

**Comment by romichg** [comment]
This is done.
