### ISSUE TITLE
Expire SSO and user login  after configurable amount of time (24h default) rather than a year.

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1101]
Right now we expire SSO cookie after 1 year. This means that if the user was disabled they still have access to TM

**Comment by romichg** [comment]
As discussed lets see if we can expire the user in TM 4.0 and logout expired user from TM 3.6 if they use the old session again. This should not effect 3.6

**Comment by romichg** [comment]
Related to #1072

**Comment by michaelhidalgo** [comment]
With Pull Request

**Comment by romichg** [comment]
Almost there. 
When the session times out and an article is requested, a login is presented. When the user logs in error is shown. This is because the last URL is saved and it points to json object

For article
http://localhost:12345/json/article/6a6210050afb

For guide
http://localhost:12345/json/article/article-50cb570207e8

**Comment by romichg** [comment]
This is fixed
