### ISSUE TITLE
Create a single deployment script for both Site and Graph DB

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#111]
This script needs to:

* [x]  clone both [TM_4_0_Design](https://github.com/TeamMentor/TM_4_0_Design) and [TM_4_0_GraphDB](https://github.com/TeamMentor/TM_4_0_GraphDB) repos
* [x] start both servers
* [x] trigger load of Uno data
* [ ]  confirm that site is working ok (via web automation scripts (WebDriver))

**Comment by romichg** [comment]
This is done for 4.0 version. Minus the check for site working which is still done manually, but we can live with this for now.
