### ISSUE TITLE
Add icons for ABAP and Ruby

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#1115]
With new content changes, ABAP and Ruby are now supported. However there is not an icon mapping for those programming languages and the empty circle is displayed instead : 

![screen shot 2016-04-14 at 09 09 42](https://cloud.githubusercontent.com/assets/1732035/14533039/a8dd0e48-0220-11e6-8f70-25bcf2630f4c.png)

We need to add those mappings and their respective icon.

**Comment by romichg** [comment]
this is fixed.
