### ISSUE TITLE
Add server ability to configure which GraphDB to use 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#112]
This will help when shifting between Dev vs QA and Local vs Hosted version of the GraphDB site

**Comment by roman87** [comment]
This is done already right? Can we close htis

**Comment by DinisCruz** [comment]
nope

**Comment by roman87** [comment]
Ah right, nevermind, was reading it wrong. Ok, moving back to P3

**Comment by romichg** [comment]
Now this is done.
