### ISSUE TITLE
Change button and links colors to align with the banding guidelines

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#1122]
Colors must follow the guidelines from https://app.frontify.com/d/NuqTcbDpYSWt/brand-style-guide#/basics/colors

**Comment by michaelhidalgo** [comment]
With PR https://github.com/TeamMentor/TM_Static/pull/109

**Comment by romichg** [comment]
This is done in dev, waiting for marketing feedback

**Comment by romichg** [comment]
Marketing approved. Closing
