### ISSUE TITLE
Main user page has no content on TM Jade (user/main.html)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#113]
In the final merge to master the main user page the automatic content shown on the main user page (user/main.html ) is not being wired any more

![image](https://cloud.githubusercontent.com/assets/656739/5453908/87f40492-8522-11e4-92c6-b5bed83b37a7.png)

First step is to write a test that represents the bug (i.e confirms that the content is not there)

**Comment by DinisCruz** [comment]
This is now fixed, and looks like this

![image](https://cloud.githubusercontent.com/assets/656739/5671400/7b486976-977f-11e4-8e9a-8c143a7d5bd3.png)

**Comment by roman87** [comment]
This looks really nice. Opened related issue #226 for some visual cleanup.
As far as this goes. 2 issues.
- [ ] 1. I think that popular search terms should follow the same functionality as Top Articles. i.e. number of times the search term was used determines its rank as opposed to the latest search term.
- [ ] 2. To be consistent with the decision we made here: https://github.com/TeamMentor/TM_4_0_Design/issues/120#issuecomment-69382887 we should not increment the counter for most popular articles if they are clicked from the home search page.

**Comment by DinisCruz** [comment]
This issue can be closed since the main page now has content

**Comment by roman87** [comment]
closing
