### ISSUE TITLE
Recently Viewed Articles not working

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#120]
Recently Viewed Articles not showing any data.
![team mentor 4 0 html version - iceweasel_008](https://cloud.githubusercontent.com/assets/1326120/5456973/71a734c8-8515-11e4-84e7-7b61f79f1751.png)

**Comment by DinisCruz** [comment]
Unit test that replicates the issue

```
  it.only 'Issue 120 - Recently Viewed Articles not working', (done)->
    jade.login_As_User ->
      jade.page_User_Main (html, $)->
        using $('#recentlyViewedArticles'),->
          $(@.find('h4')).html().assert_Is('Recently Viewed Articles')
          $(@.find('a')).length .assert_Is(0)
          done()
```

**Comment by DinisCruz** [comment]
Here is the test that confirms the fix

```coffee
  it 'Issue 120 - Recently Viewed Articles not working', (done)->
    jade.login_As_User ->
      article_Id    = 'aaaaaa_'.add_5_Letters()
      article_Title = 'bbbbbb_'.add_5_Letters()
      articleUrl = page.tm_Server + "/article/view/#{article_Id}/#{article_Title}"
      articleUrl.log()
      page.chrome.open articleUrl, ()->
        jade.page_User_Main (html, $)->
          using $('#recentlyViewedArticles a'),->
            @.attr().href.assert_Contains(article_Id)
            @.html().assert_Is(article_Title)
            done()
```

**Comment by DinisCruz** [comment]
Done with https://github.com/TeamMentor/TM_4_0_Design/commit/7349cc65e15e514812b3a60ad25291860769ebd4 and tested with https://github.com/TeamMentor/TM_4_0_QA/commit/4d5e3d7d8dc5bf84731714034f7598e280a3f27a

**Design Tests:**
![image](https://cloud.githubusercontent.com/assets/656739/5664146/eacd6b8c-9745-11e4-8881-cbea9f91150e.png)

**QA Tests:**
![image](https://cloud.githubusercontent.com/assets/656739/5664251/dac1fe0a-9746-11e4-91ff-ef313bd62ef6.png)

**Comment by DinisCruz** [comment]
Here is what it looks in action:

![image](https://cloud.githubusercontent.com/assets/656739/5664284/2d28626a-9747-11e4-8ca1-1add32493196.png)

**Comment by roman87** [comment]
Functionality works nicely. @DinisCruz  
# [ ] Should we have last 3 articles instead of only 2? 2 look awfully lonely there.
# [ ]  Another thing, is when the user click on the article from the actual Recently Viewed list, should we move that article to the top of the list? It seems like it would make sense to do so?

# [ ] Also, @luchia do you think we can make it look nicer? right now the spacing seems a bit weird between the heading and the actual articles.

# [ [ lastly @DinisCruz and @luchia, I know we agreed to rename the Home button to Search. but now it seems unintuitive to click on "search" to see my last viewed articles. What do you guys thing?

**Comment by roman87** [comment]
Assigning to @DinisCruz  for items 1 2 and 4 above. Then you can pass it to @luchia for item 3.

**Comment by DinisCruz** [comment]
> 1.  Should we have last 3 articles instead of only 2
done on latest commit

**Comment by roman87** [comment]
This looks good.
2. was discussed on the call and we agreed not to do it. for 3. A new issue was opened: #226 
Bumping it for comment on 4 so we can then close this.

**Comment by DinisCruz** [comment]
I really think that we need to have **Search** in there as a menu item, since this version of TM is designed to be **search** focused

Here is an idea, what if we:
* renamed **Search** back to **Home**
* renamed **Navigate** to **Search**
* re added the search input field (which is now starting to work) to that **Search page** (i.e. the current **Navigate** page)

**Comment by roman87** [comment]
Hmm..  Navigate has a distinct function. The point of Navigation is to brows through articles - Index of articles, Curated Content, Policy and Frameworks etc. This is where someone wants to use a taxonomy to get to content. 
Search is more about finding specific content and generate the taxonomy based on the results of the content. 
So I think they are really different in functionality. I like having the Search button. What think does not fit there is all the additional content like Top article etc. perhaps we should have a separate "home" button where we store all that information? Including users saved articles, teams saved articles etc?

**Comment by DinisCruz** [comment]
As far as I can tell, the 'Recently Viewed Article' is working

And the navigation issue is handled by https://github.com/TeamMentor/TM_4_0_Design/issues/195

So we can close this one

**Comment by roman87** [comment]
agreed closing
