### ISSUE TITLE
Should we - Reuse the TM Login ID/GUID as the main cookie for the TM_Design

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#121]
The idea is to set the user session cookie on the TM_Design site to the same one as the one from the TM site used. That value is retrieved from the user Login sequence, and can be used to check if the user is already logged in.

This should allow for transparent auth between TM_Design and main TM

**Comment by roman87** [comment]
Moving to P4 as a question. Since the benefits of this are not clear.

**Comment by DinisCruz** [comment]
this is not needed any more
