### ISSUE TITLE
Terms and Conditions Page Question

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#123]
When scrolling all the way to the bottom of the landing page there is a link to Terms and Conditions which currently points to http://localhost:1337/terms-and-conditions.html. The link at the moment is broken.

The text for the page is here:
https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/content/terms-and-conditions.md

1. Dinis, lets take it out for now from this version as we never had anything like that before. 
2. @tlaloc75  @SI-Lisa  Should we have something like this?
Here is a screenshot of where the link is-
![team mentor 4 0 html version - iceweasel_010](https://cloud.githubusercontent.com/assets/1326120/5458282/eed9bfd4-851e-11e4-82a7-5414f442cf34.png)

**Comment by michaelhidalgo** [comment]
Ok here are two test that verify that the link exist and that the content exists : 

```coffeescript

  it 'Issue 123 - Terms and conditions link is available', (done)->
    jade.page_User_Logout (html,$)->
      footerDiv =  $('#footer').html()
      footerDiv.assert_Contains("Terms &amp; Conditions")
      done();

  it 'Issue 123 - Terms and conditions Page is displayed', (done)->
    jade.page_User_Logout (html,$)->
      footerDiv =  $('#footer').html()
      footerDiv.assert_Contains("Terms &amp; Conditions")
      page.click 'Terms & Conditions', (html,$)->
        $('#security-innovation-software-license-agreement').html().assert_Is("Security Innovation Software License Agreement")
        done();
```

**Comment by michaelhidalgo** [comment]
With Pull Request

**Comment by DinisCruz** [comment]
merged
