### ISSUE TITLE
add full text search to Jade

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#126]
that simulates the current TM behaviour

**Comment by DinisCruz** [comment]
The first pass of this feature is going to be simple keyword search that will find a number of articles, which will be feed to http://localhost:1332/docs/?url=http://localhost:1332/v1.0/api-docs#!/data/articles_parent_queries in order to create the mappings required to show on the current 'navigate' UI view

**Comment by DinisCruz** [comment]
with the latest commits there is a basic text search based on search the title and subject.

For example, searching for **XSS**:

![image](https://cloud.githubusercontent.com/assets/656739/5924107/b2c61292-a650-11e4-98ed-233a9974e94a.png)

produces

![image](https://cloud.githubusercontent.com/assets/656739/5924057/53d45b40-a650-11e4-90e7-a3464293550b.png)

search for **Access Control**

![image](https://cloud.githubusercontent.com/assets/656739/5924080/74b37102-a650-11e4-9c44-389349ce8a1f.png)

produces

![image](https://cloud.githubusercontent.com/assets/656739/5924090/88d5d512-a650-11e4-96ef-e7c293f8072a.png)

Search for **Logging** which is one of the existing queries (i.e. not a search)

![image](https://cloud.githubusercontent.com/assets/656739/5924123/db23e07a-a650-11e4-9f50-57b2844fb80c.png)

produces

![image](https://cloud.githubusercontent.com/assets/656739/5924128/eb830892-a650-11e4-8c16-2257c39d5f2e.png)


#### Interesting side-effect

since the text searches are 'root queries' they can be seen at http://localhost:1337/-

![image](https://cloud.githubusercontent.com/assets/656739/5924185/90a8262c-a651-11e4-9c90-9906e4661054.png)

**Comment by DinisCruz** [comment]
check this out, what about this for a search page:

![image](https://cloud.githubusercontent.com/assets/656739/5924321/b154683a-a652-11e4-9d2f-b73f574497c5.png)

**Comment by DinisCruz** [comment]
also working as good as we will get it for the Beta (specific search improvements need to be tracked separately)

**Comment by roman87** [comment]
Cool. Now we need full article search.

**Comment by DinisCruz** [comment]
Multi keyword is now working (with code pushed into GraphDB master)

Here are some examples of the searches that work now:

![image](https://cloud.githubusercontent.com/assets/656739/6554273/12b518be-c65a-11e4-9be2-b3cd980dadd3.png)

![image](https://cloud.githubusercontent.com/assets/656739/6554275/1b8903e2-c65a-11e4-90e9-d41aedc10809.png)

![image](https://cloud.githubusercontent.com/assets/656739/6554289/3b1cdb5c-c65a-11e4-8f7e-3b11c41b827b.png)

if you want to understand how a particular score is being calculated (as per https://github.com/TeamMentor/TM_4_0_Design/issues/510) you can use the new **search/words_score/{words}** api

![image](https://cloud.githubusercontent.com/assets/656739/6554296/5360b08a-c65a-11e4-918d-c4aa5f3eaf32.png)

like this: 

![image](https://cloud.githubusercontent.com/assets/656739/6554306/705d6372-c65a-11e4-8c6f-d20f33ef2dfe.png)

The json  (see a part of it below) shows the total score, which is a sum of each words score (and you can see how much points each tag element contributed to each word)

```json
[
  {
    "id": "article-9b2962d9c4e7",
    "score": 26,
    "why": {
      "1": {
        "ul": 1,
        "li": 1,
        "a": -4
      },
      "encode": {
        "p": 6,
        "ol": 4,
        "li": 8,
        "ul": 4,
        "title": 10
      },
      "struts": {
        "ul": 2,
        "li": 2,
        "a": -8
      }
    }
  },
  {
    "id": "article-40c08d0af3c4",
    "score": 24,
    "why": {
      "1": {
        "ul": 2,
        "li": 2,
        "p": 3,
        "a": -4,
        "title": 10
      },
      "encode": {
        "p": 1,
        "ul": 2,
        "li": 2,
        "a": -8
      },
      "struts": {
        "li": 4,
        "p": 5,
        "ul": 3,
        "a": -8,
        "title": 10
      }
    }
  },
```

**Comment by roman87** [comment]
This looks good. Lots of tweaks we need to come up with for this but, those are separate issues. Great stuff.
