### ISSUE TITLE
Opening /Graph/{query} page with bad {query} should result in an 'no results' page/view

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#128]
for example http://localhost:1337/graph/aaaaaa returns all data:

![image](https://cloud.githubusercontent.com/assets/656739/5468171/0c33bde2-85c3-11e4-8eaa-319a7a0626a0.png)

![image](https://cloud.githubusercontent.com/assets/656739/5468176/1466e368-85c3-11e4-9968-3f856e4c0674.png)

**Comment by DinisCruz** [comment]
Unit Test that replicates the issue

```coffee
  it.only 'Issue 128 - Opening /Graph/{query} page with bad {query} should result in an "no results" page/view', (done)->
    jade.login_As_User ->
      page.open '/graph/aaaaaa', (html)->
        page.html (html, $)->
          $('#containers a').keys().size().assert_Bigger_Than(100) # this value should be zero
          done()
```

**Comment by DinisCruz** [comment]
This UnitTest (in TM_4_0_Design) replicates it from the backend

```coffee
    it.only '[bug 128] graphDataFromGraphDB (non existent query)', (done)->
        @timeout 5000
        filters = ""
        queryId = 'AAAAAAA'.add_5_Random_Letters()
        graphService.graphDataFromGraphDB null, queryId, filters,  (searchData)=>
            #these values are wrong: see https://github.com/TeamMentor/TM_4_0_Design/issues/128
            searchData.containers.size().assert_Bigger_Than(0)
            searchData.filters.size().assert_Bigger_Than(0)
            searchData.results.size().assert_Bigger_Than(0)
            done()
```

**Comment by DinisCruz** [comment]
This UnitTest (in TM_4_0_GraphDB) replicates the issue on the GraphDB

```coffee
    it.only '[bug #128] /data/:dataId/:queryId?show={invalid-query}' , (done)->
      supertest(app).get('/data/data-test/simple?show=aaaaaaaaa')
                    .expect(200)
                    .expect('Content-Type', /json/)
                    .end (error, response) ->
                      graph = JSON.parse(response.text)
                      #these values are wrong: see https://github.com/TeamMentor/TM_4_0_Design/issues/128
                      graph.nodes.size().assert_Bigger_Than(0)
                      graph.edges.size().assert_Bigger_Than(0)
                      done()
```

**Comment by DinisCruz** [comment]
Here is the bug

![image](https://cloud.githubusercontent.com/assets/656739/5629095/b0dede8c-95a7-11e4-8a9f-27f1b954e6fa.png)

Here is the fix:

from: ![image](https://cloud.githubusercontent.com/assets/656739/5629107/d057b3a6-95a7-11e4-918b-ee33d679d8bc.png)

to: ![image](https://cloud.githubusercontent.com/assets/656739/5629102/c0f21be0-95a7-11e4-8e54-84e4226ca2b8.png)

**Comment by DinisCruz** [comment]
Converting  **TM_4_0_Design** test into a regression test

```coffee
    it.only 'graphDataFromGraphDB (non existent query)', (done)->
        queryId = 'AAAAAAA'.add_5_Random_Letters()
        graphService.graphDataFromGraphDB null, queryId, "",  (searchData)=>
            searchData.containers.assert_Size_Is(0)          # regression test for [bug #128]
            searchData.filters.assert_Size_Is(0)
            searchData.results.assert_Size_Is(0)
            done()
```
Converting **TM_4_0_GraphDB** test into a regression test

```coffee
    it 'graphDataFromGraphDB (non existent query)', (done)->
        queryId = 'AAAAAAA'.add_5_Random_Letters()
        graphService.graphDataFromGraphDB null, queryId, "",  (searchData)=>
            searchData.containers.assert_Size_Is(0)          # regression test for [bug #128]
            searchData.filters.assert_Size_Is(0)
            searchData.results.assert_Size_Is(0)
            done()
```

Converting **TM_4_0_QA** test into a regression test

```coffee
  it 'Issue 128 - Opening /Graph/{query} page with bad {query} should result in an "no results" page/view', (done)->
    jade.login_As_User ->
      page.open '/graph/aaaaaaa', (html)->
        page.html (html, $)->
          $('#containers a').length.assert_Is(0)
          done()
```

**Comment by DinisCruz** [comment]
Next step is to run all tests locally

**TM_4_0_GraphDB**
![image](https://cloud.githubusercontent.com/assets/656739/5629344/5f443650-95aa-11e4-92d2-1469eae0408d.png)

**TM_4_0_Design**
![image](https://cloud.githubusercontent.com/assets/656739/5629447/77a7898a-95ab-11e4-8732-42434e202762.png)

**TM_4_0_QA**
![image](https://cloud.githubusercontent.com/assets/656739/5629465/a9242766-95ab-11e4-9ffc-c643341668b9.png)

**Comment by DinisCruz** [comment]
Next push all commits to github:

* **TM_4_0_GraphDB**: https://github.com/TeamMentor/TM_4_0_GraphDB/commit/994da66cec327cf58c2bf302bbe7a0a3afaa077d
* **TM_4_0_Design**: https://github.com/TeamMentor/TM_4_0_Design/commit/ef6e01815185cdceee3dd160a5d050bc5fa4fcf5
* **TM_4_0_QA**: https://github.com/TeamMentor/TM_4_0_QA/commit/7c75ecd9637692014e39732a98ab06f74180d59e

**Comment by DinisCruz** [comment]
Final step is to check if all tests passed in travis (CI service) at the [TM Repos build status](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-Repos-build-status) wiki page

Originally they didn't (TM_4_0_Design had a minor bug which also made TM_4_0_QA to fail)

---- 

![image](https://cloud.githubusercontent.com/assets/656739/5629599/4f7f57c4-95ad-11e4-83bf-589bddad8238.png)

---- 

But after a simple fix, we're back into a green mode :)

---- 

![image](https://cloud.githubusercontent.com/assets/656739/5629645/ac22bf16-95ad-11e4-8a6d-0bb81f0e62e0.png)

---- 

With Code Coverage hanging on ok :)

---- 

![image](https://cloud.githubusercontent.com/assets/656739/5629661/e0ff1f68-95ad-11e4-8fcf-ab9ef389444d.png)

**Comment by DinisCruz** [comment]
Ready for QA, @roman87  over to you 

I think it will take you longer to read this thread than to test it :)

**Comment by roman87** [comment]
haha true :)

**Comment by roman87** [comment]
This is fixed.
