### ISSUE TITLE
QA REPL Window is not opening when test is triggered from WebStorm

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#131]
This is the prob that Michael had yesterday and required the execution of the tests from the command line (once) so that the NWR window would open (after that @michaelhidalgo could use the WebStorm UI)

I think I know where the prob is and this should be addressed on directly on the [NWR](https://github.com/o2platform/nwr) codebase

**Comment by DinisCruz** [comment]
this has not happen in a while (as far as I'm aware) so we can also close this one

**Comment by michaelhidalgo** [comment]
Yap, I've not seen it lately.

2015-01-26 17:39 GMT-06:00 Dinis Cruz <notifications@github.com>:

> this has not happen in a while (as far as I'm aware) so we can also close
> this one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/131#issuecomment-71562171>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*
