### ISSUE TITLE
Write JS for Show Password on login wall

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#138]
Tried to build with CSS but it's a muck around and we already have the structures done in Foundation - think it would be easier to include jQuery so they work as they should than to keep spending time trying to develop this in css.

**Comment by luchia** [comment]
This is more of a bonus feature, I'm not sure if @roman87  will want to change this from P1.

You can find this feature on the Flare login tab, in the getting started directory.
![show-hide-pw](https://cloud.githubusercontent.com/assets/4547737/5639932/55d9f9b8-966a-11e4-906e-08df0a5bc4f7.gif)

**Comment by roman87** [comment]
@luchia  Do we really need this? What was the purpose of the user being able to see the password?

**Comment by DinisCruz** [comment]
A number of sites have it, are these usability guidelines that recommend it?

**Comment by roman87** [comment]
Oh on the sign up form it may make sense.
