### ISSUE TITLE
Write JS for form prompts on loginwall

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#139]
Tried to build with CSS but it's a muck around and we already have the structures done in Foundation - think it would be easier to include jQuery so they work as they should than to keep spending time trying to develop this in css.

**Comment by luchia** [comment]
This is more of a bonus, I'm not sure if @roman87 will want to change this from P1.

![validation-one](https://cloud.githubusercontent.com/assets/4547737/5639975/efec7abc-966a-11e4-8fcf-10f27ab75d86.gif)
![validation-two](https://cloud.githubusercontent.com/assets/4547737/5639976/eff744ce-966a-11e4-8f2c-5a432f97b6ef.gif)

Two examples of dynamically generated validation on forms. I would like this to be on our sign up form only on Flare. The design and layout is in the getting-started directory, called index-prompts.

**Comment by roman87** [comment]
Its actually quite important as we had these issues in the past. However, don't we already have the validation on jade?

**Comment by roman87** [comment]
So specifically for email, here is what I get when I put in an invalid one:
![selection_044](https://cloud.githubusercontent.com/assets/1326120/5671469/2cec1530-9756-11e4-979b-b022ab2e7aa5.png)

**Comment by roman87** [comment]
And if I hit sign up I get this:
![blah](https://cloud.githubusercontent.com/assets/1326120/5671520/8a730b0a-9756-11e4-8702-b067d12541b8.png)

**Comment by luchia** [comment]
Must be default browser validation caused by the form inputs being given values (email, password). I didn't realise it was doing that, that's cool.

**Comment by luchia** [comment]
I thought it would be a nice touch if when the user enters an incorrect password in the sign up form, it tells them that it needs to be x/y/z. Up to you guys, maybe a later feature.

**Comment by roman87** [comment]
Yea I agree, it should be there. We should do client side validation as well.

**Comment by roman87** [comment]
Especially since we do it today in 3.5 and I don't think it would be that difficult to add it in.
