### ISSUE TITLE
Fix backend support for Jade and compiled Jade (including hard-coded paths)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#144]
At the moment the jade compile/cache support is not fully working since the jade rendering is happening directly from the jade files and not from the compiled jade files (in the https://github.com/TeamMentor/TM_4_0_Design/tree/master/static/jade_js/jade folder)

There are also a couple cases of hardcoded paths (mapped to the root of the repo vs a virtual path) that need to be addressed.

The key objective is to make the /static folder completely self sufficient, and at the moment that is not happening

**Comment by romichg** [comment]
I assume this was done?

**Comment by DinisCruz** [comment]
yeah this is totally done
