### ISSUE TITLE
Fix TM_4_0_Design Unit backend UnitTests 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#145]
These are the ones here https://github.com/TeamMentor/TM_4_0_Design/tree/master/node/tests and that are currently being auto-executed by travis: https://travis-ci.org/TeamMentor/TM_4_0_Design

**Comment by roman87** [comment]
Moving to P3

**Comment by DinisCruz** [comment]
this can also be closed

**Comment by roman87** [comment]
Yep, closing
