### ISSUE TITLE
Find way to run QA tests in Travis (or another CI)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#146]
We need to have the same (run all tests in CI on every commit) set-up for the QA tests (https://github.com/TeamMentor/TM_4_0_Design/tree/master/QA) including GitHub integration

These are a bit tricker to set-up since
* they require a live TM site to hit and both Design and Graph node sites running locally
* they need a desktop to render the UI (i.e. same setup as https://travis-ci.org/o2platform/nwr/builds/43915854)
* they are separate from the other tests (since these are browser driven). Which begs the question if it will be possible to trigger multiple Travis test executions based on one commit
* ideally we should run also run these against a deployed server (and not only a localhost version)

**Comment by DinisCruz** [comment]
This part of the QA CI workflow is done (see https://travis-ci.org/TeamMentor/TM_4_0_QA) so we can close this issue

**Comment by roman87** [comment]
yep, done.
