### ISSUE TITLE
Move content/markdown content into a top level folder

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#150]
Hi @luchia I really like what you did with the markdown includes (for example https://github.com/TeamMentor/TM_4_0_Design/commit/9d26ecd56b7f879b2786ce99280e364d9f27a364#diff-fda917b1e66955b55d84e504d42391d6R26) and now I we need to put it back into the main content folder

I.e. from https://github.com/TeamMentor/TM_4_0_Design/tree/master/source/flare/__ALL/content to https://github.com/TeamMentor/TM_4_0_Design/tree/master/source/content

But I don't want to move it all at once, since there are also a couple *.jade files in there, so I think it is better if we do it first for the pages that are already on its final location (namely these https://github.com/TeamMentor/TM_4_0_Design/tree/master/source/jade)

Does this make sense? If not, don't worry, I'll do the content move in the next day(s)

**Comment by luchia** [comment]
[This has been started.](https://github.com/TeamMentor/TM_4_0_Design/commit/a3e80ff26cea47a4d98ebb992a991e427b7dacaa) I still have a bit more to do.

**Comment by luchia** [comment]
This has been finished but I can't push my changes until I fix the problems I'm having with my Graph DB.

**Comment by DinisCruz** [comment]
what's the prob with your GraphDB? 

Have you seen https://github.com/TeamMentor/TM_4_0_Design/wiki/Troubleshooting-running-QA-scripts 

If that didn't solve your prob, open an issue with it

**Comment by luchia** [comment]
[This is finished](https://github.com/TeamMentor/TM_4_0_Design/commit/f2c807184d7d9ca3c34d40438b6527036688b41c) (I think)

**Comment by romichg** [comment]
This is done.
