### ISSUE TITLE
Add asserts for new Login page content

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#151]
Here is where this new content was added https://github.com/TeamMentor/TM_4_0_Design/commit/9d26ecd56b7f879b2786ce99280e364d9f27a364#diff-730aa37cc685914c31bac880db3afc9aR95

![image](https://cloud.githubusercontent.com/assets/656739/5485347/da160f34-8691-11e4-8b68-4122996d945d.png)

Here is what it looks like

![image](https://cloud.githubusercontent.com/assets/656739/5485322/94a8e868-8691-11e4-83c3-7fdae3bd2f8e.png)

Here is where the asserts need to be added:

https://github.com/TeamMentor/TM_4_0_Design/blob/master/QA/tests/jade-anonymous-users.coffee#L115-L126

![image](https://cloud.githubusercontent.com/assets/656739/5485355/f418589c-8691-11e4-9669-08ae3f0412ff.png)

@michaelhidalgo, you're ok to handle this one?

**Comment by DinisCruz** [comment]
@roman87 this is the one that Michael and Salle are using to learn the workflow. it is a nice and (easier) one.

The fact that it is a P4 (in this case) means that if it is not fixed is not critical. But the path for michael and Salle to be able to help fixing P0 issues, passes though fixing a number of simpler ones (like this)

**Comment by roman87** [comment]
Yes good one for Michael and Salle.

**Comment by DinisCruz** [comment]
Since the change has been made I'm going to close this one

What would be nice is if the content in the test was actually the one from the MD files (as described in https://github.com/TeamMentor/TM_4_0_Design/issues/186 )

**Comment by DinisCruz** [comment]
@tekgirl77 and @michaelhidalgo for reference (and as you can see on this commit https://github.com/TeamMentor/TM_4_0_QA/commit/581556b3bf3ae77f7b87ae37c67bd31e35c17c22) the final fix for issues like this should be added to the [Issues-sprint-1.coffee](https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/issues-sprint-1.coffee) file
