### ISSUE TITLE
Top left logo for non-logged in users needs to go to /guest/default.html (or just /)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#155]
And at the moment it goes to /user/main.html

![image](https://cloud.githubusercontent.com/assets/656739/5495228/bf67e1f0-86f3-11e4-85d9-c572f1095914.png)

This is caused by the mixin reuse of the top-left nav section in both Jade and Flare

**Comment by DinisCruz** [comment]
This has been fixed

**Comment by roman87** [comment]
This is done.
