### ISSUE TITLE
Create simple setup for config options and auth with TM server

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#160]
The idea is to start with a simple simple set-up/workflow:

1. when TM Design starts it is in a 'TM disconnected' mode (which should work until the point that the user tries to login')
2. TM Design should ask for an TM 3.5 admin to login
3. when TM 3.5 admin logins, TM Design will
* login the admin user (in TM 3.5)
* create an TM 3.5 user account for the TM Design server
* get an Auth token for that TM 3.5 account
* save those details in a local config file (which doesn't get commit to GitHub)

4. for now, to reset these values (or point to a different TM server) the workflow will be to delete that local config file

This will address the main issue described in https://github.com/TeamMentor/TM_4_0_Design/issues/89

**Comment by roman87** [comment]
This can wait until sprint 3 at this point.

**Comment by romichg** [comment]
This is no longer needed.
