### ISSUE TITLE
Top nav issue when resizing into smaller screensize

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#161]
Notice the top nav-bar, from

![image](https://cloud.githubusercontent.com/assets/656739/5501307/8be76348-8750-11e4-8c3f-a9edf4ed0d28.png)

to

![image](https://cloud.githubusercontent.com/assets/656739/5501308/96af6136-8750-11e4-83c3-d12748b582f3.png)

to 

![image](https://cloud.githubusercontent.com/assets/656739/5501312/9ed57f62-8750-11e4-9c43-24b050f912b8.png)

Similar formatting issue in this pages:

![image](https://cloud.githubusercontent.com/assets/656739/5501317/afbf230a-8750-11e4-814e-450662f10fe0.png)

![image](https://cloud.githubusercontent.com/assets/656739/5501319/b67aaf70-8750-11e4-8e1a-10ca105ac505.png)

The post login pages look good

**Comment by romichg** [comment]
done.
