### ISSUE TITLE
Use CSS Sprites to reduce the number of requests made to load a page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#163]
At the moment we make quite a lot of requests for each page loaded. Ideally there should be one request per type of resource: HTML, CSS, JS and images.

References:
* http://css-tricks.com/css-sprites/
* http://alistapart.com/article/sprites
* http://stackoverflow.com/questions/1227412/css-sprites-and-ie6
* http://stackoverflow.com/questions/922748/css-sprites-images-rendered-with-bad-quality-in-ie
* http://csssprites.com/
* https://katz.co/googles-sprite-image-is-a-thing-of-beauty/ (this trick has been used by google for ages)

Requests made:

**16x for /**
![image](https://cloud.githubusercontent.com/assets/656739/5501592/88106c7e-8755-11e4-814a-030f7c63edc5.png)

**7x for About**
![image](https://cloud.githubusercontent.com/assets/656739/5501595/9327e920-8755-11e4-8cb3-812068288d62.png)

**10x for Features**
![image](https://cloud.githubusercontent.com/assets/656739/5501601/a6e476f4-8755-11e4-9062-2ab81a3a569a.png)

**7x for Sign-up**
![image](https://cloud.githubusercontent.com/assets/656739/5501608/b79abb98-8755-11e4-8846-5340898d922f.png)

**7x for Login**
![image](https://cloud.githubusercontent.com/assets/656739/5501611/c10f4306-8755-11e4-828b-b23b5f54d2f4.png)

**8x for Library list**
![image](https://cloud.githubusercontent.com/assets/656739/5501631/fe20eb00-8755-11e4-8358-6385c2a2b91a.png)

**Comment by luchia** [comment]
This has been completed for the landing pages in Jade, Flare still needs to be re-done with the new sprites though.

##### Index
![screen shot 2015-01-02 at 4 05 00 pm](https://cloud.githubusercontent.com/assets/4547737/5594617/ddf2d60a-929e-11e4-88d8-f429ed7f7b52.png)

##### About
![screen shot 2015-01-02 at 4 05 11 pm](https://cloud.githubusercontent.com/assets/4547737/5594618/ddf7d3d0-929e-11e4-88d3-5bfdc9de1fc0.png)

##### Features
![screen shot 2015-01-02 at 4 05 19 pm](https://cloud.githubusercontent.com/assets/4547737/5594619/ddff9f70-929e-11e4-97bf-312d679ec5d1.png)

**Comment by luchia** [comment]
Flare is done as well but has some extra stylesheets while we're not compiling our SCSS files. Once Dinis has built that bit, we will be down to two css files for Flare landing page -

##### Index
![index](https://cloud.githubusercontent.com/assets/4547737/5601738/71f94f2e-9361-11e4-9602-d68db711ff20.png)

##### About
![about](https://cloud.githubusercontent.com/assets/4547737/5601740/926ef34e-9361-11e4-8c8f-0e67d23d3953.png)

##### Features
![screen shot 2015-01-03 at 3 55 13 pm](https://cloud.githubusercontent.com/assets/4547737/5601741/a4520e7a-9361-11e4-9c4a-fa9dc1323d15.png)

**Comment by DinisCruz** [comment]
Very very nice @luchia 

Just one small node that I added to https://github.com/TeamMentor/TM_4_0_Design/issues/184

**Comment by roman87** [comment]
Looks good!

![selection_053](https://cloud.githubusercontent.com/assets/1326120/5709251/4c99c75c-9a66-11e4-81cf-2c6969270410.png)
