### ISSUE TITLE
Query Bug and add unit test for search results data

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#164]
Fix what happened when we were working on https://github.com/TeamMentor/TM_4_0_Design/issues/154#issuecomment-67613930 where suddenly there where no results shown on the left-hand side 

![](https://cloud.githubusercontent.com/assets/656739/5502184/58685438-875e-11e4-8972-73f854998a0f.png)

In that scenario, there was also prob if the user clicked on the Authorization link 

![image](https://cloud.githubusercontent.com/assets/656739/5502259/56efbec4-875f-11e4-9709-ad2682d0f8a6.png)

while in the Authorisation query:

![image](https://cloud.githubusercontent.com/assets/656739/5502256/4f12d3f8-875f-11e4-8697-1b4e5e08e950.png)

**Comment by DinisCruz** [comment]
I'm pretty sure that related to this (issue 164) is the fact that http://localhost:1337/graph/Data%20Validation also broke in one of the latest pushes

Here is the test that should pass and is now failing

```coffee
  it 'Graph - Data Validation', (done)->
    jade.page_User_Graph 'Data+Validation', (html,$)->
      all_H3 = ($(h3).html() for h3 in $('h3'))
      all_H4 = ($(h4).html() for h4 in $('h4'))

      all_H3.assert_Is([ 'Logging', 'Filters' ])
      all_H4.assert_Contains('Showing 89 articles')
      all_H4.assert_Contains('Constrain, Reject, And Sanitize Input')
      all_H4.assert_Contains('How to Constrain Input For Length Range Format And Type')
      all_H4.assert_Contains('Constrain, Reject, And Sanitize Input')
      done();
```

**Comment by DinisCruz** [comment]
The "add unit test for search results data" part of this issue is under way with the fix pushed for https://github.com/TeamMentor/TM_4_0_Design/issues/198

**Comment by DinisCruz** [comment]
This 'query bug' is fixed with  https://github.com/TeamMentor/TM_4_0_Design/commit/28ed0c330d2f9a4e602f9e44292ff922b0cb0917

This closes this issue, because for example the Authorization issue shown above is now fixed:

![image](https://cloud.githubusercontent.com/assets/656739/5636136/4d23333a-95e7-11e4-9c8f-1ea381deebcc.png)

Note that this not the final version of this page since we still need to have https://github.com/TeamMentor/TM_4_0_Design/issues/94 and https://github.com/TeamMentor/TM_4_0_Design/issues/93

**Comment by roman87** [comment]
Looks good. Closing
