### ISSUE TITLE
Improve performance of Jade Home page (size and load times)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#167]
Here is the latest version at http://tm-4-0-design.azurewebsites.net/

500k loaded in 8s

![image](https://cloud.githubusercontent.com/assets/656739/5526907/a3565a32-89f0-11e4-892f-f7baea895eba.png)

**Comment by luchia** [comment]
Addressed in #163, this needs to be checked.

**Comment by DinisCruz** [comment]
This is fixed, you can see it in action at http://tm-4-design.herokuapp.com/


![image](https://cloud.githubusercontent.com/assets/656739/5602029/6be060de-9328-11e4-847f-81b230ca9637.png)

**Comment by romichg** [comment]
This is done.
