### ISSUE TITLE
Refactor TeamMentor 3.5 code into separate module/repo

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#169]
Consolidate both sets of node/js code that connects to TeamMentor 3.5 backend. This is the code that knows how to talk with the multiple TM 3.5 REST services, and it currently split between the TM Design and TM Graph code.

By refactoring and putting it in npm's repository we also gain a nice javascript based API to talk with TeamMentor. 

90% of the code already exists, and the only new bit of code that needs to be added is the one to allow the authentication into 3.5 webservices (https://github.com/TeamMentor/TM_4_0_Design/issues/90 , https://github.com/TeamMentor/TM_4_0_Design/issues/89 and https://github.com/TeamMentor/TM_4_0_Design/issues/160)

Now is the right time to do it, since once we turn off anonymous access from TM 3.5 uno server, both 4.0 TM node sites (Design and Graph) will need to access in an authenticated way (to be provided by this new node-teammentor module)

**Comment by roman87** [comment]
This was done.
