### ISSUE TITLE
Add special test to 'wake-up'  TeamMentor 3.5 server

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#172]
This test needs to have a long timeout, and will deal with cases like https://github.com/TeamMentor/TM_4_0_Design/issues/145#issuecomment-67862768

The core code for this should be on https://github.com/TeamMentor/TM_4_0_Design/issues/169, with a simple test on both backend and QA tests

**Comment by roman87** [comment]
Not a major priority at this point. Can wait until Sprint 3.

**Comment by romichg** [comment]
Now part of #933
