### ISSUE TITLE
Fix articles-by-weight data feed

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#174]
At the moment it is on **tm-data** (http://localhost:1332/data/tm-data/articles-by-weight) and it needs to be on tm-uno (http://localhost:1332/data/tm-data/articles-by-weight)

Also we need to figure out what should be formula for these? For now should it be by 'number to queries that contains an article'

This is needed to address the https://github.com/TeamMentor/TM_4_0_Design/issues/113 issue

**Comment by DinisCruz** [comment]
Since we are not going to get this data from the TM backend in the short-term (i.e. this week), I used a different strategy to calculate these values.

This is now done by counting all articles 'clicked' by the user (the ones shown in the 'recently viewed') and showing the top 5

**Comment by DinisCruz** [comment]
like this (ignore the 'title' since that was generated by Unit Tests UI Automation)

![image](https://cloud.githubusercontent.com/assets/656739/5671450/eaaf316e-977f-11e4-805d-dd4168471ab7.png)

**Comment by roman87** [comment]
At this point this is a good solution. The best solution for this would be "Like" button on the article. Articles with most "likes" make it to the page. It can also be manually overwridden.  I opened a story for this https://github.com/TeamMentor/Master/issues/940 for sprint 4.

**Comment by roman87** [comment]
closing.
