### ISSUE TITLE
Add server side persistence of session data

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#175]
This is needed to hold (for now) the 'last articles' seen by the user (required for https://github.com/TeamMentor/TM_4_0_Design/issues/174) and will also allow the logged in user status to survive a node-server restart (which at the moment doesn't happen)

There is already an express module that does this, so this shouldn't be too difficult

**Comment by DinisCruz** [comment]
done with https://github.com/TeamMentor/TM_4_0_Design/pull/193

**Comment by roman87** [comment]
This is done
