### ISSUE TITLE
Support storage of auto tokens in local config file

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#178]
This will help with https://github.com/TeamMentor/TM_4_0_Design/issues/90#issuecomment-68060626 and is related to https://github.com/TeamMentor/TM_4_0_Design/issues/160

**Comment by DinisCruz** [comment]
@luchia's error is because it is not finding the module 'nedb' which is on https://github.com/TeamMentor/TM_4_0_Design/blob/master/package.json#L40

That should be fixed with an ```npm install``

**Comment by luchia** [comment]
Cool, fixed for me.

**Comment by roman87** [comment]
this works now.
