### ISSUE TITLE
Write test that confirms the leak of TM 3.5 from SendPasswordReminder error

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#182]
At the moment the error message shown from a error 500 response from TM 3.5 SendPasswordReminder (asmx) will leak the location of the upstream TM 3.5 server.

Not a major issue, but something with a little of security properties (info leak)

This should be added to set of Unit Tests called 'Security Issues - Accepted'

@michaelhidalgo this is a good one for you. See the latest tested added to Login-Controller.test.coffee for the code you can use to access (and replicate) this behaviour

**Comment by roman87** [comment]
Yea really not an issue. The upstream server is available for editing anyways.

**Comment by romichg** [comment]
Not an issue. Closing.
