### ISSUE TITLE
Add polish to Flare

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#183]
- [x] Transitions on links;
- [x] Transitions on buttons;
- [x] Button for Get Started in the landing page navigation

**Comment by roman87** [comment]
Making this a P3 to align with Flare priorities.

**Comment by luchia** [comment]
[Buttons have been done](https://github.com/TeamMentor/TM_4_0_Design/commit/477be852b64e6a1cfc95e236a5201192981cc950) -

![buttons](https://cloud.githubusercontent.com/assets/4547737/5868580/38df9e5a-a2f7-11e4-8574-d9f741fdd5f1.gif)
![search-bar-buttons](https://cloud.githubusercontent.com/assets/4547737/5868581/38e0f8ae-a2f7-11e4-8c07-766866ae132f.gif)

**Comment by roman87** [comment]
Looks nice! can't wait to see it in action.

**Comment by luchia** [comment]
Links in the Application Navbar -

![menu](https://cloud.githubusercontent.com/assets/4547737/5946123/24d2bba4-a77f-11e4-8464-4f0437f6b9c6.gif)

**Comment by luchia** [comment]
Get Started button on the Landing Page navigation - 

![lpbutton](https://cloud.githubusercontent.com/assets/4547737/5946432/66078ef4-a781-11e4-8eae-6ee8dd148f42.gif)

**Comment by romichg** [comment]
Whatever happened to this thing? @luchia

**Comment by luchia** [comment]
The application evolved. Designs were changed etc. This wouldn't really fit in anywhere now.
