### ISSUE TITLE
Source of all design 'native documents'

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#185]
Lucy, where are all the base design documents that you use to create the TM images?

Namely the photoshop and illustrator files

We have to make sure that those files are all located in a GitHub or file storage location, so that if you lost your laptop tomorrow nothing would be lost

**Comment by roman87** [comment]
Most of the pdf versions are here: https://github.com/TeamMentor/WhatsCookin/tree/master/UI%20Mockups

**Comment by luchia** [comment]
I lost the originals when my Macbook died, but the pdfs are where Roman said and my other working files are throughout all of these issues.

**Comment by roman87** [comment]
closing this as there is nothing more to be done here.
