### ISSUE TITLE
No support for case when user has images turned off

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#187]
Just to confirm (me and lucy where having a chat about this on Skype), that TM 4.0 (Jade and Flare) will NOT support the case when the user disables images on his browser

With Jade we can support the case when the user disabled Javascript, but I think supporting an text only (no images) it a bit too much :) 

@luchia assigning to you so that you can comment (then move it to @roman87 )

**Comment by luchia** [comment]
It'd definitely be easier if we didn't have to support it.

**Comment by roman87** [comment]
Yes we don't have to support it :)
Just as an FYI here is how current TM looks like in a text only browser. Overall - not bad.
![rom titi08 -dev-teammentor-tm_4_0_design_037](https://cloud.githubusercontent.com/assets/1326120/5636054/968a0a06-95bc-11e4-9914-a47f8b78888b.png)
![rom titi08 -dev-teammentor-tm_4_0_design_038](https://cloud.githubusercontent.com/assets/1326120/5636056/98cb5838-95bc-11e4-98c8-036c83191abc.png)
![rom titi08 -dev-teammentor-tm_4_0_design_039](https://cloud.githubusercontent.com/assets/1326120/5636064/a347b20c-95bc-11e4-912c-f3ee83877fb9.png)
![rom titi08 -dev-teammentor-tm_4_0_design_040](https://cloud.githubusercontent.com/assets/1326120/5636065/a50b9cd4-95bc-11e4-95dd-72f0d171b482.png)

**Comment by michaelhidalgo** [comment]
Very interesting, I did not know that was possible :)

2015-01-06 14:57 GMT-06:00 RomichG <notifications@github.com>:

> Yes we don't have to support it :)
> Just as an FYI here is how current TM looks like in a text only browser.
> Overall - not bad.
> [image: rom titi08 -dev-teammentor-tm_4_0_design_037]
> <https://cloud.githubusercontent.com/assets/1326120/5636054/968a0a06-95bc-11e4-9914-a47f8b78888b.png>
> [image: rom titi08 -dev-teammentor-tm_4_0_design_038]
> <https://cloud.githubusercontent.com/assets/1326120/5636056/98cb5838-95bc-11e4-98c8-036c83191abc.png>
> [image: rom titi08 -dev-teammentor-tm_4_0_design_039]
> <https://cloud.githubusercontent.com/assets/1326120/5636064/a347b20c-95bc-11e4-912c-f3ee83877fb9.png>
> [image: rom titi08 -dev-teammentor-tm_4_0_design_040]
> <https://cloud.githubusercontent.com/assets/1326120/5636065/a50b9cd4-95bc-11e4-95dd-72f0d171b482.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/187#issuecomment-68932180>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
that feels like the BBS world in 1995 :)

**Comment by DinisCruz** [comment]
what where you using to browse? VIM?

**Comment by roman87** [comment]
Hahaha.. yes, I still remember the phone bill I ran up for my parents :). This is lynx. Its quite old, but comes in handy sometimes.

**Comment by romichg** [comment]
Closing..
