### ISSUE TITLE
Small nav issue on help page navigation in small screen size

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#189]
http://localhost:1337/help/index.html

![image](https://cloud.githubusercontent.com/assets/656739/5602236/6b090f2e-9339-11e4-90a4-7ecc81dce74b.png)

Is ok when in bigger window

![image](https://cloud.githubusercontent.com/assets/656739/5602237/8986ca9a-9339-11e4-9550-58e3673cdf5a.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-01-06 at 9 30 29 am](https://cloud.githubusercontent.com/assets/4547737/5621873/b96ca212-9586-11e4-89bc-f57fd0526299.png)
![screen shot 2015-01-06 at 9 30 45 am](https://cloud.githubusercontent.com/assets/4547737/5621874/b9b2bfea-9586-11e4-9794-cb7795b64d83.png)

**Comment by roman87** [comment]
Don't forget to change the status to QA and assign to someone to test. In this case to me.

**Comment by roman87** [comment]
All fixed.
