### ISSUE TITLE
Create page with TM Repos build status and QA repo to it

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#190]
This is now done at https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-Repos-build-status and looks like this:

----

![image](https://cloud.githubusercontent.com/assets/656739/5603297/6692300a-9376-11e4-8b04-34cbd8b09a50.png)

----

what is really cool is that the travis for the QA (https://travis-ci.org/TeamMentor/TM_4_0_QA) is set to run ALL 3 sets of tests (Design, GraphDB and QA) which means that if (for example) these is a test that fails in the Design tests, the QA travis will be left in 'build:error' status

----

![image](https://cloud.githubusercontent.com/assets/656739/5603280/c1d9517e-9375-11e4-91c2-780aaa7ff968.png)

**Comment by roman87** [comment]
We should probably move this somewhere else at some point. But for now it looks good.
