### ISSUE TITLE
GraphDB randomly fails.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#191]
Graph DB fails when clicking on any link in navigate menu. This behavior is sporadic and random but consistent. 

![selection_029](https://cloud.githubusercontent.com/assets/1326120/5615701/c2ec7bf2-94cb-11e4-900f-9e62d0467e65.png)

![selection_030](https://cloud.githubusercontent.com/assets/1326120/5615707/c92a95a8-94cb-11e4-8a45-612df8524ba1.png)

![selection_031](https://cloud.githubusercontent.com/assets/1326120/5615731/f756889c-94cb-11e4-8218-9ff3a6d784de.png)

**Comment by DinisCruz** [comment]
I believe this has some DoS capabilities
