### ISSUE TITLE
When clicking on the TEXT of any filter, the top filter is selected.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#192]
![selection_032](https://cloud.githubusercontent.com/assets/1326120/5616180/ea6d11e2-94cf-11e4-9459-8632ac3f54c2.png)

**Comment by DinisCruz** [comment]
That is related to https://github.com/TeamMentor/TM_4_0_Design/issues/94

That right-hand side nav is not working, which is what I'm working on next

**Comment by roman87** [comment]
Ok then I am moving this to your queue.

**Comment by DinisCruz** [comment]
Here is the test that replicates the issue:

```coffee
  it.only 'Issue 192 - When clicking on the TEXT of any filter, the top filter is selected',(done)->
    page.html (html,$)->
      for td in $('td')
        input = $(td).find('input')
        if (input.length)
          label = $(td).find('label')
          $(input).attr().id.assert_Is('technology1')
          label.attr().for.assert_Is('technology1')   
      done()
```

Here is the test with a couple extra logging messages, showing the non-unique values of the input's **id** and lable's **for** values

![image](https://cloud.githubusercontent.com/assets/656739/5631622/cc211f9e-95bf-11e4-84ea-09886f551926.png)

**Comment by DinisCruz** [comment]
Here is the fix 

![image](https://cloud.githubusercontent.com/assets/656739/5632381/28049cfe-95c6-11e4-863d-955c14689236.png)

here is the regression test 

```coffee
  it.only 'Issue 192 - When clicking on the TEXT of any filter, the top filter is selected',(done)->
    jade.login_As_User ->
      page.open '/graph/logging', ->
        # this code removes two rows so that only have the right-hand-side nav showing on page
        code = "children = document.documentElement.querySelector('.row').children;
                children[0].remove();
                children[0].remove();"
        page.chrome.eval_Script code, ->
          page.html (html,$)->
            for td in $('td')
              input = $(td).find('input')
              if (input.length)
                value = $(td).text()
                label = $(td).find('label')
                $(input).attr().id.assert_Is(value)
                label.attr().for.assert_Is(value)
            done()
```

**Comment by DinisCruz** [comment]
Fixed with https://github.com/TeamMentor/TM_4_0_Design/commit/08bbd85136870746095467f108f5cc0aa7e52886 and https://github.com/TeamMentor/TM_4_0_QA/commit/73c783456050f875d35dd43af511beca43e54aec

**Comment by roman87** [comment]
I thought @luchia was going to take a look and see if it is doable to have the checkboxes and  receive the checkbox event?

**Comment by DinisCruz** [comment]
even if we can get an event from a checkbox, we agreed that for Jade you can only have 1 selected option on the right

**Comment by luchia** [comment]
So we don't actually need the checkboxes anymore right...? Because only one can ever be selected.

**Comment by DinisCruz** [comment]
Yes, no need for checkboxes in Jade

**Comment by roman87** [comment]
Ok cool so I am closing this one.
