### ISSUE TITLE
Wire the step down navigation.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#195]
As we talked on the call, once the user hits navigate they should be brought into the main UI. Each time a user clicks on a level, they are brought down to that level and are shown the tree of that level. The user can go back with breadcrumbs.
Lucy can you put a couple of screen shots on how it would look like.
Thanks.

**Comment by luchia** [comment]
Hey @roman87 and @DinisCruz, take a look at these and tell me if it's possible.

* User goes to Navigate page and clicks Principles & Standards (or Guidance I think it is now)
* User clicks Cryptographic Storage
![navigatepage](https://cloud.githubusercontent.com/assets/4547737/5622078/f6961d74-9588-11e4-8f03-f8f5461066cb.jpg)

* User clicks Use a strong PRNG to open the 2nd level directory
![first-directory](https://cloud.githubusercontent.com/assets/4547737/5622077/f69093fe-9588-11e4-992d-5c541a53da2e.jpg)

* User can click 3rd level directory to continue down the tree
![2nd-directory](https://cloud.githubusercontent.com/assets/4547737/5622076/f6896110-9588-11e4-92c0-2375a5dc3fe4.jpg)

Does that make sense?

**Comment by roman87** [comment]
Yea, except we are skipping the first step and going straight into first level directory, right?

**Comment by luchia** [comment]
That could work too. Saves us from using a page that is different to our layout as well (first screenshot).

**Comment by luchia** [comment]
Assigned to Dinis, so he can give his feedback.

**Comment by DinisCruz** [comment]
This is now working

Starting on **http://localhost:1337/graph/Guidance** which is the top level

#### Guidance:

![image](https://cloud.githubusercontent.com/assets/656739/5889618/b3bacd66-a428-11e4-81f3-ac7b8aae5f21.png)

if **Logging** is clicked, we get

#### Guidance : Logging

![image](https://cloud.githubusercontent.com/assets/656739/5889619/cda795c4-a428-11e4-9bf2-0edd1b440661.png)

if **Protect Logs** is clicked, we get

#### Guidance : Logging : Protect Logs
![image](https://cloud.githubusercontent.com/assets/656739/5889624/e0593e7a-a428-11e4-916a-3182cb8ab2a0.png)

Notice the **NAVIGATE** bar which has the links for:  **Guidance**, **Logging** and **Protect Logs**

![image](https://cloud.githubusercontent.com/assets/656739/5889629/05805f08-a429-11e4-974a-84c0f68c2d85.png)

Clicking on **Logging** in the nav bar, brings up back to the **Logging** page

![image](https://cloud.githubusercontent.com/assets/656739/5889634/2844fb2a-a429-11e4-8923-f49bc6b2551a.png)

and the same for clicking on **Guidance**

![image](https://cloud.githubusercontent.com/assets/656739/5889636/9449fe60-a429-11e4-92ba-1bd687a11337.png)

**Comment by roman87** [comment]
Looks good! great stuff!!!
