### ISSUE TITLE
What should happen when an already logged in user returns to TM

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#196]
Now that we have session persistence (due to https://github.com/TeamMentor/TM_4_0_Design/issues/175) what should be the page shown to users when returning with a valid login session?

At the moment when they open the home page (http://localhost:1337/) they see the default non-logged-in page

![image](https://cloud.githubusercontent.com/assets/656739/5626810/38902ca2-9588-11e4-9841-8d585387a0e9.png)

And there is no way to get to the user pages (like for example http://localhost:1337/user/main.html) . Unless they login again or open that link directly

**Comment by roman87** [comment]
Lets leave it the way it is until we have session persistence stored in the graph database, like it is supposed to :)

**Comment by DinisCruz** [comment]
Making this a P0 so that I'll fix it for the beta (fix is quite simple)

**Comment by roman87** [comment]
this is not a priority for the beta. Filtering and data manipulation is.

**Comment by DinisCruz** [comment]
Here is the test that represents the bug
```coffee
  it.only 'Issue 196 - What should happen when an already logged in user returns to TM', (done)->
    jade.login_As_User ->
      jade.page_User_Main (html, $)->
        page.chrome.url (url_user)->
          page.open '/',->
            page.chrome.url (url_root)->
              url_root.assert_Is_Not url_user
              done()
```

**Comment by DinisCruz** [comment]
done, 

Test that confirms the fix:

````coffee
  it.only 'Issue 196 - What should happen when an already logged in user returns to TM', (done)->
    jade.login_As_User ->
      jade.page_User_Main (html_user_main, $)->           # get html of user page after login
        page.open '/', (html_direct)->                    # get html of direct opening up / page (while logged in)
          html_direct.assert_Is html_user_main            # ensure they are the same
          jade.page_User_Logout ()->                      # logout user
            page.open '/', (html_after_logout)->          # get html of direct opening up / page (after logout)
              html_direct.assert_Is_Not html_after_logout # confirm it is not the same as logged in page
              page.chrome.url (url)->
                url.assert_Contains('/index.html')        # confirms redirect to 'index.html'
                done()
```
