### ISSUE TITLE
filter text wrapping under checkboxes (right hand-side nav) 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#197]
As with what is happening with the total's value,  the filter's text needs to not wrap under the checkbox

Here is what the prob looks like

![image](https://cloud.githubusercontent.com/assets/656739/5634185/f186bea4-95d5-11e4-9d88-cf84cce051e7.png)

**Comment by luchia** [comment]
Strange, it doesn't do it on mine -

![screen shot 2015-01-07 at 12 52 33 pm](https://cloud.githubusercontent.com/assets/4547737/5640047/193c3d20-966c-11e4-9b75-c85dcfa46b29.png)

Anyway, I did some googling and found what I needed to do but for some reason, only some tables are affected by this in the #filters div. Dinis, can you have a look at this for me?

![screen shot 2015-01-07 at 1 14 43 pm](https://cloud.githubusercontent.com/assets/4547737/5640273/489a8cf4-966f-11e4-854e-a8c601d1dace.png)

**Comment by DinisCruz** [comment]
It is fixed with your latest changes
