### ISSUE TITLE
Left-hand-side query selection must have a visual clue and needs to be clickable (to clear filter)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#198]
On the left, when a query is selected (like in the case bellow), there should be a visual clue that of which one is selected and clicking on it should remove the filter

![image](https://cloud.githubusercontent.com/assets/656739/5634250/5597f6e2-95d6-11e4-9cf7-d6fadc9496ba.png)

Making this a P0 since it is related to https://github.com/TeamMentor/TM_4_0_Design/issues/164 (and needs to be fixed before that)

**Comment by DinisCruz** [comment]
test that confirms issue 

```coffee
  it.only 'Issue 198 - Right-hand-side query selection must have a visual clue and needs to be clickable (to clear filter)',(done)->
    jade.login_As_User ->
      page.open '/graph/Logging', (html, $)->
        linkText = "Centralize Logging"
        if $('#containers a').html() is null              # return if link is not there
          done()
          return
        page.click linkText, (html, $)->                  # click on link
          $('#containers a').html().log().assert_Is('')   # bug: this value should be be empty
          done()
```

**Comment by DinisCruz** [comment]
Here is what the fix looks like

![image](https://cloud.githubusercontent.com/assets/656739/5635527/c1afad10-95e1-11e4-8068-dd92813b40e4.png)

or

![image](https://cloud.githubusercontent.com/assets/656739/5635542/dc2579e0-95e1-11e4-9b64-9d0275d5a13e.png)

**Comment by DinisCruz** [comment]
Test is now a regression test
```coffee
  it 'Issue 198 - Right-hand-side query selection must have a visual clue and needs to be clickable (to clear filter)',(done)->
    jade.login_As_User ->
      page.open '/graph/Logging', (html, $)->
        linkText = "Centralize Logging"
        if $('#containers a').html() is null                  # return if link is not there
          done()
          return
        page.click linkText, (html, $)->                      # click on link
          $('#containers a').html().log().assert_Is(linkText)
          done()     
```

**Comment by DinisCruz** [comment]
Fixed with https://github.com/TeamMentor/TM_4_0_Design/commit/b73e0304aca9aed59d799ccb618e22a10955390f
and
https://github.com/TeamMentor/TM_4_0_QA/commit/98852592e3e8e895c3d330d532ebd071f1f6e79c

**Comment by roman87** [comment]
Fixed.
