### ISSUE TITLE
Breadcrumbs are broken

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#199]
![breadcrumbs](https://cloud.githubusercontent.com/assets/656739/5635527/c1afad10-95e1-11e4-8068-dd92813b40e4.png)

This is not correct, they should not have list-style-types.

**Comment by luchia** [comment]
This is fixed -

![screen shot 2015-01-07 at 10 44 04 am](https://cloud.githubusercontent.com/assets/4547737/5638938/2958c28a-965a-11e4-89a3-f8cf3f7757a0.png)
![screen shot 2015-01-07 at 10 44 09 am](https://cloud.githubusercontent.com/assets/4547737/5638939/298cd070-965a-11e4-8685-3f91d5c8aef9.png)

**Comment by DinisCruz** [comment]
Nice once, 

@luchia small request, when documenting the fix can try to point to the commit that did this fix (it makes it easier to review and to learn)

**Comment by luchia** [comment]
Sure. Re-assigning to me after our meeting this morning, there is some work to do to make the navigation of these more obvious.

**Comment by DinisCruz** [comment]
Yap, we're going to bake this breadcrumbs into a nice navigation

**Comment by luchia** [comment]
This is what they look like at the moment -

![screen shot 2015-01-08 at 11 23 41 am](https://cloud.githubusercontent.com/assets/4547737/5656534/d11c50fc-9729-11e4-82a8-f011b038b9f8.png)

Style might change a bit (feedback, changing my mind etc) but the structure is there. @DinisCruz I have re-assigned back to you so you can do your thing with the logic on these. [I left the breadcrumbs commented out in the mixin file](https://github.com/TeamMentor/TM_4_0_Design/commit/6eb90ca7ae315d320fbcbc0df464484513d20730#diff-23d4ea778261837faeebd0770580fb9bR143).

**Comment by DinisCruz** [comment]
Cool, I've fixed the UnitTests and will take it from here 

Nice work :)

**Comment by roman87** [comment]
Yep, looks really good.

**Comment by roman87** [comment]
TeamMentor/Master#914

**Comment by DinisCruz** [comment]
You get the 'invented word of the day' :trophy: 

![image](https://cloud.githubusercontent.com/assets/656739/5729828/52f44e1c-9b6d-11e4-8324-118ec5ab92c7.png)

**Comment by roman87** [comment]
Hahaha.. I did invent the word :). These are bugs/tasks/feature requests that belong to a story :)

**Comment by DinisCruz** [comment]
https://github.com/TeamMentor/TM_4_0_Design/issues/195 addresses this issue

**Comment by roman87** [comment]
Yes can be closed.
