### ISSUE TITLE
Make font on filters and queries font a bit smaller

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#201]
That should make it easier to focus on the main articles content

**Comment by luchia** [comment]
Can you please tell me what you think of this?

![screen shot 2015-01-07 at 12 58 12 pm](https://cloud.githubusercontent.com/assets/4547737/5640117/2605e1ea-966d-11e4-9d6e-16c3b0622516.png)

**Comment by DinisCruz** [comment]
I like it :)

**Comment by DinisCruz** [comment]
this is done, closing it

**Comment by roman87** [comment]
and looks quite nice.
