### ISSUE TITLE
Table row border-bottoms are missing

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#202]
![border-bottom](https://cloud.githubusercontent.com/assets/656739/5635527/c1afad10-95e1-11e4-8068-dd92813b40e4.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-01-07 at 11 10 41 am](https://cloud.githubusercontent.com/assets/4547737/5639208/dbfc8b30-965d-11e4-8abe-0167eb15ad71.png)

**Comment by roman87** [comment]
This is fixed.
