### ISSUE TITLE
Swap navigate button and home button in navigation

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#203]

**Comment by luchia** [comment]
This has been fixed -

##### Original
![screen shot 2015-01-07 at 10 46 01 am](https://cloud.githubusercontent.com/assets/4547737/5638953/775b7374-965a-11e4-950e-68d63aa27666.png)

##### Fixed
![screen shot 2015-01-07 at 10 46 32 am](https://cloud.githubusercontent.com/assets/4547737/5638954/77921974-965a-11e4-9ee0-3ed126b44f80.png)

**Comment by DinisCruz** [comment]
@roman87 wasn't the idea to also renamed 'home' to 'search' 

Which actually I quite like since this new TM should be 'search focused'

**Comment by DinisCruz** [comment]
yap, closing this one

**Comment by roman87** [comment]
So now we have a question on where to keep "my saved articles" "my teams articles" etc. Which originally was supposed to be under the navigate list. i.e. under "index". I think we will need to come back to this one at some point soon.
