### ISSUE TITLE
Tidy SCSS files

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#205]
I've just been copying and pasting my styles from the CSS files, so there is a bit of clutter and excess code in those files.

**Comment by luchia** [comment]
[Jade is finished.](https://github.com/TeamMentor/TM_4_0_Design/commit/109e0ea4927e1e5081e69f7fdd46a789a7e3b5a0)

**Comment by luchia** [comment]
[Flare is finished as well.](https://github.com/TeamMentor/TM_4_0_Design/commit/72b4e480ac6e842b490ec55ffdd7cf0936b8160b)

**Comment by DinisCruz** [comment]
yap done
