### ISSUE TITLE
Add page to render jade minixs directly

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#212]
This is a TM_4_0_Design page that will allow the direct rendering of Jade mixins

Making this a P0 since it is needed for the development of https://github.com/TeamMentor/TM_4_0_Design/issues/120, https://github.com/TeamMentor/TM_4_0_Design/issues/113 and https://github.com/TeamMentor/TM_4_0_Design/issues/93 (and a bunch of other P1 issues)

Dev actions:

* [x] with GET request, pass get parameters as model
* [ ] with POST request, pass post data as model to view (NOT IMPLEMENTED - since we can pass viewModel JSON as serialised JSON in a get request)
* [x] support two ways to resolve the mixin to use: 
 * in url path
 * via get parameter
* [x] mixin to execute is provided as parameter

There should be no XSS concerns since Jade is secure-by-default and all data is encoded-in-context (that said this will make it easier to run the fuzz described in https://github.com/TeamMentor/TM_4_0_Design/issues/210)

If this works ok, it might also be very useful to do the same type of rendering for jade pages

This should be easy to do since all the code functionality and services required are already in place

**Comment by DinisCruz** [comment]
Since there [doesn't seem to be a way](https://github.com/jadejs/jade/issues/1811) to render Mixins directly, here is the code that can be used to simulate it:

```coffee
jade   = require('jade')
        code = "include globals.jade\n" +
               "h2= tm_version\n" +
               "+save-div"
        log code
        jadePath = process.cwd().path_Combine('/source/jade/_mixins/tmp.jade')
        log jade.compile(code, {filename: jadePath })({abc:'aa'})
```

**Comment by DinisCruz** [comment]
done with commit https://github.com/TeamMentor/TM_4_0_Design/commit/f676f9db32b396aae8ae36a7ea543c46b565e8c9

The syntax is:  http://localhost:1337/render/mixin/**{mixin file name}}**/**{mixin name}**?**params**

Here are some examples of this new feature in action:

* http://localhost:1337/render/mixin/images/image-securityinnovation-logo
![image](https://cloud.githubusercontent.com/assets/656739/5653057/b3ade2c2-96ae-11e4-97cc-ca1be0f0a715.png)
* http://localhost:1337/render/mixin/user-mixins/login-form
![image](https://cloud.githubusercontent.com/assets/656739/5653069/d3365764-96ae-11e4-9049-0e64528ee0f1.png)
* http://localhost:1337/render/mixin/search-mixins/directory-list?title=AAAAAA
![image](https://cloud.githubusercontent.com/assets/656739/5653091/ffcbc6e2-96ae-11e4-98c2-c15235894b90.png)

**Comment by DinisCruz** [comment]
@luchia can you review this (and close it once you confirm that it is working)

I think you will find that this technique of rendering the mixins directly is VERY powerful (try with different values)

**Comment by luchia** [comment]
This is working.
