### ISSUE TITLE
Rename 'Home' in the navigation bar to 'Search'

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#216]
A more accurate description for the User.

**Comment by luchia** [comment]
![screen shot 2015-01-08 at 11 34 53 am](https://cloud.githubusercontent.com/assets/4547737/5656560/616e6726-972a-11e4-94fb-fa9c7782cdfa.png)

[This has been done.](https://github.com/TeamMentor/TM_4_0_Design/commit/abc0cb8ca3d820153c0638a2d996b83375ccea15). Re-assigned to Dinis to update his tests.

**Comment by DinisCruz** [comment]
This is done

**Comment by roman87** [comment]
Lets make sure we mark the resolution as fixed when we close and lets keep the type.

**Comment by DinisCruz** [comment]
ok
