### ISSUE TITLE
When graph DB cannot authenticate to the backend, it should abort any data loading.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#220]
Currently, when GraphDB cannot authenticate to the backend, due to invalid user, worng authkey etc, it still downloads as much data as it can. This results in database being incomplete and causes graphDB to crash when query on non existent data set is performed. Which is probably related to https://github.com/TeamMentor/TM_4_0_Design/issues/191

**Comment by DinisCruz** [comment]
This is not relevant at more since GraphDB does not need to talk with the TM 3.5 server any more

**Comment by roman87** [comment]
Yep, obsolete
