### ISSUE TITLE
GraphDB should not crash when it can't fulfil a query

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#221]
When there is not enough data in the graph database to fulfill a query, it should return an error and not crash.
Related to #220

**Comment by DinisCruz** [comment]
Yeah that backend code is probably the one most unstable and with the least amount of code coverage

**Comment by roman87** [comment]
Cool, good idea to make it table.

**Comment by roman87** [comment]
this is fixed.

**Comment by DinisCruz** [comment]
Yeah, I have not seen that error for a while. @roman87 and @michaelhidalgo if you see it , please open an issue for it
