### ISSUE TITLE
Explore the idea to add known searches to the search dropdown in Jade

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#223]
We can't do this dynamically (since we have no JS in Jade) but if we can add an editable dropdown box to the search field, that would help the user to find a good search

at the moment the user will see its past searches:

![image](https://cloud.githubusercontent.com/assets/656739/5678145/2b670bc0-97e7-11e4-8296-fbb58f2833f3.png)

and it would be good to show this list 

![image](https://cloud.githubusercontent.com/assets/656739/5678154/4d3f79c6-97e7-11e4-8bfc-52656c06e66d.png)

**Comment by roman87** [comment]
Personally, I think this is too much information of the user and for the dropbox. But we can discuss.

**Comment by luchia** [comment]
Don't we already cover known/popular searches with the things we display on the user/main page?

**Comment by roman87** [comment]
That is true. I think this is a  feature we should have strictly in flare. lets not make things more complicated than they have to be.
