### ISSUE TITLE
Should w - Buy TravisCI Pro Subscription

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#224]
As per the thread https://twitter.com/DinisCruz/status/553486501372522496 with a PRO account our tests, will run the tests much faster (and will add some level of security to our tests). This sounds simple but I already spend considerable amounts of time waiting/checking for a travis build to start

Here are the plans: https://travis-ci.com/plans (the **Startup** is good enough for us)

TravisCI is working great for us, so its time to make it an official part of our test infrastructure (btw as you can see on https://travis-ci.org/o2platform/FluentSharp, Travis also supports C# (via mono) so we could eventually use it to build and test our main TeamMentor 3.5 codebase)

**Comment by roman87** [comment]
We need to discuss the pro's and cons of using Travis vs TC. As it is now, our main CI platform is TC with Travis being used for convenience. If we are to move to Travis as the main TC platform, we need to understand the full implications. In particular some question are:

1. What can we co in travis that we cannot do in TC
2. What can we do in TC that we cannot do in travis
3. What are the security or other risks associated with both platforms.
4. What is the implication to our deployment/staging/testing model

For now, I am making this a P4, changing this into a question.

**Comment by DinisCruz** [comment]
travis is working

**Comment by roman87** [comment]
I thought TC was working as well :)? Is it not working because we did not configure it correctly or is it because of TC limitation?

**Comment by DinisCruz** [comment]
Closing this since we don't need a TracisCI subscription for now (only if we have private repos)
