### ISSUE TITLE
Improve and fix GraphDB data retrieval API

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#225]
This is needed in order to allow https://github.com/TeamMentor/TM_4_0_Design/issues/195 and https://github.com/TeamMentor/TM_4_0_Design/issues/94

While looking at the GraphDB code also see if the root causes of https://github.com/TeamMentor/TM_4_0_Design/issues/221 and https://github.com/TeamMentor/TM_4_0_Design/issues/220 can be addressed

**Comment by DinisCruz** [comment]
Here is the main reason the GraphDB is currently quite unstable and hard-to-setup, it only has 59% code coverage (I just moved the 'db creation and parsing code' into the main GraphDB code (which is where it needs to be)):

From: https://coveralls.io/r/TeamMentor/TM_4_0_GraphDB

![image](https://cloud.githubusercontent.com/assets/656739/5711833/664ad3fa-9aa5-11e4-9aff-ba658ff15c5a.png)

Note: Ignore the 100% at the top, since that reflects the **master** branch, and the current code changes are reflected in the [Issue_225_GraphDB_Fix](https://github.com/TeamMentor/TM_4_0_GraphDB/tree/Issue_225_GraphDB_Fix) branch

**Comment by DinisCruz** [comment]
This is just about done, with the latest commits (all is synced now) 

![image](https://cloud.githubusercontent.com/assets/656739/5807002/96d7659e-a016-11e4-921d-5ef828a57c99.png)

The Design_4_0 UI is using the updated REST API (Swagger based), which looks like this

![image](https://cloud.githubusercontent.com/assets/656739/5806988/65cdc0ba-a016-11e4-8cb5-4e51c9560086.png)

There are still a couple minor things to iron out, but I will might open them as separate issues (and take the other P0 first)

**Comment by roman87** [comment]
Cool. Good stuff.

**Comment by DinisCruz** [comment]
You can close this one, the new Swagger API is really working well and is stable

**Comment by roman87** [comment]
Sure once you merge all your latest changes to master  and I can spin it up :)

**Comment by roman87** [comment]
Yep, all good and awesomely working.

**Comment by DinisCruz** [comment]
We actually need to document that, since it now our official GraphDB docs
