### ISSUE TITLE
Main Home/Search page needs a bit of aesthetic tweaking

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#226]
Now that we have added content, the main Jade page could look a bit of a facelift. 
First the spacing between the articles and the headings is evenly double, which makes it look all monolithic. The whole page also directs the user's attention away from Search, which should be the main point of the page.
Then specific issues.
1. The last item is too low and is being covered by the browser URL location when I mouse over a link (at least in Linux FF)
2. The numbers on the right can miss align when the browser is resized just right. Doesn't happen all the time but in this instance it did.  The size of the browser is 709px x 1069px
3. When I mouse over another link, the box still remains around the previously selected link. I am not sure if that is a big deal actually, just wanted to point that out.

![img1](https://cloud.githubusercontent.com/assets/1326120/5684175/f5e3ead0-97fb-11e4-9707-c3fedea86158.png)

**Comment by luchia** [comment]
Hey Roman, I've worked on the specific issues for this issue and would like your feedback so far. I'm struggling to build something alternate to keep the search bar prominent (like making it sticky), but will keep trying.

![screen shot 2015-01-12 at 10 35 20 am](https://cloud.githubusercontent.com/assets/4547737/5697813/66d3e05e-9a47-11e4-9939-f1f72a0987ab.png)
![screen shot 2015-01-12 at 10 36 55 am](https://cloud.githubusercontent.com/assets/4547737/5697814/66d513de-9a47-11e4-8522-3ffbe257c146.png)
![screen shot 2015-01-12 at 10 37 03 am](https://cloud.githubusercontent.com/assets/4547737/5697815/66df7db0-9a47-11e4-9afb-d8aa11fb1a50.png)
![screen shot 2015-01-12 at 10 38 28 am](https://cloud.githubusercontent.com/assets/4547737/5697817/66ed7cd0-9a47-11e4-84cd-f9fa7ae10e96.png)

**Comment by luchia** [comment]
This is the solution I came up with for the search bar -

![scroll](https://cloud.githubusercontent.com/assets/4547737/5698366/f115f012-9a57-11e4-8f0e-7724aad67e83.gif)

Still needs work in mobile.

**Comment by luchia** [comment]
The work in mobile -
![mobile-scroll](https://cloud.githubusercontent.com/assets/4547737/5698443/c10e117c-9a59-11e4-8d1d-488b986cd1e2.gif)

Transitioning from mobile to desktop view -
![mtod](https://cloud.githubusercontent.com/assets/4547737/5698458/ece4cd5e-9a59-11e4-9c5b-b09088a19e62.gif)

**Comment by luchia** [comment]
Re-assigned back to me because I realised you can't check it until I push my code to Github.

**Comment by roman87** [comment]
Looks good on the pictures!

**Comment by luchia** [comment]
[This has been pushed to the repo now.](https://github.com/TeamMentor/TM_4_0_Design/commit/f7110562c46fe8114ee48821dd3dcb181ec32087) 

To see it, you will need to remove comment lines from jade/mixins/user-mixins.jade:
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L140)
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L161)
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L162)
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L181)
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L182)
* [Here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L202)
* [And here](https://github.com/TeamMentor/TM_4_0_Design/blob/5aa74265d391ed14eabee78413f90b31cce2b57c/source/jade/_mixins/user-mixins.jade#L203)

This is just filler content so you can see the scroll in action. This works without it but we don't have enough content to make the page scroll, so you wouldn't be able to see it. When you're finished checking, the filler content can be removed.

Let me know what you think.

**Comment by roman87** [comment]
The scrolling looks pretty awesome! 
Couple of small things.
1. Do you think we can somehow maybe make the spacing less between the header and the first line of the content. I.e. between Recently Viewed Articles and Certificate Logging for example, so they look like they are part of one whole. In other words, so we somehow differentiate the separate sections of the page?
![selection_062](https://cloud.githubusercontent.com/assets/1326120/5733577/238594aa-9b73-11e4-8a60-226fb19567ed.png)

2. Still an issue with the numbers when resizing. 
![selection_059](https://cloud.githubusercontent.com/assets/1326120/5733596/6e4e824e-9b73-11e4-89e6-8577ff05553e.png)

**Comment by luchia** [comment]
Why do articles even have numbers @roman87 and @DinisCruz? Shouldn't it only be search terms?

**Comment by roman87** [comment]
The numbers are needed for popular search items and top articles. For popular search items they represent how popular a search item is. In our case, how many times any user had searched for this keyword.
Top article numbers represent the number of times an article had been opened. and hence, how popular it is.
We can do away with numbers, but I think it gives a nice feedback to the user. What do you think?

I really like the new spacing between the header and a list item. Looks good.

**Comment by DinisCruz** [comment]
on the use of numbers, have you seen how Discourse do it? Check it out for example on https://discuss.atom.io/ 

They provide nice feedback on what links have been clicked

**Comment by luchia** [comment]
I am having issues recreating your bug Roman. 

Re the popular search items - is it really going to actually signify how many searches it's had with a badge? I think it'd be better if we did something like Reddit or the link Dinis shared has, if that's what you want to represent:

![screen shot 2015-01-21 at 12 53 31 pm](https://cloud.githubusercontent.com/assets/4547737/5830464/8d094ac6-a16c-11e4-8f80-ba191e1c70ce.png)

Something which represents it's ranking (most searched to least searched) and how many searches it's had? What do you guys think?

**Comment by roman87** [comment]
Well.. badge that you suggest has a connotation that the popularity can be move up or down by using up or down arrow. I am not sure that is the experience we want the user to have. As the user should not be able to change the popularity of the search. I am actually fine with removing the numbers from popular search items altogether if it feels better.

**Comment by luchia** [comment]
Yeah, not the arrows so much but the ranking and the amount of times searched would be useful to have. Roman, tell me what you think about this - whether it stands out enough or it needs something else:

![screen shot 2015-01-22 at 10 03 27 am](https://cloud.githubusercontent.com/assets/4547737/5847929/99357f74-a21e-11e4-862d-2ca9b54c607c.png)
![screen shot 2015-01-22 at 10 03 34 am](https://cloud.githubusercontent.com/assets/4547737/5847926/993058be-a21e-11e4-884d-73909abf4b70.png)
![screen shot 2015-01-22 at 10 03 43 am](https://cloud.githubusercontent.com/assets/4547737/5847927/99349ec4-a21e-11e4-960b-6d048ea0df93.png)
![screen shot 2015-01-22 at 10 03 48 am](https://cloud.githubusercontent.com/assets/4547737/5847928/99352e2a-a21e-11e4-8591-1a02d2b57780.png)

**Comment by roman87** [comment]
Probably looks  a bit small. and kinda lonely. I actually think we need to keep the numbering style consistent between the filters and the numbers here.

**Comment by luchia** [comment]
Sure, that makes sense. Seeing as I can't recreate your bug, I decided to add columns to the links which you can see [here](https://github.com/TeamMentor/TM_4_0_Design/commit/29321e774998238fed52c73b3251be184652dda9). Below are some screenshots -

![screen shot 2015-01-23 at 5 39 27 pm](https://cloud.githubusercontent.com/assets/4547737/5871313/06845bfa-a327-11e4-9c53-859aea5de2a5.png)
![screen shot 2015-01-23 at 5 39 33 pm](https://cloud.githubusercontent.com/assets/4547737/5871314/06849aa2-a327-11e4-864a-617cc505862b.png)
![screen shot 2015-01-23 at 5 39 36 pm](https://cloud.githubusercontent.com/assets/4547737/5871315/0684ef5c-a327-11e4-8044-a6393307c1fc.png)

My only issue with this solution is that once you get to mobile view and the columns fill the screen, the badge is on it's own line and takes up a bit of space. It doesn't look bad though -

![screen shot 2015-01-23 at 5 39 39 pm](https://cloud.githubusercontent.com/assets/4547737/5871319/200838d0-a327-11e4-84a8-c843fe6b5cbf.png)
![screen shot 2015-01-23 at 5 39 41 pm](https://cloud.githubusercontent.com/assets/4547737/5871320/200e6764-a327-11e4-8dc7-b80e876629a0.png)

Let me know what you think.

**Comment by roman87** [comment]
I think its fine and looks good. Closing this.

**Comment by roman87** [comment]
Just make sure it makes it to Dev branch :)
