### ISSUE TITLE
Popular Search Terms do not survive a node restart

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#227]
Relates to:
#175 
#113 

Before Restart:

![selection_046](https://cloud.githubusercontent.com/assets/1326120/5686997/127fb934-9816-11e4-8470-56f43aa99064.png)

After Restart:
![selection_047](https://cloud.githubusercontent.com/assets/1326120/5687006/1f2a050e-9816-11e4-8fe5-1bdef31d3c98.png)

**Comment by DinisCruz** [comment]
yeah, those 3 are hard-coded in there
