### ISSUE TITLE
Angular JS vs React in Flare

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#228]
Since Flare is going to start with light JS, we should keep in mind that these days (in 2015) there might be other options when compared with AngularJS

[React](http://facebook.github.io/react/) in an interesting option

It looks like React has quite a lot of performance focus, for example this is why Atom Editor uses React:
* http://blog.atom.io/2014/07/02/moving-atom-to-react.html
* http://blog.atom.io/2014/07/22/default-to-react-editor.html
* http://blog.atom.io/2014/07/24/decorations.html

comparisons with AngularJS:
* https://www.codementor.io/reactjs/tutorial/react-vs-angularjs
* https://www.quora.com/Pete-Hunt/Posts/Facebooks-React-vs-AngularJS-A-Closer-Look
* http://versus.com/en/react-vs-angularjs
* http://noelwelsh.com/programming/2014/08/17/angularjs-vs-react/

Marking as P4 since this is something we should keep an eye on. Maybe do a prototype once there is a bit of meat in Flare or we hit something that has the need for performance (like a table that has hundreds or hundreds or rows)

**Comment by roman87** [comment]
Yep, we definitely want to be on the bleeding edge, as this is something we most likely not going to change in the next few years. At the same time not as much on the bleeding edge that we hit bugs of all sorts :)

**Comment by DinisCruz** [comment]
so React is being made and supported by Facebook, which kinda runs a big website :)

**Comment by roman87** [comment]
I am not a big fan of Facebook's usability :) maybe React is not the best idea :) Anyways is this something we have to decide now or is this something that can wait?

**Comment by DinisCruz** [comment]
I don't use FB, but it is quick and fast (my wife uses it)

Yeah we can wait for this, the first implementation of Flare will be done using AngularJS

**Comment by roman87** [comment]
Ok, so can we close this question for now?

**Comment by DinisCruz** [comment]
ok

**Comment by DinisCruz** [comment]
For reference I just had another look at ReactJS vs AngularJS and here are the reasons why I think we should keep on the current path and use Angular on TM 4.0
- Angular 1.3 is an MVC framework with really good support for: Controllers, Services and Views (React on its own admission is mainly focused on the 'View' component)
- Angular 2.0 seems to contain most of the big advantages currently mapped to React, so although the jump from Angular 1.3 to 2.0 seems to be quite steep, it will allow us to have access (if needed) to the current perceived React advantages
- It seems that one of the big advantages of React is it speed, and I don't think we will need that kind of DOM manipulation speed anytime soon (since we will be using the server-side graphdb for that)
- most comparisons on Angular vs React seem to:
  a) conclude that React is better
  b) be written by users that did not had a lot of experience with AngularJS, and I would say with a lot of experience of jQuery (note that If I get my way we will NOT be using jQuery on TM 4.0 (i.e. it is a banned API :)  ))
  c) focus on simple scenarios (where Angular might be overkill)
  d) complain about Angular 'complexity' (which again implies not very deep Angular knowledge)
  e) don't cover how to test Angular/React
- There are not a lot of published books about React (with the first ones coming out at the end of 2015). Compare this with the dozen books written about Angular
- The current TM dev team already has good knowledge of Angular (specially since we use it on TM 3.5)
- AngularJS security seems more mature than React (note for example the use of CSP) and documentation about it
- I quite like how AngularJS Javascript looks like (specially when written in CoffeeScript) vs ReactJS Javascript which does seem to contain a lot more DOM manipulation (ie. just like jQuery). Of course that on this one I'm bias for Angular because I know more Angular than React :)

**Comment by romichg** [comment]
I think we closed that topic :). It is too late in the game now to make any changes anyways, so I am glad we are happy with the path we chose :)
