### ISSUE TITLE
Remove emoticons from status messages

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#229]
We should remove the emoticons from status messages. 
![selection_052](https://cloud.githubusercontent.com/assets/1326120/5708148/a78d9ea4-9a5c-11e4-85ee-4a955e329417.png)

**Comment by luchia** [comment]
I have fixed the error messages that I could, but some of them come from the backend by the looks of it -

![screen shot 2015-01-13 at 9 57 17 am](https://cloud.githubusercontent.com/assets/4547737/5713693/a3c0b866-9b0a-11e4-8e07-7842a25418ff.png)

Assigning to Michael so he can either tell me how to change these or he can change them.

**Comment by luchia** [comment]
Michael and I had a look at this today and it seems like it was only the mixin that had smiley faces, not the backend.

So this has been fixed and needs to be checked now.

**Comment by michaelhidalgo** [comment]
This is how it looks like after Lucy did the fix : 

@roman87 , have you seen other places where there are emoticons?

![screen shot 2015-01-12 at 7 05 00 pm](https://cloud.githubusercontent.com/assets/1732035/5714469/ecae15cc-9a8e-11e4-8bea-ff507d6d570f.png)

**Comment by michaelhidalgo** [comment]
I fixed a broken test with this Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/232

The change is fairly simple as I just changed the assertion to match the returning value (which does not have the smiley face).

**Comment by michaelhidalgo** [comment]
Now it is passing in Travis https://travis-ci.org/TeamMentor/TM_4_0_Design

**Comment by roman87** [comment]
Don't forget that there is a bunch of frown faces there as well :)
