### ISSUE TITLE
Change password reset message

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#230]
We should change the password reset message to what we have now in TM 3.5
"If you entered a valid address, then a password reset link has been sent to your email address."

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/59c2a9b8743c675693b3eab4127d57d770fb04a9).

**Comment by michaelhidalgo** [comment]
This is fixed.

**Comment by michaelhidalgo** [comment]
Assigning it to me to write a test for it.

**Comment by roman87** [comment]
Looks like we can't test this unitll #242 is fixed. Assigning to @michaelhidalgo for unit test.

**Comment by michaelhidalgo** [comment]
Test case for this is already here https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/regression-sprint-1.coffee#L32

**Comment by roman87** [comment]
Looks goodl
