### ISSUE TITLE
Create alert for user to see when their password does not meet TM requirements

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#231]
We have in-browser validation for when a user doesn't enter a correct email address but we do not have a way to tell the user what the password should contain. This is important because TM has many requirements for a password to be acceptable and it may take a couple of tries before the user could submit a new one.

Suggestions were made to have individual messages for each variance - eg. If the user submits a password that is too short, it will tell them it is too short. The problem with this is that a user could submit a password that is too short AND with a no non-number character, we couldn't alert them to both.

Another suggestions has been to create an alert that tells them on submission what our password requirements are. This is also a good idea, but it still is likely that our user will fail to sign up for TM before they succeed, which is something we want to help them with.

I will work on having this information available on the Sign Up form without requiring submission, perhaps underneath the password form input or above it.

**Comment by luchia** [comment]
Two options that I came up with are below.

##### Prompts on top of the input
![screen shot 2015-01-13 at 11 01 09 am](https://cloud.githubusercontent.com/assets/4547737/5714389/9f1509da-9b13-11e4-8b2f-058dd49e73bd.png)

##### Prompts underneath the input
![screen shot 2015-01-13 at 11 01 25 am](https://cloud.githubusercontent.com/assets/4547737/5714399/b9dc0462-9b13-11e4-8293-d97d6b02e846.png)

I prefer it above the input because it makes sense that we would tell a user what is required of them before they do it.

**Comment by luchia** [comment]
Some more work with spacing on the second screenshot (prompts below inputs) -

![screen shot 2015-01-13 at 11 32 45 am](https://cloud.githubusercontent.com/assets/4547737/5714669/fd62e8fa-9b17-11e4-99f0-f787429eabc3.png)

**Comment by roman87** [comment]
I think this looks good now. Closing
