### ISSUE TITLE
Add TOC statement to Jade sign up form

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#233]
The same as Flare, we do not have a small prompt that tells the user they agree to our terms and conditions on sign up.

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/843e515f15c4138539eddb3b0d7437d7fd714323) -

![screen shot 2015-01-13 at 12 15 44 pm](https://cloud.githubusercontent.com/assets/4547737/5715021/0d709fe8-9b1e-11e4-9068-b75674e7ddf8.png)

**Comment by roman87** [comment]
I am not sure if this is a good idea ether. @tlaloc75 what do you suggest? Personally to me terms and conditions on a sign up page is a big turn off.

**Comment by roman87** [comment]
This agreed to and is working fine.
