### ISSUE TITLE
Terms and Conditions page has no navigation (Jade)

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#235]
It's a really long page with no indication of what is contained in it. I think we'd be helping our users if we gave them some sort of table of contents or sub-navigation so they can access any specific parts that interest them.

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/f2c807184d7d9ca3c34d40438b6527036688b41c) -

![screen shot 2015-01-13 at 2 04 11 pm](https://cloud.githubusercontent.com/assets/4547737/5715880/17d32f64-9b2d-11e4-8ba4-906bfaa9badc.png)

**Comment by roman87** [comment]
Honestly, I am not sure its a good idea @tlaloc75  what do you think?  This is a legal document that is quite generic, nobody really reads it, and making it something more than what people are used to expect from this type of link may have some negative effects.

**Comment by roman87** [comment]
So it seems like this actually what is liked, as this breaks up the dull pattern of usual terms and agreements.
There is an issue with the navigation. It seems like it is a bit off. When I click on "License Grants" for example, it skips the first few lines.
![selection_056](https://cloud.githubusercontent.com/assets/1326120/5733473/7d2fb622-9b71-11e4-9ace-f39a5b9f9d16.png)

![selection_057](https://cloud.githubusercontent.com/assets/1326120/5733489/a6949302-9b71-11e4-8e43-a7ebf9425aee.png)

How license grant actually starts:
![selection_058](https://cloud.githubusercontent.com/assets/1326120/5733494/bc87e7e0-9b71-11e4-92c7-19cdf8871863.png)

**Comment by luchia** [comment]
So I managed to hack together a fix. This is caused by our sticky nav covering where the actual heading is.

**Comment by roman87** [comment]
When I click on "Termination" nothing happens.
I am starting to thing this is becoming more trouble than its worth :) Let me know what you think?

**Comment by luchia** [comment]
That was a broken link that I missed, I fixed the typo in [this commit](https://github.com/TeamMentor/TM_4_0_Design/commit/51b8013967a37ef2464d5f0cbd11fd11706a8977) and they all work now.

**Comment by romichg** [comment]
done
