### ISSUE TITLE
Update Flare footer to match Jade footer (landing pages)

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#236]
I did some work for #234 and updated the footer in the process. I think it looks really good and would like to do a similar layout for our Flare landing pages.

**Comment by luchia** [comment]
[This has been done.](https://github.com/TeamMentor/TM_4_0_Design/commit/127c579f8c0bb719e3c4760ab7432b30d6e23ff1#diff-a8e48b3ed925827bc6dca14b7d11dc48R119)

**Comment by roman87** [comment]
hmm.. seems like I am getting a blank page on flare/all

![selection_054](https://cloud.githubusercontent.com/assets/1326120/5724387/309d9fca-9b19-11e4-8f39-672db6bb6ce1.png)

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/9a20dfc042f532a54afc465973ecfb3e84bf5843).

Dinis fixed the routing for this on the Dev branch, @roman87.

![screen shot 2015-01-14 at 9 53 36 am](https://cloud.githubusercontent.com/assets/4547737/5731910/1e34f77c-9bd5-11e4-8458-99d8b171b86b.png)
![screen shot 2015-01-14 at 9 53 46 am](https://cloud.githubusercontent.com/assets/4547737/5731911/1e3b8498-9bd5-11e4-9a9c-800aa8db4ea8.png)

**Comment by romichg** [comment]
done
