### ISSUE TITLE
TM_Design no longer starts under windows

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#237]
This seems like an argument parsing error, probably has something to do with not escaping some characters in the package.json file.  There is also some compilation warnings on npm update.

> contextify@0.1.11 install C:\TM40\TM_4_0_Design\node_modules\juice\node_module
s\jsdom\node_modules\contextify
> node-gyp rebuild

acorn@0.8.0 node_modules\jade\node_modules\constantinople\node_modules\acorn-glo
bals\node_modules\acorn
transformers@2.1.0 node_modules\jade\node_modules\transformers
├── promise@2.0.0 (is-promise@1.0.1)
├── css@1.0.8 (css-stringify@1.0.5, css-parse@1.0.4)
└── uglify-js@2.2.5 (optimist@0.3.7, source-map@0.1.43)
|
C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\jsdom\node_modules\context
ify>node "c:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild
acorn@0.8.0 node_modules\jade\node_modules\with\node_modules\acorn
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  contextify.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\jsdom\node
_modules\contextify\build\contextify.vcxproj]
C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\jsdom\node_modules\contex
tify\node_modules\nan\nan.h(1221): warning C4267: 'argument' : conversion from
'size_t' to 'int', possible loss of data [C:\TM40\TM_4_0_Design\node_modules\ju
ice\node_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]
C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\jsdom\node_modules\contex
tify\node_modules\nan\nan.h(1247): warning C4267: 'argument' : conversion from
'size_t' to 'int', possible loss of data [C:\TM40\TM_4_0_Design\node_modules\ju
ice\node_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]
C:\Users\Administrator\.node-gyp\0.10.33\deps\v8\include\v8.h(184): warning C45
06: no definition for inline function 'v8::Persistent<v8::Object> v8::Persisten
t<v8::Object>::New(v8::Handle<v8::Object>)' [C:\TM40\TM_4_0_Design\node_modules
\juice\node_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]
C:\Users\Administrator\.node-gyp\0.10.33\deps\v8\include\v8.h(184): warning C45
06: no definition for inline function 'v8::Persistent<v8::FunctionTemplate> v8:
:Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' [C:\T
M40\TM_4_0_Design\node_modules\juice\node_modules\jsdom\node_modules\contextify
\build\contextify.vcxproj]
     Creating library C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\jsd
  om\node_modules\contextify\build\Release\contextify.lib and object C:\TM40\TM
  _4_0_Design\node_modules\juice\node_modules\jsdom\node_modules\contextify\bui
  ld\Release\contextify.exp
  Generating code
  Finished generating code
  contextify.vcxproj -> C:\TM40\TM_4_0_Design\node_modules\juice\node_modules\j
  sdom\node_modules\contextify\build\Release\\contextify.node
jsdom@0.9.0 node_modules\juice\node_modules\jsdom
├── xmlhttprequest@1.7.0
├── nwmatcher@1.3.4
├── htmlparser2@3.8.2 (domelementtype@1.1.3, entities@1.0.0, domutils@1.5.0, dom
handler@2.3.0, readable-stream@1.1.13)
├── request@2.51.0 (caseless@0.8.0, aws-sign2@0.5.0, forever-agent@0.5.2, oauth-
sign@0.5.0, json-stringify-safe@5.0.0, tunnel-agent@0.4.0, stringstream@0.0.4, q
s@2.3.3, node-uuid@1.4.2, mime-types@1.0.2, combined-stream@0.0.7, form-data@0.2
.0, http-signature@0.10.1, bl@0.9.3, tough-cookie@0.12.1, hawk@1.1.1)
├── cssstyle@0.2.22
└── contextify@0.1.11 (bindings@1.2.1, nan@1.3.0)

Administrator@WIN-2F62C9N5USL /c/TM40/TM_4_0_Design (master)
$ npm start

> TM_4_0_Design@0.5.0 start C:\TM40\TM_4_0_Design
> npm run start-dev

> TM_4_0_Design@0.5.0 start-dev C:\TM40\TM_4_0_Design
> node_modules/supervisor/lib/cli-wrapper.js -i node/tests/ --extensions 'coffee
,js' app.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! TM_4_0_Design@0.5.0 start-dev: `node_modules/supervisor/lib/cli-wrapper
.js -i node/tests/ --extensions 'coffee,js' app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TM_4_0_Design@0.5.0 start-dev script.
npm ERR! This is most likely a problem with the TM_4_0_Design package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/supervisor/lib/cli-wrapper.js -i node/tests/ --extensi
ons 'coffee,js' app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_Design
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\nodejs\\\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "run" "start-dev"
npm ERR! cwd C:\TM40\TM_4_0_Design
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\TM40\TM_4_0_Design\npm-debug.log
npm ERR! not ok code 0
 
npm ERR! TM_4_0_Design@0.5.0 start: `npm run start-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TM_4_0_Design@0.5.0 start script.
npm ERR! This is most likely a problem with the TM_4_0_Design package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start-dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_Design
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm
-cli.js" "start"
npm ERR! cwd C:\TM40\TM_4_0_Design
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\TM40\TM_4_0_Design\npm-debug.log
npm ERR! not ok code 0

Administrator@WIN-2F62C9N5USL /c/TM40/TM_4_0_Design (master)
$

**Comment by DinisCruz** [comment]
I think it is because windows does not recognise node js files like osx/linux does

can you try this 
```sh
node node_modules/supervisor/lib/cli-wrapper.js -i node/tests/ --extensions 'coffee
```

which is basically prepending ```node``` to the commands you can see at ```npm run```

**Comment by roman87** [comment]
yep that worked. Cool!

**Comment by roman87** [comment]
Crated a wiki page with the instructions. https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-run-GraphDB-and-NodeTM-under-Windows

**Comment by DinisCruz** [comment]
Cool, and I just added the issues https://github.com/TeamMentor/TM_4_0_Design/issues/241 so that you can use **npm start** on windows (which is the standard way to start tm)
