### ISSUE TITLE
Express is running under debug mode

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#239]
As described in our own [Code Assisted Penetration Testing of a NodeJS App](http://blog.securityinnovation.com/blog/2014/10/code-assisted-penetration-testing-of-a-nodejs-app.html) SI blog, we need to handle the case of running Express outside Debug mode (which we shouldn't in production environments)

At the moment we are affected:

![image](https://cloud.githubusercontent.com/assets/656739/5720631/bf874eb6-9b1e-11e4-8385-e721449edfc8.png)

* [ ] More research is needed
* [ ] Write Unit test to replicate issue

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by roman87** [comment]
Yep good one. We also need to take a closer look at all the modules we are depending on, their security, dependencies, support and maturity. That is exactly why we should limit the modules we use and be carefull when we deside to use one.

**Comment by DinisCruz** [comment]
> That is exactly why we should limit the modules we use and be carefull when we deside to use one. 
yap, and I always take that into account when adding a new dependency

Believe it or not, I'm actually quite conservative when adding new dependencies, and always try to limit them to the maximum 

And when I pick an npm module to import, I tend to favour simple vs complex (i.e. a large number of dependencies is definitely not something that I reward)

**Comment by roman87** [comment]
I am pretty sure you do. My point is that we should document these well and understand the whole dependency tree :)

**Comment by DinisCruz** [comment]
>  understand the whole dependency tree :)

Good luck with that

I think there are a lot on Node Community that would like something like that (have you seen https://nodesecurity.io/), maybe something like https://www.owasp.org/index.php/OWASP_Dependency_Check for Node

**Comment by roman87** [comment]
Well then its a security risk :). We are dependent on code that is of an unknown vendor, unknown support and we don't really know what code that code depends on :)
Sounds a bit dodgy if I put it that way no?

**Comment by DinisCruz** [comment]
it is dodgy and it is why the whole application security world is a mess, specially since everybody is doing it:  Maven, NuGet, Node, etc..

**Comment by roman87** [comment]
Not that I want to start a philosophical discussion here, but that is why Cobol is still around :)

**Comment by DinisCruz** [comment]
On a parallel thread, there is a case for us (namely SI) to be involved in a 'locked-down' version of Express (i.e. a secure-by-default version of Express, or another node based web server), since we will need it

**Comment by romichg** [comment]
Closing this discussion due to TTL.
