### ISSUE TITLE
Login_Controller.loginUser throws Cannot read property 'Login_Status' of undefined

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#240]
When the answer from

![image](https://cloud.githubusercontent.com/assets/656739/5721544/cbca7ac0-9b2a-11e4-8899-ebae61a7de5f.png)

is null

here is the error

![image](https://cloud.githubusercontent.com/assets/656739/5721504/6384adf0-9b2a-11e4-8535-29fcd34c69ef.png)

Worryingly this was not picked up by the TM_Design tests, but by this TM_QA test:

![image](https://cloud.githubusercontent.com/assets/656739/5721576/267aac88-9b2b-11e4-9b80-777dd7ad238a.png)

First task is to add an test to TM_Design to replicate this issue (so that we eventually add it to the regression tests)

P0 Since this actually breaks the normal site usage (probs in logging in)

**Comment by roman87** [comment]
A bit unrelated, it is good we are finding/fixing all these issues. However I am worried that we are finding them before we have our beta release. Process wise it would be much more efficient to fix these after the beta release. I am considering moving this to P1

**Comment by michaelhidalgo** [comment]
Good catch Dinis, can you please assign it to me as I developed that feature?

**Comment by DinisCruz** [comment]
>  However I am worried that we are finding them before we have our beta release.

I view it the other way around, it's good that we are finding these issues (instead of having the users reporting them)

Also note that this is a side effect of code recently submitted https://github.com/TeamMentor/TM_4_0_Design/pull/222

**Comment by michaelhidalgo** [comment]
Yeah, I agree. I can see a lack of validation on the object per se. I was
wondering if the code coverage and the cyclomatic complexity would help to
avoid this nasty scenarios.
I think it would because cyclomatic complexity metric computes the
different decisions in code. I wonder if it is possible to measure the
coverage per method with coveralls?


2015-01-13 9:18 GMT-06:00 Dinis Cruz <notifications@github.com>:

> However I am worried that we are finding them before we have our beta
> release.
>
> I view it the other way around, it's good that we are finding these issues
> (instead of having the users reporting them)
>
> Also note that this is a side effect of code recently submitted #222
> <https://github.com/TeamMentor/TM_4_0_Design/pull/222>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/240#issuecomment-69759441>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by roman87** [comment]
Well, that is what beta is for right :) Its good that we are finding them, My focus though is to have a functioning beta at this time and issues like this can be resolved after we have delivered on functionality. Analogy is if you are building a house -  to put the roof on a house before you fix the stuck door :).  Anyways  now that I tested this issue it seems like it breaks the login and signup sequence all the time. Which is pretty bad, so this discussion doesn't really concern this issue as it should be fixed right the way.
What is concerning is that we have this pass our tests and make it into master repo. We should have full automation tests that include the login sequence. 
We also should think of a workflow where unstable (just pushed) code does not make it into master before it passes the tests. So all of new code should be merged into a separate branch say - Automation or unstable, and CI would automatically merge it with master once all the tests pass.

**Comment by DinisCruz** [comment]
well, what we should start doing very soon, is not to commit to master directly

We should start coding into the Dev branch and only merge into master if the https://travis-ci.org/TeamMentor/TM_4_0_QA tests (which at the moment will run all tests)

**Comment by roman87** [comment]
Yep, exactly. In TC can't we do the commit to master automatically if the tests pass?

**Comment by roman87** [comment]
All of this is actually described here:
https://tm4tm.teammentor.net/article/fc34db97-e5f0-48b7-9e53-ac7d010a1895
https://tm4tm.teammentor.net/article/fc34db97-e5f0-48b7-9e53-ac7d010a1895

**Comment by DinisCruz** [comment]
As per 
![image](https://cloud.githubusercontent.com/assets/656739/5724586/8e09d9f0-9b44-11e4-8bb0-3dc551e356c1.png)

the **?.** looks like a good fix for this (and other potential cases, like https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/controllers/Login-Controller.coffee#L50 )

**Comment by DinisCruz** [comment]
Actually, my original analysis was wrong, although the code that is failing is from that commit, the real prob was caused by ....
![image](https://cloud.githubusercontent.com/assets/656739/5724931/e3a3e872-9b46-11e4-9a3b-fae0f54b92b0.png)

(from https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/content/globals.jade#L17-L20)
... which removed the **name** attribute from the input field

@luchia for input fields you need to have the **name** attribute since that is the one used by the browser on the form submission. So in this case (see the fix I'm going to push next) we need to have both **id** and **name** attributes (with the convention being that both have the same name)

**Comment by roman87** [comment]
It looks like this might be then related to: #242

**Comment by DinisCruz** [comment]
yap

**Comment by DinisCruz** [comment]
will have a fix for it in about 10m to 20m

**Comment by DinisCruz** [comment]
This has been fixed with https://github.com/TeamMentor/TM_4_0_Design/commit/15914c6636c78db1a930edfcc43124912dd07724 but I still want to add the unit test for this edge case before we close this

@michaelhidalgo over to you :)

**Comment by michaelhidalgo** [comment]
Pull request https://github.com/TeamMentor/TM_4_0_Design/pull/258

**Comment by DinisCruz** [comment]
yap nice one @michaelhidalgo
