### ISSUE TITLE
Make Node run scripts compatible with Windows

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#241]
As per the prob described at  https://github.com/TeamMentor/TM_4_0_Design/issues/237#issuecomment-69735645, change these https://github.com/TeamMentor/TM_4_0_Design/blob/master/package.json#L15-L23 commands to use the **node**  process

**Comment by roman87** [comment]
Cool

**Comment by roman87** [comment]
This is address with https://github.com/TeamMentor/TM_4_0_GraphDB/pull/2 in  GraphDB and
https://github.com/TeamMentor/TM_4_0_Design/pull/277 in nodeTM

**Comment by DinisCruz** [comment]
done
