### ISSUE TITLE
Password reset no loner works

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#242]
Related to #230 

Looks like password reset has stopped working.
Once I click on the get password
![selection_055](https://cloud.githubusercontent.com/assets/1326120/5724758/cca1edfc-9b1b-11e4-80b2-7b0378d61051.png)
 button here is what I get.

**Comment by michaelhidalgo** [comment]
Yep, the name attribute for the email field is missing, which means it is not send as a part of the payload.

**Comment by DinisCruz** [comment]
This has been fixed with https://github.com/TeamMentor/TM_4_0_Design/commit/15914c6636c78db1a930edfcc43124912dd07724 and this error is the current error message for this edge case, so we can close this

**Comment by roman87** [comment]
This is now fixed.
