### ISSUE TITLE
Move mixins from content folder into _mixins folder

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#243]
https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/content/globals.jade
https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/content/images.jade

@luchia I want to open a number of mixin related issues, are you ok if I assign them to you?

**Comment by luchia** [comment]
Okay, I moved this into a shared-mixins directory and fixed all the routing issues with flare/jade that were caused when I moved the files.

And yes, feel free to pass on Jade related issues to me :)

**Comment by DinisCruz** [comment]
nice one, this is done
