### ISSUE TITLE
User signup is broken 

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#247]
One of the browser automation test we have validates that there is an error by checking the URL (which is good) but does not check the current error message.

I realized that the Signup is failing with an error indicating that Passwords do not match. It seems like the latest changes introduced in the UI did changed the name of the confirm password text box, which raises a validation because the look up of the body parameter is with different name.

This leads that the Signup will always fail with an error indicating that Passwords do not match.

**Comment by DinisCruz** [comment]
yap, you also need to change those names

but first add a test that represents this prob

**Comment by michaelhidalgo** [comment]
This has been fixed  with this Pull Request (that I merged) https://github.com/TeamMentor/TM_4_0_Design/pull/249/files

**Comment by roman87** [comment]
Look good
