### ISSUE TITLE
Create wiki page with instructions on how to set-up travis

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#250]
Use this issue since you can copy and paste images here. 

I will help you as you go along :)

**Comment by tekgirl77** [comment]
![image](https://cloud.githubusercontent.com/assets/6649463/5731194/984fe9d4-9b46-11e4-9b1b-a555b92a82fb.png)

**Comment by tekgirl77** [comment]
![image](https://cloud.githubusercontent.com/assets/6649463/5731227/e9707108-9b46-11e4-91ef-dd0ce85a93d9.png)

**Comment by tekgirl77** [comment]
![image](https://cloud.githubusercontent.com/assets/6649463/5731247/1a482410-9b47-11e4-8767-ca8090db4a70.png)

**Comment by DinisCruz** [comment]
Looking good, now you need to 
1) click on that Off button next to the TM_4_0_Design repo
2) click on the little tool next to it
3) push a commit 
4) see the build result
5) confirm that it shows here: https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-Repos-build-status

**Comment by roman87** [comment]
I am surprised travis doesn't have the same document :)

**Comment by tekgirl77** [comment]
https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-sync-Travis-CI-with-your-GitHub-repository

This issue can be closed.  :)

**Comment by michaelhidalgo** [comment]
Great job! It looks really nice and helpful!

**Comment by tekgirl77** [comment]
Thanks!  :)


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by roman87** [comment]
Good stuff. Closing. Salle, next time assign to someone else to QA (usually me:)) and change the status of an issue to Action:QA.

**Comment by tekgirl77** [comment]
Ok sounds good, thanks!


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]
