### ISSUE TITLE
Fix broken mixin refs in flare pages

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#252]
for example

![image](https://cloud.githubusercontent.com/assets/656739/5731747/2288b256-9b7f-11e4-874f-4d28e65fe2aa.png)

As part of this issue, write a test that will open all current flare pages directly and detect if there are any compilation errors (@DinisCruz or @michaelhidalgo will write this test, @luchia will fix the pages directly)

Making it a P1 because there are a number of Flare pages that currently are not visible due to compilation errors

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/c900ad229c65f748295a8ed05e3a33008add3f9a).

**Comment by roman87** [comment]
moving to P3 to align with Flare priorities.

**Comment by DinisCruz** [comment]
Done

**Comment by roman87** [comment]
@DinisCruz Do we need a test for this one?

**Comment by DinisCruz** [comment]
that was already being caught by a test, which now passes
