### ISSUE TITLE
Fix broken UI test that is hanging Travis (user sign-up with weak pwd related)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#253]
@michaelhidalgo  just hit this prob with https://travis-ci.org/TeamMentor/TM_4_0_QA/builds/46920320 

![image](https://cloud.githubusercontent.com/assets/656739/5731834/4080786a-9b80-11e4-97cf-da78ef4cf813.png)

and although on master the next build passed, this one https://travis-ci.org/TeamMentor/TM_4_0_QA/builds/46853434 had the same prob

@michaelhidalgo since this also happens on your fork, can you see if you can figure out the prob

P0 since this is actually breaking the QA test suite execution

**Comment by roman87** [comment]
Since this is an intermittent problem I am not sure it warrants a P0. But yes take a quick look.

**Comment by DinisCruz** [comment]
Main QA branch has not shown this issues in a couple builds (like https://travis-ci.org/TeamMentor/TM_4_0_QA/builds/46927909) 

If the next couple ones from Michael's PR doesn't have this, we can close this issue

**Comment by michaelhidalgo** [comment]
Yeah it seems like it is not longer happening

**Comment by DinisCruz** [comment]
ok closing it
