### ISSUE TITLE
Jade sign up forms are bland and boring

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#254]
![screen shot 2015-01-14 at 12 14 09 pm](https://cloud.githubusercontent.com/assets/4547737/5732953/e01b2d78-9be6-11e4-8881-0b8620c2ceb7.png)
![screen shot 2015-01-14 at 12 14 12 pm](https://cloud.githubusercontent.com/assets/4547737/5732954/e02946f6-9be6-11e4-94b1-20992c096b4c.png)

**Comment by roman87** [comment]
But they are Jade :) they are supposed to be blend and booring. Making it a P3 for now.

**Comment by luchia** [comment]
Not necessarily :)

![screen shot 2015-01-14 at 5 55 22 pm](https://cloud.githubusercontent.com/assets/4547737/5735745/b90f918a-9c16-11e4-83f8-285e7f7f33d0.png)
![screen shot 2015-01-14 at 5 56 05 pm](https://cloud.githubusercontent.com/assets/4547737/5735746/b91c300c-9c16-11e4-9ab2-d6fc5201a4d3.png)
![screen shot 2015-01-14 at 5 56 09 pm](https://cloud.githubusercontent.com/assets/4547737/5735747/b91da324-9c16-11e4-9864-719e6dc93800.png)
![screen shot 2015-01-14 at 5 56 18 pm](https://cloud.githubusercontent.com/assets/4547737/5735748/b92036f2-9c16-11e4-97d2-3e5c787a603c.png)

**Comment by DinisCruz** [comment]
I like it :+1:

**Comment by roman87** [comment]
The shading is actually too light on my screen. It almost blends everything in.

**Comment by roman87** [comment]
![20150114_102057](https://cloud.githubusercontent.com/assets/1326120/5743125/357970ce-9be5-11e4-9e63-a96f557b9b81.jpg)
![20150114_102927](https://cloud.githubusercontent.com/assets/1326120/5743132/421c0bd4-9be5-11e4-9722-952969e4a1ee.jpg)

**Comment by roman87** [comment]
Bumping this up to P0 as it is looking pretty bad on my screen. And chances are I am not the only one :)

**Comment by luchia** [comment]
Hey, take a look at these screenshots -

##### Sign Up
![screen shot 2015-01-21 at 12 16 09 pm](https://cloud.githubusercontent.com/assets/4547737/5830370/1fc650ea-a16b-11e4-9e7b-89da4d5201c5.png)

##### Login
![screen shot 2015-01-21 at 12 19 21 pm](https://cloud.githubusercontent.com/assets/4547737/5830369/1fc4f254-a16b-11e4-9725-a3d958511cd8.png)

##### Search Bar
![screen shot 2015-01-21 at 12 22 05 pm](https://cloud.githubusercontent.com/assets/4547737/5830367/1fc27132-a16b-11e4-9c99-dee87f7e5762.png)

##### Search Bar Selected
![screen shot 2015-01-21 at 12 22 07 pm](https://cloud.githubusercontent.com/assets/4547737/5830368/1fc28f50-a16b-11e4-9194-a48e2727d3a9.png)


You can also view them in the app on the Dev branch.

**Comment by DinisCruz** [comment]
merged into master

**Comment by roman87** [comment]
Still can't make the distincion on my screen.

**Comment by luchia** [comment]
@roman87, what do you think of the below screens? I had a go at adding darker colours but on the Mac screen it's too dark and quite ugly. Instead I added some drop shadows and am hoping I can get your opinion about whether it improves the contrast or not. Thank you.

![screen shot 2015-01-22 at 10 07 29 am](https://cloud.githubusercontent.com/assets/4547737/5848092/7badb00a-a220-11e4-85a0-395f29893dd5.png)
![screen shot 2015-01-22 at 10 07 38 am](https://cloud.githubusercontent.com/assets/4547737/5848093/7bd9d69e-a220-11e4-9522-6fc09644b1a8.png)
![screen shot 2015-01-22 at 10 07 45 am](https://cloud.githubusercontent.com/assets/4547737/5848094/7bf97e90-a220-11e4-9198-119b69855e08.png)
![screen shot 2015-01-22 at 10 07 47 am](https://cloud.githubusercontent.com/assets/4547737/5848095/7bfa82a4-a220-11e4-9609-ecfd7ff9260d.png)

**Comment by roman87** [comment]
Yea I think this looks much better. You can even make shadow a bit less and it would still have contrast.

**Comment by luchia** [comment]
Like this?

![screen shot 2015-01-23 at 9 42 41 am](https://cloud.githubusercontent.com/assets/4547737/5867154/44107406-a2e4-11e4-918e-28e066a393f4.png)
![screen shot 2015-01-23 at 9 42 51 am](https://cloud.githubusercontent.com/assets/4547737/5867155/443933e6-a2e4-11e4-96af-85b5a09aa2ed.png)
![screen shot 2015-01-23 at 9 42 58 am](https://cloud.githubusercontent.com/assets/4547737/5867156/443ddba8-a2e4-11e4-84e6-d267722536ca.png)

**Comment by roman87** [comment]
Yep looks good!
