### ISSUE TITLE
Breadcrumbs style is not quite right

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#255]
They don't quite fit in with the application and the rest of the style.

![screen shot 2015-01-14 at 12 16 31 pm](https://cloud.githubusercontent.com/assets/4547737/5732976/30eba71e-9be7-11e4-862e-f3000ab3757b.png)

**Comment by roman87** [comment]
Navigate button doesn't belong there, but I actually like the way it is, Jason also said he liked how it looks.

**Comment by luchia** [comment]
Okay, I will close it.
