### ISSUE TITLE
No :active link styles

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#256]
We should have these to make clear where users are.

**Comment by DinisCruz** [comment]
Yap that is very important

Btw, don't assign the Action:Dev to this kind of issue (that label is for backend code), the one you should be using is the Action:Design

**Comment by luchia** [comment]
So we had a couple of these already but not all of them. I've now covered these in the referenced commit. Will we call these dynamically @DinisCruz?

**Comment by DinisCruz** [comment]
> So we had a couple of these already but not all of them. I've now covered these in the referenced commit. Will we call these dynamically @DinisCruz?

Sorry @luchia , not following the question

What are we going to call dynamically?

**Comment by luchia** [comment]
The active links? For each page that is active, we need to define the class on the link so that it shows?

**Comment by DinisCruz** [comment]
yes you need to have a class so that we can apply it when the jade page is rendered on the server-side

**Comment by luchia** [comment]
Okay, well I created those and they are ready to be put in.

**Comment by DinisCruz** [comment]
sure
