### ISSUE TITLE
Showing articles/save button/clear button are not aligned correctly

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#262]
![screen shot 2015-01-16 at 11 49 51 am](https://cloud.githubusercontent.com/assets/4547737/5770424/e74a5520-9d75-11e4-87c3-2a3d5f67367e.png)
 
They are not level with each other as shown in the screenshot

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-01-21 at 1 48 07 pm](https://cloud.githubusercontent.com/assets/4547737/5830982/85c1c9f2-a174-11e4-9c72-b5a17d15cee8.png)
![screen shot 2015-01-21 at 1 51 01 pm](https://cloud.githubusercontent.com/assets/4547737/5830983/912a0020-a174-11e4-9f82-251cd6620c60.png)

**Comment by luchia** [comment]
Taking this back because they are broken on Flare -
![screen shot 2015-01-22 at 12 01 40 pm](https://cloud.githubusercontent.com/assets/4547737/5849230/713a091c-a22e-11e4-846e-f60c745eef4f.png)

**Comment by roman87** [comment]
Can you create a separate issue for this in flare and pass this to me to test.

**Comment by luchia** [comment]
Sure.

**Comment by roman87** [comment]
Looks good on jade. closing
