### ISSUE TITLE
Flare buttons are being overridden by Foundation

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#263]
![screen shot 2015-01-16 at 11 50 15 am](https://cloud.githubusercontent.com/assets/4547737/5770436/051c50bc-9d76-11e4-8297-f5908b1b23f3.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-01-21 at 1 48 07 pm](https://cloud.githubusercontent.com/assets/4547737/5830972/6927e2ae-a174-11e4-94f2-68bc0c476483.png)

**Comment by romichg** [comment]
done
