### ISSUE TITLE
Create a Threat Model for TM 4.0 (Jade, Flare and GraphDB)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#269]
Maybe using a tool like Microsoft Threat Modeling tool (windows only):

* http://blogs.microsoft.com/cybertrust/2014/04/15/new-microsoft-threat-modeling-tool-2014-now-available/
* http://blogs.microsoft.com/cybertrust/2012/08/23/microsofts-free-security-tools-threat-modeling/
* http://www.microsoft.com/en-us/download/details.aspx?id=42518

Or another tool (ideally an online one, which would work on OSX)

An key objective will be to map the threats into the unit tests, so that we have real-time metrics on how we are doing

We should also create a nice set of diagrams that visualise TM's Security, Attack Surface and Risks

Also map out relevant TM articles on this topic :) 

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by roman87** [comment]
This sounds like the Seattle team can help with. Asigning to me to story and prioritize.

**Comment by DinisCruz** [comment]
yeah, that would be great. In fact, I think the SI Services team has an SDL that they recommend (and help to implement) so it would be great to also map/follow that

**Comment by romichg** [comment]
Services team did a security assessment of TM and found no issues. We will continue to do periodic security assessments at major milestone releases.
