### ISSUE TITLE
Map out current security practices with 'Simplified Implementation of the Microsoft SDL'

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#270]
* http://www.microsoft.com/security/sdl/default.aspx
* docs can be downloaded from http://www.microsoft.com/en-us/download/details.aspx?id=12379

![image](https://cloud.githubusercontent.com/assets/656739/5792987/ef319ac2-9f29-11e4-94a0-39dae79a11cc.png)

We are already doing a lot of these, but it will be good to formalize them (for example on the one SDL steps that is missing is  [Create a Threat Model for TM 4.0 (Jade, Flare and GraphDB)](https://github.com/TeamMentor/TM_4_0_Design/issues/269) )

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by roman87** [comment]
Assigning to myself to story and prioritize

**Comment by romichg** [comment]
Great idea, we will need to rely on Services team to help with this one.
