### ISSUE TITLE
Improve TM 4.0 Page Performance

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#272]
As I was reading High Performance Browser Networking book (http://chimera.labs.oreilly.com/books/1230000000545), I realized that the author references  this tool http://www.webpagetest.org
This is a nice graph of the performance test applied to the latest version of TM 4.0

![screen shot 2015-01-18 at 12 32 14 pm](https://cloud.githubusercontent.com/assets/1732035/5794928/9f99c042-9f48-11e4-982e-8faff8a180ca.png)

Here is the actual performance result http://www.webpagetest.org/result/150118_7Z_VWE/1/details/

It seems like we could improve it a little bit !

**Comment by roman87** [comment]
Looks like content download is the biggest one. We really need to do this test once we are running in IIS.

**Comment by roman87** [comment]
Assinging to myself for storying and prioritization.

**Comment by romichg** [comment]
Done.
