### ISSUE TITLE
Add ability to configure the 3.5 backend server used in tmDesign

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#280]
Right now the server is hard coded to tmdev01-uno.teammentor.net we need this option to be configurable in the .tm.config.json file found in a directory higher than the tmDesign code (i.e. in ../)

**Comment by michaelhidalgo** [comment]
@DinisCruz according to this issue, I was thinking on adding a new value in here https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/misc/Config.coffee#L11

Do you agree?

**Comment by roman87** [comment]
Yes lets add it there for now.

**Comment by DinisCruz** [comment]
yap

**Comment by roman87** [comment]
Ok so it looks like the configuration is done here 
```
 @library_Data = path.join(@cache_folder, "library_Data")
@version = '0.1.1'
@enable_Jade_Cache = enable_Jade_Cache || false
-
+ @tm_35_Server ='https://tmdev01-uno.teammentor.net/'
+ @tmWebServices ='Aspx_Pages/TM_WebServices.asmx'
```
And not in the .tm.config.json file correct?

**Comment by michaelhidalgo** [comment]
Yes for now. I'm going to add a new issue because it needs more refactoring (i.e standardize the configuration in a new repo https://github.com/TeamMentor/node-teammentor)

**Comment by roman87** [comment]
Ok cool.

**Comment by roman87** [comment]
This works great.
