### ISSUE TITLE
Adjust column breakpoints on Jade

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#281]
When the columns break into desktop view at the moment, columns are really still too small (because the screen is too narrow) to be functional or to look good.

**Comment by luchia** [comment]
@DinisCruz, what do you think about the break points that I've adjusted for?

![screen shot 2015-01-22 at 10 34 44 am](https://cloud.githubusercontent.com/assets/4547737/5848270/52e8b848-a222-11e4-8381-0504084412d0.png)
![screen shot 2015-01-22 at 10 34 47 am](https://cloud.githubusercontent.com/assets/4547737/5848266/52e723ac-a222-11e4-976a-87f977474c65.png)
![screen shot 2015-01-22 at 10 34 50 am](https://cloud.githubusercontent.com/assets/4547737/5848268/52e78b6c-a222-11e4-9784-4e90d7e1403f.png)
![screen shot 2015-01-22 at 10 34 52 am](https://cloud.githubusercontent.com/assets/4547737/5848267/52e760a6-a222-11e4-9b9b-927dfc47629c.png)
![screen shot 2015-01-22 at 10 34 56 am](https://cloud.githubusercontent.com/assets/4547737/5848269/52e7f0e8-a222-11e4-9ba9-2149e275da2c.png)

**Comment by DinisCruz** [comment]
Still feel a bit of a jump, since you go from

![image](https://cloud.githubusercontent.com/assets/656739/5852535/64d2a3dc-a210-11e4-9100-daf9e77c1114.png)

to

![image](https://cloud.githubusercontent.com/assets/656739/5852539/6ff6d882-a210-11e4-8b27-16818a838262.png)

with just a couple pixels change (in the size of the window)

**Comment by roman87** [comment]
I don't this this is very important for this release. I think we can live with this in Jade.

**Comment by luchia** [comment]
Ohhh, I thought you meant that the content was too small in the columns Dinis, so I made the breakpoint larger so when they do break, there is more room for them. 

You could do something like below, for example, but I don't know how I would actually do that because we can't use flex-box to order columns or divs in Jade (legacy browsers don't support it).

![untitled-1](https://cloud.githubusercontent.com/assets/4547737/5865843/48bfff00-a2d8-11e4-8190-a6cd46626049.jpg)

**Comment by DinisCruz** [comment]
so on the diagram above which one is which (left and right)

**Comment by luchia** [comment]
Desktop view on the left, medium screen view on the right.

**Comment by roman87** [comment]
Again, lets not break our head over this with Jade. I suggest we close this and re-address when we are testing flare.

**Comment by DinisCruz** [comment]
ok, I think can't live with it as it is

**Comment by roman87** [comment]
I hope you mean "you can" :)

**Comment by DinisCruz** [comment]
yeah (just updated the comment)
