### ISSUE TITLE
Flare search bar has style issues

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#282]
![screen shot 2015-01-22 at 10 50 02 am](https://cloud.githubusercontent.com/assets/4547737/5848610/fe9c3b8a-a225-11e4-9787-8f15e446e26f.png)
![screen shot 2015-01-22 at 10 50 09 am](https://cloud.githubusercontent.com/assets/4547737/5848614/0ccd787c-a226-11e4-97cf-838b41f32d90.png)

The drop-shadow from Jade carries over and there is a gap between the two buttons.

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/8d94a76a7fa5f466e5cb29d8868710bca0aa2c56).

![screen shot 2015-01-22 at 11 21 27 am](https://cloud.githubusercontent.com/assets/4547737/5848859/1a01089e-a229-11e4-8795-3e95c350624c.png)

**Comment by romichg** [comment]
fixed
