### ISSUE TITLE
Add email links to error pages (Flare)

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#283]
Each page says to contact support staff if there are further issues but doesn't give a contact email.

![screen shot 2015-01-22 at 11 04 40 am](https://cloud.githubusercontent.com/assets/4547737/5848651/88099a5c-a226-11e4-91db-e32a5901b461.png)
![screen shot 2015-01-22 at 11 04 42 am](https://cloud.githubusercontent.com/assets/4547737/5848650/8809548e-a226-11e4-8dc1-4162810bec63.png)
![screen shot 2015-01-22 at 11 04 43 am](https://cloud.githubusercontent.com/assets/4547737/5848649/8807970c-a226-11e4-815c-fbe2d9298163.png)

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/be17a7578c4ad9bd5ee92dbbbf8d9605a39f450a).

**Comment by roman87** [comment]
These error messages are static pages. Why do we have them in Flare? Should this and the whole story covering this issue (https://github.com/TeamMentor/Master/issues/902)  be in Jade?

**Comment by luchia** [comment]
I thought I had put it in Jade already but maybe when we merged Flare and Jade, they didn't get brought over.

In any case, I've just added them to Jade. Did you want me to assign this to @DinisCruz or @michaelhidalgo to handle routing?

**Comment by roman87** [comment]
I think this issue can be closed then. There is already a story about error pages.
