### ISSUE TITLE
Jade styles are over-riding Flare forms

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#284]
![screen shot 2015-01-22 at 11 05 39 am](https://cloud.githubusercontent.com/assets/4547737/5848661/a9e47322-a226-11e4-8b59-6cc0f322cef9.png)
![screen shot 2015-01-22 at 11 05 43 am](https://cloud.githubusercontent.com/assets/4547737/5848662/aa0950ac-a226-11e4-8209-c02874939278.png)
![screen shot 2015-01-22 at 11 05 46 am](https://cloud.githubusercontent.com/assets/4547737/5848663/aa0c8448-a226-11e4-8cf3-779a0a26b31f.png)
![screen shot 2015-01-22 at 11 05 49 am](https://cloud.githubusercontent.com/assets/4547737/5848664/aa337210-a226-11e4-9e61-6615d97f9d98.png)

**Comment by luchia** [comment]
This has been fixed by removing the Jade CSS stylesheet. However, I need to now go through and apply all the styles that we need from Jade into Flare. This has already been done in the SCSS files but they aren't compiling yet so I need to do it in the CSS.

**Comment by roman87** [comment]
So one thing to remember, is that we should be re-using as much of Jade in Flare as possible. The site should be able to run with just one flare page. For example we would add the flare search page on top of jade. but everything else remains as Jade. Makes sense?

**Comment by luchia** [comment]
Good point. As we discussed in the meeting, I will be making mixins for shared styles between Jade and Flare. When the application compiles it's SCSS files, the two separate sites will pull shared styles from the one stylesheet, rather than having to import Jade's entire stylesheet and override styles with Flares stylesheets.

Roman should I create a new issue for this particular task? As this doesn't really relate to the title of this issue.

**Comment by roman87** [comment]
Yes absolutely, create an issue and label accordingly.

**Comment by luchia** [comment]
Flare navigation has been completed in #286.

**Comment by luchia** [comment]
Status update - Almost finished this issue, just have the user pages left to do.

**Comment by luchia** [comment]
Finished this work yesterday.

**Comment by romichg** [comment]
fixed
