### ISSUE TITLE
Large gap between heading and list group on Flare/help/index

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#285]
![screen shot 2015-01-22 at 11 06 47 am](https://cloud.githubusercontent.com/assets/4547737/5848669/cee0577c-a226-11e4-979d-2ccdb9205b57.png)

**Comment by luchia** [comment]
This has been fixed in the above commit.

![screen shot 2015-01-23 at 5 45 57 pm](https://cloud.githubusercontent.com/assets/4547737/5871363/c714d5b6-a327-11e4-928e-21ccb9a1536e.png)

**Comment by romichg** [comment]
done
