### ISSUE TITLE
Flare navigation is broken

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#286]
![screen shot 2015-01-22 at 11 07 59 am](https://cloud.githubusercontent.com/assets/4547737/5848681/f6bdd8d2-a226-11e4-90ef-0a8cfca0b0b5.png)

Menu icon is pushed down on desktop and mobile.

**Comment by luchia** [comment]
This is more of an application wide thing at the moment, so I've amended the title of this issue to reflect that -

![screen shot 2015-01-27 at 6 11 38 pm](https://cloud.githubusercontent.com/assets/4547737/5915314/fce1f248-a64f-11e4-8df9-3d11239b3b85.png)

**Comment by luchia** [comment]
Today, I spent more time locking down how Flare will work. This includes fixing the navigation. I created a test environment and spent time getting everything right and using flexbox as much as possible.

We now have three layouts - one for mobile, one for tablet, one for desktop. Everything fits in together nicer and has a much smoother look. I have not transferred this structure into the Flare style sheets but I will do that tomorrow. Check out the gif below to see how it works

![layout](https://cloud.githubusercontent.com/assets/4547737/5915337/58535b08-a650-11e4-80cd-a67783be74f2.gif)

**Comment by luchia** [comment]
Below are the three navbars in the referenced commit -

##### Application Nav
![screen shot 2015-01-28 at 11 55 53 am](https://cloud.githubusercontent.com/assets/4547737/5945932/c5bf9480-a77d-11e4-8c9f-1a3898ff0814.png)
![screen shot 2015-01-28 at 11 55 58 am](https://cloud.githubusercontent.com/assets/4547737/5945935/c5c28ee2-a77d-11e4-9117-61f6b41dbf8d.png)
![screen shot 2015-01-28 at 11 56 29 am](https://cloud.githubusercontent.com/assets/4547737/5945936/c5c39396-a77d-11e4-911e-afb8506c0faa.png)

##### Landing Page Nav
![screen shot 2015-01-28 at 11 57 38 am](https://cloud.githubusercontent.com/assets/4547737/5945933/c5c0a14a-a77d-11e4-85c3-85e13e274e8b.png)
![screen shot 2015-01-28 at 11 57 42 am](https://cloud.githubusercontent.com/assets/4547737/5945934/c5c25c24-a77d-11e4-9afb-a0e0e770458f.png)
![screen shot 2015-01-28 at 11 57 44 am](https://cloud.githubusercontent.com/assets/4547737/5945937/c5c461e0-a77d-11e4-8f29-2999c0fc1c0c.png)

##### Customer Navbar
![screen shot 2015-01-28 at 11 57 49 am](https://cloud.githubusercontent.com/assets/4547737/5945938/c5f08478-a77d-11e4-8a56-1c2866a1b340.png)
![screen shot 2015-01-28 at 11 57 53 am](https://cloud.githubusercontent.com/assets/4547737/5945940/c5f32796-a77d-11e4-83fe-bdd27016a715.png)
![screen shot 2015-01-28 at 11 57 56 am](https://cloud.githubusercontent.com/assets/4547737/5945939/c5f315ee-a77d-11e4-88c1-951580a4eee5.png)

Our problem with these now is that the TM Logo does not resize and fit itself within it's container (because it's a sprite). I am looking at trying to make it a responsive sprite but that is a separate issue and I will open one now.

**Comment by luchia** [comment]
@roman87, I had to work on this first because it affects how other issues are solved - #183 and #284.

**Comment by romichg** [comment]
fixed
