### ISSUE TITLE
Rename TM_4_0_GraphDB to TM_Graph

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#288]
Since GraphDB is basically now an API we can call it just TM_Graph (might as well drop the 4_0 part to).

This should be easy to do, but will require changes in the submodules references (I wonder how travis will handle that)

**Comment by roman87** [comment]
Not a priority for this release. We can do it after Beta. I do agree with the idea though. Maybe we can even think of a cool name for it.

**Comment by romichg** [comment]
This is done no?
