### ISSUE TITLE
We reached 1000 Commits

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#293]
![image](https://cloud.githubusercontent.com/assets/656739/5866955/7df4ac06-a28e-11e4-8446-bd6dfe8c7457.png)

Pretty cool milestone :)

**Comment by luchia** [comment]
:)

**Comment by roman87** [comment]
Yey!!! 
![selection_064](https://cloud.githubusercontent.com/assets/1326120/5869556/1548da10-a289-11e4-910b-320ebe358630.png)

![selection_065](https://cloud.githubusercontent.com/assets/1326120/5869557/19881bfe-a289-11e4-83f3-80a84ec1708e.png)

![selection_066](https://cloud.githubusercontent.com/assets/1326120/5869559/1e3e2c9c-a289-11e4-917d-266beefbe355.png)
