### ISSUE TITLE
Flare search bar is too flat

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#294]
Jade has a nice search bar -
![screen shot 2015-01-23 at 10 53 44 am](https://cloud.githubusercontent.com/assets/4547737/5867938/2f97e7c0-a2ee-11e4-9df8-2f3f26c80835.png)

See what we can do for Flares -
![screen shot 2015-01-23 at 10 53 27 am](https://cloud.githubusercontent.com/assets/4547737/5867940/3785790c-a2ee-11e4-9fcd-c382edf5606c.png)

**Comment by romichg** [comment]
done
