### ISSUE TITLE
Show a friendly error message when TM3.5 backend is not available

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#295]
When the user hits login, or anything else that requires communications to 3.5 back end and for some reason it is not available show a friendly error message. 
Lucy can you create a page and pass on to @michaelhidalgo  for implementation.
This is part of sprint 3 so no need to start on this now.

**Comment by luchia** [comment]
This has already been done. The pages are in the user directory (error-occurred, unavailable and upgraded .jade files) @michaelhidalgo.

**Comment by michaelhidalgo** [comment]
@roman87 can we close this issue, I believe it is similar to this one https://github.com/TeamMentor/TM_4_0_Design/issues/551

**Comment by roman87** [comment]
Yes agreed closing as dupe of #551
