### ISSUE TITLE
Find better solution for the 'NAVIGATE' clue

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#299]
Now that we have a working navigation (as seen on https://github.com/TeamMentor/TM_4_0_Design/issues/195#issuecomment-71344680) I think we can do better than the current **NAVIGATE** text

![](https://cloud.githubusercontent.com/assets/656739/5889629/05805f08-a429-11e4-974a-84c0f68c2d85.png)

**Comment by roman87** [comment]
Yea I agree "Navigate" text seems out of place here. we need something else.

**Comment by luchia** [comment]
I did quite a bit of work on this today and am really happy with how it looks. This is a more consistent style with 4.0 (ties in with the forms and search bar). Let me know what you think -

![screen shot 2015-01-27 at 12 28 08 pm](https://cloud.githubusercontent.com/assets/4547737/5912587/a4b4e446-a621-11e4-9132-32bbf7bd2f10.png)
![screen shot 2015-01-27 at 12 30 06 pm](https://cloud.githubusercontent.com/assets/4547737/5912588/a4e1d01e-a621-11e4-9cf9-a755add23e9d.png)

**Comment by roman87** [comment]
Um.. honestly, I am really not sure why we have "Navigate" button there in the firs place. It is a bit redundant no? and takes up a bit of space.I like the color change of the active level.

**Comment by DinisCruz** [comment]
I like the design element, but I agree that 'Navigate' sounds weird.

Maybe it is because 'Navigate' implies an action, where maybe 'Path' or 'Location' would make more sense?

**Comment by luchia** [comment]
Yeah, it's meant to show the path of the user. Path is probably a better word.

![screen shot 2015-01-27 at 12 30 06 pm](https://cloud.githubusercontent.com/assets/4547737/5915303/d49d0e44-a64f-11e4-8740-5ee0d56af598.png)

**Comment by DinisCruz** [comment]
Yap, PATH looks much better

![image](https://cloud.githubusercontent.com/assets/656739/5915998/f1f8d9ce-a603-11e4-92e5-fb7e793bcd4b.png)


btw @luchia there a little issue with the wrapping of items:

![image](https://cloud.githubusercontent.com/assets/656739/5916018/16f40da2-a604-11e4-8814-4987a9ab4a7a.png)

**Comment by luchia** [comment]
Woops, meant to post the Path photo. Re-assigned back to me to fix the wrapping issue.

**Comment by luchia** [comment]
Fixed in the referenced commit and have attached a screenshot with filler text -

![screen shot 2015-01-28 at 6 48 54 am](https://cloud.githubusercontent.com/assets/4547737/5926871/13a15310-a6ba-11e4-9c6e-014531a91dfd.png)

**Comment by luchia** [comment]
Taking this back because of the suggestion made with #348. To be able to make them work in together will require a different solution.

**Comment by luchia** [comment]
After some feedback, I have revised how the path appears and have come up with the following solution, which I think is a lot nicer and won't confuse the user (it looked too similar to the search bar before):

![screen shot 2015-01-29 at 11 20 00 am](https://cloud.githubusercontent.com/assets/4547737/5951127/530c348a-a7ae-11e4-9c96-c8fa075926c5.png)

**Comment by luchia** [comment]
Feedback from @Roman was that the style of this may clash with a search box if they are ever on the same page, so I decided to strip back the style and have something a little more plain -

![screen shot 2015-01-29 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/4547737/5951588/27c3f068-a7b5-11e4-9c60-cf7c62702b13.png)

**Comment by roman87** [comment]
I think this looks good. There is quite large spacing between each word and "/" I am not sure if that is necessary. It takes up too much space and confuses (at least me) visually.

**Comment by roman87** [comment]
Also it seems like the line spacing is quite large when the line wraps

![selection_077](https://cloud.githubusercontent.com/assets/1326120/5995556/2ec78f58-aa64-11e4-839e-aee89dd58d42.png)

**Comment by luchia** [comment]
Fixed in the referenced commit.

![screen shot 2015-02-03 at 10 49 17 am](https://cloud.githubusercontent.com/assets/4547737/6012352/c5d4af28-ab92-11e4-9adb-5c3ce2368702.png)

**Comment by roman87** [comment]
Feedback from Jason - This needs more work. The word GUIDANCE seems like it doesn't belong there. Maybe we should not show anything until the user clicks on something? Overall seems like we can do better style.

Hey, Lucy, maybe we should go back to the PARENT->CHILD->GRANDCHILD  style?

**Comment by luchia** [comment]
As per our meeting this morning, we discussed removing the sub-nav from the navigate/guidance index view. @DinisCruz, is this more to do with logic than view?

**Comment by DinisCruz** [comment]
one thing here is that the only reason 'Guidance' shows there is because that is the name of the root query

**Comment by luchia** [comment]
As per our meeting this morning, we are now only shown the breadcrumbs after the root URL. This removes the doubling up of headings when there is only one breadcrumb item. See below for example.

![screen shot 2015-02-05 at 11 04 34 am](https://cloud.githubusercontent.com/assets/4547737/6053178/cc49dbe4-ad27-11e4-90be-d1a6becc13f7.png)
![screen shot 2015-02-05 at 11 04 38 am](https://cloud.githubusercontent.com/assets/4547737/6053177/cc48eb1c-ad27-11e4-92be-ebd58b3caab8.png)

**Comment by roman87** [comment]
I think this looks good. Closing
