### ISSUE TITLE
Bug in top-level queries total number of articles

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#301]
The top level query 'Guidance' is not showing the correct number of articles

For example on **Guidance** it is showing only 51 (and it should show at least 794)

**http://localhost:1337/graph/Guidance**

![image](https://cloud.githubusercontent.com/assets/656739/5889663/8eb384fc-a42a-11e4-98fb-bcf3e6116dc1.png)

The other top level queries are better, but still not 100% accurate

* http://localhost:1337/graph/Category
* http://localhost:1337/graph/Phase
* http://localhost:1337/graph/Technology
* http://localhost:1337/graph/Type

![image](https://cloud.githubusercontent.com/assets/656739/5889667/e861a024-a42a-11e4-9118-2759c6882509.png)

The problem is in the GraphDB and happens during the creation of this mapping **http://localhost:1332/data/query_mappings/query-d994753ff409** (also ensure that the list of articles is unique, so that articles that appear on more than one query, are not duplicated in the list of articles in the parent queries)

**Comment by DinisCruz** [comment]
Done with latest commits

Guidance now looks like this

![image](https://cloud.githubusercontent.com/assets/656739/5907433/c5eabf54-a596-11e4-9e2c-62f28f9bc683.png)

**Comment by roman87** [comment]
This is done. However related to https://github.com/TeamMentor/TM_4_0_Design/issues/321

**Comment by DinisCruz** [comment]
the prob here was another one,

In here what was happening was that the issues where not being 'added up' (from the child-query to its parents (recursively)
