### ISSUE TITLE
Use spaces instead of Tabs for Jade pages

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#302]
Hi @luchia , I was editing a couple *.Jade pages and noticed that you used tabs (instead of spaces) for the tabbing of elements

It better to use spaces, since that is more compatible across multiple editors.

This is just an issue to raise your awareness, so please close it once you have read it.

I also created the page https://github.com/TeamMentor/TM_4_0_Design/wiki/Development-Style-Guide to contain our current development style guides (feel free to add your our ideas and best practices)

**Comment by luchia** [comment]
Hi Dinis, thanks for pointing it out. It's a habit to do tabs just from previous programming projects but I'll keep it at the forefront of my mind when working from now on.

Thank you.

**Comment by DinisCruz** [comment]
no worries, I usually set it on the IDE so that it defaults to 'Using spaces for tabs'
