### ISSUE TITLE
Write test for 'Account expired'

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#304]
As seen on https://github.com/TeamMentor/TM_4_0_QA/commit/448ff232de1becf92622778f68866d6b607982ed#commitcomment-9433663

**Comment by michaelhidalgo** [comment]
Yap, good catch, we do not have a test for this cases :)

**Comment by michaelhidalgo** [comment]
This is done https://github.com/TeamMentor/TM_4_0_QA/pull/6/files

**Comment by roman87** [comment]
All merged. Closing.
