### ISSUE TITLE
It is possible to brute force TM Usernames and Passwords

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#308]
#### Description
With the 4.0 changes to user login messages, it is now possible to brute force user's logins and password 

The user logins are discovered via the login and signup error messages

The password are brute forced using the known logins

#### Risk Analysis
This change was driven by the desire to improve the user's experience (3.5 provided no messages at all and it was quite problematic)

The use of strong passwords mitigates the risk

There is detailed logging messages for bad password, so if the logs are being monitored, brute force attacks will be detected

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by DinisCruz** [comment]
@roman87 I marked as 'By Design' since this is one of the risks that we are currently accepting as part of 4.0

**Comment by roman87** [comment]
Closing as non-actionable.
