### ISSUE TITLE
Lose the title on the graph (when viewed with a small width)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#309]
Note how the 'Java' title (top left)

![image](https://cloud.githubusercontent.com/assets/656739/5898665/8092d4d4-a549-11e4-8b4b-f950a97317ad.png)

is hidden here:

![image](https://cloud.githubusercontent.com/assets/656739/5898657/764e3e3c-a549-11e4-93db-cce508d1dbc3.png)

**Comment by luchia** [comment]
[This has been fixed -](https://github.com/TeamMentor/TM_4_0_Design/commit/6eb7b57f506d43576fb93830aa5a8d1c05ae1c82)

![screen shot 2015-01-27 at 10 50 24 am](https://cloud.githubusercontent.com/assets/4547737/5911521/5f9825d0-a612-11e4-80e4-b39a78ee253f.png)

**Comment by roman87** [comment]
This is fixed.
