### ISSUE TITLE
Password Reset console error when redirecting after resetting password

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#311]
Had I been paying attention, I would have notice that when the redirection to /guest/login-pwd-reset.html is performed, there is a console error :  Can't set headers after they are sent 

![screen shot 2015-01-26 at 5 33 30 am](https://cloud.githubusercontent.com/assets/1732035/5903860/d428ad62-a549-11e4-98e1-33ede868dc50.png)

This error is caused by the absence of a return when redirecting.

**Comment by michaelhidalgo** [comment]
Fixing it with this PR https://github.com/TeamMentor/TM_4_0_Design/pull/312

**Comment by DinisCruz** [comment]
merge is done

**Comment by romichg** [comment]
fixed
