### ISSUE TITLE
Remove the "Clear" Button from the Navigate page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#314]
It is redundant to have it on the jade page. We do not allow to select multiple filters at this time so the button is confusing.

**Comment by luchia** [comment]
[This has been fixed -](https://github.com/TeamMentor/TM_4_0_Design/commit/e204d81bb4fa902b48f3ddd8b1a08ddc9476386b)

![screen shot 2015-01-27 at 10 44 19 am](https://cloud.githubusercontent.com/assets/4547737/5911463/809221c4-a611-11e4-8797-c1ad61c87e0a.png)

**Comment by roman87** [comment]
All done.
