### ISSUE TITLE
Add GraphDB capability to perform Wikitext and Markdown transformations

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#315]
Markdown should be easy since we can use the same library used by Jade

WikiText transformation will require a little research and tests (specially to make sure it is as compatible as possible with the C#-based WikiText transformation currently happening on TM 3.5)

This is needed for https://github.com/TeamMentor/TM_4_0_Design/issues/194

**Comment by DinisCruz** [comment]
done on Dev , and can be seen in action on both the swagger APIs and on the Article pages

**Comment by roman87** [comment]
Yep, html and wikitext look good.
