### ISSUE TITLE
Add search capabilities to the TM GraphDB API

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#316]
This is needed for https://github.com/TeamMentor/TM_4_0_Design/issues/126

**Comment by DinisCruz** [comment]
The GraphDB API has now a new section called 'Search' and has the following methods:

![image](https://cloud.githubusercontent.com/assets/656739/5923697/5fb42a74-a64d-11e4-920a-daec0fa0902f.png)

**Comment by DinisCruz** [comment]
this is done, we need to improve the search capability, but those will be specific improvements

**Comment by roman87** [comment]
Well, we also need full article body search. I think this is part of this issue :)

**Comment by DinisCruz** [comment]
@roman87 I think we can close this , since the full text search is already covered by https://github.com/TeamMentor/TM_4_0_Design/issues/126

**Comment by roman87** [comment]
Ok will close this as a dupe.
