### ISSUE TITLE
Cache GraphDB generated json files in order to improve view performance

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#317]
Since the 'GraphDB generated json files' do not change for existing libraries, we can cache (or pre-generate) the json files used by the UI

For example the **query_tree** objects (like http://localhost:1332/data/query_tree/query-d994753ff409) which is are a bit expensive to calculate.

The latest version contains a first mini-pass at doing some of this caching, with the query results being stored in memory. This means that there is only one calculation of the **query_tree** objects per server.

But the best way to do this, will be to actually use temp files to store this info, since that will allow for the pre-calculation of those values.

The pre-calculation of json results will also help to deal with the weakest link at the moment of the TM GraphDB which is the levelDB and levelgraph (which still don't handle very well multiple requests)

**Comment by roman87** [comment]
I think that in memory caching is fine for the moment and it does not introduce any cache sync issues if data changes. Lets keep it that way it is and not put any more work on this.

**Comment by roman87** [comment]
Any work on file caching that is. If we can improve in-memory caching, we should do so.

**Comment by DinisCruz** [comment]
Done via the referenced commit

There is a new folder called 'data_cache' inside the '.tmCache' folder which contains the saved jsons (I will show it in action in the call)

The performance increase is significant and so if the DB stability

**Comment by roman87** [comment]
So far looks good. Performance is faster and haven't been able to crash the DB yet.
