### ISSUE TITLE
Review TM Design 'REST proxying' of requests to TM Graph, and check for URL Path manipulations

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#325]
At the moment TM Design is doing the typical REST proxying of requests, where it takes data from the user and uses it to create REST calls to the backend (in this case TM Graph).

This is a very dangerous proposition since payloads like **aaaa/../bbbb** or **aaaa&b=c#** would be modifying the REST call made to the backend REST service (from TM Design to TM Graph).

What is needed is a strong set of unit tests that confirms that the url generation of REST calls is done securely and there is no way to inject payloads into those calls

I actually think that we have a couple vulns already in the current TM Design since this is quite easy to do (from a coding point of view), AND, we don't have any unit tests that cover this specific scenario. See this presentation http://blog.diniscruz.com/2014/03/updated-presentation-of-resting-on-your.html for more details

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by roman87** [comment]
This is the wrong approach! What is needed is a strong set of input validation rules that validate user input. I am surprised we take unsanitised input from the user? 
From the navigation side, a URL that is not in the format we expect should be thrown out.

**Comment by roman87** [comment]
See #364 and #355

**Comment by DinisCruz** [comment]
> This is the wrong approach! 

what do you mean? The pattern to proxy requests? The use of strong/safe URL generation APIs to generate the REST calls?

> What is needed is a strong set of input validation rules that validate user input.

See my https://github.com/TeamMentor/TM_4_0_Design/issues/364#issuecomment-72424087 . I don't think that this is an Input Validation prob. NOT that I'm saying that we shouldn't validate and/or sanitise the input. My point is that the real solution is based on safe URL generation, and not on data validation

> I am surprised we take unsanitised input from the user? 

Welcome to the world of web development :) ... where how to handle user input is one of the hardest challenges.

Btw, we already do that in lots of places in TM 4.0, if you look at most controllers, there is no validation being done on user input.

For example, look at what we do with user login credentials: 

https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/controllers/Login-Controller.coffee#L42-L51

```coffee
    username = @.req.body.username
    password = @.req.body.password
```

at this stage, those values have had no validation done to them, and in this case I would argue that they shouldn't. It's up to the login server/service to figure out what to do with them, and what to accept (or not).

We might add some global limit (as in form fields should not have more than 1024 chars), but  the specific validation/sanitization should be done by the user/consumer of that data.

Another good example is the user sign-up: https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/controllers/Login-Controller.coffee#L167-L180

```coffee
    newUser =
              {
                  username : @.req.body.username,
                  password : @.req.body.password,
                  email    : @.req.body.email
              }
    options = {
                method: 'post',
                body: {newUser: newUser},
                json: true,
                url: @.webServices + '/CreateUser_Response'
              };

    request options, (error, response, body)=>
```
with again no validation done on TM_Design.

Btw, this is a really hard question, and one that all web development team face, ie: 'Where should data validation, sanitisation and encoding occur'

Note 1: On both examples, its totally safe to relay that data back to the user, since we use Jade to create the final HTML, which is able to encode in context (i.e. the ending is done based on the final location of that data (which is only known to the view))

Note 2: I think that there is an edge case for data validation which is 'Max data size of an data field', which we need to figure who is the best entity to do it without introducing two many side-effects and conner cases (It might be that 1024 or 256 is enough for all TM_Design entry points, but that is a separate question (i.e. see https://github.com/TeamMentor/TM_4_0_Design/issues/370)

>From the navigation side, a URL that is not in the format we expect should be thrown out.

Sure, but the question is who decides that format?

Btw, we shouldn't close this issue until we have tests that prove that we don't have this problem. We are doing this dangerous pattern (as the title describes), so what we need is assurance that we do it safely

**Comment by roman87** [comment]
By wrong approach, I mean that we should not be writing a test case that proves we have an issue. We need to build safe-checks into the code, like input validation, that validate and sanitize input. We do not need to have "a strong set of unit tests that confirms that the url generation of REST calls is done securely and there is no way to inject payloads into those calls" - this is a task already well accomplished by SAST and DAST scanners and manually by our Services team. 
We are on the defending side here, we need to build walls and moats. Catapults and cannons are for a different product that we are not building :)

**Comment by DinisCruz** [comment]
> By wrong approach, I mean that we should not be writing a test case that proves we have an issue. 

the test should prove that we don't have that issue.

In practice (as many of our regression tests shows), this  starts by writing a test that proves that we do have the issue, which helps the coding of the fix. Then once the issue is correctly handled, that test becomes a regression test

> We need to build safe-checks into the code, like input validation, that validate and sanitize input. 

sure, but those need to be verified by tests, specially to confirm that we don't re-introduce the prob in the future

> We do not need to have "a strong set of unit tests that confirms that the url generation of REST calls is done securely and there is no way to inject payloads into those calls" 

yes we do

> This is a task already well accomplished by SAST and DAST scanners and manually by our Services team.

nope, at best we have a low-hanging fruit pass by the scanners, and a best-effort by our Services team

at the moment none of them would be able to provide the kind of assurance that we need (unless they actually delivered tests like the ones I describe here).

And on the SAST front, do any of the commercial scanners handle NodeJS apps? I really have my doubts about the quality of their analysis (and I'm looking forward to seeing the results (when they are available))

> We are on the defending side here, we need to build walls and moats.

Correct, and we need to confirm that our walls and moats match our expectation (which is exactly what this set of tests is all about)

At the moment we already have tests that break when a new url mapping is added to express (the node web server), which is great. We also need to have tests that check the critical parts of our coding, and make sure they are not introducing security vulns. This is one of those tests

**Comment by roman87** [comment]
Ok we will agree to disagree on this one :) We should not write tests to validate what should not be working is not working. We can only write tests that prove what should be working is working. Otherwise (not counting few edge cases) we are getting into a world of DAST tools and we are not in that business.

**Comment by DinisCruz** [comment]
The referenced commit (https://github.com/TeamMentor/TM_4_0_Design/commit/46e66f4a0dc7a8dc437804f8549df6b4cda4da02) is designed to test this and to make sure the data is correctly encoded before being sent to the GraphDB.

The use of ```.url_Encode()``` will prevent the injection of payloads like ```../```

The only issue is that at the moment we are still not checking the url generation process and there is no way to check if the issue is not introduced in the future by mistake.

But for now, I think that we have this issue covered, so I'll mark it for close.

For reference here are the chars encoded by url_Encode(): https://github.com/o2platform/fluentnode/blob/master/test/utils/encoding.test.coffee#L4-L6

![image](https://cloud.githubusercontent.com/assets/656739/6200148/f22d8094-b462-11e4-8533-f620bdfec954.png)

**Comment by romichg** [comment]
done.
