### ISSUE TITLE
Should - Error message reveals information about account?

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#327]
![image](https://cloud.githubusercontent.com/assets/3578332/5944761/6bb9e872-a6f7-11e4-804b-f6a90d4cee8f.png)
The error message should be changed to something like:  The account or password is invalid.  Please try again and check your spelling and caps lock"

**Comment by roman87** [comment]
@BendixSpring  Thank you for this. I changed it into a question since this is a never ending discussion between usability and security :). I am interested in what others think. This is really an easy change for us.

**Comment by romichg** [comment]
Closing due to TTL.
