### ISSUE TITLE
Instructions for passwords need to be made more accurate

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#328]
The current instructions are as follows:
Your password should be at least 8 characters long. It should have one uppercase and one lowercase letter, a number and a special character.

To be more precise, you can have more than one uppercase, number, special character:
Your password should be at least 8 characters long. It should have *at least one of each of the following:* uppercase and lowercase letters, number and special character.

**Comment by roman87** [comment]
@luchia  can we fix that and then pass it on to @michaelhidalgo to fix the error message when the user submits a bad password.

**Comment by luchia** [comment]
This has been fixed in the reference commit.

![screen shot 2015-01-29 at 9 52 42 am](https://cloud.githubusercontent.com/assets/4547737/5949729/aac1fbcc-a79c-11e4-9974-373538c87e44.png)

**Comment by michaelhidalgo** [comment]
With Pull Request Fixing Issue https://github.com/TeamMentor/TM_4_0_Design/issues/328

**Comment by romichg** [comment]
This was done. @BendixSpring could you confirm this was fixed to your satisfaction?

**Comment by romichg** [comment]
If not I will obviously re-open the issue.

**Comment by BendixSpring** [comment]
This is OK.  I think I'd make things plural + a blurb about longer passwords:

Your password should be at least 8 characters long. It should have at least one of each of the following: uppercase and lowercase letters, number**s**, and special character**s**.

A longer password is a stronger password.

**Comment by romichg** [comment]
Makes sense, however we only look for one number and once special character on the back-end, so making it plural wouldn't really reflect what we are enforcing. But yes agreed, we should look into enforcing stronger password in the future.
