### ISSUE TITLE
When Search returns no hits, user should be offered to do another search

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#329]
Perhaps adding the search box to the failed search might be useful to allow people to do another search
![image](https://cloud.githubusercontent.com/assets/3578332/5944981/4bd1b4ca-a6f9-11e4-89d9-6270abc64fc9.png)

**Comment by DinisCruz** [comment]
I agree, we are playing with alternatives ways to show this page, take a look at this view https://github.com/TeamMentor/TM_4_0_Design/issues/324

That will be available next week on the next beta release (or locally if you run from the latest build)

**Comment by roman87** [comment]
Agred, rewording the issue a bit. and tracking with the basic search story.

**Comment by romichg** [comment]
This is fixed. @BendixSpring could you confirm?

**Comment by BendixSpring** [comment]
Yup!  This is working now.
