### ISSUE TITLE
sign-up form clears inputs on validation error

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#330]
If you submit the sign-up form with e.g., a password that is too short, the page refreshes with an error message but all of the input fields are blank. For usability, the values entered for username and email address should persist.

**Comment by roman87** [comment]
Good point. We need to see how to fix that.

**Comment by DinisCruz** [comment]
@michaelhidalgo the solution for this is to re-add those values to the view-model used on those pages

**Comment by luchia** [comment]
I think this needs to be done from the backend right? Assigning to Michael.

**Comment by michaelhidalgo** [comment]
I found a way to address this issue, it will preserve all the values.

![screen shot 2015-01-29 at 1 29 50 pm](https://cloud.githubusercontent.com/assets/1732035/5964631/4872c234-a7bb-11e4-979f-467f2d1961ce.png)

**Comment by DinisCruz** [comment]
@michaelhidalgo looks good

**Comment by luchia** [comment]
Awesome @michaelhidalgo :)

**Comment by roman87** [comment]
@michaelhidalgo  Michael, looking at the test, you are also persisting the passwords that do not match. Correct? I think we should persist all the information other than the passwords. Since the user has to re-enter them anyways and we need to give the user a clue that they need to be re-entered.

**Comment by michaelhidalgo** [comment]
Yeah it does make sense. I'll adjust the fix and the test scenario,

Thanks!

2015-02-01 11:31 GMT-06:00 RomichG <notifications@github.com>:

> @michaelhidalgo <https://github.com/michaelhidalgo> Michael, looking at
> the test, you are also persisting the passwords that do not match. Correct?
> I think we should persist all the information other than the passwords.
> Since the user has to re-enter them anyways and we need to give the user a
> clue that they need to be re-entered.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/330#issuecomment-72374226>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by roman87** [comment]
Hey @michaelhidalgo I noticed we still keep the password field populated. But now that I think of it, maybe it is not such a bad idea. I will close it for now.

**Comment by roman87** [comment]
Actually, keeping open to follow up back with Tom when next beta is out. :)

**Comment by roman87** [comment]
@tecknicaltom Tom, thanks again for this. This has been fixed on the latest beta at https://beta.teammentor.net. Can you let me know if the fix works as expected.
Thanks.

**Comment by tecknicaltom** [comment]
looks fixed to me

**Comment by roman87** [comment]
Awesome! Thanks, closing this one.
