### ISSUE TITLE
Search returns no hits for obvious terms

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#331]
I did not get any search hits with the following:
SSL
xss
cross site scripting
sqli
sql injection
input validation
crypto

Is the search engine working?

**Comment by BendixSpring** [comment]
And the search terms pop up on the home page under "Popular search terms".  If there is no content, you'd better log that somewhere and consider building content.  And don't post it as a popular search term.

**Comment by DinisCruz** [comment]
the search engine on this version is not working very well.

And I agree that we shouldn't show popular searches that have no results (as now tracked on https://github.com/TeamMentor/TM_4_0_Design/issues/336 )
