### ISSUE TITLE
Server error due to javascript in search

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#333]
I did a search on <marquee> tag and got the web.config file dumped:

Server Error in '/' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

Notes: The current error page you are seeing can be replaced by a custom error page by modifying the "defaultRedirect" attribute of the application's <customErrors> configuration tag to point to a custom error page URL.

<configuration>
    <system.web>
        <customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>
    </system.web>
</configuration>

**Comment by DinisCruz** [comment]
Hi @BendixSpring , is this the error you are getting

https://github.com/TeamMentor/TM_4_0_Design/issues/332

**Comment by BendixSpring** [comment]
No, Dinis.  I think the email should have a screen shot of the error message.

 

--Danny

**Comment by roman87** [comment]
@BendixSpring  Can you let us know specifically what you searched for?

**Comment by BendixSpring** [comment]
The marquee tag

 

Apparently I had brackets around it, and they were stripped out by git.

**Comment by roman87** [comment]
Ok so it is the same error message you got as in https://github.com/TeamMentor/TM_4_0_Design/issues/332#issuecomment-71899151 ?

**Comment by BendixSpring** [comment]
Yes, same error.  You can try a search with:  <marquee> tag

And it should spit the same message

**Comment by roman87** [comment]
Ok great. I'll close this as a dupe then.
