### ISSUE TITLE
Vulnerable to directory traversal

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#335]
Doing a search of this:
/on the server.
Gives this error message:
 Requested URL: /graph/on the server.
Notice /graph/on the server.

Adding ../ to the front of the message (../on the server.) gives this error message
Requested URL: /on the server.
Notice that we lost /graph and have moved up a directory

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by DinisCruz** [comment]
can you post an screenshot?

**Comment by BendixSpring** [comment]
It should be in the message

**Comment by DinisCruz** [comment]
Also can you take a look at https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security , namely this thread https://github.com/TeamMentor/TM_4_0_Design/issues/206 (the path transversal part starts in the middle of it)

**Comment by BendixSpring** [comment]
![image](https://cloud.githubusercontent.com/assets/3578332/5945519/04a86324-a6fd-11e4-934c-76060d62be13.png)


Here is with the ../
![image](https://cloud.githubusercontent.com/assets/3578332/5945535/268cc9c6-a6fd-11e4-8439-4e7c72a7dc06.png)

**Comment by BendixSpring** [comment]
Here is an example of a search term I used to pull up a page from the web server
../article/view/d898d2a2-f20a-45bb-b232-6713cb618de8/All%20Output%20Data%20Is%20Encoded

It's possible that the search engine ignored stuff and just found the page, but if there really is an /article  directory one level above the /graph directory, then maybe this query did pull that page

**Comment by roman87** [comment]
I will take a look. Probably related to #332 and #347

**Comment by DinisCruz** [comment]
@BendixSpring I'm struggling to replicate this, can you give me the exact URL?

For example this http://beta.teammentor.net/../article/view/d898d2a2-f20a-45bb-b232-6713cb618de8/All%20Output%20Data%20Is%20Encoded works ok (i.e. I can't replicate the issue)

**Comment by BendixSpring** [comment]
Dinis:

 

That is the URL I used.  If the /article directory is at the same level as /graph, then this is a valid directory traversal.

 

Someone did a nice traversal using the logo.  Look in the logs for that example to see what they did.

 

--Danny

**Comment by DinisCruz** [comment]
humm, the url didn't make it into the github Issue (see https://github.com/TeamMentor/TM_4_0_Design/issues/335#issuecomment-71934300 for what it looks like)

@roman87 is this something we can get from the IIS logs?

**Comment by BendixSpring** [comment]
It looks like the app is filtering out the ../ so this URL does correctly display the logo when entered into the search box
https://beta.teammentor.net/graph/../static/assets/logos/logos.jpg

**Comment by DinisCruz** [comment]
so on that case, that is actually a path that exists https://beta.teammentor.net/static/assets/logos/logos.jpg

**Comment by BendixSpring** [comment]
Right, that path exists.  It appears that the ../ is being stripped out, and the URL works.  The interesting thing would be:  can we get a URL that points to something where we shouldn’t be able to access?

**Comment by DinisCruz** [comment]
as far as I can tell, you can only get files that exist inside the current TM_4_0_Design root folder. This is  'by design' at the moment (see https://github.com/TeamMentor/TM_4_0_Design/issues/206 for more details)

I have not seen a case where you can get a file from outside that web root

**Comment by roman87** [comment]
I agree with @DinisCruz this seems to be correct behaivour as by design. The server will show anything that is a valid URL. In the above example http://beta.teammentor.net/../article/view/d898d2a2-f20a-45bb-b232-6713cb618de8/All%20Output%20Data%20Is%20Encoded  is a valid URL.
@BendixSpring is there a case where there there is actual traversal to a URL that is not normally accessible? 
I am marking this as to be closed. From the above comments it doesn't seem like there is a vuln. Correct me if I am wrong of' course :)

**Comment by BendixSpring** [comment]
It appears that you are filtering ../, so this is probably not an issue.

**Comment by roman87** [comment]
Alright, closing as by design :)
