### ISSUE TITLE
Search is not working well

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#337]
I tried a number of search terms:
xss
cross site scripting
sqli
SQL injection
access control
Access Control

and kept getting 0 hits.  Something isn't working correctly.

**Comment by DinisCruz** [comment]
correct, on this version (Beta 1), the search only returns a hit that match one of the existing views or queries

on Beta 1.1 you will have a much better search: see https://github.com/TeamMentor/TM_4_0_Design/issues/126

**Comment by DinisCruz** [comment]
related to https://github.com/TeamMentor/TM_4_0_Design/issues/336

**Comment by BendixSpring** [comment]
I am unable to get a search that hits any terms.  If that functionality works, are the keywords highlighted in the list of returned searches?

**Comment by DinisCruz** [comment]
Try 

* Logging   ,  https://beta.teammentor.net/search?text=Logging
* Authorization   , https://beta.teammentor.net/search?text=Authorization

**Comment by roman87** [comment]
Closing this as by design. I might have omitted it but I was intending to specify that search does not work in my email.
