### ISSUE TITLE
404 error on a very long search

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#339]
Set the search string size (client and server) to something reasonable.

I got the following error when I did the search below:
![image](https://cloud.githubusercontent.com/assets/3578332/5945966/3993da34-a700-11e4-802c-9e64cc435da5.png)

I did a search with this string:
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken
chicken

**Comment by DinisCruz** [comment]
Here what that search looks like 

https://beta.teammentor.net/search?text=chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken

this one also causes error 400

https://beta.teammentor.net/graph/chickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenc

I think this is caused two things

a) use of GET parameter on search
b) reaching the maximum GET size limit of Node (or IIS)

**Comment by michaelhidalgo** [comment]
It turns out that this might be a path limitation to 256 characters

This one breaks :

https://beta.teammentor.net/graph/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

This one does not :

https://beta.teammentor.net/graph/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

2015-01-28 17:52 GMT-06:00 Dinis Cruz <notifications@github.com>:

> Here what that search looks like
>
> https://beta.teammentor.net/search?text=chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chi
> cken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+
> chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken
> <https://beta.teammentor.net/search?text=chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+ch%20icken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken%20+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken+chicken>
>
> this one also causes error 400
>
> https://beta.teammentor.net/graph/chickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchic
> kenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenc
> <https://beta.teammentor.net/graph/chickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchicken%20chickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenchickenc>
>
> I think this is caused two things
>
> a) use of GET parameter on search
> b) reaching the maximum GET size limit of Node (or IIS)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/339#issuecomment-71942119>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by roman87** [comment]
@BendixSpring this should be fixed now. Can you please double check and make sure the fix is to your liking.

Thanks.

**Comment by BendixSpring** [comment]
This is the error message when I type in an overly long query:



It’s an improvement.  Do I like it?  It’s not my ideal, but under the circumstances it works.
