### ISSUE TITLE
TM Logo sprite is not responsive

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#340]
This means that it doesn't resize to fit it's container when the screens are small, causing overlap.

![screen shot 2015-01-28 at 11 57 53 am](https://cloud.githubusercontent.com/assets/4547737/5946028/57febaba-a77e-11e4-8cf0-feaa9da2bd0f.png)

**Comment by roman87** [comment]
@luchia, this is flare correct?

**Comment by luchia** [comment]
Yes

**Comment by luchia** [comment]
This relates to #356 and my discoveries trying to solve that issue.

**Comment by luchia** [comment]
After doing a lot of reading for #356 and personal research, I propose that we move Flare away from CSS Sprites. 

My reasons for this are:
- We are relying on images which are not scalable and are difficult to make high quality enough for all resolutions while keeping sizes down.
- CSS Sprites are notoriously difficult to make responsive (as I've discovered!!!). SVG sprites are not.
- Smaller file sizes on SVG's means we can accommodate mobile users and desktop users with the same images, cutting down on resource usage.

With this in mind, here are the materials which will help me migrate Flare over to SVGS -
* [Smashing Magazine](http://www.smashingmagazine.com/2012/01/16/resolution-independence-with-svg/)
* [Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Scaling_of_SVG_backgrounds)

What needs to be moved over -
* TM and SI logos
* Stock images
* Client logos

I want to modify the effort to 2 days on this one because I am now moving all of our resources over to a new file type, not just the TM logo.

**Comment by roman87** [comment]
Sounds like  a good plan.  Anyone has any objections?

**Comment by DinisCruz** [comment]
nope, sounds good

**Comment by luchia** [comment]
I've completed the work for the background stock images. I am now waiting for a vector copy of the SI logo so I can finish that.

I am also going to have to source the vector logos for the client images but I wanted to check first about something. @roman87 (i think it was you) mentioned that you wanted these as separate files because you wanted to be able to change them? Is that still true or does that sound accurate if it was someone else?

If that's the case, I won't make the client logos into one svg sprite.

**Comment by roman87** [comment]
Well.. the question here is, how much work is it to change the SVG to add/remove images. If this is something that we can turn around very quickly - like in 48h (and I mean from request to add/remove image to deployment in production) then we can incorporate them in the svg sprite.

**Comment by luchia** [comment]
Yeah, it's quick as long as we have the vector file for the client logo. What I'm working on now is sourcing the current logos we have on the landing page, in the right format.

**Comment by luchia** [comment]
So it's not as easy as I thought to source all of the vector logos for client images. I suggest that we stay with JPG's for these particular items so that we can easily source replacements or new ones as required.

The only thing I have left to do for this issue is:
- [ ] Add media queries for large screens (wider than 2000px)
- [ ] Work out how to get logo sprites responsive

The whole responsive sprite thing is turning out to be a lot more complicated than I originally thought. I spent most of today trying to get this to work before needing a break. I'll try again tomorrow.

**Comment by luchia** [comment]
Yay, worked it out. I just need to do the SI logo now.

![screen shot 2015-03-03 at 5 06 50 pm](https://cloud.githubusercontent.com/assets/4547737/6457586/c90af7b0-c1c7-11e4-94f9-c08ed7ff33b7.png)
![screen shot 2015-03-03 at 5 06 56 pm](https://cloud.githubusercontent.com/assets/4547737/6457587/c91b35c6-c1c7-11e4-8ca9-b1df0671c93c.png)
![screen shot 2015-03-03 at 5 06 58 pm](https://cloud.githubusercontent.com/assets/4547737/6457588/c91fd004-c1c7-11e4-98a3-ea859a1ba6af.png)
![screen shot 2015-03-03 at 5 07 00 pm](https://cloud.githubusercontent.com/assets/4547737/6457589/c9215c8a-c1c7-11e4-8479-396117a05555.png)

**Comment by luchia** [comment]
SI logo is done -

![screen shot 2015-03-03 at 5 20 28 pm](https://cloud.githubusercontent.com/assets/4547737/6457722/a9b7ee70-c1c9-11e4-9ed1-0cb40dd5ff6a.png)
![screen shot 2015-03-03 at 5 20 32 pm](https://cloud.githubusercontent.com/assets/4547737/6457723/a9d91d2a-c1c9-11e4-813b-e0b1bbaf9575.png)
![screen shot 2015-03-03 at 5 20 36 pm](https://cloud.githubusercontent.com/assets/4547737/6457726/a9deca2c-c1c9-11e4-9a96-e44c8fcf33ed.png)
![screen shot 2015-03-03 at 5 20 38 pm](https://cloud.githubusercontent.com/assets/4547737/6457725/a9dd7e60-c1c9-11e4-934c-b454891a8093.png)
![screen shot 2015-03-03 at 5 20 40 pm](https://cloud.githubusercontent.com/assets/4547737/6457724/a9dd2f32-c1c9-11e4-813e-7e1145bf5f16.png)

**Comment by luchia** [comment]
Yay, finally done -

![screen shot 2015-03-10 at 6 00 50 pm](https://cloud.githubusercontent.com/assets/4547737/6584191/48bde678-c7b5-11e4-99fa-8e58528d2522.png)
![screen shot 2015-03-10 at 6 00 59 pm](https://cloud.githubusercontent.com/assets/4547737/6584192/48eeb9f6-c7b5-11e4-8439-1c4376a044c6.png)
![screen shot 2015-03-10 at 6 01 47 pm](https://cloud.githubusercontent.com/assets/4547737/6584193/490a405e-c7b5-11e4-8ba9-845feea9b2d6.png)
![screen shot 2015-03-10 at 6 01 50 pm](https://cloud.githubusercontent.com/assets/4547737/6584194/490d4c72-c7b5-11e4-90d5-424c91b7d7e7.png)
![screen shot 2015-03-10 at 6 01 56 pm](https://cloud.githubusercontent.com/assets/4547737/6584196/491a9aee-c7b5-11e4-8216-1a221d4e91be.png)
![screen shot 2015-03-10 at 6 02 01 pm](https://cloud.githubusercontent.com/assets/4547737/6584195/491a1998-c7b5-11e4-8f69-1dc5cf3b2173.png)
![screen shot 2015-03-10 at 6 02 03 pm](https://cloud.githubusercontent.com/assets/4547737/6584197/491b5272-c7b5-11e4-9191-0c56ea5d94d3.png)

If everyone is happy with this, I would like to suggest that we move over the clients sprite which I managed to get working using legacy browser supported code (!!!). It looks really good, is responsive as well and it'll remove 5 HTTP requests :)

I couldn't get the sprites to work on Flare  for the SI & TM logo so there are two separate files for those, but we removed the 5 extra requests from the client logos so I think it's okay.

**Comment by luchia** [comment]
And in the application, we now have a logo that doesn't push out of it's container -

![screen shot 2015-03-11 at 6 13 17 am](https://cloud.githubusercontent.com/assets/4547737/6584307/08f00eb2-c7b6-11e4-99e9-5cce60ad024b.png)
![screen shot 2015-03-11 at 6 15 06 am](https://cloud.githubusercontent.com/assets/4547737/6584308/08ff64ca-c7b6-11e4-80fd-140be5518322.png)

**Comment by romichg** [comment]
fixed
