### ISSUE TITLE
Create shared mixins (CSS) between Jade and Flare

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#342]
As per [my comment](https://github.com/TeamMentor/TM_4_0_Design/issues/284#issuecomment-71289039) on #284, we have decided to create a shared mixins SASS file that contains styles shared between the two versions of the application.

This cuts down on duplicate code and makes things easier to maintain.

**Comment by luchia** [comment]
This has been completed. The styles can be found here -

![screen shot 2015-02-17 at 6 41 11 pm](https://cloud.githubusercontent.com/assets/4547737/6224998/924855a4-b6d4-11e4-9196-377d5b52330b.png)

**Comment by luchia** [comment]
I will also need to create a new issue relating to converting our CSS files to SCSS but it can wait until most style changes have been completed and Dinis has built the functionality that compiles SCSS.

**Comment by romichg** [comment]
Done
