### ISSUE TITLE
Clicking on a bad search request from Recent Searches generates HTTP 400 Error

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#343]
Click a bad popular search
![image](https://cloud.githubusercontent.com/assets/3578332/5946226/1affdf1c-a702-11e4-9e2b-44ad0284bcbe.png)

Get an error message
![image](https://cloud.githubusercontent.com/assets/3578332/5946218/0e5ae02c-a702-11e4-8ac5-230ad15063f4.png)

**Comment by DinisCruz** [comment]
can you share the url that you had when you got that error 400?

Also what is that text on the search terms? :)

**Comment by BendixSpring** [comment]
I have no idea what the text is, but it is a screenshot of what what displayed.  I will see if I can find the URL in my history.

**Comment by BendixSpring** [comment]
https://beta.teammentor.net/graph/T%CC%94%CD%A5%CC%93%CD%A9%CC%BF%CC%B8%CC%B6%CD%9F%CC%A1%CC%B7%CC%B3%CD%9A%CC%9F%CD%89%CD%88%CC%99%CD%85%CC%9DE%CD%A8%CC%BD%CC%80%CD%9B%CD%A7%CC%8C%CD%84%CC%93%CC%93%CD%A7%CC%BF%CD%AD%CC%84%CC%94%CC%8F%CD%AF%CD%8B%CC%94%CC%95%CC%9B%CC%B8%CC%B7%CC%A1%CC%9F%CC%9C%CC%B2%CC%A5%CC%B9A%CC%94%CC%87%CD%84%CD%9B%CD%A8%CD%9B%CD%AA%CD%A9%CD%A5%CD%97%CC%94%CD%9B%CC%BF%CD%AD%CD%A6%CC%8B%CD%80%CC%B4%CC%B8%CC%9B%CD%89%CD%96%CD%88%CD%85%CC%A4M%CC%9A%CD%A9%CD%8A%CC%BD%CD%91%CD%92%CC%94%CD%8B%CD%A8%CD%90%CC%BF%CC%B7%CD%93%CD%99%CD%89%CC%B1%CC%AD%20%CC%88%CC%81%CD%97%CC%91%CC%92%CC%8C%CD%90%CC%86%CD%A3%CD%91%CC%8C%CD%A8%CC%82%CD%97%CD%AF%CD%A6%CC%80%CC%BE%CD%A2%CD%81%CC%95%CD%8D%CD%89%CD%8E%CC%B2%CC%B2%CC%B3%CC%A3%CC%A4%CC%BB%CD%94M%CC%89%CC%84%CC%81%CD%91%CC%8E%CC%91%CC%8B%CC%8B%CD%9B%CC%94%CD%A3%CC%8D%CD%90%CD%9B%CD%A5%CC%90%CC%8F%CD%9F%CC%B6%CC%B0%CC%9E%CC%AB%CC%B0%CD%96%CD%9A%CD%8EE%CC%93%CC%94%CD%8B%CD%AA%CD%A8%CC%8F%CD%8A%CC%8B%CD%90%CC%A8%CC%B8%CD%95%CC%97%CC%9F%CC%BC%CC%AE%CC%A6%CC%BB%CC%9D%CC%A9%CC%9E%CC%AE%CC%A4%CC%9D%CD%94%CC%AF%CC%98%CC%96%CD%96%CC%B9N%CD%A6%CD%84%CC%8B%CD%AB%CC%82%CC%82%CC%9A%CC%8A%CC%80%CD%AE%CD%AA%CD%9E%CC%B8%CD%9D%CC%A4%CC%BC%CD%94%CC%A5%CC%A4%CC%BC%CC%9E%CC%9C%CD%94%CC%9C%CC%B9%CD%9A%CD%99%CD%8E%CC%AF%CC%A9T%CD%A4%CD%AA%CD%91%CD%84%CD%AD%CC%8A%CC%B8%CD%98%CD%A2%CC%A9%CD%99%CC%BB%CC%B0%CC%A5%CC%B9%CC%99%CD%87%CC%A5%CD%8D%CC%96%CC%96%CD%99%CD%85%CD%8E%CC%A3%CC%96%CC%AAO%CD%A6%CD%A3%CD%9B%CC%85%CC%8B%CC%8D%CC%80%CD%84%CD%8B%CC%B6%CC%B5%CC%A6%CC%AF%CC%98%CD%99%CC%A5%CC%99%CD%96%CC%AD%CC%AE%CC%B3%CC%B2%CC%AF%CD%89%CC%AD%CC%BA%CC%AA%CC%9F%CC%A4R%CC%86%CD%97%CD%A8%CC%8F%CD%83%CC%86%CC%81%CC%89%CD%83%CD%9B%CD%8C%CC%92%CD%91%CD%8B%CD%8B%CD%A0%CC%95%CD%A0%CC%A7%CC%A8%CD%99%CD%96%CC%BA%CC%9E%CC%9E%CC%9C

**Comment by DinisCruz** [comment]
That is a really cool payload :)

What is that , some kind of weird Unicode conversion?

**Comment by DinisCruz** [comment]
marking this to be closed since we are tracking the 'error 400 on long searches' at https://github.com/TeamMentor/TM_4_0_Design/issues/339 , and, the fix for https://github.com/TeamMentor/TM_4_0_Design/issues/336 prevents that particular string from being see by other users

**Comment by roman87** [comment]
Yea I agree this would be fixed by those issues, but we can track this one as well to make sure we include someone from fiddling with the URL.

**Comment by BendixSpring** [comment]
Dunno!  I found it in the list of recent searches and clicked!

**Comment by roman87** [comment]
This has been fixed. @BendixSpring could you confirm it is fixed to your liking. I couldn't reproduce the problem. The URL is pretty cool though :)

**Comment by DinisCruz** [comment]
Humm I just got this on the live server

![image](https://cloud.githubusercontent.com/assets/656739/7032709/86dae8d2-dd42-11e4-8ed9-f1437862179e.png)

and this locally

![image](https://cloud.githubusercontent.com/assets/656739/7032788/1d95a4c4-dd43-11e4-8105-88782cf46bef.png)

Looks like IIS is throwing up the error

**Comment by roman87** [comment]
So looking at this for a bit, it seems like there is nothing we can do with IIS in this case:
https://technet.microsoft.com/en-us/library/cc753103%28v=ws.10%29.aspx
```
noteNote
You cannot customize the following HTTP errors: 400, 403.9, 411, 414, 500, 500.11, 500.14, 500.15, 501, 503, and 505.
```

Though not ideal, I think we can live with this for now.

**Comment by roman87** [comment]
@BendixSpring can you let us know if this is fixed to your satisfaction?

**Comment by DinisCruz** [comment]
Did you try http://stackoverflow.com/questions/7511239/asp-net-mvc-how-to-handle-400-bad-request-error-when-url-end-with ?

I was under the impression that this could be handled with web.config options

**Comment by roman87** [comment]
The link you point to to actually says that it is impossible to do that:) The guy that says that it is possible assumes that there is an existing response from an application, we don't have an existing response since the request never makes it to the reverse proxy.

MS Docs says you can't do that :). I am sure there is a hack. Some people say that if you enable detailed errors it maybe possible. But I don't think we should do that.

**Comment by romichg** [comment]
Closing due to TTL
