### ISSUE TITLE
Show user friendly error messages when Invalid or unauthorized URL is requested. 

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#344]
Logged in as a user

Attempt to access:  https://beta.teammentor.net/admin

Get the following error:
![image](https://cloud.githubusercontent.com/assets/3578332/5946264/65719d6a-a702-11e4-801a-78532d07d00a.png)

**Comment by roman87** [comment]
Reworded this a bit. Will be done in sprint 3. Tacked here: https://github.com/TeamMentor/Master/issues/902

**Comment by michaelhidalgo** [comment]
This issue has been fixed. We now display a generic error message

![screen shot 2015-02-18 at 2 08 46 pm](https://cloud.githubusercontent.com/assets/1732035/6255704/d4544a22-b777-11e4-9f2a-45a065c55c25.png)

**Comment by romichg** [comment]
Needs to be verified in flare.

**Comment by romichg** [comment]
done
