### ISSUE TITLE
GraphDB dies / crash sporadicaly causing "Blank page came up when trying to reset the filters" or clicking on Navigate

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#349]
It's unclear how to remove filters and get back to the default search page.

I clicked GUIDANCE on the navigate bar, and got this blank page:
![image](https://cloud.githubusercontent.com/assets/3578332/5946709/e38ff8e2-a705-11e4-9417-931c1f6a53e4.png)

**Comment by DinisCruz** [comment]
Can you replicate this?

**Comment by roman87** [comment]
I had this happen a number of times. And other users had complained as well. It seems like graphDB dies at some point and on windows it takes a while for it to restart. We need to have logs https://github.com/TeamMentor/TM_4_0_Design/issues/86 to see what is going on.

**Comment by roman87** [comment]
Rewording to match what is actually happening.

**Comment by DinisCruz** [comment]
This is another issue that would be addressed with https://github.com/TeamMentor/TM_4_0_Design/issues/317

**Comment by roman87** [comment]
I don't see how #317 address the issue. Whenever there is a search, graphDB would be used. If we can't make graphDB more stable, we need to have a pool of them running. Which is a mess btw.

**Comment by DinisCruz** [comment]
At the moment there is a finite amount of possible graphDb searches, so if we pre-generate them (which is what #317 is all about), the actually requests hitting the GraphDB will be minimal

And even more important, even if there is a prob with the GraphDB, 99% of the users will not be affected, since they will be using the cached version

**Comment by roman87** [comment]
Most amounts of users will be using the search bar :). Which is something we cannot pre-load. That is why I think #317 will not solve the issue.

**Comment by roman87** [comment]
Can we detect that GraphDB has died during a query and show a message saying "Sorry this is taking longer than usual" and keep retrying?

**Comment by DinisCruz** [comment]
yeah, we can do that

**Comment by DinisCruz** [comment]
The best way to handle this to cache the heavier results which we  will have with https://github.com/TeamMentor/TM_4_0_Design/issues/317 (just made that a P0)

I will also look at trying to detect when the GraphDb is down (or not available)

**Comment by DinisCruz** [comment]
This shouldn't be happening any more

**Comment by roman87** [comment]
Haven't been able to duplicate this anymore. Will follow up with @BendixSpring

**Comment by roman87** [comment]
@BendixSpring thanks again for your feedback. This issue had been resolved on the latest beta at https://beta.teammentor.net . Could you take a look and let me know if the fix works as expected? Thanks.

**Comment by BendixSpring** [comment]
Looks like this is working.

**Comment by roman87** [comment]
Great, closing the issue.
