### ISSUE TITLE
Allow support for monitoring local library content changes and reload data

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#351]
With a focus of only updating the data that changed

**Comment by DinisCruz** [comment]
P3 since we can have a more manual solution in the short term

**Comment by roman87** [comment]
Putting this into sprint4 since it is quite complicated and we can survive without this for now.

**Comment by romichg** [comment]
This is done with a manual solution. Any more robust solution will be based on TM Editor..
