### ISSUE TITLE
UI is too busy with text

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#352]
The UI has way too much text.  I've suggested elsewhere some ideas for cutting down on the text.
Feature Request: Collapse filters to help people navigate them [#350](https://github.com/TeamMentor/TM_4_0_Design/issues/350)
Feature Request: Show NEW or UPDATED article filters [ #345] (https://github.com/TeamMentor/TM_4_0_Design/issues/345)

**Comment by DinisCruz** [comment]
@luchia can you share here (as screenshots) your 'clearer UI' ideas for Flare 

(@BendixSpring **Flare** is our code-name for the version with Javascript, and **Jade** is our code-name for the no-Javascript version that is currently deployed)

**Comment by roman87** [comment]
@BendixSpring  I agree. The idea for the Flare UI is to have left-hand side navigation and right-hand side filters slide in and out. New and updated articles would be shown on the main search screen (inside an accordion).

**Comment by romichg** [comment]
@BendixSpring let me know if this has been resolved to your satisfaction.

**Comment by romichg** [comment]
Closing due to ttl.
