### ISSUE TITLE
Move orphan articles from Lib_Uno into a separate library

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#353]
key concepts:
 - the Lib_Uno library should have the exact same number of articles that are on the beta site (794 at the moment)
 - the new library (we can call it 'Lib_Staging' will have the articles that are currently orphans in Lib_Uno (i.e. not in any folder or view)

The idea will then be that Serge and the other content editors can use this Lib_Staging to create the folder and views that will be imported back into Lib_Uno (this workflow is also the one can be used to bring new content into TM_Uno (for example a new NodeJs library))

**Comment by michaelhidalgo** [comment]
This has been done. The new library is here https://github.com/TMContent/Lib_UNO_TMP1

**Comment by DinisCruz** [comment]
very cool, where is the script that did it?

**Comment by roman87** [comment]
Need to create a TM 3.5 server that consumes that library.

**Comment by roman87** [comment]
This is done.
https://uno-tmp1.teammentor.net/teamMentor
