### ISSUE TITLE
show 'no results found' to user when there are no search results

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#354]
The fix pushed to fix issue https://github.com/TeamMentor/TM_4_0_Design/issues/336 removed the 'feature' of adding those bad searches to the list of previous search (while redirecting the user back to the search page.)

What is also needed is to tell the user that there were no results

**Comment by roman87** [comment]
@DinisCruz do you think @michaelhidalgo can have a shot at this?

**Comment by DinisCruz** [comment]
sure

**Comment by luchia** [comment]
I'll take this and create a template for @michaelhidalgo to use.

**Comment by luchia** [comment]
Hey @michaelhidalgo, check out the referenced commit to see where the files are.

**Comment by romichg** [comment]
This is done.
