### ISSUE TITLE
HTTP 413 Request entity too large in Login form

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#359]
If you enter a long value in the username textbox in the login form, you receive this error 
Note that the stack trace also shows up directories. 

![screen shot 2015-01-31 at 7 35 26 am](https://cloud.githubusercontent.com/assets/1732035/5988223/fe4347f8-a91b-11e4-872f-583411b188f1.png)

**Comment by DinisCruz** [comment]
nice, it looks like the error was thrown by the body parser module

@michaelhidalgo can you write three tests to replicate this:

* one directly at the affected api (body parser is it is that one)
* one using express with supertest 
* one via web automation (the previous one should go on TM_Design and this one should go on TM_QA)

**Comment by michaelhidalgo** [comment]
Yeah absolutely

**Comment by michaelhidalgo** [comment]
Ok, I dig a little bit more on this issue : It seems like we can limit the request size https://github.com/expressjs/body-parser (look a the limit property)

.**limit - maximum request body size. (default: <100kb>)**

![book](https://cloud.githubusercontent.com/assets/1732035/5992359/ea6822c8-a9eb-11e4-8f25-85a697d370cd.jpg)

We can also add a client side validation for it.

**Comment by roman87** [comment]
Really nice one. Though no estimate of effort. Please choose one next time :)

**Comment by DinisCruz** [comment]
@michaelhidalgo can you find a web page with that info (I can't read the text on the screenshot).

Btw, I like the book reference (can you also mention the book name, page and paragraph)

**Comment by michaelhidalgo** [comment]
Yap.
This screenshot was taken from the book I'm currently reading **Node.js In action. It's from the chapter 7 : Connect's built-in middleware, page number  150.**
 
![image](https://cloud.githubusercontent.com/assets/1732035/6003218/60385620-aabf-11e4-8def-adbbd38db4fe.jpg)

Then in page number 151  

![image2](https://cloud.githubusercontent.com/assets/1732035/6003296/24ce07fa-aac0-11e4-9b27-9bd11e10f796.jpg)

**Comment by DinisCruz** [comment]
So this means that we should be able to implement https://github.com/TeamMentor/TM_4_0_Design/issues/370 using that setting?

**Comment by michaelhidalgo** [comment]
Yes I think so. We need to define that max lenghts.
Note that Express limits the header max length to 80KB 

https://github.com/joyent/node/blob/597eb6a5aebbc2afbd76d16e568a86ed28509bc7/deps/http_parser/http_parser.h#L56

**Comment by michaelhidalgo** [comment]
Here is the test scenario
```coffeescript
 it.only 'Issue 359- Login request is too large', (done)->
    username = ''.add_Random_Letters(100000)
    password = ''.add_Random_Letters(100000)
    jade.login username,password,  (html, $) ->
      html.assert_Contains('Error: request entity too large')
      done()
````

![screen shot 2015-02-05 at 11 59 34 am](https://cloud.githubusercontent.com/assets/1732035/6065913/805320f4-ad2e-11e4-9fec-404c1f681bd3.png)

**Comment by DinisCruz** [comment]
cool, now did you had an idea for the fix

**Comment by michaelhidalgo** [comment]
Well we can limit the request max length to something smaller but the behavior would be the same, the bodyparser will realize that the request is larger than it can actually handle, so the error would be the same, the only significant difference would be that we are limiting the length to something smaller and avoid any potential DoS.

What do you think about : 

1. Client-side validations constraints for max lengths
2. Global setting for request max length.
3. Error page to handle HTTP 500 server errors

**Comment by DinisCruz** [comment]
This test confirms that node is not handling bad stuff on the url

```coffee
  it.only 'Show unavailable page on unhandled node error', (done)->
    page.open '/aaaaaa*&%5E(*&*(*%5E&%%5E', (html,$)->
      html.assert_Contains 'Error: Bad Request'
      done()
```

**Comment by DinisCruz** [comment]
Here is the regression test:

```coffee
  it.only 'Show unavailable page on unhandled node error', (done)->
    page.open '/aaaaaa*&%5E(*&*(*%5E&%%5E', (html,$)->
      $('#an-error-occured').html().assert_Is 'An error occured'
      done()
```

Now what happens is we show the 404 message (with the error for now logged into the console)

I first used the 'unavailable' page , but i think the 404 will make more sense in most cases

![image](https://cloud.githubusercontent.com/assets/656739/6070746/26d0f20a-ad87-11e4-98c8-2958095d19cb.png)

**Comment by DinisCruz** [comment]
Here is the 404 test

```coffee
  it.only 'Show 404 page', (done)->
    check_404 = (payload, next)->
      page.open payload, (html,$)->
        $('#404-message').html().assert_Contains 'HTTP 404 error - check the URL and refresh '
        next()

    check_404 '/aaaaaa' ,->
      check_404 '/12312341/aaaaaa' ,->
        check_404 '/!!@@£$/123' ,->
          done()
```

**Comment by michaelhidalgo** [comment]
This approach works, however, when there is a server error (namely HTTP 500), it is displayed as if it was a HTTP 400  

![screen shot 2015-02-05 at 5 20 51 pm](https://cloud.githubusercontent.com/assets/1732035/6071452/91647730-ad5b-11e4-95be-41d4b2c1dabf.png)

**Comment by DinisCruz** [comment]
yeah, that is what I was mentioning on my comment above, this is currently handing all unhanded errors

Since we know that it is an error 500 on the server side, there is probably not a lot of reasons to tell the user (or attacker) the error 500

**Comment by michaelhidalgo** [comment]
It makes sense.

2015-02-05 17:26 GMT-06:00 Dinis Cruz <notifications@github.com>:

> yeah, that is what I was mentioning on my comment above, this is currently
> handing all unhanded errors
>
> Since we know that it is an error 500 on the server side, there is
> probably not a lot of reasons to tell the user (or attacker) the error 500
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/359#issuecomment-73152268>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by michaelhidalgo** [comment]
PR https://github.com/TeamMentor/TM_4_0_Design/pull/429/files
I'll add automation test for this case.

**Comment by DinisCruz** [comment]
merged, ready for QA

**Comment by roman87** [comment]
Looks cool. Get an error in express when sending a large string. 
Error with request url: /user/login 
 Error: request entity too large
  at makeError (/home/rom/Dev/TeamMentor/TM_4_0_Design/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
  at module.exports (/home/rom/Dev/TeamMentor/TM_4_0_Design/node_modules/body-parser/node_modules/raw-body/index.js:40:15)
  at read (/home/rom/Dev/TeamMentor/TM_4_0_Design/node_modules/body-parser/lib/read.js:64:3)

Good stuff. Now we just need to log things like this.
