### ISSUE TITLE
On production servers, handle error messages and display default 'error' page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#360]
For example https://github.com/TeamMentor/TM_4_0_Design/issues/359 is one of those cases where we need to handle the error internally and show the default 'error' page

Note that these errors should be logged internally, and ideally shown in real-time to TM 4.0 admin

References
* http://www.joyent.com/developers/node/design/errors
* http://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling

**Comment by roman87** [comment]
Yes, ideally they would go into a log file.

**Comment by roman87** [comment]
related to #86

**Comment by DinisCruz** [comment]
This is now done

We handle all errors within express and as https://github.com/TeamMentor/TM_4_0_Design/issues/536 we also store that info to disk

**Comment by roman87** [comment]
Not really. I can't see from the log files that there was any error:
Design
{"url":"/blahblah","ip":"127.0.0.1","level":"info","message":"","timestamp":"2015-03-16T17:01:32.394Z"}
DB:
{"method":"GET","url":"/convert/to_ids/blahblah","level":"info","message":"","timestamp":"2015-03-16T16:58:53.638Z"}

**Comment by romichg** [comment]
This is done as described in the issue.
