### ISSUE TITLE
Add Logging-Service class which will be used to add and view logging messages

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#361]
This will address part of https://github.com/TeamMentor/TM_4_0_Design/issues/86 

Key feature of this service is the ability to easily add 'status/action' messages to parts of the application.

For example: 
 * 'user login', 'page open' ,'user created', 'article view', etc....  (which are user activities)
 * 'server started', 'data loaded', 'search graph created' (which are internal TM activities)

This is a shared module, which will be used by the multiple TM modules (Graph and Design)

**Comment by DinisCruz** [comment]
The solution for https://github.com/TeamMentor/TM_4_0_Design/issues/536 added this service and it includes the capturing of a number of these actions

The data is saved to disk into the .logs folder

**Comment by roman87** [comment]
yes this is done.
