### ISSUE TITLE
Clean up the /deploy and /static folders on TM_Design

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#362]
At the moment the TM_Design uses files from both https://github.com/TeamMentor/TM_4_0_Design/tree/master/deploy and https://github.com/TeamMentor/TM_4_0_Design/tree/master/static

There should only be one source of static files

Note that at the moment we are running the site from non-compiled code (i.e. direct coffee and jade). the final version of TM 4.0 will run from static-precompiled files (coffee, jade and scss)

**Comment by romichg** [comment]
This was done.
