### ISSUE TITLE
Research ability to embed Video and PDFs into the TM 4.0 pages (JADE)

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#363]
See if we can embed video and PDF pages into the full article view page #194 and into the landing page as a tutorial (https://github.com/TeamMentor/Master/issues/909#issuecomment-66240308)

**Comment by DinisCruz** [comment]
The research is done and we can do this, as long as the video and pdfs are hosted by a 3rd party

What we will support is the framing of a 3rd party service which will handle the serving of the video and pdfs

What we need now is specific use cases and actually examples

**Comment by roman87** [comment]
Yep this can be closed. @SI-Lisa  as you can see from above, we can embed videos and pdfs hosted elsewhere in our pages. Checklists are a bit more complicated since they require state to be maintained per user.
