### ISSUE TITLE
Refactor the TM_Design upstream TeamMentor calls to use the shared TeamMentor-Service

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#366]
For example the Login-Controller should be using a shared TeamMentor-Service API  https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/controllers/Login-Controller.coffee

**Comment by romichg** [comment]
no longer needed. The solution will be to remove the TM 3.5 dependency completely.
