### ISSUE TITLE
Create a good Flare Wiki page that explains to the work what Flare is

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#371]
This should be located at https://github.com/TeamMentor/TM_4_0_Design/wiki/Flare 

See my original comments (included below as an image) for the reasons why I needed that page today

![image](https://cloud.githubusercontent.com/assets/656739/6002925/3c8efb40-aaef-11e4-8ae9-56cac2ccc73e.png)

@luchia can you have a go at editing that page? This is something that you have done already across multiple documents and issues

**Comment by roman87** [comment]
I think we should have a first version of flare before we get into this. And yes we should have the same thing for jade.

**Comment by roman87** [comment]
Closing in 2 days unless there is an effort specified @DinisCruz :)

**Comment by DinisCruz** [comment]
I think this is something that @luchia should add to her tasks.

It is actually something we should have already done.

Basically, if somebody asks 'What is Flare?' where do we send them? At the moment we don't really have a central location that represents all the great ideas we already have for flare, but have not implemented

**Comment by roman87** [comment]
Yes we absolutely do. These are all the stories that are in TeamMentor/master. They represent what you are talking about. Perhaps they are not in a marketing material form, but the stuff is there.

**Comment by roman87** [comment]
and as far as the work effort, I think whoever opens an issue needs to assess the effort. The person assigned may re-assess but we need an initial estimate.

**Comment by luchia** [comment]
[I started work on this](https://github.com/TeamMentor/TM_4_0_Design/wiki/Flare). I will keep working on it this week.

**Comment by luchia** [comment]
I think I have done all I can on this issue until Dinis starts working on it and we have updated storyboards and screenshots that we can put in the Wiki.

Does this need to be closed or should I keep this issue?

**Comment by roman87** [comment]
Just put some links here with all the story boards and mockups and close it.

**Comment by luchia** [comment]
Done.
