### ISSUE TITLE
Refactor TM_Design Help Controller to use local copy of content

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#372]
Once we have the articles rendered ok (see https://github.com/TeamMentor/TM_4_0_Design/issues/194) we need to move the Help content into a separate Help_Controller that uses that capability to render the content locally.

At the moment the content comes from docs.teammentor.net which is another dev/qa dependency that we need to eliminate.

Since the Docs repo is public, we can just clone it directly and do the same that we currently do for the Lib_Vulnerabilites

Related to https://github.com/TeamMentor/TM_4_0_Design/issues/238

**Comment by roman87** [comment]
This is pretty much the same as #664

**Comment by DinisCruz** [comment]
yes we can close this since the issue at hand is tracked by #664

**Comment by roman87** [comment]
Closing this as dupe of #664
