### ISSUE TITLE
Need a better queue when navigating filters

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#373]
Right now all the filters, their headings and the selected filter are all of the same typeface/font. Can we make a distinction between the filter heading and the selected filter?

**Comment by luchia** [comment]
Do you think this works better @Roman?

![screen shot 2015-02-03 at 10 40 56 am](https://cloud.githubusercontent.com/assets/4547737/6012221/45e9cf4c-ab91-11e4-84b1-c14e2e8d8765.png)
![screen shot 2015-02-03 at 10 41 00 am](https://cloud.githubusercontent.com/assets/4547737/6012222/45eb0f1a-ab91-11e4-916f-4ab1b3bbcb04.png)
![screen shot 2015-02-03 at 10 41 04 am](https://cloud.githubusercontent.com/assets/4547737/6012223/45eecb28-ab91-11e4-88f4-ab3702d21fda.png)

**Comment by roman87** [comment]
I think this looks really good now.
