### ISSUE TITLE
Need a way to clear the selected filter

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#374]
right now there is no way to clear the filter selection.

**Comment by luchia** [comment]
![screen shot 2015-02-03 at 11 10 34 am](https://cloud.githubusercontent.com/assets/4547737/6013008/b086fd30-ab9a-11e4-9351-0f0b261d5f19.png)
![screen shot 2015-02-03 at 11 10 35 am](https://cloud.githubusercontent.com/assets/4547737/6013009/b0b605ee-ab9a-11e4-9a8e-4572b7975d51.png)

**Comment by roman87** [comment]
Can't say I am in love with it.Seems big, is all the way to the right. Doesn't seem to have any visual relationship to the actual button which shows which filter is selected. Maybe another version :)?

**Comment by luchia** [comment]
What do you think about this, @roman87?

![screen shot 2015-02-04 at 9 54 32 am](https://cloud.githubusercontent.com/assets/4547737/6032360/de2d4316-ac53-11e4-9009-ba370ea0a709.png)

**Comment by DinisCruz** [comment]
nice , I like it, it should be obvious that that's where filters can be removed

**Comment by roman87** [comment]
Yep looks really really good. Simple, intuitive and easy to use.
