### ISSUE TITLE
When clicking on a space between the filter word and the number nothing happens

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#375]
![tooltip_080](https://cloud.githubusercontent.com/assets/1326120/6007780/d7e4eeba-aaea-11e4-8727-15940214870f.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-03 at 10 13 45 am](https://cloud.githubusercontent.com/assets/4547737/6012013/33424e26-ab8e-11e4-9f53-b90c5d97c9b5.png)

**Comment by roman87** [comment]
Unable to test this untill https://github.com/TeamMentor/TM_4_0_Design/issues/400 is fixed.

**Comment by roman87** [comment]
This is fixed.
