### ISSUE TITLE
Remove the "Category" filter from the UI

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#377]
After some discussions with Serge we thought that to ease the confusion between the "Category" filter and the taxonomy, in the current version, it is the best and easiest approach to remove the Category filter from the UI.

**Comment by luchia** [comment]
I actually think this is to do with @DinisCruz because it's logic-related, not front-end related. I cannot do this from the view.

**Comment by roman87** [comment]
@DinisCruz can we do this as soon as possible. I would like to show how this looks without the category filter to a few people.

**Comment by DinisCruz** [comment]
done, 

![image](https://cloud.githubusercontent.com/assets/656739/6037585/48491c54-ac4d-11e4-850f-ccd706dc4f95.png)

**Comment by roman87** [comment]
This is done.
