### ISSUE TITLE
Create full text search with the lefthand side filters 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#378]
This implements: https://github.com/TeamMentor/Master/issues/131

**Comment by DinisCruz** [comment]
Don't think this is relevant anymore

**Comment by roman87** [comment]
Um.. of course it is relevant. We still don't have lefthand side filters in our search result.

**Comment by DinisCruz** [comment]
ok first proper implementation of this is now live

![image](https://cloud.githubusercontent.com/assets/656739/8556780/234fec30-24f1-11e5-9215-2e6f73e069ff.png)

![image](https://cloud.githubusercontent.com/assets/656739/8556813/5bd04d34-24f1-11e5-827f-890c9ab17771.png)

**Comment by DinisCruz** [comment]
is this issue still relevant?

**Comment by romichg** [comment]
This is done. The rest of this issue is covered in #951
