### ISSUE TITLE
Can inject content into "Recently Viewed Articles" and "Top Articles"

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#379]
Changing the text after an article's guid and following the link will cause the injected text from being added to the "Recently Viewed Articles" section of the page. Doing that repeatedly will cause the injected text to be listed in "Top Articles".

Shouldn't the titles for these sections come from the articles themselves, not from the user input?

**Comment by roman87** [comment]
Good catch. Very much agree. I think this was one of those "lets hack this up now and fix later" things. 
@michaelhidalgo Do you want to take a shot at fixing this?

**Comment by DinisCruz** [comment]
Actually , this is already being addressed with in the current beta. The title now comes from the Article Graph data (i.e. the metadata) vs the url.

**Comment by roman87** [comment]
Yep, looks like its fixed. will follow up with Tom when next beta is out.

**Comment by roman87** [comment]
@tecknicaltom Tom, thanks again for this. Could you take a look at the latest beta at https://beta.teammentor.net and let me know if the fix is as expected.
Thanks.

**Comment by tecknicaltom** [comment]
I'm a little confused while trying to repro this now. All the article links seem to have removed the slug (simplified version of the title) from the url. Where before a link looked something like (from memory):
https://beta.teammentor.net/article/b3f0d1dfe15b/Passwords-Are-Not-Left-in-Memory
they now just look like:
https://beta.teammentor.net/article/article-b3f0d1dfe15b

Were the more readable URLs removed?

**Comment by DinisCruz** [comment]
@tecknicaltom they work differently now.

next beta will introduce the more readable link (also without the content injection)

**Comment by DinisCruz** [comment]
@tecknicaltom what do you think of how were doing it on the latest beta?

![image](https://cloud.githubusercontent.com/assets/656739/6787833/3cf5f664-d18d-11e4-9303-d12c940a3456.png)

this is what the link looks like  http://beta.teammentor.net/article/fc9e969d5d52/Use-Positive-Input-Validation

**Comment by roman87** [comment]
TTL expired Closing
