### ISSUE TITLE
logout appears broken

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#380]
1. Be logged in and view the TM4 page at https://beta.teammentor.net/user/main.html
2. Click the logout link on the top right
3. Notice that you are redirected to https://beta.teammentor.net/guest/default.html and the link in the top right now says "LOGIN"
4. Manually navigate to to https://beta.teammentor.net/user/main.html
5. Observe that you appear to be logged in

**Comment by DinisCruz** [comment]
Humm, I think that might be a cache issue

I can't replicate it locally, and when running with the cache disabled, I was not able to replicate it:

![image](https://cloud.githubusercontent.com/assets/656739/6049787/759026b6-acb2-11e4-97f5-3daa85fa8442.png)

**Comment by DinisCruz** [comment]
@tecknicaltom  I just wrote this unit-test which replicates your steps, but I can't replicate your result:

```coffee
  it.only 'Issue 380 - logout appears broken', (done)->
    jade.login_As_User (html,$)->
      $('#popular-Search-Terms h4').html().assert_Is 'Popular Search Terms'
      page.click 'LOGOUT', ->
        page.chrome.url (url)->
          url.assert_Contains '/guest/default.html'
          page.open '/user/main.html',(html,$)->
            $('#loginwall .alert').html().assert_Is 'You need to login to see that page.'
            done()
```

Here is what it looks like after running the test:

![image](https://cloud.githubusercontent.com/assets/656739/6050159/5a5e8632-acb5-11e4-9418-c14e5a5d7d5d.png)

**Comment by roman87** [comment]
I am not able to duplicate it ether.

**Comment by roman87** [comment]
@tecknicaltom thanks again for your feedback. Could you try to duplicate this on https://beta.teammentor.net ?
Let us know if this has been fixed as expected.

**Comment by roman87** [comment]
TTL expired. Closing
