### ISSUE TITLE
submitting blank login form gives error

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#381]
Submitting the login page by clicking on the "Access Team Mentor" button with a blank form results in being redirected to https://beta.teammentor.net/user/source/jade/guest/login-Fail.jade with an error message:
Cannot GET /user/source/jade/guest/login-Fail.jade

**Comment by roman87** [comment]
Nice one. @luchia can you fix that one? I think we lost that page somewhere.

**Comment by luchia** [comment]
Mmm, nope - it's still there. I'm not sure what's going on with this one as there are no messages in the logs. All the pages (sign-up-OK, sign-up-Fail, login-Fail) aren't working. Possibly a routing issue, @DinisCruz?

**Comment by roman87** [comment]
Ok sending it @DinisCruz way.

**Comment by DinisCruz** [comment]
actually @michaelhidalgo can you fix this one

It is just a simple redirect fix

![image](https://cloud.githubusercontent.com/assets/656739/6037537/84cd2e50-ac4c-11e4-8c1d-0493e8ee5d0b.png)

we also need a TM_QA test for this scenario (trying to login with no data)

**Comment by michaelhidalgo** [comment]
Yeah, I'm working on this one  right now!

**Comment by michaelhidalgo** [comment]
here is the test
```
 it.only 'Issue 381-submitting blank login form gives error', (done)->
    jade.login '','',  (html, $) ->
      html.assert_Contains("Cannot GET /user/source/jade/guest/login-Fail.jade")
      done()
```

**Comment by DinisCruz** [comment]
Test looks great, now you need to do the fix and change the test to be a regression test

**Comment by michaelhidalgo** [comment]
Probably in flare we can add client side validations to avoid submitting the form at all if required fields are empty.

![screen shot 2015-02-04 at 4 31 18 pm](https://cloud.githubusercontent.com/assets/1732035/6051183/69c0d21c-ac8b-11e4-9042-0e59253b425f.png)

**Comment by michaelhidalgo** [comment]
Actually, I added the required attribute too

![screen shot 2015-02-04 at 4 38 34 pm](https://cloud.githubusercontent.com/assets/1732035/6051281/5ee92352-ac8c-11e4-8bc4-60bbe8773e78.png)

**Comment by michaelhidalgo** [comment]
Fixed here https://github.com/TeamMentor/TM_4_0_Design/pull/393/files

**Comment by roman87** [comment]
Looks good! Changing to Action:Close to follow up with the submitter when beta2 is out.

**Comment by roman87** [comment]
@tecknicaltom thanks again for your feedback. This has been fixed on https://beta.teammentor.net
Could you take a look and let us know if the fix is as expected. 
Thanks.

**Comment by tecknicaltom** [comment]
looks fixed, even if the browser doesn't respect the required attributes

**Comment by roman87** [comment]
Great, thank you, closing this one.
