### ISSUE TITLE
Account enumeration in login

### ISSUE THREAD

**Issue by MorganDavis** [TeamMentor/TM_4_0_Design#382]
The login form discloses valid usernames due to the different responses "Username does not exist" and "Wrong Password"

Please refer to TeamMentor article: "Do Not Disclose Valuable Information in Error Messages" located at

https://beta35.teammentor.net/article/a880d974-3543-4190-ae63-ea7e8ac11d0a

for Guidance on the issue.

**Comment by roman87** [comment]
This is really a dupe of #327 and  a subject we debated for sometime. The question here is usability vs security. We received a number of customer feedback on old TM stating just that they want to know if the password or username is wrong. 
I think the answer is to make this configurable. @michaelhidalgo can we extend the configurable text we send in bad password and bad username error messages to tbot? By default lets make it "Bad username/password combination" for both errors.

**Comment by michaelhidalgo** [comment]
Yes, TEAM Mentor 3.6 backend changes allows this messages to be configurable. 
There will be a new configuration section (that can  be accessed from TBOT).

![screen shot 2015-02-05 at 9 16 22 am](https://cloud.githubusercontent.com/assets/1732035/6062805/27999364-ad18-11e4-8fe5-27d6e015fdc4.png)

After restarting TM, the changes should take place in the UI : 

![screen shot 2015-02-05 at 9 15 57 am](https://cloud.githubusercontent.com/assets/1732035/6062825/424c9378-ad18-11e4-819a-53f430b8c94f.png)

The idea behind detailed error messages is pretty much improve user experience in a way that she can understands why it is failing. As @roman87  stated, this is a divergence between security vrs usability, however, we can customise the error message in a way that does not represents a security risk.

**Comment by roman87** [comment]
Cool, Assigning to myself and making a P0 to test and follow up with Morgan.

**Comment by roman87** [comment]
All of the error messages are editable and configurable. Lets change the default ones to:
Login_PasswordDoNotMatch": "Wrong username or bad password",
    "UserNameDoNotExistErrorMessage": "Wrong username or bad password",

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/Dev/pull/171

**Comment by roman87** [comment]
@MorganDavis  Thanks for your feedback. This has been fixed on the new beta (beta 2). It is now on https://beta.teammentor.net. Could you please take a look and let us know if the solution is as expected?

Note, that there is still a possibility of account enumeration through the sign up page, however the usability hit on that one is significant enough not to make changes in favor of a generic error. The way to solve that problem is to require user to enter CAPTCHA every time they sign up. This has not been implemented yet. 

Thanks.

**Comment by MorganDavis** [comment]
Byte for Byte the responses are identical. =]

**Comment by roman87** [comment]
Awesome :)
