### ISSUE TITLE
Should a full view article open in a new tab.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#383]
There has been a number of discussion regarding how a new article should be opened. Some people think it should open in a new tab with switching between tabs taking you back to the article. Some people think that we should keep it all in one tab with a button for "back to search results" 
Perhaps we should do both? @luchia ?

**Comment by roman87** [comment]
Here is an opinion of one user:
This comes from Anna Stenwick
Once logged in, the first thing I did was click on one of the "Top Articles".  When I did this it required me to login again before being able to read it.  Once I was viewing the article, there was no way to navigate further other than by simply clicking the Back button (which brought me back to the second login screen). 

After navigating with the search and filters, I see now that it was actually a new tab and to get back to the search results I simply needed to close that tab.  Personally I think this is not intuitive, most websites don't automatically open new tabs. A 'return to search results' button might be a more intuitive option

**Comment by luchia** [comment]
A lot of websites do actually open in tabs, especially websites that offer a lot of content to be read. I am really indifferent about which way we go with this - people that like to browse in tabs are always going to click links with the Ctrl/Cmd button held and people that don't will use the browser as they always have. We can cater for different types of users by really only catering for one (the non-tab person).

**Comment by DinisCruz** [comment]
I think that now that the search/navigate view opens quick quickly and that the UI doesn't move , we should open it the same tab.

That way the users that want to open in a new tab can explicitly do that

**Comment by roman87** [comment]
Ok agreed. That way we can have the user open it in different tab by right clicking.
