### ISSUE TITLE
On the About page the bold headline spacing between lines looks like they are only half-spaced.  It looks very cramped.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#387]
This feedback comes from Gene Carter via email.  
I've asked for a screenshot.

**Comment by luchia** [comment]
Fixed in the referenced commit.

![screen shot 2015-02-05 at 6 19 20 am](https://cloud.githubusercontent.com/assets/4547737/6048845/13ed1462-acff-11e4-913a-a2ad5f26f3c3.png)

**Comment by roman87** [comment]
Looks good. Tracking to follow up with Gene.

**Comment by roman87** [comment]
Gene confirmed this to be fixed.
