### ISSUE TITLE
About page: It says “TeamMentor” in the last paragraph. Should say "TEAM Mentor"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#388]
This feedback comes from Gene Carter via email.

**Comment by luchia** [comment]
Fixed in the referenced commit.

![screen shot 2015-02-05 at 6 19 20 am](https://cloud.githubusercontent.com/assets/4547737/6048826/f4e1662c-acfe-11e4-89e5-194607e851bd.png)

**Comment by roman87** [comment]
Cool, fixed

**Comment by roman87** [comment]
This is on the beta site. Following up with Gene. Closing in a week if no further feedback is received.

**Comment by roman87** [comment]
Gene confirmed this is fixed. Closing
