### ISSUE TITLE
About page: Fortify should have a trademark.  

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#389]
This feedback comes from Gene Carter via email

**Comment by luchia** [comment]
Taking this, because it relates to me moreso than Dinis.

**Comment by luchia** [comment]
This has been fixed in the second referenced commit.

![screen shot 2015-02-05 at 6 31 19 am](https://cloud.githubusercontent.com/assets/4547737/6049126/bccfb958-ad00-11e4-85cb-389551aa9b2b.png)

**Comment by roman87** [comment]
Cool this is done.

**Comment by roman87** [comment]
This is on the beta site. Following up with Gene. Closing in a week if no further feedback is received.

**Comment by roman87** [comment]
Gene confirmed this to be fixed. Closing
