### ISSUE TITLE
Features page: The headline is confusing

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#390]
Comes from Gene Carter via email.

The headline says “TEAM Mentor provides intelligence to fix vulnerabilities and comply”    Comply with what?

**Comment by luchia** [comment]
I will send marketing an email as they provided the content.

**Comment by luchia** [comment]
Send a follow up email regarding this issue this morning.

**Comment by roman87** [comment]
@SI-Lisa  could you please follow up with the marketing team on this question?

**Comment by romichg** [comment]
Closing due to TTL.
