### ISSUE TITLE
Is Filter "Any" for a technology confusing?

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#391]
This feedback comes from Gene Carter via email:

"On the Filters on the Right,  the definition of “Any” in the Technology section is confusing.  I would think that Any would be for used all technologies, but only articles that say “Any” show up.  I think the proper way to handle “Any” is to include those results for each technology (i.e. include those results when iOS is selected, making it 4 articles in the picture below, not 2), not to have it as a separate category."

There has been a number of related issues dating a while back regarding this. https://github.com/TeamMentor/Master/issues/49 and https://github.com/TeamMentor/Master/issues/113

I propose we rename the confusing terminology to something like "Agnostic" or "Not Tech Specific". 

@tlaloc75 What do you think?

After all this filter is just a Universe of articles minus Tech specific articles (U - (T1 u T2.. u Tn)  or !((T1 u T2.. u Tn)

**Comment by luchia** [comment]
Don't we get an article relating to any technology without filtering? :)

**Comment by roman87** [comment]
Well, no we get all articles. Both technology specific and technology agnostic articles. Filter "Any" is supposed to select only  the technology agnostic articles.

**Comment by tlaloc75** [comment]
I agree that it is confusing and we need a different term. I think we need a simple term, Agnostic doesn't quite get us there as its loaded with other meanings. We could use General, but that's potentially confusing as well. How about Platform (or Technology) Independent?

**Comment by roman87** [comment]
@SI-Lisa @luchia @DinisCruz @michaelhidalgo 
What does everyone else think of these two? Should we go with "Technology Independent"?

**Comment by SI-Lisa** [comment]
I think "Any" or "All" or would do the trick - I think most people get what
that means when filtering.

**Comment by DinisCruz** [comment]
I prefer 'All' to 'Technology Independent' 

'Technology Independent' would also look weird when compared with the other values in the Technology filters

**Comment by roman87** [comment]
I changed made the latest change to "All" lets see how it looks. I think it doesn't look very well, as it assume that "All" the technology filters are in effect, when in fact it is only articles that are technology independent are shown. I guess we need a different way of saying "technology independent"?

This will be on beta on monday.

**Comment by BendixSpring** [comment]
Try All Technologies.  "All" is to vague.

**Comment by roman87** [comment]
Changed to "Technology Independent" lets see how this goes. Closing.
