### ISSUE TITLE
On new search page first result title is hidden by search bar

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#392]
Hi @luchia on the latest design you pushed, the search results was hiding the first title (and total number of results message)

![image](https://cloud.githubusercontent.com/assets/656739/6057003/a4783d7a-ad10-11e4-9063-0316a7f35d37.png)

I fixed it temporarily by adding a couple br to the mixi

![image](https://cloud.githubusercontent.com/assets/656739/6057008/ba99fd6e-ad10-11e4-9a37-304c911a8c23.png)

But this should be fixed on the css directly

Here is what it looks like with my temp fix 
![image](https://cloud.githubusercontent.com/assets/656739/6057028/e9fb95ae-ad10-11e4-9150-a4dc33a8f441.png)

**Comment by luchia** [comment]
Hey @DinisCruz, I added the fix but I think there is something wrong with the code. The div is there but it's not populated (at least, not for me).

![screen shot 2015-02-06 at 9 19 13 am](https://cloud.githubusercontent.com/assets/4547737/6071415/55b60236-ade1-11e4-8b91-bce4b9bb1372.png)

**Comment by DinisCruz** [comment]
humm, what does the jade look like?

**Comment by luchia** [comment]
It's the same mixin that we have for the other version of search.

**Comment by DinisCruz** [comment]
can you put it here?

**Comment by luchia** [comment]
Sure, this is the mixin -

![screen shot 2015-02-06 at 12 07 09 pm](https://cloud.githubusercontent.com/assets/4547737/6073335/b29caf7e-adf8-11e4-960d-a8780139baba.png)

**Comment by DinisCruz** [comment]
@luchia, give the latest design changes, is this how it is supposed to look like

![image](https://cloud.githubusercontent.com/assets/656739/6137495/53678a66-b171-11e4-8506-d7e6b7315c37.png)

**Comment by luchia** [comment]
Taking this to fix the styles.

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

**Comment by luchia** [comment]
See here -

![screen shot 2015-02-11 at 11 04 31 am](https://cloud.githubusercontent.com/assets/4547737/6139969/ca1c7722-b1dd-11e4-8bc6-65d6ae427c9a.png)
![screen shot 2015-02-11 at 11 04 33 am](https://cloud.githubusercontent.com/assets/4547737/6139970/ca2303da-b1dd-11e4-9e09-06c1d1c11c57.png)
![screen shot 2015-02-11 at 11 04 35 am](https://cloud.githubusercontent.com/assets/4547737/6139971/ca2f57f2-b1dd-11e4-8df0-caf8759564ef.png)

**Comment by roman87** [comment]
Yep, looks good. closing.
