### ISSUE TITLE
Encoding error on at least one article

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#395]
![selection_082](https://cloud.githubusercontent.com/assets/1326120/6070436/452e2984-ad5a-11e4-916d-535f16656802.png)

**Comment by DinisCruz** [comment]
It looks like this can be fixed in the content

![image](https://cloud.githubusercontent.com/assets/656739/6071920/491e8794-ad93-11e4-9df9-fcb627a85a55.png)

**Comment by roman87** [comment]
It seems like all of our C++ articles have + encoded as &#43.  I thin we encode this in TM 3.5 this way. We need to be able to support the same encoding in 4.0. Alternatively maybe we write a script that will run after the library is loaded to change all the encoding? Lets discuss.

**Comment by DinisCruz** [comment]
Let's do this on a fork of the content which we can use to make batch changes to content and then send it as a PR to serge

**Comment by roman87** [comment]
Yep sound like a plan.

**Comment by DinisCruz** [comment]
@michaelhidalgo same for this one, you need a test that finds the articles that have this issue

Use cheerio so that you work directly on html

**Comment by roman87** [comment]
cool!
