### ISSUE TITLE
Signup page text is split in two lines when resizing the browser a little bit

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#397]
I get the latest Dev version and it seems like the text is split in two lines when resizing the browser 

![screen shot 2015-02-06 at 7 10 31 pm](https://cloud.githubusercontent.com/assets/1732035/6090079/2a54a022-ae34-11e4-880d-72fc8bfeb3fe.png)

and this is how it looks like when resizing it, note that the text is split in two lines :  
 
![screen shot 2015-02-06 at 7 08 20 pm](https://cloud.githubusercontent.com/assets/1732035/6090080/34b9e496-ae34-11e4-8d32-061a06ae880d.png)

**Comment by DinisCruz** [comment]
You mean the text inside the top-left green text box?

If so, that kind of line break is ok, isn't it?

**Comment by roman87** [comment]
Yea I think the break in this issue is ok. We can discuss if others disagree. I think the issue in this page is https://github.com/TeamMentor/TM_4_0_Design/issues/408 and that is why it visually seems like there is a problem.

**Comment by michaelhidalgo** [comment]
Yes, I agree, Issue https://github.com/TeamMentor/TM_4_0_Design/issues/408 is a better to describe it.

**Comment by luchia** [comment]
Did some reading over the weekend and have come up with a solution to improve our typography in terms of responsiveness. You can see it in action in the referenced commit or attached below.

![screen shot 2015-02-10 at 7 57 35 am](https://cloud.githubusercontent.com/assets/4547737/6116728/be04970a-b0fa-11e4-96f2-2d7949a8015f.png)
![screen shot 2015-02-10 at 7 57 39 am](https://cloud.githubusercontent.com/assets/4547737/6116729/be289d3a-b0fa-11e4-849b-56bdd45bf545.png)

**Comment by romichg** [comment]
fixed
