### ISSUE TITLE
Full article view seems to narrow. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#402]
Now that there is a border around the text, it looks quite narrow on my screen. The empty spaces on left and right really stand out. 
![selection_089](https://cloud.githubusercontent.com/assets/1326120/6098540/e2d3d84e-afaf-11e4-8f54-3c846e77c152.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-10 at 9 10 30 am](https://cloud.githubusercontent.com/assets/4547737/6118088/a896a308-b105-11e4-9f36-c8e8adebcef7.png)

**Comment by roman87** [comment]
Looks good now.
