### ISSUE TITLE
Do we need a "Back to Search Results/Navigate Results" button on the full article view?

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#404]
Lets discuss this. It seems like the browser "Back" button does the job fine. I propose we keep it the way it is and see what feedback we get from the beta? @DinisCruz @michaelhidalgo  @tekgirl77 What do you think?

**Comment by DinisCruz** [comment]
I like the X

And although the back will work on some cases it will not on others (for example if you click on multiple filters, the Back will bring back the previous filter, not the 'cleared filter' view)

**Comment by roman87** [comment]
Sorry, I think I wasn't clear. I meant that when you open the full article view, if I want to get back to search results, or navigate results, should we have a "Back to Search Results" or "Back to Navigate Results" button. Or should we assume that the user will hit the browser back button to get there. 
I like the X on the filter as well.

**Comment by luchia** [comment]
I think the use of the back button on the browser works for the moment, why don't we wait to see if we get any feedback from anyone?

**Comment by luchia** [comment]
As per our meeting this morning, we discussed usability and possible issues with creating a separate back button from the article. Everyone agreed that using the browser back button seems to be the most logical and usable solution for allowing the user to go back to the search results.

Re-assigned to Roman for QA/Closing.

**Comment by roman87** [comment]
All agreed. Closing.

**Comment by roman87** [comment]
As we all agreed, we don't need a button that duplicates the browser back button functionality. We will monitor user feedback for this.
