### ISSUE TITLE
After searching, when clicking on a filter, "Recent Searches" gets messed up.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#405]
Follow this steps to reproduce.
1. Search for xss
2. select any filter on the result page
3. deselect the filter on the result page
4. hit the "search" home button

Observe the result:
![selection_090](https://cloud.githubusercontent.com/assets/1326120/6100948/bbb943aa-afe8-11e4-9fd8-6e5e5370774c.png)

**Comment by DinisCruz** [comment]
this should also be fixed now

**Comment by roman87** [comment]
This is fixed.
