### ISSUE TITLE
Search page seems to narrow

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#406]
On my screen the search page looks a bit to narrow, comparative to the empty space on the left and right of it.
![selection_090](https://cloud.githubusercontent.com/assets/1326120/6100955/041e007c-afe9-11e4-85a6-0f9f9014277b.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-10 at 9 07 42 am](https://cloud.githubusercontent.com/assets/4547737/6117934/4f43ff04-b104-11e4-8ede-fa246505edab.png)

**Comment by roman87** [comment]
Looks good now
