### ISSUE TITLE
Bring back ability to click on a title to open the article

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#407]
The ability to open an article by clicking on the title is no longer there. Clicking on the plus sign is really not intuitive.
![selection_091](https://cloud.githubusercontent.com/assets/1326120/6100983/a9a1632c-afe9-11e4-94ab-6286af0e5318.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-10 at 7 16 27 am](https://cloud.githubusercontent.com/assets/4547737/6116044/8107b454-b0f5-11e4-8046-361a92edbed5.png)

**Comment by roman87** [comment]
this is fixed.
