### ISSUE TITLE
When search returns no results. Show a sorry page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#411]
Show a page which says - sorry we could not find any articles matching your query. 
Right now we just show a blank search page.
![selection_094](https://cloud.githubusercontent.com/assets/1326120/6115694/80fe0024-b075-11e4-8bc6-1d61bb555307.png)

**Comment by DinisCruz** [comment]
What about like this

![image](https://cloud.githubusercontent.com/assets/656739/6137399/6d171644-b170-11e4-8de7-fbd63c4bc415.png)

**Comment by roman87** [comment]
Yep. I think it looks good. Anyone else comments?

**Comment by luchia** [comment]
Looks good.

**Comment by roman87** [comment]
Closing.
