### ISSUE TITLE
Add syntax colouring to Jade Article's rendering

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#413]
Shouldn't be very hard since the Markdown APIs we are using already support it

This is what it looks like at the moment (with no formatting)

![image](https://cloud.githubusercontent.com/assets/656739/6129698/3b408a84-b138-11e4-8689-58f80957aaf7.png)

**Comment by DinisCruz** [comment]
Example of article that needs this asap: http://beta.teammentor.net/article/article-e152ebaf03f0

![image](https://cloud.githubusercontent.com/assets/656739/6233241/752f0d10-b6c9-11e4-939c-3c030a56912a.png)

@luchia can you add the gray boxes on the <pre> tags in the article view? It looks better than the current white background (eventually the code will be correctly formated

**Comment by roman87** [comment]
Shouldn't  this be a separate issue, assigned to @luchia?

**Comment by DinisCruz** [comment]
yeah, its better to split it

I just opened https://github.com/TeamMentor/TM_4_0_Design/issues/455 so that @luchia can do her part there

**Comment by roman87** [comment]
As far as color goes, does it make sense to do this in Jade? Perhaps it is better to wait until flare, where we have a lot more resources on the full article view page?

**Comment by DinisCruz** [comment]
yeah we should do it in Jade, since it is already supported by the parsers and it reduces the client overhead.

It will also make it look nice as a stand alone article (i.e. to be saved locally)

**Comment by roman87** [comment]
Ok, lets just make sure it doesn't take more than a day. If it does then we should drop it in favor of spending time on it in flare.

**Comment by DinisCruz** [comment]
For reference on the current TeamMentor.net, it looks like this

https://teammentor.net/article/65d76aae-7c7f-4914-aca0-e84684e919ee
![image](https://cloud.githubusercontent.com/assets/656739/7165436/9d0c52c2-e39f-11e4-9f46-1f7ba364d673.png)

with the styles applied like this

![image](https://cloud.githubusercontent.com/assets/656739/7165447/adddef66-e39f-11e4-8717-70cc3fa03d5a.png)

using this API:
https://teammentor.net/aspx_Pages/scriptCombiner.ashx?s=ArticleView_JS&dontMinify=true

![image](https://cloud.githubusercontent.com/assets/656739/7165510/f3da6d00-e39f-11e4-8ef2-dd84a3104859.png)

Original source code is at: https://github.com/TeamMentor/Dev/tree/master/Source_Code/TM_WebSites/Website_3.5/Javascript/jsPrettify

(note that we don't need to use this API, there are a number of Node Friendly options we can look at)

**Comment by tekgirl77** [comment]
[PR submitted here](https://github.com/TeamMentor/TM_4_0_Design/pull/714)

**Comment by DinisCruz** [comment]
@roman87 check this out, @tekgirl77 did a great job with this commit and I just pushed it to dev since I think it looks good enough to into CR.Beta.7

**Comment by DinisCruz** [comment]
Here is what the syntax highlight looks now (which is already much better than before)

http://localhost:1337/article/55ea97e52ba5/Encode-All-Output-Data

![image](https://cloud.githubusercontent.com/assets/656739/7251410/2d238222-e823-11e4-976d-697145430f08.png)

http://localhost:1337/article/d5f54a2485e6/Protect-Credentials-Within-a-Connection-String-in-Code

![image](https://cloud.githubusercontent.com/assets/656739/7251420/45ab01ee-e823-11e4-8569-046a612cf08a.png)

http://localhost:1337/article/76077de05e90/Add-Unique-Tokens-to-HTTP-Requests-Using-Java-Server-Faces-(JSF)

![image](https://cloud.githubusercontent.com/assets/656739/7251424/59fc2c9a-e823-11e4-95c0-a5522ac0253b.png)

**Comment by DinisCruz** [comment]
Added to #703

**Comment by DinisCruz** [comment]
back to dev since there is a small bug in it

@tekgirl77 when we were pushing into production I noticed that if the jade cache is enabled the syntax highlight will not work. Which makes it not work

```coffee
renderJadeFile: (jadeFile, params)=>
      if (@.cacheEnabled() is false)
        jadeFile_Path = @.calculateJadePath(jadeFile)
        if (fs.existsSync(jadeFile_Path))
          if params and params.article_Html
              params.article_Html = @.apply_Highlight(params.article_Html)
          return jade.renderFile(jadeFile_Path,params)
        return ""

      targetFile_Path = this.calculateTargetPath(jadeFile);
      if (fs.existsSync(targetFile_Path) == false)
          if (this.compileJadeFileToDisk(jadeFile) == false)
              return "";

      return require(targetFile_Path)(params);
```

The solution is to do apply the changes to the params variable before the check for jade cache

**Comment by tekgirl77** [comment]
@DinisCruz how's [this?](https://github.com/tekgirl77/TM_4_0_Design/commit/73e308786049a1f4819e97d1fdff8fff95da8bbd)

**Comment by roman87** [comment]
I think we can close this right?

**Comment by roman87** [comment]
This is done. Closing
