### ISSUE TITLE
Search Bar has no box. It all blends in on my screen.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#414]

**Comment by luchia** [comment]
This has been fixed.

![screen shot 2015-02-12 at 5 17 41 pm](https://cloud.githubusercontent.com/assets/4547737/6163257/482136a0-b2db-11e4-9d6c-6d40e3a81cb1.png)
![screen shot 2015-02-12 at 5 19 13 pm](https://cloud.githubusercontent.com/assets/4547737/6163258/48217ea8-b2db-11e4-8ff8-d851807821fb.png)

**Comment by roman87** [comment]
This is fixed.
