### ISSUE TITLE
Popular search items should not repeat themselves:

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#415]
![selection_097](https://cloud.githubusercontent.com/assets/1326120/6157112/fc96c908-b20c-11e4-8e0d-15bc976374ff.png)

**Comment by DinisCruz** [comment]
This is actually a dupe of https://github.com/TeamMentor/TM_4_0_Design/issues/440

**Comment by DinisCruz** [comment]
This was another variation of the issues resolved recently ( see https://github.com/TeamMentor/TM_4_0_Design/issues/415 )

**Comment by roman87** [comment]
Closing as dupe of #440
