### ISSUE TITLE
Weird result when searchign for “cross site”

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#417]
![selection_095](https://cloud.githubusercontent.com/assets/1326120/6157190/7016d224-b20d-11e4-9043-bcab54195fd0.png)

**Comment by DinisCruz** [comment]
same issue as https://github.com/TeamMentor/TM_4_0_Design/issues/401 (which also addressed this)

Although in the latest Lib_Uno data, there are more than one result for 'cross site'

**Comment by roman87** [comment]
This looks fixed.
