### ISSUE TITLE
No need for “Get Started by Searching” on the results page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#418]
It doesn't really make sense to have it on the results page. Also I am wondering if it makes sense at all. After the second time someone uses it, it is pretty much obvious that you search there.

**Comment by luchia** [comment]
I decided to put the placholder words into the label, which makes more sense. This has been done in the referenced commit.

![screen shot 2015-02-12 at 5 14 36 pm](https://cloud.githubusercontent.com/assets/4547737/6163210/b916c3e4-b2da-11e4-9595-a524b7abfaf6.png)

**Comment by roman87** [comment]
This is done.
