### ISSUE TITLE
Numbers next to filters are out of line

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#424]
Browser size: 1135x707

![capture](https://cloud.githubusercontent.com/assets/1326120/6175822/f83de542-b2c7-11e4-8a02-d499e9cbe26f.PNG)

**Comment by luchia** [comment]
So this issue relates to my work with #342 and has been fixed in the referenced commit.

**Comment by roman87** [comment]
This is fixed, but still a bit of an issue #428
