### ISSUE TITLE
TEAM Mentor version is not displayed in the About page (in the footer)

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#425]
We have a unit test that verifies that TM version is displayed in the about page at the bottom (specifically in the footer) however, it seems like it was removed.

![screen shot 2015-02-12 at 3 05 04 pm](https://cloud.githubusercontent.com/assets/1732035/6176969/8b254f8a-b2c8-11e4-9743-606972a03ba4.png)

**Comment by luchia** [comment]
[This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/27474ffe8d8cb0007f508b2288612cfb0229c213).

**Comment by roman87** [comment]
Looks fixed. Michael, can you make sure the unit test passes and close this?

**Comment by michaelhidalgo** [comment]
Yes it is fixed and we have a test for that :)
