### ISSUE TITLE
filters (on right) cannot be locked or the user can't access lower values

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#426]
![image](https://cloud.githubusercontent.com/assets/656739/6177783/37e6edb8-b301-11e4-9bc0-d0894f1ab0ea.png)

**Comment by luchia** [comment]
Cool, that was something I was playing with the two-column layout. This has been fixed.

**Comment by roman87** [comment]
Looks like it was fixed. Dinis want to close this since I am not exactly sure what you mean by your description :)

**Comment by DinisCruz** [comment]
yes it has been fixed
