### ISSUE TITLE
Preserve username on login fail

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#430]
At the moment when trying to login...
![image](https://cloud.githubusercontent.com/assets/656739/6200244/f2902880-b466-11e4-80bf-9a9d5d1dff83.png)
...and failing, the username value is lost

![image](https://cloud.githubusercontent.com/assets/656739/6200246/01a79b6e-b467-11e4-86c3-daab63d30b61.png)

The expected behaviour is that we should keep the username in there (the password should not be replayed)

**Comment by michaelhidalgo** [comment]
Yes good catch. This fix was applied to the signup form. I'm assigning it to me.

**Comment by roman87** [comment]
Yep. good one.

**Comment by michaelhidalgo** [comment]
Merged.

**Comment by roman87** [comment]
Fixed. Closing
