### ISSUE TITLE
The top line of the User login message is not visible in Jade mobile mode

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#431]
![image](https://cloud.githubusercontent.com/assets/656739/6200249/2f9c1e6e-b467-11e4-8f4d-5f615455ce8a.png)

It is ok in full width mode:

![image](https://cloud.githubusercontent.com/assets/656739/6200250/4e6d4f16-b467-11e4-8e10-edef267b8d20.png)

**Comment by roman87** [comment]
Nice catch. Just as a theoretical though. What if we write an automation test that takes snapshots of the images in different size browsers. We review those images manually. Then what if we run the test again, and compare the jpg files to the known set of good images. Theoretically the files should be the same?

**Comment by roman87** [comment]
Also lets not forget to set the effort :)

**Comment by luchia** [comment]
That isn't the most recent version. The loginwall isn't white anymore.

![screen shot 2015-02-17 at 9 27 51 am](https://cloud.githubusercontent.com/assets/4547737/6220520/42aad014-b687-11e4-90d9-232fa3dce1b9.png)

**Comment by roman87** [comment]
I can duplicate this on the smallest possible browser size. Also the new buttons look out of line.
In general, we gotta stop changing the design at this point. Unless there is a bug we need to fix, or a pressing design issue we need to draw a line for Jade. 

![selection_110](https://cloud.githubusercontent.com/assets/1326120/6233756/3575a4b6-b6a3-11e4-9d5c-5b086846475b.png)

**Comment by DinisCruz** [comment]
> Just as a theoretical thought. What if we write an automation test that takes snapshots of the images in different size browsers. We review those images manually. Then what if we run the test again, and compare the jpg files to the known set of good images. Theoretically the files should be the same?

Not that theoretical, and totally doable. In fact this is something that I want to do (eventually) as part of the the final batch of QA tests (the ones that run on the final deployable version of the code, with all data loaded)

in fact one of the 'browser automation' services already provides kinda of that workflow

The idea is to make it easy for a human (or script) to detect visual changes like this one

**Comment by luchia** [comment]
This is ready for QA.

**Comment by michaelhidalgo** [comment]
Assigning it to me.

**Comment by michaelhidalgo** [comment]
This is fixed. I tested it with Sauce Labs in Iphone and Android emulators.

platform : Linux
browserName : android
version : 5.0

![android1](https://cloud.githubusercontent.com/assets/1732035/6468330/f468cf5a-c199-11e4-98ac-fbd88abeab0d.png)

platform : Mac 10.10
screen-resolution : 1024x768
version : 8.1
![iphone1](https://cloud.githubusercontent.com/assets/1732035/6468345/13f8d19e-c19a-11e4-973e-42f07ed8cf72.png)

![iphone2](https://cloud.githubusercontent.com/assets/1732035/6468344/13f8c3a2-c19a-11e4-8452-954d3223c99b.png)

![iphone3](https://cloud.githubusercontent.com/assets/1732035/6468343/13f8c14a-c19a-11e4-89b7-cac5bbca3f32.png)
