### ISSUE TITLE
Get rid of numbers in the top articles

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#434]
As agreed on the last call, remove the numbers from the Top Articles.

**Comment by luchia** [comment]
This was done in the referenced commit.

![screen shot 2015-02-17 at 9 23 01 am](https://cloud.githubusercontent.com/assets/4547737/6220502/fe3bee36-b686-11e4-8801-d0dbaaa55f11.png)

**Comment by roman87** [comment]
This is done.
