### ISSUE TITLE
Delay in updating "Popular Search Items"  on Windows

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#437]
![bug1](https://cloud.githubusercontent.com/assets/1326120/6206177/63d87d9e-b552-11e4-8880-c63f8aeb2072.gif)

**Comment by DinisCruz** [comment]
I'm pretty sure that that is a client cache issue?

Can you replicate that with the 'chome cache disabled?'

Btw, nice animated gif (can you add a [wiki page](https://github.com/TeamMentor/TM_4_0_Design/wiki) with details of the technology and workflows used?)

**Comment by DinisCruz** [comment]
@michaelhidalgo can you write a QA for this

**Comment by roman87** [comment]
I just checked from the same browser, going to my local version running on linux, and it works fine. Then the same browser pointing to beta.teammentor.net and I am duplicating the same exact behavior. I believe this is something that is happening with the cache when express is running on windows.

**Comment by DinisCruz** [comment]
@roman87 can you try to replicate this with the latest version? I can't replicate it any more

**Comment by romichg** [comment]
Fixed.
