### ISSUE TITLE
Links inside articles are broken

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#443]
If an article has inner links, like this:

![image](https://cloud.githubusercontent.com/assets/656739/6226122/17a99fa0-b68a-11e4-95b8-d1616d875bab.png)

the user will get an article 404 when clicking on them 

![image](https://cloud.githubusercontent.com/assets/656739/6226131/2ed367c4-b68a-11e4-9283-d707a2e0e61b.png)

The reason is because the article links are based on the article id (i.e. a Guid), but at the moment the article viewer uses the GraphDB id (for example article-4b260155d79e) to resolve the article.

the solution is to allow articles to be resolved by GUID (and while adding that feature see if they can also be resolved by title)

**Comment by roman87** [comment]
Yep sounds like a good plan.

**Comment by DinisCruz** [comment]
Here are the 4 tests that (will) represent the 4 scenarios that we need to support:
 * graphDB id
 * article original GUID
 * article title
 * dashed article title

```coffee
describe '/article/:key',->

    article = null

    before (done)->
      graphDb.articles (data)->
        article = data.values().first()
        done()

    check_Article_Contents = (key, selector, expected_Text, next)->
      jade.page_User_Article key, (html,$)->
        $(selector).text().assert_Is expected_Text
        next()

    it 'by id', (done)->
      check_Article_Contents article.id    , '#title', article.title  , done

    it 'by guid', (done)->
      check_Article_Contents article.guid  , '#article #oops', 'Oops' , done

    it 'by title', (done)->
      check_Article_Contents article.title , '#article #oops', 'Oops' , done

    it 'by dashed-title', (done)->
      dashed_Title = article.title.replace(/ /g,'-')
      check_Article_Contents dashed_Title  , '#article #oops', 'Oops' , done
```

Note that only the first is currently working, the others are showing the 'no article found page'

**Comment by roman87** [comment]
in the case where there are multiple articles with the same title, what if we show the technology agnostic article? Or a navigate page with the list of articles with the same name?

**Comment by DinisCruz** [comment]
Also support the scenario http://{server}/article/{id}/{title}

http://beta.teammentor.net/article/article-e152ebaf03f0/Hash-a-Password-Using-a-Random-Salt

**Comment by DinisCruz** [comment]
done, all code is pushed (both design master and dev have this code)

**Comment by roman87** [comment]
Some scenarios are missing. 
1. http://localhost:1337/article/0e4dcf783651/Sensitive%20Data%20Is%20Not%20Logged
2. http://localhost:1337/article/article-0e4dcf783651/Sensitive%20Data%20Is%20Not%20Logged
3. There are multiple articles titled "Centralize Logging" as we agreed, we need to show a search page for theses articles.

**Comment by DinisCruz** [comment]
Latest code push contains the first two scenarios and I opened https://github.com/TeamMentor/TM_4_0_Design/issues/469 to track the 3rd (which needs to be handled differently on the backend)

http://localhost:1337/article/0e4dcf783651/Sensitive%20Data%20Is%20Not%20Logged

![image](https://cloud.githubusercontent.com/assets/656739/6320856/c005729a-bae1-11e4-85f0-7bf5ded57129.png)

http://localhost:1337/article/article-0e4dcf783651/Sensitive%20Data%20Is%20Not%20Logged

![image](https://cloud.githubusercontent.com/assets/656739/6320866/086a28be-bae2-11e4-9f7a-bc6818e83f0f.png)

**Comment by roman87** [comment]
Ok looks good. closign
