### ISSUE TITLE
Help page content should have full width (or handle better images)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#444]
this is what happens on small widths

![image](https://cloud.githubusercontent.com/assets/656739/6227519/bdc4f71e-b698-11e4-87d8-307880c84808.png)

and large widths

![image](https://cloud.githubusercontent.com/assets/656739/6227529/cd9bcf78-b698-11e4-84c1-40519f10af36.png)

**Comment by roman87** [comment]
What's the work effort? Closing in 2 days if no work effort is specified :)

**Comment by luchia** [comment]
[This has been fixed.](https://github.com/TeamMentor/TM_4_0_Design/commit/bf6446b96992f42fdb50efdbf0d89ec97a97e21b)

![Uploading Screen Shot 2015-02-18 at 9.40.08 am.png . . .]()
![Uploading Screen Shot 2015-02-18 at 9.40.12 am.png . . .]()
![screen shot 2015-02-18 at 9 40 14 am](https://cloud.githubusercontent.com/assets/4547737/6239313/87658444-b752-11e4-914a-a85967db300d.png)

**Comment by DinisCruz** [comment]
yap, done

**Comment by roman87** [comment]
Actually can we make it wider? it seems like there is lots of space missing on the help pages.

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-19 at 1 33 23 pm](https://cloud.githubusercontent.com/assets/4547737/6261267/ac51f7fc-b83c-11e4-9a63-55b80e3b1e1b.png)

**Comment by roman87** [comment]
Cool. this is fixed now.
