### ISSUE TITLE
[Q] Remove uses of | in Jade files

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#446]
As see here for example

```jade
//- Form Inputs
mixin username-input
    label(for='username')
        | Username
    input(type='text', id='username', name='username', placeholder='Username',value='#{viewModel?viewModel.username:""}',required,maxlength='256')
```
(from https://github.com/TeamMentor/TM_4_0_Design/blob/d98fffb86e47e32d8a690868195c598ef0515d97/source/shared-mixins/globals.jade#L21)

This is related to https://github.com/TeamMentor/TM_4_0_Design/issues/385 since we really shouldn't be using | (pipe) in Jade files (since that means 'no encoding and raw html'

**Comment by luchia** [comment]
Except in some cases, where it's needed to display the icon and the text following it in line - such as on the navigation bar.

**Comment by DinisCruz** [comment]
@luchia can you point me to those exact cases (I want to see if I can come up with a solution that doesn't use the |  )

**Comment by michaelhidalgo** [comment]
I did a search in the application to identify those cases where we are using the | character : 

1.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/jade/_mixins/globals.jade
2.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/jade/_mixins/landing-page-mixins.jade
3.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/shared-mixins/globals.jade
4.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/flare/mixins/globals.jade
5.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/flare/mixins/application-mixins.jade
6.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/flare/mixins/articles-mixins.jade
7.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/flare/mixins/flare_landing_page_mixins.jade
8.https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/flare/mixins/links.jade
9.

**Comment by luchia** [comment]
Thanks @michaelhidalgo :) @DinisCruz the globals mixins L5-20 are the ones I was talking about.

**Comment by DinisCruz** [comment]
@luchia did you try using a **span** tag?

It doesn't seem to have an impact on the ui

Also why are you using the **i** on the style? Are you getting some mappings from the **italic** class?

![image](https://cloud.githubusercontent.com/assets/656739/6333533/b9aaeb42-bb85-11e4-8d33-5a31ba58fbbf.png)

**Comment by roman87** [comment]
@luchia please let me know if this task (start to finish) will take 4h or less. Otherwise we need to reclasify

**Comment by luchia** [comment]
It took me about 20 minutes and has been done in the two referenced commits.

**Comment by luchia** [comment]
Assigned to @michaelhidalgo for QA.

**Comment by michaelhidalgo** [comment]
We can close this issue. I did a search for the "|" character in the .jade files and the occurrences where removed.
