### ISSUE TITLE
Add privacy policy, and link, to TM

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#448]
Privacy policy is currently being reviewed. Once it is published, we need to add it to TM 4.0 with appropriate links in sign up page and footer.

**Comment by luchia** [comment]
Was this the EULA that you sent me?

**Comment by roman87** [comment]
no this is something that we may need to add in the future, so just think of where the link would go on the sign up page. You don't need to add anything now.

**Comment by luchia** [comment]
@roman87, has this document been completed yet?

**Comment by romichg** [comment]
done
