### ISSUE TITLE
Update EULA

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#449]
We need to update the EULA to the latest version found here:
https://drive.google.com/open?id=0B4dAjIRTCZzqWnJOaGZWY3VNM3c&authuser=0

**Comment by luchia** [comment]
Don't have access to that document, can you please approve my request for access?

**Comment by roman87** [comment]
Sent it to you in an email.

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

**Comment by roman87** [comment]
- [ ] none of the menu items below and inclusive of Article V work.
- [ ] the text page is two narrow
- [ ] terms and conditions link on the sign up page does not look like a link until you hover over it.

**Comment by luchia** [comment]
All fixed :)

**Comment by roman87** [comment]
There are 2 links that don't work :)

**Comment by luchia** [comment]
Fixed in the referenced commit :)

**Comment by roman87** [comment]
Ok cool. Closing.
