### ISSUE TITLE
Artifact left after clicking an article to full view page and then clicking the back button.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#451]
In Navigate, click on any article.
Click on the "Back" browser button to get back to the previous page.
Notice the artifact.
![selection_112](https://cloud.githubusercontent.com/assets/1326120/6236938/b16ab8e0-b6bc-11e4-9fb1-92366f4b4fde.png)

**Comment by luchia** [comment]
Is anyone able to recreate this, @DinisCruz @michaelhidalgo @tekgirl77? I'm having no luck.

**Comment by DinisCruz** [comment]
nope I can't replicate it too

**Comment by roman87** [comment]
I can replicate it on FF on Windows. Can you guys give it a shot on windoze?

**Comment by luchia** [comment]
Is it an outline @roman87 ? Can you try recreating it now as I added an outline property to links?

**Comment by roman87** [comment]
It wasn't an outline, but its gone now :)
