### ISSUE TITLE
For logged in users, the handled error page is showing the 'non logged in' nav-bar

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#454]
This is what is currently happening

![image](https://cloud.githubusercontent.com/assets/656739/6240736/691f0b88-b70a-11e4-839d-0f7accdeeab0.png)

and it should be this

![image](https://cloud.githubusercontent.com/assets/656739/6240744/7eb82d1c-b70a-11e4-83ef-c7e32198a149.png)

The 500.jade file is already using the correct base layout (which is ```../_layouts/page```)

```jade
extends ../_layouts/page
include ../_mixins/error-mixins.jade

block content
    #application
        .row
            .col-3
                .lge-container
                    br
            .col-6
                .lge-container
                    +error_500
            .col-3
                .lge-container
                    br
```

What is needed is to populate the ```loggedIn``` variable  (used by ```../_layouts/page```) with the correct value

```jade
if (loggedIn)
	include page_home
else
	include page_landing.jade
```

@michaelhidalgo do you want to have a go at this one?

**Comment by michaelhidalgo** [comment]
Looking into this issue....

**Comment by michaelhidalgo** [comment]
This is the test that for this issue : 

```coffeescript
 it 'Issue 454- Login/Signup options are displayed for logged in users', (done) ->
    jade.login_As_User ()->
      page.open '/article/%s', (html,$)->
        $('#an-error-occured').html().assert_Is("An error occured")
        $('p').html().assert_Is('If this continues, please contact your <a href=\"mailto:support@securityinnovation.com\">TEAM Mentor Support Team</a>.')
        #Testing that Sign Up and Login links are displayed
        $('ul').html().assert_Contains('Sign Up')
        $('ul').html().assert_Contains('Login')
        done()
```

**Comment by roman87** [comment]
Bumping this up as it is pretty important we fix it.

**Comment by michaelhidalgo** [comment]
Yeah I will focos on this

El sábado, 7 de marzo de 2015, RomichG <notifications@github.com> escribió:

> Bumping this up as it is pretty important we fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/454#issuecomment-77702981>
> .
>


-- 
Sent from Gmail Mobile

**Comment by michaelhidalgo** [comment]
I'm currently working on this issue, however, it seems like when there are jade extends like this one : 

```jade
extends ../_layouts/page
```
There is not a HTTP GET performed to retrieve the page, so the router is not picking it up.

I'm trying to come up with another solution

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/603

**Comment by roman87** [comment]
Looks good, closing.
