### ISSUE TITLE
Make code samples show inside gray box (in articles)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#455]
As per https://github.com/TeamMentor/TM_4_0_Design/issues/413#issuecomment-74709540 until syntax-highlight support is added on the server side, we can make the code samples look okish if they are shown inside a gray box

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

**Comment by roman87** [comment]
The boxes and the text  are really light on my screen. Can we make the code samples darker?

**Comment by luchia** [comment]
Can you have a look and tell me what you think now Roman?

**Comment by roman87** [comment]
Nope, the text is really light, the box is gray and it all blends in.

**Comment by roman87** [comment]
![20150223_104954](https://cloud.githubusercontent.com/assets/1326120/6332552/46505e24-bb54-11e4-9177-d402ad53421f.jpg)

**Comment by luchia** [comment]
Is that your screen? :( The whole application looks really, really bad.

**Comment by DinisCruz** [comment]
yeah the text inside the ```<pre>``` is a bit grey. Here is what it looks to me:

![image](https://cloud.githubusercontent.com/assets/656739/6340096/11423e54-bbb4-11e4-8a14-a7a05536f6cc.png)

**Comment by roman87** [comment]
@DinisCruz you need to take pictures with the a camera otherwise the screen difference does not really show. I saw TM on Micheal’s mac and it looks totally different. 
I will take some photos of my screen so you can see what I see. I also asked Lauren to see if she can find a windowze laptop

**Comment by roman87** [comment]
Ok here are some pictures of my screen. They are not great, but you get to see how the app looks like.

![selection_120](https://cloud.githubusercontent.com/assets/1326120/6342798/a12cfdea-bbac-11e4-8aa4-e0b6f40391c5.png)
![selection_121](https://cloud.githubusercontent.com/assets/1326120/6342799/a12e6f9a-bbac-11e4-87a7-07d76c324e6e.png)
![selection_122](https://cloud.githubusercontent.com/assets/1326120/6342803/a412c36e-bbac-11e4-904a-d885ae13f7b6.png)
![selection_123](https://cloud.githubusercontent.com/assets/1326120/6342808/a9b9a954-bbac-11e4-95f8-03566c24ff69.png)
![selection_124](https://cloud.githubusercontent.com/assets/1326120/6342809/ac20a01c-bbac-11e4-8301-9d0242c9555c.png)
![selection_125](https://cloud.githubusercontent.com/assets/1326120/6342810/b0a501b4-bbac-11e4-9a7e-892114bf9dc9.png)
![selection_126](https://cloud.githubusercontent.com/assets/1326120/6342814/b42f292c-bbac-11e4-94f7-db951e9115a1.png)

**Comment by luchia** [comment]
Well that sucks. I wonder if there is a way to load different stylesheets for different OS's? It really looks like too much contrast on a Mac when you do the colours for PC and the colours for Mac look too light on PC screens.

**Comment by roman87** [comment]
Other web sites don't seem to be having this issue on my laptop :). I also think it is less to do with mac/pc vs mac screen.

**Comment by luchia** [comment]
More of a hardware issue than anything else. I tried a couple of more ideas, tell me what you think -

![screen shot 2015-02-26 at 2 41 35 pm](https://cloud.githubusercontent.com/assets/4547737/6386623/c6affdd0-bdcb-11e4-99a0-c958e2156756.png)
![screen shot 2015-02-26 at 2 42 53 pm](https://cloud.githubusercontent.com/assets/4547737/6386621/c6af4278-bdcb-11e4-82be-a4fe2b87a98a.png)
![screen shot 2015-02-26 at 2 43 59 pm](https://cloud.githubusercontent.com/assets/4547737/6386622/c6af5dbc-bdcb-11e4-9168-885a94ddf924.png)
![screen shot 2015-02-26 at 2 44 45 pm](https://cloud.githubusercontent.com/assets/4547737/6386620/c6af2360-bdcb-11e4-9d3f-36b3e31c8130.png)

**Comment by roman87** [comment]
I can't say I am loving the green background :)
What about the background from current TM? Or we can just put it in a box and change the font?

**Comment by luchia** [comment]
I did up there ^^ but you guys said there wasn't enough contrast.

**Comment by roman87** [comment]
If you change the font and make the code exmaples darker there will be contrast :)

**Comment by luchia** [comment]
As per our meeting this morning, I have set the background the same colour as TM's background and have added a dark border for contrast. The code samples also have 1px letter spacing so there is an obvious difference between paragraph content and code content.

![screen shot 2015-02-27 at 3 49 04 pm](https://cloud.githubusercontent.com/assets/4547737/6407833/67fccdd6-be98-11e4-8928-13ac4c9b9cd7.png)

**Comment by roman87** [comment]
Ok but can you make the font smaller and monospace?
![selection_133](https://cloud.githubusercontent.com/assets/1326120/6424305/a8e19012-bec4-11e4-87c3-d6d088d9f5e0.png)

**Comment by luchia** [comment]
The font is monospace, it's Lucida Console or Courier. If you don't like that one, we can look at using a different web font?

![screen shot 2015-03-02 at 1 38 20 pm](https://cloud.githubusercontent.com/assets/4547737/6434887/6c4642f0-c0e1-11e4-8e61-91727e91e8aa.png)

I made the font slightly smaller. It looks like this now -

![screen shot 2015-03-02 at 1 38 12 pm](https://cloud.githubusercontent.com/assets/4547737/6434890/7cc2c770-c0e1-11e4-9c3a-ca92e60a54f4.png)

**Comment by roman87** [comment]
I think its fine for Jade, we will make it better in flare.
