### ISSUE TITLE
[Q] Add (removed) css-check code

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#456]
Due to the bug described at https://github.com/Automattic/juice/issues/104 the QA scripts are not currently doing checks on the rendered css

This could be addressed with an improved use of the ```juice``` api, or with another node css-inliner

**Comment by DinisCruz** [comment]
see solution provided at https://github.com/Automattic/juice/issues/104#issuecomment-74871476

**Comment by tekgirl77** [comment]
Strangely enough this test @DinisCruz wrote to test this, which was throwing an error previously per his notes on Automattic/juice#104, is running successfully on my machine:


![screen shot 2015-02-26 at 3 49 34 pm](https://cloud.githubusercontent.com/assets/6649463/6402842/6ea48bd8-bdd0-11e4-98bd-e422205eb760.png)


However, when I change juiceContent to juiceResources in the original regression test it does throw the same error @DinisCruz referenced in Automattic/juice#104.


![screen shot 2015-02-26 at 3 49 00 pm](https://cloud.githubusercontent.com/assets/6649463/6402959/4f48872a-bdd1-11e4-88bb-fd83e6cc55de.png)

**Comment by tekgirl77** [comment]
Tried proposed solution and updated notes @ https://github.com/Automattic/juice/issues/104#issuecomment-83099719

**Comment by tekgirl77** [comment]
Tested with their latest juice beta build and it still seems to have issues with using the absolute path.  Notes here @ https://github.com/Automattic/juice/issues/104#issuecomment-83192701

Will see what they come back with.

**Comment by DinisCruz** [comment]
ok cool, btw, if we can't get this to work, we could try another CSS Inline api

**Comment by tekgirl77** [comment]
I was thinking that too... we'll give them a bit to see if they come back
with a fix first, since they seem so close to having this working and have
been pretty responsive.


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by tekgirl77** [comment]
Played around with "inliner" a bit today with no luck.  
https://github.com/remy/inliner

``` Coffeescript 
  it.only 'Issue 456 - Refactor css-check code', (done)->
    inliner = require('inliner')
    jade.login_As_User ->
      jade.page_User_Main (html, $)->
        cheerio = require('cheerio')
        baseUrl = page.tm_Server;
        log "baseUrl is " + baseUrl
        inliner baseUrl, (err,cssHtml)->
          throw (err) if err
          $css = cheerio.load(cssHtml)
          attributes = $css('.input-group-btn').attr()
          attributes.assert_Is { class: 'input-group-btn', style: 'display: table-cell; vertical-align: bottom;' }
          done()
```


![screen shot 2015-03-24 at 9 08 55 am](https://cloud.githubusercontent.com/assets/6649463/6804829/7120d7ce-d205-11e4-84d3-42c0030f2636.png)

**Comment by tekgirl77** [comment]
Submitted [PR here](https://github.com/TeamMentor/TM_4_0_QA/pull/30) - 
Replaced Juice w/ "inline-css" for TM_4_0_Design/456.
https://github.com/jonkemp/inline-css

If this looks good, this issue can be closed - let me know if you'd like any changes made.

**Comment by DinisCruz** [comment]
yap, code is merged and all tests are passing 

![image](https://cloud.githubusercontent.com/assets/656739/7133202/afd4a1e2-e288-11e4-80db-f494aa5bc687.png)
