### ISSUE TITLE
[Q] Refactor GraphDB services into better folder locations

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#457]
Hi @michaelhidalgo and @tekgirl77 can you you take a look at the refactored location of the GraphDB services and let me know what you think of it?

There is quite a lot of code in those methods and I'm trying to simplify the code and make it easier to read/test

See https://github.com/TeamMentor/TM_4_0_GraphDB/commit/1945dc709dbcb1710e2a8f43f06971f3f6d0f401 commit for the code changes and the [services](https://github.com/TeamMentor/TM_4_0_GraphDB/tree/master/src/services) folder for the latest version of the file structure.

![image](https://cloud.githubusercontent.com/assets/656739/6247453/a6531082-b76c-11e4-94f3-93b51b5c65b0.png)

(since a lot of refactoring has been done, this issue is more of a question to Michael and Salle)

**Comment by tekgirl77** [comment]
Looks more intuitive and organized to me, separated by function.  2 thumbs up!

**Comment by DinisCruz** [comment]
Just pushed https://github.com/TeamMentor/TM_4_0_GraphDB/commit/2681f4da6a7e7d436e74831b30333cb90ff387fb which continues the refactoring and splits the Import-Service.coffee into multiple files

Import-Service was massive and contained all sorts of functionality (as can seem bellow by the new files created from it) 

![image](https://cloud.githubusercontent.com/assets/656739/6252839/fbcdb940-b794-11e4-9c89-bbd4b56838b2.png)

![image](https://cloud.githubusercontent.com/assets/656739/6252879/4101cc54-b795-11e4-9e05-87c8f81daaa5.png)

I'm now done with this set of refactorings. @michaelhidalgo please close the issue once you've reviewed it

**Comment by michaelhidalgo** [comment]
Ok cool :)

El miércoles, 18 de febrero de 2015, Dinis Cruz <notifications@github.com>
escribió:

> Just pushed TeamMentor/TM_4_0_GraphDB@2681f4d
> <https://github.com/TeamMentor/TM_4_0_GraphDB/commit/2681f4da6a7e7d436e74831b30333cb90ff387fb>
> which continues the refactoring and splits the Import-Service.coffee into
> multiple files
>
> Import-Service was massive and contained all sorts of functionality (as
> can seem bellow by the new files created from it)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/656739/6252839/fbcdb940-b794-11e4-9c89-bbd4b56838b2.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/656739/6252879/4101cc54-b795-11e4-9e05-87c8f81daaa5.png>
>
> I'm now done with this set of refactorings. @michaelhidalgo
> <https://github.com/michaelhidalgo> please close the issue once you've
> reviewed it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/457#issuecomment-74909735>
> .
>


-- 
Sent from Gmail Mobile

**Comment by romichg** [comment]
done
