### ISSUE TITLE
Searching using an article's 'title' produces no results

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#459]
Searching for example for 'All File Path and Name Input Is Canonicalized' should result in at least 3 articles (since there are 3 articles with that title)

here is what is currently happening

![image](https://cloud.githubusercontent.com/assets/656739/6253758/bbaa9d86-b79b-11e4-8e37-71dea5c3acdc.png)

this is the expected behaviour

![image](https://cloud.githubusercontent.com/assets/656739/6253773/cebaed90-b79b-11e4-99e2-4f9e3b988a59.png)

**Comment by DinisCruz** [comment]
Done

Note: the root cause of the issue was the fact that there is a search for a title that matches the search query (so that the searches shown below work), and since the article also has a title (in the graphdb) the article-id was being treated as a query (which of course had no results)

![image](https://cloud.githubusercontent.com/assets/656739/6253811/20113082-b79c-11e4-8404-c1c2ed427ebf.png)

![image](https://cloud.githubusercontent.com/assets/656739/6253868/7ac1fd68-b79c-11e4-91f8-7f0413f22c0a.png)

**Comment by roman87** [comment]
All is fixed. Good catch.
