### ISSUE TITLE
[Q] Delete _Old_To_Delete_Soon folder 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#468]
@luchia can we delete the https://github.com/TeamMentor/TM_4_0_Design/tree/master/_Old_To_Delete_Soon/__Not_Used_In_Jade folder?

If so, can you do it?

**Comment by DinisCruz** [comment]
Ok, I just deleted this, for reference the files can be seen (and browsed) on this commit https://github.com/TeamMentor/TM_4_0_Design/tree/edbe73213b631611b19a33558e69bb18e9846110/_Old_To_Delete_Soon/__Not_Used_In_Jade

**Comment by roman87** [comment]
done, closing
