### ISSUE TITLE
Show search results for 'article direct view using title' that have more than 1 match

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#469]
See this thread for more details https://github.com/TeamMentor/TM_4_0_Design/issues/443#issuecomment-75175416

The idea is to show this

![image](https://cloud.githubusercontent.com/assets/656739/6320838/43513cc0-bae1-11e4-9937-775650222f47.png)

when directly opening an article using its title. 

For example http://localhost:1337/article/Centralize-Logging which at the moment goes to the first article found:

![image](https://cloud.githubusercontent.com/assets/656739/6320843/686ddfb8-bae1-11e4-96a4-7fa832840b7b.png)

**Comment by roman87** [comment]
I am going to make this a P1, since search and bug fixes are more important.

**Comment by DinisCruz** [comment]
I don't think we need this anymore, there will be very real cases of this being actually hit by an user, and the new search capabilities will deal with this

Basically we should be saying: 'dont link to urls without the guid on it' , here is a good example of how to do it : http://localhost:1337/article/c423cd29744a/Centralize-Logging

**Comment by roman87** [comment]
Well, an easy direct link to an article title is still something we need to support as it is a requirement for 
https://github.com/TeamMentor/Master/issues/879
And specifically: 
https://github.com/TeamMentor/Master/issues/375
https://github.com/TeamMentor/Master/issues/878

**Comment by roman87** [comment]
I am going to move this to Sprint 3 though as this is something we can do later.

**Comment by DinisCruz** [comment]
still think we should drop this specific feature

**Comment by roman87** [comment]
How else are you going to use a direct link to article title?

**Comment by DinisCruz** [comment]
we should use the 'direct link' field that we added on 3.5 or use the current links

**Comment by roman87** [comment]
Yes, but what if I want the direct link to be the article title?

**Comment by DinisCruz** [comment]
That should not be a supported action, specially since it would lead to broken links if the title it renamed

**Comment by roman87** [comment]
Ok agreed. dropping
