### ISSUE TITLE
Default to /article/{article-id}/{dashed-article-title} syntax for search article links

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#470]
Following the feature added at https://github.com/TeamMentor/TM_4_0_Design/issues/443 

Instead of using [http://localhost:1337/article/article-000000026eca](http://localhost:1337/article/article-000000026eca) for links created on the 'search' page:

![image](https://cloud.githubusercontent.com/assets/656739/6320880/68c9b6ca-bae2-11e4-9253-2e4fca932242.png)

... or search result links:

![image](https://cloud.githubusercontent.com/assets/656739/6320900/ad587d3a-bae2-11e4-9fd9-fd8b856e83db.png)

Use the shorter and more descriptive syntax of: [http://localhost:1337/article/000000026eca/All-File-Path-and-Name-Input-Is-Canonicalized](http://localhost:1337/article/000000026eca/All-File-Path-and-Name-Input-Is-Canonicalized)

![image](https://cloud.githubusercontent.com/assets/656739/6320910/e3d6450e-bae2-11e4-9f60-9bc091210e46.png)

**Comment by roman87** [comment]
Making this a P1 as well. Search and Recent articles are more important.

**Comment by DinisCruz** [comment]
This is now fixed https://travis-ci.org/TeamMentor/TM_4_0_Design/builds/53928313

now the links that you can see on http://localhost:1337/search?text=Log+Files+Are+Protected

![image](https://cloud.githubusercontent.com/assets/656739/6595204/0ae3a042-c7e0-11e4-850b-0a5350f22615.png)

go to: http://localhost:1337/article/e6ad7b8a48f0/Log-Files-Are-Protected

![image](https://cloud.githubusercontent.com/assets/656739/6595211/216be0ea-c7e0-11e4-9bc3-a8e0cab59d70.png)


same thing is happening on the links from the main **/show/{query}** pages

http://localhost:1337/show/query-6234f2d47eb7,query-1a265c6dffd1

![image](https://cloud.githubusercontent.com/assets/656739/6595224/364fba4a-c7e0-11e4-80f4-39cf0c5eba21.png)

with the first link going to 

http://localhost:1337/article/22924d76a42b/Set-Pointers-to-Null-After-Deallocation-to-Prevent-Dangling-Pointers

which is a big link, but kinda works

![image](https://cloud.githubusercontent.com/assets/656739/6595245/58cfc52e-c7e0-11e4-962d-917ee8e10f16.png)

The **Recently Viewed** and **Top Articles** links are also now using the same url format

![image](https://cloud.githubusercontent.com/assets/656739/6595255/732c7f16-c7e0-11e4-8f75-b1f459841a8b.png)

**Comment by roman87** [comment]
Looks good!
