### ISSUE TITLE
Navigate Button is not intuative

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#471]
This feedback comes from both @joebasirico and @BendixSpring .It is not clear to the user that they need to click on the navigate in order to see the whole taxonomy of articles and navigate using keywords/filters. Perhaps we rename it to Index? or Directory? Anyways this needs more thinking.

**Comment by luchia** [comment]
Didn't we already go through all of that and ended up at Navigate, last year?

**Comment by BendixSpring** [comment]
I’m not sure what’s been done or what was decided.  But if the navigate button is still not intuitive, then maybe the discussion should be revisited.

 

--Danny

**Comment by roman87** [comment]
Agreed with @BendixSpring  we have two power users unclear on this, we need to revisit the discussion. 
Also remember that we discussed last year that  navigate button was supposed to open up a menu of things, including "Index", "My Saved Articles" etc.. We did away with the menu for this release, but left the "Navigate" button.

**Comment by luchia** [comment]
Gotcha.

**Comment by roman87** [comment]
Jason suggested we rename it to "Index". Any objections? if not can we make that change?

**Comment by BendixSpring** [comment]
Index is probably better.  Let’s try and see how it works.

**Comment by luchia** [comment]
As discussed in our meeting this morning, we have made the change from Navigate to Index. I made the change to Index -

![screen shot 2015-02-25 at 10 33 30 am](https://cloud.githubusercontent.com/assets/4547737/6362151/c88e76a6-bcd9-11e4-95f0-ae9cdad639b2.png)

However, I now think that maybe the icon that is paired with the link doesn't make sense. So I added a different one instead, which I think is better -

![screen shot 2015-02-25 at 10 38 07 am](https://cloud.githubusercontent.com/assets/4547737/6362200/786bd8a2-bcda-11e4-8065-d8ab8bf8664c.png)

**Comment by BendixSpring** [comment]
Looks good!

 

So from a usability perspective, there is a certain dissonance.  The thing that is so nice about this tool is the ability to select topics and filters.  Yet when the tool is first opened, they are not there.  What do we want  users to do first?  Search?  Click a popular topic?  What if the first thing the user wants to do is select a category and then filter?  I think you need to have the filters.

**Comment by roman87** [comment]
Yep, I like it as well. will follow up and close it when next beta is out.

**Comment by luchia** [comment]
@BendixSpring, I thought I would have a go at answering some of your questions.

From our (the company) perspective, the original overall goal is to make TM a search-driven application so that's what we focus on from the start. We make quick searches and results easy (popular search terms/articles, new articles etc) and we make it easy for the user to begin searching straight away.

The index is still there for navigation and browsing but I like to think that most of our users are pretty good searchers, for their own work related purposes and through personal time spent using popular search engines. I know that my own googling skills are 100x better than before I learnt to program. Something about trying to fix bugs can make you a desperate person!

Jade doesn't and can't easily answer the question that you're asking. We have designed the application in Flare so that from the get-go, users are able to access filters when and if they need them to narrow their search results. Flare is going to be a huge improvement on user experience and accessibility and will answer a lot of the questions I think people have about how this version of TM is better than the last. It really is a big step forward for the app and I can't wait to share it.

**Comment by roman87** [comment]
@BendixSpring to expand a bit on @luchia comments. There are basically 3 ways that people want to access information in TM. 
1. They know something about the thing they are looking for. In this case, we provide a faceted search. i.e. the user searches for some keyword they think they know and then presented with a set of filters to narrow the search down (think amazon, ebay, etc) 
2. They want to browse the information/directory of our articles through some taxonomy. In this case we provide our Index -  a way to navigate the article list by selecting topics, subject matters, and filtering those down. Or alternatively starting with a filter, like technology and navigating subjects and topics (that is no there yet). There are multiple taxonomies that can be accommodated. So far we only have one.
3. They have no clue what they are looking for. This is where curated content comes in. These are set of articles that offers a sandbox to explore ideas and subjects, with links to more content. (this is not there yet)

So yes, the primary function is to search. That is why the filters, the taxonomy and article list are not there on the first page.

**Comment by BendixSpring** [comment]
Roman:

 

You said that there are 3 basic ways people want to access TM information.  Why do you think that most people will choose “search” over one of the other methods?  In terms of user friendliness, put all 3 options up front when a user logs in.  Maybe today the user will select #1.  Maybe tomorrow they will select #3.  

 

Why limit search options with the current implementation?

 

--Dannyh

**Comment by roman87** [comment]
Well, it is impossible to put all 3 on the front page :) So the two currently implemented options (search and navigation) are there on the main menu. the front page has a search bar, most popular/recent articles/searches, in the future it it may have things like - trending articles, news, my teams articles etc. 

I am not sure I understand by what you mean by "Why limit search options with the current implementation?"

**Comment by BendixSpring** [comment]
Maybe I just don’t understand things.

 

One the left side, there is some selector thing.  (Sorry, I don’t know what it’s called.)  On the right side, there is a filter.  That’s 2 navigation solutions.  Then you have the search bar.  That’s a third solution.  And then you have popular articles.  That’s a fourth solution.

 

Users may try the left selector thingy or the filters or the search bar or the popular articles.  Why not just have all of those displayed on first login?  They are available after a user starts looking for content.

 

I hope this helps explain my confusion.

 

--Danny

**Comment by roman87** [comment]
Yes I very much see what you are saying. The problem here is that in your example, popular articles will not fit on the screen :). In the future the curated content will not fit on the screen  etc... The idea here was to provide multiple starting points for the user to look at content, with emphasis on search.  We can't just put all the starting point on the first page all at once as it will be a mess. Look at ti this way, when you go to amazon, the front page you see has little relevance to what you really want. (in fact for amazon its a space to put up advertizements of their products. Then you can ether hit the directory and navigate through it, or you can search for the product and filter out things. These are both starting points that lead to different user experiences. 
We can definitely play with multiple options and see how they all work.

Hope this makes sense.

**Comment by romichg** [comment]
Closing due to TTL
