### ISSUE TITLE
[Q] Add controller to handle pages that need to be shown to anonymous and logged in users

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#474]
At the moment we have routes like ```.../guest/{jade page}``` for pages that should only be seen by anonymous users, and ```.../user/{jade page}``` for pages that should only be seen by logged in users

The question is what should we call the pages that should be seen by both?

For example the Help pages or the **Terms & conditions`** page (see https://github.com/TeamMentor/TM_4_0_Design/issues/461). Both need to have dynamic top navigation, since the links to show depend on the user's logged in status

I'm thinking of going with **misc**, with a new controller called ```Misc-Controller.coffee``` being added to the TM_Design code (this controller which would create routes using the format  ```/misc/{jade page}``` )

**Comment by roman87** [comment]
Why is this a Quality type? This is really a task that is needed to resolve #461 bug.

**Comment by romichg** [comment]
This is done.
