### ISSUE TITLE
[Q?] refactor Help Pages tests so that TM_Design does not depend on live server

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#475]
At the moment the tests that check if the help functionality is still working ok are placed on the wrong locations.

The TM_Design tests are currently doing an end-to-end test checks, and the QA tests are very light

While making this change, move the Help_Controller and tests into the **/misc** folder (as per https://github.com/TeamMentor/TM_4_0_Design/issues/474)

**Comment by roman87** [comment]
Seems like the title of this issue does not match the description. Can we clarify?

**Comment by DinisCruz** [comment]
This is done on the latest commits
