### ISSUE TITLE
Filter and navigation div's should not move when scrolling the article list. Both righthand and lefthand side filters should, when opened stay put.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#478]
This is only for Flare. Seems obvious but just noting it here.

**Comment by luchia** [comment]
Both search and what?

**Comment by roman87** [comment]
Sorry, was thinking faster than i I was typing :)

**Comment by luchia** [comment]
Mentioned in #522

**Comment by luchia** [comment]
This has been fixed in my recent work on Flare which also relates to #702. I'm in the process of merging all the Flare files over to the new layout which works better in the browser. This issue has been resolved but can't really be tested/checked/proven until we have Flare wired up.

**Comment by luchia** [comment]
This has been completed, still need to tidy up the smaller elements within this feature but the functionality is there -

![http://i.imgur.com/eEupdyd.gif](http://i.imgur.com/eEupdyd.gif)

**Comment by romichg** [comment]
Moving it back to @luchia since we just talked about how exactly this should be done.

**Comment by luchia** [comment]
This has been completed. PR submitted today.

**Comment by romichg** [comment]
This is done.
