### ISSUE TITLE
Terms and Conditions Page header misconfigured

### ISSUE THREAD

**Issue by dineshshetty** [TeamMentor/TM_4_0_Design#479]
When I log in to the application, the page headers normally change from "Login" to "Logout". However, even after login, if I navigate to the Terms and Conditions page, the page header still shows "login". It should show "Logout", since I navigated to the page after logging in to the application.

Step1: Log in to the application.
![image](https://cloud.githubusercontent.com/assets/2169995/6361762/aa650572-bc53-11e4-80a7-099b21acaddc.png)
Observe, that the header now gives an option of "Logout".
Step 2: Open any of the existing guidelines:
![image](https://cloud.githubusercontent.com/assets/2169995/6361769/bbf2bda2-bc53-11e4-8c5f-15be77906954.png)
Step 3: Click on the Terms and Conditions option at the end of the page.
![image](https://cloud.githubusercontent.com/assets/2169995/6361799/fc33279e-bc53-11e4-903e-2cdf28034688.png)
Observe that the page header is still "Logout" as this is a postlogin page.
Step 4: Below screenshot shows the Terms and Conditions page 
![image](https://cloud.githubusercontent.com/assets/2169995/6361853/83087d3c-bc54-11e4-8f1b-ac69dbcf8840.png)
Observe that the page header shows "login" even though this page was launched after a successful login. 
Any post login page should give a "logout" page header instead of the "login" page header.

**Comment by michaelhidalgo** [comment]
Thanks for your feedback @dineshshetty , this issue is related to https://github.com/TeamMentor/TM_4_0_Design/issues/454

**Comment by roman87** [comment]
Thank you so much @dineshshetty  it is a known issue :). However I also notice that on your first screen shot you seem to be experiencing the same issue as described here: https://github.com/TeamMentor/TM_4_0_Design/issues/451
We have fixed it, but it is not in the latest beta, yet. What hardware/OS are you running on?

**Comment by dineshshetty** [comment]
I came across the bug while running the latest Firefox on Windows 8.1. The
base hardware is  Lenovo W530.

-dns

**Comment by DinisCruz** [comment]
@dineshshetty this has been fixed on the CR.Beta.3 version we just pushed to https://beta.teammentor.net

can you take a look? 

and if the issue has been addressed, please close it :)

**Comment by dineshshetty** [comment]
Tested this now, and looks like it has been resolved :) Thanks.

**Comment by roman87** [comment]
Great, thanks
