### ISSUE TITLE
Is the logout button bold on purpose?

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#483]

**Comment by luchia** [comment]
I don't think it is, at least it doesn't look it on my screen. 

![loginsignup](https://cloud.githubusercontent.com/assets/4547737/6407748/4f6248f2-be96-11e4-991b-f64e9d823916.jpg)

Can you show me what it looks like on yours?

**Comment by roman87** [comment]
Hmm.. doesn't seem like its there anymore. I was talking about the Nav button logout. Weird. Will close this for now. Just keep an eye on it if it happens again.
