### ISSUE TITLE
Still a problem with artile titles scrolling past the search bar on mobile view

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#485]
![selection_135](https://cloud.githubusercontent.com/assets/1326120/6427496/1fe1e31a-bf51-11e4-9ac6-3362b085498d.png)

**Comment by luchia** [comment]
Not still a problem, it just would have come up again with all the recent changes we to the structure of the app. Should be fixed now.

![screen shot 2015-03-02 at 1 28 31 pm](https://cloud.githubusercontent.com/assets/4547737/6434809/391ea526-c0e0-11e4-9a70-63778c060936.png)
![screen shot 2015-03-02 at 1 29 05 pm](https://cloud.githubusercontent.com/assets/4547737/6434810/39200c7c-c0e0-11e4-8ec6-0bc0ecae7da7.png)
![screen shot 2015-03-02 at 1 29 27 pm](https://cloud.githubusercontent.com/assets/4547737/6434811/392086ca-c0e0-11e4-8805-05c0d621a322.png)
![screen shot 2015-03-02 at 1 29 32 pm](https://cloud.githubusercontent.com/assets/4547737/6434813/3920b226-c0e0-11e4-8a21-fe769689ac7c.png)
![screen shot 2015-03-02 at 1 29 41 pm](https://cloud.githubusercontent.com/assets/4547737/6434812/39208d64-c0e0-11e4-9f3c-50b345220a91.png)

**Comment by DinisCruz** [comment]
yap, fixed on latest commits

**Comment by michaelhidalgo** [comment]
Yes it seems like it was fixed in the latest commit, this is how it looks like in iphone emulation mode 

![0003screenshot](https://cloud.githubusercontent.com/assets/1732035/6449478/7e8b4460-c0e6-11e4-9164-386f092ebf82.png)

**Comment by roman87** [comment]
This is fixed
