### ISSUE TITLE
[Q] Refactor node source code inside TM_Design into a src folder

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#487]
To follow conversion all non-test code should be inside an **src** folder which should be at the same level as the **tests** folder

![image](https://cloud.githubusercontent.com/assets/656739/6438608/c5bfa412-c0c2-11e4-8fb5-9ec7381b0a48.png)

Also, I think we could name that **node** folder to something that would make more sense (maybe **server** or **lib** or **code**)

**Comment by roman87** [comment]
I like lib and server :)

**Comment by romichg** [comment]
done
