### ISSUE TITLE
Can we change 'Help' to 'Docs'?

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#489]
Seems like it's more explanatory of what the page contains and fits in with the tone we use throughout the app/websites relating this product.

**Comment by roman87** [comment]
Sure, lets make it so.

**Comment by luchia** [comment]
This can be seen on new branch 'Issue_489_Change_Link_Name'. Screens below -

![screen shot 2015-03-04 at 9 33 42 am](https://cloud.githubusercontent.com/assets/4547737/6474557/ae8987fa-c251-11e4-98da-d06c444f1ba7.png)
![screen shot 2015-03-04 at 9 33 46 am](https://cloud.githubusercontent.com/assets/4547737/6474558/aec2b6b0-c251-11e4-867b-c0a44e9df508.png)

**Comment by roman87** [comment]
Looks good, lets merge the change.

**Comment by luchia** [comment]
This has already been merged to Dev.

**Comment by roman87** [comment]
Done. Closing
