### ISSUE TITLE
Security Innovation Copyright footer out of date

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#490]
The copyright footer note displayed below indicates from 2007 to 2014, we should be using the current year dynamically.

![screen shot 2015-03-02 at 10 03 06 pm](https://cloud.githubusercontent.com/assets/1732035/6456384/e41b3b1e-c127-11e4-9415-cbedc86483cb.png)

**Comment by roman87** [comment]
Yep good one. @luchia can you work with @michaelhidalgo to get this fixed. First lets change it to 2015 as a P0 in Jade, and then lets work on doing it dynamically on the backed as a P3 in Flare.

**Comment by luchia** [comment]
This can be seen on the Issue_490_Change_Copyright_Date branch. Screens below -

![screen shot 2015-03-04 at 9 37 25 am](https://cloud.githubusercontent.com/assets/4547737/6474617/2541d1ea-c252-11e4-9828-6d5e388bc407.png)

**Comment by luchia** [comment]
While I'm on this issue, do we need all of that information in the copyright?

**Comment by michaelhidalgo** [comment]
Yap, it was fixed in the referenced branch.
![screen shot 2015-03-05 at 10 07 35 am]
(https://cloud.githubusercontent.com/assets/1732035/6508580/57cd0e04-c31f-11e4-83b8-82db9b7ce20f.png)

**Comment by roman87** [comment]
Looks good. Lets create a PR.

**Comment by luchia** [comment]
This was already merged from my branch.

**Comment by michaelhidalgo** [comment]
This is fixed.

![screen shot 2015-03-09 at 11 02 57 am](https://cloud.githubusercontent.com/assets/1732035/6559897/aa39bd98-c64b-11e4-8577-05d8f5f23ac2.png)
