### ISSUE TITLE
First click of right hand side filter doesn't work (2nd does)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#492]
I just noticed a weird bug on the right hand side nav. Here are the steps to replicate

1) open http://localhost:1337/show/Guidance

![image](https://cloud.githubusercontent.com/assets/656739/6461779/4adc53b0-c19b-11e4-8762-f02021b11c8f.png)

2) click on a filter (for example **C++** ), which will open http://localhost:1337/show/Guidance/query-68d5b99e58ae

note that the filter didn't work and the **selected filter** box is empty

![image](https://cloud.githubusercontent.com/assets/656739/6461785/62de34ba-c19b-11e4-9140-fa3b6a61fbc0.png)

3) click again on the same filter (in this case **C++**, and we will get http://localhost:1337/show/Guidance/query-a54bd222cc71 which is the correct result

![image](https://cloud.githubusercontent.com/assets/656739/6461791/8794550a-c19b-11e4-91a5-e7451cedfaae.png)

**Comment by DinisCruz** [comment]
I found the root cause of this, the problem happens when the **dataReload** method is called and the data_cache is not cleaned/removed

This can be triggered by a full run of the unit tests (without first removing the .tmCache) or via the REST API:

![image](https://cloud.githubusercontent.com/assets/656739/6467755/1ae3a352-c1c8-11e4-9900-ec218377bfcb.png)

Since we now have a method to quickly delete the **data_cache** (see https://github.com/TeamMentor/TM_4_0_Design/issues/498) and one will not get a clean unit test execution (see below), I think we can make this a P2. @roman87 what do you think?

@tekgirl77 do you want to have a go at writing a QA script that checks for the correct behaviour via the web ui?

For reference here is the GraphDB tests that will fail when this problem is occurring (which is cool, since it means that when the problem is happening, GraphDB unit test execution will not complete without test failtures)

```coffee
      it 'query_tree_filtered', (done)->
        @timeout 10000
        clientApi.root_queries (data)=>
          root_Queries = data.obj
          query_Id = root_Queries.queries.first().id
          filters  = ''
          clientApi.query_tree {id: query_Id, filters: filters }, (data)=>
            size_No_Filters = data.obj.results.size()
            result_Filter   = data.obj.filters.first().results.first()
            filter_Query_Id = result_Filter.id
            filters         = filter_Query_Id
            clientApi.query_tree_filtered {id: query_Id, filters: filters }, (data)=>
              data.obj.results.assert_Size_Is result_Filter.size
              done()
```

**Comment by roman87** [comment]
Good catch. I can't replicate it though. What if we call delete data_cache as part of the reload. Seems logical?

**Comment by DinisCruz** [comment]
Actually, the problem is not that easy to replicate (and there is a case when the tests will still pass when the problem exists).

In all cases it is fixed by removing the **data_cache** folder

The positive test (check when all is ok) is not affected by this, since what we should be testing is for the expected behaviour (note that this test will eventually also be executed in the set of tests that will run against a live/QA instance of TM 4.0)

**Comment by tekgirl77** [comment]
@DinisCruz I have no data coming up at all @ http://localhost:1337/show/Guidance - it does not show in neither the QA/GraphDB nor GraphDB for me... 


![screen shot 2015-03-19 at 9 08 59 am](https://cloud.githubusercontent.com/assets/6649463/6733681/48bfa606-ce19-11e4-97bc-f306e0172b61.png)

**Comment by tekgirl77** [comment]
Submitted pull request for QA:
https://github.com/TeamMentor/TM_4_0_QA/pull/24

 ``` Coffeescript
  it 'Issue 492 - Validate right-hand side filter is working',(done)->
    jade.login_As_User ()->
      jade.page_User_Graph "Index", (html,$)->
        $('#activeFilter').text().assert_Is('')
        $($('#filters .filter-icon').get(2)).text().assert_Is("C++")
        filterLink = $('#filters .nav a').eq(2).attr().href
        page.open filterLink, (html,$)->
          clearFilterLink = $('#activeFilter a')
          activeLinkText = $('#activeFilter').text().remove(clearFilterLink.text())
          activeLinkText.assert_Is("C++")
          done()
```

**Comment by tekgirl77** [comment]
Also, this passes on my local machine, but is throwing an assertion error on [Travis](https://travis-ci.org/tekgirl77/TM_4_0_QA).

**Comment by romichg** [comment]
Can we close this?

**Comment by DinisCruz** [comment]
yes we can close it, @tekgirl77 can you submit a PR with the test (rebased) to the latest https://github.com/TeamMentor/TM_QA

Thanks
