### ISSUE TITLE
Fix  hr thematic break when displaying article's references

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#495]
As displayed in this article http://localhost:1337/article/cf9e691f-d091-4b46-8177-ce1a3bda24f8, the hr element displayed to separate the content from the reference seems to be centered in the screen. Also there is a big space between the hr element and the Adapted from Microsoft patterns & practices guidance text.

![screen shot 2015-03-03 at 6 33 57 am](https://cloud.githubusercontent.com/assets/1732035/6462557/c1059302-c16f-11e4-8f2d-38a1513faf4f.png)

**Comment by DinisCruz** [comment]
In this case, I think the HR might look better if it is wider?

That way the spacing would be ok

**Comment by roman87** [comment]
@luchia  can you take a look and let us know what you think?

**Comment by luchia** [comment]
I think the spacing is fine but I changed the width on the branch Issue_495_HR. Screens below -

![screen shot 2015-03-04 at 9 49 51 am](https://cloud.githubusercontent.com/assets/4547737/6474819/16ad4810-c254-11e4-95eb-ccfc356e69b0.png)

**Comment by michaelhidalgo** [comment]
I think it looks good. I searched this article (which has few content and the reference to Patterns & Practices) http://localhost:1337/article/article-1ae6d25f1315

![screen shot 2015-03-05 at 10 14 13 am](https://cloud.githubusercontent.com/assets/1732035/6508754/4bad8fbc-c320-11e4-81ba-1488fbfedca0.png)

**Comment by roman87** [comment]
Looks good. Closing

**Comment by roman87** [comment]
Ooops sorry, lets create a PR for this. And assign it back to me.

**Comment by luchia** [comment]
This was also already merged.

**Comment by roman87** [comment]
Yep closing
