### ISSUE TITLE
Should we show user recent searches on Search page?

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#496]
While fixing the recent 'top articles' and 'popular searches' It was easy to also capture the current user's latest searches

What do you think? This is what it would look like:

![image](https://cloud.githubusercontent.com/assets/656739/6462635/a8f0317c-c1a2-11e4-8d12-7f70387cd736.png)

**Comment by roman87** [comment]
As discussed, lets hold off on this in Jade.
