### ISSUE TITLE
TEAM Mentor Search box encoding Issue for + (URL Encoding)

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#497]
It seems like the Search text box is behaving a bit weird when displayed results previously selected from the  main page.

1. In this case, C++ is a search element : 
![screen shot 2015-03-03 at 6 40 11 am](https://cloud.githubusercontent.com/assets/1732035/6462621/45ae1462-c170-11e4-851d-8c26d70cfdee.png)

2. This is how it looks like in the raw HTML 

![screen shot 2015-03-03 at 6 40 53 am](https://cloud.githubusercontent.com/assets/1732035/6462623/45b18b60-c170-11e4-9229-f9c76ca0a573.png)

3. When clicking in C++ To display the results for that technology, the  ++ characters are replaced by white spaces :  

![screen shot 2015-03-03 at 6 41 09 am](https://cloud.githubusercontent.com/assets/1732035/6462622/45b18d4a-c170-11e4-816f-900093c86410.png)

4. By looking at the raw HTML we confirm that there are white spaces when there should be the  ++ characters.

![screen shot 2015-03-03 at 6 41 22 am](https://cloud.githubusercontent.com/assets/1732035/6462624/45b73862-c170-11e4-8596-e81f803c170a.png)

**Comment by michaelhidalgo** [comment]
Note that this does not happen with the apostrophe character  : 

The URL is : http://localhost:1337/search?text=Don%27t

![screen shot 2015-03-03 at 6 47 36 am](https://cloud.githubusercontent.com/assets/1732035/6462714/1b4c7f78-c171-11e4-930c-18fc56dc3eac.png)

When looking for C++, the URL is http://localhost:1337/search?text=C++

**Comment by michaelhidalgo** [comment]
This is indeed a URL encoding Issue as the C++ should be URL-encoded as C%2B%2B

http://localhost:1337/search?text=C%2B%2B

![screen shot 2015-03-03 at 7 17 40 am](https://cloud.githubusercontent.com/assets/1732035/6463150/3f9b1b6a-c175-11e4-82e0-2724c28143d4.png)

**Comment by michaelhidalgo** [comment]
... and it is also happening in beta https://beta.teammentor.net/user/main.html

![screen shot 2015-03-03 at 7 22 19 am](https://cloud.githubusercontent.com/assets/1732035/6463226/ed86ec90-c175-11e4-8310-1c761a7fbcce.png)

**Comment by michaelhidalgo** [comment]
We might need to use the CoffeeScript URL-encode methods http://coffeedoc.info/github/dropbox/dropbox-js/ie/classes/Dropbox/Xhr.html#urlEncode-class when rendering the POPULAR SEARCH TERM from the graph.

**Comment by roman87** [comment]
Yep, looks like a very good catch!

**Comment by roman87** [comment]
@michaelhidalgo do you want to take a stab? at fixing this? This seems like simply making sure we do urlencode before saving to popular search items.

**Comment by michaelhidalgo** [comment]
Yeah, assigning it to me.

2015-03-03 12:11 GMT-06:00 RomichG <notifications@github.com>:

> @michaelhidalgo <https://github.com/michaelhidalgo> do you want to take a
> stab? at fixing this? This seems like simply making sure we do urlencode
> before saving to popular search items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/497#issuecomment-77001024>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
for reference in this case the reason the + are being converted into spaces, is because the browser converts + into spaces (when used in the url)

**Comment by michaelhidalgo** [comment]
This test verifies that the popular search items contains links that are not url encoded.

```coffeescript
  #This test verifies that the link text is not Url-encoded
    it.only "Issue_497 - Url encoding on popular search items", (done)->
      jade.page_User_Main (html,$)->
        searchItems = ($(link).attr('href') for link in $('#popular-Search-Terms a'))
        searchItems.assert_Contains("/search?text=C++")
        done()
```

**Comment by DinisCruz** [comment]
@michaelhidalgo we will need to add that 'C++' (and maybe other examples) value to the searches so that it shows when running the tests from the CI server

**Comment by michaelhidalgo** [comment]
You are right, I'll refactor the test to search for 'C++' and other cases so those terms become part of the Popular Search Terms.

In order to populate them in that list, we need to search for it and pick up at least one article right?

**Comment by michaelhidalgo** [comment]
@DinisCruz  what do you think about this 

```coffeescript
#This test verifies that the link text is not Url-encoded
    it.only "Issue_497 - Url encoding on popular search items", (done)->
      jade.page_User_Main (html,$)->
        #search patterns
        plusSearch      = page.tm_Server + '/search?text=C%2B%2B'
        ampersandSearch = page.tm_Server + '/search?text=%26'
        mainPageSearch  = page.tm_Server + '/user/main.html'
        # searching patterns to populate them in the Popular Search Terms
        page.chrome.open plusSearch, ()->
          page.chrome.open plusSearch, ()->
            page.chrome.open ampersandSearch, ()->
              page.chrome.open ampersandSearch, ()->
                page.chrome.open mainPageSearch, ()->
                  searchItems = ($(link).attr('href') for link in $('#popular-Search-Terms a'))
                  searchItems.assert_Contains("/search?text=C++")
                  searchItems.assert_Contains("/search?text=&")
                  done()
```

**Comment by michaelhidalgo** [comment]
This is the test after the fix 

```coffeescript
 it.only "Issue_497 - Url encoding on popular search items", (done)->
      jade.page_User_Main (html,$)->
        #search patterns
        plusSearch      = page.tm_Server + '/search?text=C%2B%2B'
        ampersandSearch = page.tm_Server + '/search?text=%26'
        mainPageSearch  = page.tm_Server + '/user/main.html'
        # searching patterns to populate them in the Popular Search Terms
        page.chrome.open plusSearch, ()->
          page.chrome.open plusSearch, ()->
            page.chrome.open ampersandSearch, ()->
              page.chrome.open ampersandSearch, ()->
                page.chrome.open mainPageSearch, ()->
                  searchItems = ($(link).attr('href') for link in $('#popular-Search-Terms a'))
                  searchItems.assert_Contains("/search?text=C%2B%2B")
                  searchItems.assert_Contains("/search?text=%26")
                  done()
```

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/509

**Comment by DinisCruz** [comment]
merged

**Comment by DinisCruz** [comment]
@michaelhidalgo can you push that unit test to https://github.com/TeamMentor/TM_4_0_QA ?

**Comment by roman87** [comment]
This is fixed. @michaelhidalgo can you do the push and then close this issue

**Comment by michaelhidalgo** [comment]
This issue has been merged into Dev. Closing it now.
