### ISSUE TITLE
Add API method to delete the GraphDB data cache

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#498]
This is the folder that contains the cached version of the data API results as Json, and will look similar to this: 

![image](https://cloud.githubusercontent.com/assets/656739/6466593/b3332680-c1c0-11e4-95d3-eef9d2bb6d0f.png)

This method is now available at the config section as **delete_data_cache** ( also invokable directly at http://localhost:1337/config/delete_data_cache )

![image](https://cloud.githubusercontent.com/assets/656739/6466570/8f83c334-c1c0-11e4-90a8-98b72df58814.png)

When executed it will delete the **data_cache** folder and return:

![image](https://cloud.githubusercontent.com/assets/656739/6466608/d411c438-c1c0-11e4-9a8a-ac1711811bda.png)

**Comment by roman87** [comment]
Is this pushed? I don't seem to be able to have it available.

**Comment by DinisCruz** [comment]
@roman87 it is now (for issues like this, I try to link to the commits , so that it is easier to see if the code is there or not)

**Comment by roman87** [comment]
Was this pushed?

**Comment by roman87** [comment]
This is done.
