### ISSUE TITLE
Add 'is' 'Library'  mapping to the TM Library's root node query_Id

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#499]
Although we could find the root of the imported library by looking at 'root nodes' (ie nodes that did not had any parent queries) this was not very efficient since there were already 4 more 'root nodes' (the 4 Metadata ones) and each new search was also creating a root node.

The lack of easy way to find the 'Library root query_id'  was also what was causing the problems with not having data when loading the 'Vulnerabilities' library, since the index is currently hard-coded to the 'Guidance' query, and not (as it should be) to the root query of the library important (regardless if is called 'Guidance' or not)

The solution was to add an extra triplet to the Library Import process so that there are two mappings for that root node ('Query' and 'Library')

This can be tested by searching for **is** and **Library** at 

![image](https://cloud.githubusercontent.com/assets/656739/6466829/43e41db4-c1c2-11e4-9e27-5eee389c50fc.png)

and then using that **query_id** at

![image](https://cloud.githubusercontent.com/assets/656739/6466841/5653c4cc-c1c2-11e4-9431-dd9502eaf86c.png)

The **loadData** test is also checking to make sure that there is a 'Library' mapping

```coffee
  it 'load_Data', (done)->
    @timeout 20000
    using tmGuidance, ()->
      @.load_Data ()=>
        @.importService.graph.allData (data)=>
          data.assert_Size_Is_Bigger_Than(1700)                            # there should be a large number of triplets
          @.importService.graph_Find.find_Using_Is 'Library', (results)->
            results.assert_Size_Is 1                                       # there should only be one library
            done()
```

**Comment by roman87** [comment]
Nice and elegant. This will also allow us to load multiple root nodes  (i.e. libraries if necessary. For example curated pages. but I don't think this was pushed yet.

**Comment by DinisCruz** [comment]
@roman87 I actually don't think we should support that scenario (multiple library root nodes). The point of having that entry is to have a 'top level' node (which in this case it is called 'Library')

From now on, if you want a separate library just load it on a separate TM instance (eventually we could add the option to TM_Design to chose which server to talk to (which would actually mean 'what library to show'))

**Comment by roman87** [comment]
@DinisCruz well that is true, however we need to be able to support multiple taxonomies. I.e. multiple keywords/queries pointing to the same article. For example, if we have OWASP top 10 taxonomy (formerly OWASP top 10 Library) we need to be able to point A1 Injection to our Injection articles.

**Comment by roman87** [comment]
And this may help us with this mapping. But I agree, we should not have more than one Library of articles.
