### ISSUE TITLE
TM Logo is missing

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#500]
![selection_141](https://cloud.githubusercontent.com/assets/1326120/6467938/a8bef42a-c19f-11e4-941f-ce674c9aded6.png)

**Comment by DinisCruz** [comment]
I've just pushed a fix for this

@michaelhidalgo or @tekgirl77  can you write a unit tests to confirm that these files are there (i.e. add to the regression tests a check for the two files referenced in the commit)

**Comment by roman87** [comment]
fixed. assigning to @tekgirl77 for unit test

**Comment by tekgirl77** [comment]
Submitted [PR here](https://github.com/TeamMentor/TM_4_0_QA/pull/31) for unit test.

Dependent on Juice replacement [PR](https://github.com/TeamMentor/TM_4_0_QA/pull/30) for [456](https://github.com/TeamMentor/TM_4_0_Design/issues/456)

**Comment by DinisCruz** [comment]
Very cool!!!!

Check this out, if I remove the css that applied the logo the test fails

![image](https://cloud.githubusercontent.com/assets/656739/7133139/1eff9802-e288-11e4-9d46-aadd267fc7df.png)

once the logo is there, the test passes

![image](https://cloud.githubusercontent.com/assets/656739/7133144/33da2300-e288-11e4-8678-40d52c5dd12d.png)

great work @tekgirl77 :)
