### ISSUE TITLE
Breakng into mobile view too early.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#502]
Seems like we are breaking into mobile view too early. 
This is 800 by 697 browser
![selection_142](https://cloud.githubusercontent.com/assets/1326120/6472944/e3ac502c-c1c3-11e4-99f1-6b1da1e6a1b2.png)

**Comment by luchia** [comment]
So @michaelhidalgo fixed this this morning on our meeting. I've attached his screenshot -

![screen shot 2015-03-03 at 4 19 02 pm](https://cloud.githubusercontent.com/assets/4547737/6477826/ef78b404-c277-11e4-80ce-4710efc42678.png)

And I've quickly made the change in my version on branch Issue_502 and have screens below. The screen now breaks at 660px -

![screen shot 2015-03-04 at 2 14 01 pm](https://cloud.githubusercontent.com/assets/4547737/6477914/e27c80c2-c278-11e4-8f67-d32921ed5de5.png)

**Comment by luchia** [comment]
I merged the branch 'Issue_502' onto Lucy, @Dinis.

**Comment by roman87** [comment]
Looks good, Lets merge it into Dev

**Comment by luchia** [comment]
This has already been merged from the Lucy branch.

**Comment by roman87** [comment]
yep, closing
