### ISSUE TITLE
Cannot load data anymore

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#507]
Steps to reproduce.
1. git pull
2. npm update
3. rm -rf ./.tmCache
4. npm test

**Comment by roman87** [comment]
Here is my config file. Used to work before:
{
  "tm_3_5_Server": "https://tmdev01-uno.teammentor.net",
  "content_Folder": "./.tmCache/_TM_3_5_Content",
  "default_Repo": "https://github.com/TMContent/Lib_UNO.git",
  "current_Library": "Lib_UNO"
}

**Comment by michaelhidalgo** [comment]
did you run a npm install for the Graph Database? I think I had the same issue

**Comment by DinisCruz** [comment]
Is this still happening?

When in doubt check the current head with the travis builds (https://travis-ci.org/TeamMentor/TM_4_0_GraphDB/builds) 

which in this case is ok

![image](https://cloud.githubusercontent.com/assets/656739/6497237/d5a3d844-c2d4-11e4-9582-af9c92dbb638.png)

**Comment by roman87** [comment]
So the problem happens because the tests time out on git clone (I am on a slower connection), and the next test begins to run, while DB is still locked. I think we can close this.
