### ISSUE TITLE
Create install script/tool for GraphDB

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#520]
This should have two modes: **install** and **update-data**

Step 0 is to do an initial clone of TM_Graph or TM_QA

**install**: 
1. [ ] remove .tmCache
2. [ ] update code git repo (via git pull of target branch (in principle ```master```))
3. [ ] clone data git repo
4. [ ] **update-data** steps (described below)

**update-data**
1. [ ] update git repo (via git pull of target branch (in principle ```master```))
2. [ ] update data repo (via git pull)
3. [ ] remove cached data files
4. [ ] convert data repo *.xml into *.json 
5. [ ] create search artifacts
6. [ ] run UI tests to confirm that all is good (these are the selenium tests that will also need to be executed from saucelabs)

**Comment by roman87** [comment]
Michael, want to give it a shot in sprint 3

**Comment by michaelhidalgo** [comment]
Yes, I like the workflow for the setup.

**Comment by romichg** [comment]
This is already done with last rounds of scripts. I think this is as good as we are going to get while we need to support 3.5 as a backend.
