### ISSUE TITLE
Can we shorten the TM summary on the sign up/login pages?

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#523]
These pages are now out of proportion because we're not using the full-width of the screen anymore.

![screen shot 2015-03-11 at 8 45 43 am](https://cloud.githubusercontent.com/assets/4547737/6587051/0b05150c-c7cb-11e4-89eb-11763357abbf.png)
![screen shot 2015-03-11 at 8 46 13 am](https://cloud.githubusercontent.com/assets/4547737/6587057/1741dec2-c7cb-11e4-8398-404c465bf3b1.png)

I propose that we compress the summary about what you can do with TM so it looks more balanced -

![screen shot 2015-03-11 at 8 55 15 am](https://cloud.githubusercontent.com/assets/4547737/6587155/60db0940-c7cc-11e4-89cd-08d1b23ea8eb.png)

I just made those changes really quickly in the browser, but I think there should be less spacing around those items. Regardless, you can see that it significantly shortens the length of the page and looks a lot more balanced.

**Comment by luchia** [comment]
Or, we could even strip the list altogether (after all, it is double up content from the landing page) -

![screen shot 2015-03-11 at 9 00 04 am](https://cloud.githubusercontent.com/assets/4547737/6587206/17ed53c2-c7cd-11e4-999a-98e857b0c545.png)

**Comment by roman87** [comment]
So first, why when we switch to HDPI mode we actually have a smaller window? Here is what I mean:
this is 1266x764
![selection_148](https://cloud.githubusercontent.com/assets/1326120/6588935/29ec62c4-c76f-11e4-8828-2e1364242fb9.png)

and this is just 20 pix more
1282x772
![selection_149](https://cloud.githubusercontent.com/assets/1326120/6588934/26565e94-c76f-11e4-8c7f-2e57c2e9c0ba.png)

Then to answer your question, I think we need the list. Doubling up is re-enforcement, which is always good. I think we can live with just the first sentence though.

**Comment by luchia** [comment]
I'm not actually too sure why it does that in HDPI. I did some googling and found a fix for media queries where you target devices higher than a certain pixel width ( (-webkit-device-pixel-ratio: 1.5), can you let me know if that fixes it?

I made the changes and merged it into the Lucy branch. You can see it below or on the branch - 

![screen shot 2015-03-11 at 5 25 48 pm](https://cloud.githubusercontent.com/assets/4547737/6592017/aca33130-c813-11e4-9a3f-5f239cbbab2c.png)
![screen shot 2015-03-11 at 5 25 50 pm](https://cloud.githubusercontent.com/assets/4547737/6592016/aca2b642-c813-11e4-8264-ed399c6cb488.png)

**Comment by roman87** [comment]
So we still have the issue of HIDPI screens switching to smaller version of the site but I will open a separate issue on that. . https://github.com/TeamMentor/TM_4_0_Design/issues/530
Closing this one
