### ISSUE TITLE
Create a narrow-width verison of the Docs page

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#524]
Just to see what it looks like.

**Comment by luchia** [comment]
This can be seen on the Issue_524 branch. I think this could work quite well. @roman87 @DinisCruz @michaelhidalgo, let me know what you want to do.

![screen shot 2015-03-11 at 10 48 50 am](https://cloud.githubusercontent.com/assets/4547737/6588399/f45e21d8-c7dc-11e4-87e5-79c66623f111.png)
![screen shot 2015-03-11 at 10 48 54 am](https://cloud.githubusercontent.com/assets/4547737/6588400/f49898a4-c7dc-11e4-8459-c0cb3001e783.png)

**Comment by roman87** [comment]
I think this looks fine, only @luchia you need to make sure that clicking on any of the docs items also opens up in a small window, as well as be careful about images.

**Comment by luchia** [comment]
Images will be fine because they have a max-width of 100%, making them responsive. I added the fix for the other pages (they used a different template).

You can see it on the Lucy branch or below -

![screen shot 2015-03-11 at 5 28 41 pm](https://cloud.githubusercontent.com/assets/4547737/6592053/30554f2c-c814-11e4-893b-819c446608e1.png)
![screen shot 2015-03-11 at 5 28 46 pm](https://cloud.githubusercontent.com/assets/4547737/6592054/305a74e8-c814-11e4-8b31-3656efe18468.png)
![screen shot 2015-03-11 at 5 28 51 pm](https://cloud.githubusercontent.com/assets/4547737/6592055/305bd46e-c814-11e4-8b5c-4ba4bdbee908.png)

**Comment by roman87** [comment]
Looks good. Closing.
