### ISSUE TITLE
Update "Index" link to point to /show/Index instead of /show/Guidance

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#525]
Right now clicking on Index points to /show/Guidance, which is no longer the case, since I updated library name to be Index.

This should be updated here: source/jade/_mixins/links.jade 
But I think there is a number of tests that will need to be updated as well.

**Comment by DinisCruz** [comment]
related to https://github.com/TeamMentor/TM_4_0_Design/issues/482 and https://github.com/TeamMentor/TM_4_0_Design/issues/499

**Comment by DinisCruz** [comment]
To level link now points to **/show/** which will show the root library (i.e. the Library root node). Note that this means that **/show/** doesn't show the list of root queries (which after this fix is not that useful (see https://github.com/TeamMentor/TM_4_0_Design/issues/528))

This is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/656739/6593704/d9d0f548-c7d2-11e4-8a57-a635b492ebaf.png)

Note that you can still access the query directly

http://localhost:1337/show/Guidance (before the update to the latest version of Lib_Uno)

![image](https://cloud.githubusercontent.com/assets/656739/6593719/f563b49e-c7d2-11e4-8dab-f66d1f3a82ae.png)

http://localhost:1337/show/Index (after the update to the latest version of Lib_Uno)
![image](https://cloud.githubusercontent.com/assets/656739/6593856/fcaa7f34-c7d3-11e4-9e09-49548921dbce.png)

**Comment by roman87** [comment]
This is done, thank you!
