### ISSUE TITLE
Support searching via URL parameter using syntax http://{site}/search/{text}

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#529]
This was easy to add so I just pushed a change that extends the search params to the url (which makes it more user-friendly to change directly)

After this change, the **http://localhost:1337/search/struts** url will give the same search results as **http://localhost:1337/search?text=struts**

Here are some screetshots of this feature in action

**http://localhost:1337/search?text=struts**

![image](https://cloud.githubusercontent.com/assets/656739/6602977/017be0b4-c817-11e4-9dcc-7de8c91cec88.png)

**http://localhost:1337/search/struts**

![image](https://cloud.githubusercontent.com/assets/656739/6602992/1940e046-c817-11e4-8025-874039000963.png)

Not all searches will work, but I think it is a nice little feauture

**Comment by roman87** [comment]
Well, xss+fix+prevent did not work, so probably not that useful, yet :)
but simple words work.
