### ISSUE TITLE
IIS is throwing errors when the article title matches an banned extension

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#533]
This is caused by IIS blocking particular extensions (see https://github.com/TeamMentor/TM_4_0_Design/issues/532)

![image](https://cloud.githubusercontent.com/assets/656739/6608483/41345420-c83f-11e4-87f1-6329b89ddf1c.png)

**Comment by DinisCruz** [comment]
Could also be these guys

![image](https://cloud.githubusercontent.com/assets/656739/6608518/7c8380b4-c83f-11e4-8a64-b9f676c45d9d.png)

**Comment by DinisCruz** [comment]
and this one

![image](https://cloud.githubusercontent.com/assets/656739/6608527/9db9c9a0-c83f-11e4-8c69-3e6de04d0b99.png)

**Comment by roman87** [comment]
I was thinking about this and I realized that the best way to fix this is to URL encode the article title. We cannot restrict the title of the article to contain only the allowed URL character set. Therefore we must encode them:

List of allowed URL characters
Unreserved

The alphanumerical upper and lower case character may optionally be encoded:

    A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    a b c d e f g h i j k l m n o p q r s t u v w x y z
    0 1 2 3 4 5 6 7 8 9 - _ . ~

Reserved

Special symbols must sometimes be percent-encoded:

    ! * ' ( ) ; : @ & = + $ , / ? % # [ ]

Further details can for example be found in RFC 3986 and http://www.w3.org/Addressing/URL/uri-spec.html.

**Comment by DinisCruz** [comment]
well the URL is already encoded, the problem is with the dot which by default is not encoded by any html/url encoding functions

I just added a small fix (see https://github.com/TeamMentor/TM_4_0_Design/commit/23663e1c006e567c73871d4c0bbf8bb2301fd109) which removes the dots from the search results, the recently viewed articles and top articles

![image](https://cloud.githubusercontent.com/assets/656739/6664937/dcb32ae0-cbcb-11e4-973d-58454142dd8a.png)

![image](https://cloud.githubusercontent.com/assets/656739/6664931/d1cc06c4-cbcb-11e4-93a5-85040b5476e5.png)

Now clicking of the affected link (the one with the dot at the end) will go to the article (without the dot in the url)

![image](https://cloud.githubusercontent.com/assets/656739/6664954/f94e72c2-cbcb-11e4-928c-d347c3f53dc6.png)

**Comment by DinisCruz** [comment]
I think the solution above solves this issue (specially since we should try to keep IIS changes to the minimum)

**Comment by roman87** [comment]
This is fixed.
