### ISSUE TITLE
Add support for Google Analytics using a GIF

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#534]
See https://developers.google.com/analytics/resources/articles/gaTrackingTroubleshooting?csw=1#gifParameters and http://adambuchanan.me/post/20500736298/google-analytics-without-javascript-or-cookies

This will work by dynamically creating a gif url on the server that looks something like this

```
http://www.google-analytics.com/__utm.gif?utmwv=4&utmn=769876874&utmhn=example.com&utmcs=ISO-8859-1&
utmsr=1280x1024&utmsc=32-bit&utmul=en-us&utmje=1&utmfl=9.0%20%20r115&utmcn=1&
utmdt=GATC012%20setting%20variables&utmhid=2059107202&utmr=0&
utmp=/auto/GATC012.html?utm_source=www.gatc012.org&utm_campaign=campaign+gatc012&
utm_term=keywords+gatc012&utm_content=content+gatc012&utm_medium=medium+gatc012&utmac=UA-30138-1&
utmcc=__utma%3D97315849.1774621898.1207701397.1207701397.1207701397.1%3B...   
```

**Comment by michaelhidalgo** [comment]
First attempt https://github.com/TeamMentor/TM_4_0_Design/pull/830/files

**Comment by DinisCruz** [comment]
That first attempt is really good but it is creating one 'active user per session' 

We need to map these mappings to the users, which this https://github.com/hybridgroup/gabba/issues/23#issuecomment-16968679 might be part of the solution

**Comment by DinisCruz** [comment]
https://github.com/thomasbachem/php-ga/blob/3a93d0c7e8aace4a13d13d1b16bdf49d18ab3f2f/src/GoogleAnalytics/Internals/Request/Request.php#L151-L153

**Comment by roman87** [comment]
As discussed on the call, lets take a look at other analytic services. Whichever one we choose we should carefully correlate our data acquisition methods with what we are trying to collect, as described here: https://github.com/TeamMentor/TM_4_0_Design/issues/763#issuecomment-102824140

**Comment by michaelhidalgo** [comment]
This was done with Piwik API.

**Comment by romichg** [comment]
Done.
