### ISSUE TITLE
Re-add the save console log to disk

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#536]
This is the functionality that was saving all log files into into the .log folders

We need this for both GraphDB and DesignTM.

The logs can be saved on a ../logs folder (i.e. one folder above TM_Design and TM_Graph)

This is a real prob for the version deployed in IIS since it node is running as service in there and we don't capture the console.out)

**Comment by DinisCruz** [comment]
This is done on the branch https://github.com/TeamMentor/TM_4_0_Design/tree/Issue_550_Log_SaaS

@roman87 can you take a look

**Comment by roman87** [comment]
Yes, logging to file works great.See my comment in https://github.com/TeamMentor/TM_4_0_Design/issues/550#issuecomment-80783677 
once that's done lets move it into Dev branch.

**Comment by DinisCruz** [comment]
ok, just pushed to Dev the code with only the logging to the file system

**Comment by DinisCruz** [comment]
I just added the same Logging-Service to GraphDB, so you should now see a .logs folder inside the TM_4_0_GraphDB folder

Note that I made the logs rotate every day (vs every hour)

**Comment by roman87** [comment]
Looks good, closing this.
