### ISSUE TITLE
[L] Sometimes the top nav of the help page is showing the wrong menu 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#537]
I was not able to reproduce this reliably, by I had a case when this is what the non-logged in user sees this (the logged in nav bar)
![image](https://cloud.githubusercontent.com/assets/656739/6608984/2f47dc28-c844-11e4-9a39-04aa12dc0ab3.png)

See if we can reproduce this on a QA unit test

**Comment by roman87** [comment]
Can you outline the steps you took to make this happen?

**Comment by romichg** [comment]
This was fixed with #910
