### ISSUE TITLE
Remove Symantec Logo from the Landing Page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#538]
This comes from Jeff Berry via email. Apparently we can't use Symantec Logo.

**Comment by luchia** [comment]
Who can we use instead?

**Comment by roman87** [comment]
@SI-Lisa any ideas? Lucy, For now just remove it.

**Comment by SI-Lisa** [comment]
Roman,
I will ask Maureen if she knows of any customers who we have an agreement
with to use their logo in a way such as this.

**Comment by luchia** [comment]
This has been fixed and I've moved the client logo sprites I was talking about from Flare to Jade (this is the revision that saves us 5 extra HTTP requests).

**Comment by roman87** [comment]
ok this is done
