### ISSUE TITLE
Tabs and Spaces being used breaks Password Reset form

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#543]
At the moment, the latest version of Dev introduced this issue :  

![screen shot 2015-03-12 at 12 03 09 pm](https://cloud.githubusercontent.com/assets/1732035/6624551/a27d6a12-c8af-11e4-8c5f-d6cb661b691a.png)

This is the problematic file : 

![screen shot 2015-03-12 at 12 02 53 pm](https://cloud.githubusercontent.com/assets/1732035/6624562/bc7c3a9c-c8af-11e4-898b-571d1b07aeb9.png)

assigning it to @michaelhidalgo

**Comment by DinisCruz** [comment]
yeah @luchia every now and then pushes a jade page like that

**Comment by DinisCruz** [comment]
For reference https://beta.teammentor.net/guest/pwd-forgot.html is not affected

![image](https://cloud.githubusercontent.com/assets/656739/6625815/570f7d64-c8ea-11e4-8f63-cf2e8d17a1db.png)

**Comment by michaelhidalgo** [comment]
This has been fixed. There is already a QA test that checks that behaviour (and it was key to find the problem).
