### ISSUE TITLE
Support the search for html tags (for example <script> or <head>) 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#547]
Our code samples will have this, and with the changes to https://github.com/TeamMentor/TM_4_0_Design/issues/546 we are almost there.

The problem is that there is actually a sanitisation happening when creating the search query (ironically for security) which removes the < and > chars

For example a search on the UI for ```<script>``` will result in the following rest calls

```
GET /data/query_tree/search--script-
GET /convert/to_ids/%3Cscript%3E
GET /search/query_from_text_search/%3Cscript%3E
GET /data/query_tree/search--script-
```

with the problem being with the **query_tree** call (and the graphDB value used as subject/query-id)

@roman87 can you map the P rating of this issue? (I remember that searching for ```<script>`` was a request from an TM user)

**Comment by DinisCruz** [comment]
Here is a variation of this bug that michael hit with one of his unit tests

after searching for **/** the next searches for chars like **&** will also be added to the list of **/** searches

![image](https://cloud.githubusercontent.com/assets/656739/6627104/a932c89a-c8f3-11e4-9ce8-e5e3f4b22c9f.png)

**Comment by roman87** [comment]
nicely done.
