### ISSUE TITLE
Alert Messages now have green background, why?

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#548]
![selection_153](https://cloud.githubusercontent.com/assets/1326120/6643847/003544be-c986-11e4-9612-f812a9ba0975.png)

**Comment by luchia** [comment]
Not sure why this is in Jade's css, but I've fixed it on the Lucy branch.

![screen shot 2015-03-14 at 4 47 41 pm](https://cloud.githubusercontent.com/assets/4547737/6650983/e8d291de-ca69-11e4-8e3e-6398736f43ab.png)

**Comment by roman87** [comment]
ok done.
