### ISSUE TITLE
Logos are now smaller than the text above

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#554]
![selection_158](https://cloud.githubusercontent.com/assets/1326120/6660537/36bcc19a-cb72-11e4-8de2-7eef1818e2fd.png)

This is on Lucy Branch.

**Comment by luchia** [comment]
As discussed in our meeting this morning, this was necessary after removing the Symantec logo. Originally we had 6 logos and that means two rows of three columns. Now we only have 5 and making it sit nicely in two rows wasn't easy.

This is a simple fix and quickly addresses #538 without holding up Beta launch. I want to add a 6th logo at some point again, I think it looks better.

**Comment by roman87** [comment]
This was done
