### ISSUE TITLE
Sort queries and filters

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#557]
Also requested by @BendixSpring 

I just noticed that both set of filters (left and right hand side) and not sorted

![image](https://cloud.githubusercontent.com/assets/656739/6665153/309a58fc-cbce-11e4-99ee-49f110502d4a.png)

I think it would make sense to order this alphabetically or to add the capability for that order to be 'gamed/defined'

@SergeTruth what do you think?

note: from a effort point of view, sorting the results alphabetically should not be too hard

**Comment by roman87** [comment]
I think it is more important to have the capability of having the order defined than simply sorting. I have an idea on how this should be done in TM 5.0 visually.  We can talk about it a bit later.

**Comment by roman87** [comment]
We have a user also suggesting to sort subjects and filters. Let make it sorted, unless @SergeTruth objects.

**Comment by DinisCruz** [comment]
What do you mean by 'sort by subject'?

**Comment by roman87** [comment]
"sort subjects" - sort the keywords/queries. i.e. the lefthand side subjects. 
Basically sort everything alphabetically :) makes sense?

**Comment by BendixSpring** [comment]
From a usability perspective, sorting is a must.  Or at least a user-configurable option.

**Comment by roman87** [comment]
Bumping this to a P0, should be fairly easy to do and will add usability

**Comment by DinisCruz** [comment]
Done, queries and filters now looks like this:

![image](https://cloud.githubusercontent.com/assets/656739/7143302/92dd42da-e2d6-11e4-90a1-a73074b62b4d.png)

![image](https://cloud.githubusercontent.com/assets/656739/7143309/9fc15c2a-e2d6-11e4-8dea-1fc1b818839b.png)

![image](https://cloud.githubusercontent.com/assets/656739/7143316/a7004104-e2d6-11e4-9820-780d18aef85a.png)

**Comment by roman87** [comment]
Yep, all nicely sorted. Will follow up with  @BendixSpring once this is out in beta.

**Comment by roman87** [comment]
@BendixSpring could you take a look at the latest beta and let us know if this particular issue had been resolved to your satisfaction and is working as expected.
Thanks.

**Comment by BendixSpring** [comment]
This issue is fixed for the index, but is not fixed for the Fitlers:
![image](https://cloud.githubusercontent.com/assets/3578332/7458530/1adb4498-f263-11e4-8fb6-be4c7d48cd13.png)

The words are not sorted alphabetically in the filters pane.

**Comment by roman87** [comment]
@BendixSpring I am not sure what you mean :). Looks pretty alphabetical to me..

**Comment by BendixSpring** [comment]
Ha!  Indeed!  I thought NET would come after “A”.

 

But .NET does come before “A”.

 

It’s good!

**Comment by roman87** [comment]
Great, thanks. Closing this one.
