### ISSUE TITLE
In IIS, redirect unhandled errors to TM 4.0 error page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#558]
In this case http://beta.teammentor.net/article/4199598f3446/Output-Encoding-Using-JSF* (note the * at the end of the url)

![image](https://cloud.githubusercontent.com/assets/656739/6665475/d86f17fe-cbd1-11e4-8494-169ef8ea0ff6.png)

should go to 

![image](https://cloud.githubusercontent.com/assets/656739/6665482/e3e7e660-cbd1-11e4-9c45-8178a00814c5.png)

**Comment by roman87** [comment]
Hmm... interesting, I thought this was fixed. Will take a look.

**Comment by roman87** [comment]
This is now fixed.
