### ISSUE TITLE
The top level animation is bouncing quite slowly

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#560]
It happened on this page: http://beta.teammentor.net/flare/home/navigate

![image](https://cloud.githubusercontent.com/assets/656739/6673497/8f290c14-cc0b-11e4-84b8-26f6b2a6af1d.png)

(@luchia this is a test issue)

**Comment by luchia** [comment]
Yup, I think we're not even going to keep this navigation (it's very Jade-like) and we're doing the navigation I proposed in What's Cookin'.

**Comment by roman87** [comment]
This will be fixed with https://github.com/TeamMentor/TM_4_0_Design/issues/576.

**Comment by luchia** [comment]
See #576 for the fix for this issue. I think this can be closed, once #576 is QA'ed.

**Comment by luchia** [comment]
Assigning to @roman87 to be closed due to #576 being completed and merged onto Dev.

**Comment by romichg** [comment]
Done.
