### ISSUE TITLE
email validation error unfriendly

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#562]
If you have a browser that does not validate the email address (with type="email") in the registration page, and you enter an invalid email address, the error message is:

> Error: The field Email must match the regular expression '^[\w-+\.]{1,}\@([\w-]{1,}\.){1,}[a-zA-Z]{2,4}$'.

While I love regular expressions, I may be in the minority in that regard.

**Comment by roman87** [comment]
Why, everyone should love regex :). Good catch, we'll fix it.

**Comment by michaelhidalgo** [comment]
This issue is related to https://github.com/TeamMentor/TM_4_0_Design/issues/563, the idea is to fix them at the same time.

**Comment by michaelhidalgo** [comment]
Related to https://github.com/TeamMentor/TM_4_0_Design/issues/607

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/Dev/pull/173

**Comment by DinisCruz** [comment]
add my comments, almost there

**Comment by michaelhidalgo** [comment]
With new Pull Request TeamMentor/Dev#176
@DinisCruz can you please review it?

**Comment by DinisCruz** [comment]
looks good (with one small comment)

**Comment by michaelhidalgo** [comment]
@DinisCruz can you review it again, I have fixed it based on your recommendations https://github.com/TeamMentor/Dev/pull/176

**Comment by DinisCruz** [comment]
merged

**Comment by roman87** [comment]
@tecknicaltom This has been fixed in latest beta. Could you let us know if this is resolved to your satisfaction?

**Comment by roman87** [comment]
@tecknicaltom could you just confirm that this works now the way you'd expect?

**Comment by romichg** [comment]
Closing due to TTL
