### ISSUE TITLE
Create Hyperlinks to other SI content

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#564]
For example, on the about page:  https://beta.teammentor.net/guest/about.html when discussing Team Professor, put a link to the Team Professor page.

**Comment by roman87** [comment]
@BendixSpring does this issue pertain to the landng/about pages or to the TM content as well? If it is the latter then its a much bigger project :)

**Comment by BendixSpring** [comment]
Just for the Landing/About pages.

**Comment by luchia** [comment]
Makes sense. I've done this quickly - took my less than 10 minutes. There were only two that I could see which were TEAM Professor and Checkmarx. It's on the Lucy branch.

**Comment by BendixSpring** [comment]
I’d only link to SI-branded products and services :)

**Comment by luchia** [comment]
Fixed :)

**Comment by roman87** [comment]
Perhaps you should make it underlined, so it is clear its a link? I can't tell its a link unless I mouse over.

**Comment by luchia** [comment]
Sure, I applied it to all links within #landing-page which covers a number of pages -

![screen shot 2015-03-23 at 12 53 22 pm](https://cloud.githubusercontent.com/assets/4547737/6773344/c863e81e-d15b-11e4-85b1-ccdc5b30b770.png)
![screen shot 2015-03-23 at 12 53 53 pm](https://cloud.githubusercontent.com/assets/4547737/6773345/c8680304-d15b-11e4-996a-76fc033e7350.png)
![screen shot 2015-03-23 at 12 53 57 pm](https://cloud.githubusercontent.com/assets/4547737/6773346/c868ace6-d15b-11e4-9c63-77558a73f1b9.png)

**Comment by roman87** [comment]
Where is the branch for this fix?

**Comment by luchia** [comment]
On the Lucy branch.

**Comment by DinisCruz** [comment]
That code is now on master

![image](https://cloud.githubusercontent.com/assets/656739/6808918/dcefb436-d24e-11e4-8b03-9935475c7d95.png)

**Comment by roman87** [comment]
This is done

**Comment by roman87** [comment]
Re-opening to follow up with @BendixSpring  when it is on beta.

**Comment by romichg** [comment]
This is done. @BendixSpring Can you let me know if this is resolved to your satisfaction. If not I will reopen it. Otherwise closing.

**Comment by BendixSpring** [comment]
I don’t see any links on the pages originally noted.

I guess you can close this.

**Comment by romichg** [comment]
@BendixSpring the only page that has other SI products is the about page, which has the TP link in it..Which original pages you refer to?

**Comment by BendixSpring** [comment]
The about page does has the TP link.  This is good. We are done with this.

**Comment by romichg** [comment]
Ok great! Thank you!!!
