### ISSUE TITLE
Questions about the Index button

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#565]
Is the Index button at the top of the page supposed to be a toggle?  I can make it go away if I click search, otherwise, it remains displayed.

Index usually implies an *alphabetically sorted* list of topics.  Two recommendations:  Sort the list and make it more granular.  For example, consider adding "Secure coding".  Then a person would go to the filters and select "iOS" or "Java" for example.  This is more intuitive.

**Comment by roman87** [comment]
@BendixSpring  Can you clarify what you mean by "I can make it go away if I click search, otherwise, it remains displayed"  - do you have a screen shot? 
 Making it alphabetical is already on the issue list. I am going to bump its priority.  https://github.com/TeamMentor/TM_4_0_Design/issues/557

Can you also elaborate what you mean by "make the list more granular"

**Comment by BendixSpring** [comment]
When I click SEARCH, the index goes away:



 

Making the index more granular means having more “topics” to choose from.  This list is really too limited.  For example, I was expecting to see Coding Guidelines.  But really an index is a fairly comprehensive list:

Ajax

Azure

APIs

ASP .NET

Architecture

Blacklisting

Bugs

Character encoding….

**Comment by roman87** [comment]
@BendixSpring  I am still not sure I understand. Are you suggesting that the word Index is inappropriate for our taxonomy? Perhaps we should replace it with "Directory". Basically, we have organized our articles in a hierarchy of  subject matter categories. There is definitely room for improving the categories, but I think what you are suggesting is to get rid of the hierarchy? 
As far as specific "Secure Coding" where do you see that fit in our current taxonomy? It is a fairly vague subject that can encompass multiple other things.  We are planning a 3d way of accessing our content specifically for vague subjects. These would be part of the gateway articles. - Articles that provide high level description with paths to explore the content deeper.

**Comment by BendixSpring** [comment]
The term “index” means “an alphabetical list of names, subjects, etc., with references to the places where they occur, typically found at the end of a book”.  So if you are going to call something an index, it should be a fairly complete listing of topics/terms.

 

A taxonomy connotes a structured classification of things.  For example:  https://business.yahoo.com/

 

From my perspective, the most important thing is to help user find the right information as quickly as possible without having to do any extra “treasure hunting”.  So if that means having a fairly comprehensive listing of topics down the left side, great!  If it means getting the search function working like google, then great.  But this business of having to sift through so much chaff to find the grain is way too much work and renders this tool less than useful.

 

In a nutshell, the existing taxonomy is not detailed enough to help users find what they need quickly.  One approach from a usability perspective is to expand the taxonomy – more categories, more detail, and then when demoing the system, show how the filters can really narrow the search.  If you want ideas for more taxonomy details, let me know.  But one approach might include OWASP Top 10, SAN/CWE Top 25, Testing, Secure Coding Guidance, Authentication, Authorization, Logging, Error Handling, Input Validation, Database Security, etc.

 

Making the search work like google will also help finding the information easier.  When demoing the product, do a search and then show how the filters can help narrow the search.  

 

Returning 100 records is nice, but it will be a much better tool if it returns 10 records that really match what the user is after.

**Comment by roman87** [comment]
Ok so let me try to break this up into couple of things here. 

1. "The term “index” means “an alphabetical list of names, subjects, etc" - Once we are done with issue https://github.com/TeamMentor/TM_4_0_Design/issues/557. Will this then look like the Index? I assume it will correct?

2. "In a nutshell, the existing taxonomy is not detailed enough" - Could you open an issue in https://github.com/TMContent/Lib_UNO/issues with the things you feel are missing from the taxonomy? Note that a lot of the things you mention like "Authentication, Authorization, Logging, Error Handling, Input Validation," are already there. Also CWE, PCI, OWASP Top 10 will be added at a later stage. These are essentially taxonomies that point will point more or less to the same content. 

Thanks, sorry for this back and fourth, but I am just trying to break up your feedback into concrete points that we can address.

**Comment by BendixSpring** [comment]
I found this in wikipedia:  

 

Subject indexing is the act of describing or  <http://en.wikipedia.org/wiki/Document_classification> classifying a  <http://en.wikipedia.org/wiki/Document> document by  <http://en.wikipedia.org/wiki/Keyword_%28search%29> index terms or other symbols in order to indicate what the document is  <http://en.wikipedia.org/wiki/Aboutness> about, to summarize its  <http://en.wikipedia.org/wiki/Content_%28media_and_publishing%29> content or to increase its  <http://en.wikipedia.org/wiki/Findability> findability. In other words, it is about identifying and describing the  <http://en.wikipedia.org/wiki/Subject_%28documents%29> subject of documents. Indexes are constructed, separately, on three distinct levels: terms in a document such as a book; objects in a collection such as a library; and documents (such as books and articles) within a field of knowledge.

 

The key point for me is “..to increase its findability.”  Having such a small list on the left side does not help users find what they are looking for.  The point is to provide enough important keywords to help the users find what they want.  Then by applying the filters on the right side, they can really narrow what they need to look at.

 

So technically an index is a full list of all of the key words or key terms in the document (or set of documents).

 

It would be unwieldy to have a full list, unless you could expand and contract it, but that adds all sorts of extra user interactions.  So a compromise would be to have a moderately comprehensive list of topics/keyword, rather than an exhaustive list.

 

So creating the alphabetical list from issue #557 <https://github.com/TeamMentor/TM_4_0_Design/issues/557>  is a good start, but it’s a very short and incomplete list.

 

I will make suggestions elsewhere for topics.

**Comment by roman87** [comment]
Ok thanks. I am closing this issue unless you feel we haven't came up with a solution in the issues linked to above.
