### ISSUE TITLE
Search does not support exact string searches

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#566]
This is basic functionality expected in modern searches.  This lack of functionality should be clearly documented in the online help.  

Consider adding a "?" graphic next to the search box that describes the limitations of search and any other useful searching guidance to make search more useful.

**Comment by roman87** [comment]
We have an issue for exact search strings, and just opened an issue for the doc page.Closing this as duplicate of #573 and #519 will follow up through those specific issue. 
Thanks.
