### ISSUE TITLE
Code example is blank

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#567]
On this page,some of the code examples are blank:
https://beta.teammentor.net/article/00e671ecd068/Do-Not-Cache-Sensitive-Data

![image](https://cloud.githubusercontent.com/assets/3578332/6676521/eb4e3620-cbfe-11e4-8c78-625756bdfe5a.png)

**Comment by michaelhidalgo** [comment]
This is actually a HTML encoding issue in the article. If you look at the textbox you will notice it is being rendered.

Note that this is also happening in teammentor.net https://teammentor.net/article/f9d523ec-7328-4be5-93c6-00e671ecd068

**Comment by BendixSpring** [comment]
I see the same problem, but I don’t see it rendering.  Even when I view source, I don’t see any of the content.

 

Are you saying there is a encoding issue that needs to be fixed?

**Comment by michaelhidalgo** [comment]
Interesting... In Google Chrome, I can actually insert text

![screen shot 2015-03-16 at 3 31 40 pm](https://cloud.githubusercontent.com/assets/1732035/6676948/5a4c8e7c-cbf1-11e4-9a5d-7d2afe9733f4.png)

**Comment by BendixSpring** [comment]
Maybe I misunderstood what is displayed.  I thought it would show code.  I didn’t think it was an interactive form.

 

I’m using Firefox.

**Comment by michaelhidalgo** [comment]
Yeah, it should be the raw HTML of a text box with autocomplete disabled, but rather than that, the textbox is rendered.

**Comment by michaelhidalgo** [comment]
This issue is being tracked here https://github.com/TMContent/Lib_UNO/issues/19

**Comment by michaelhidalgo** [comment]
Thanks for reporting this Issue @BendixSpring !

**Comment by roman87** [comment]
Great stuff! I am going to close it here as it is tracked in TMContent
