### ISSUE TITLE
Should we allow more than 250 articles to be displayed, page by page

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#570]
It would be nice to have an option to show a series of pages to look at the articles as google does.  This would allow the user to look at 50 (or whatever) articles at a time, and just click "next page" to look at the next batch of articles.

The maximum page size should be set by the user and default to 50 or so.

**Comment by roman87** [comment]
We had this discussion here https://github.com/TeamMentor/TM_4_0_Design/issues/298
Basically there is no reason for the user to ever see more than 250 articles. It is really not realistic for someone to go through 250 articles, page by page. If someone has to do this, then it means our content is not well organized and needs to be divided/filtered better. 
But we can re-open the discussion. 
So @DinisCruz @tekgirl77 @luchia @SergeTruth @michaelhidalgo @tlaloc75 What do you think?

**Comment by BendixSpring** [comment]
We can apply the same logic to google.  No one is going through 50 million pages.  But I’ve gone and looked through hundreds of pages to find things that might be a hit.

 

Don’t put artificial limitations on the users.  If there are 1500 articles, then let the user page through them 50 at a time, or whatever.

**Comment by roman87** [comment]
1 Vote goes for pages. Anyone else?

**Comment by tekgirl77** [comment]
How are the 250 articles chosen to be displayed; is it always the first 250 articles?  So the end-user would only ever see the same 250 articles pertaining to the same search query?  As an end-user, I would like the idea of knowing how many total articles are a hit on the relevant topic queried.  If there are 301, then I'd like to see 301 search results and know that I can try to filter it even more by refining my search query or page through the results to try and find exactly what I am looking for.  I agree that we should not limit the information possibilities for the end-user.

**Comment by roman87** [comment]
@tekgirl77  you actually see how many articles are there in total. It says (showing 250 out of N) articles. 

Ok 2 votes for pages.

**Comment by DinisCruz** [comment]
yeah we should add pages here

and I don't think we should show more than 20 results per page

**Comment by BendixSpring** [comment]
When you allow users to interact with the system in a way THEY are comfortable with, I do hope you allow customization so that people can work with pages that gives them the most efficiency.  20 results per page is probably a good default value, but give people the flexibility to change it.  People do log in, so you can store their preferences and customizations.  It gives them a sense of control and ownership.  Remember you are dealing with programmers here :)

**Comment by roman87** [comment]
3 Votes for pages. Ok lets give it a shot.

**Comment by roman87** [comment]
This is now tracked https://github.com/TeamMentor/TM_4_0_Design/issues/712
