### ISSUE TITLE
multiple filters in index

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#571]
Is it possible to filter results by multiple filter types? For instance, articles related to C++ (Technology) during implementation (Phase). Clicking a second filter seems to remove the first

**Comment by roman87** [comment]
Yea, that's is a limitation of the current version. We are working on making it work in next version.

https://github.com/TeamMentor/TM_4_0_Design/issues/472

I am going to close this as a duplicate and follow up with you when it is ready.

Thanks.

**Comment by DinisCruz** [comment]
This is now working on the latest dev, should be on the live beta soon
