### ISSUE TITLE
Filter by Technology is not alphabetic

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#572]
I think usability would be improved if the Technology filters were alphabetical.

I think "All" should be "All Technologies" to be less ambiguous.

.NET 3.5 has lots of articles, but no other version of .NET does.  Why is that?

**Comment by roman87** [comment]
@bendixspring
"I think usability would be improved if the Technology filters were alphabetical." - this is covered here: https://github.com/TeamMentor/TM_4_0_Design/issues/557


"I think "All" should be "All Technologies" to be less ambiguous." - Can you add your thoughts to the discussion here:  https://github.com/TeamMentor/TM_4_0_Design/issues/391
The problem with calling it "All" is it assumes that All of the technologies are applied, when in fact it is the technology articles that are shown. 

".NET 3.5 has lots of articles, but no other version of .NET does. Why is that?" - this is covered here: https://github.com/TMContent/Lib_UNO/issues/17

I am going to close this as duplicate. It would be great if you could participate in the discussion in the respective topics :) Again thanks for this feedback!
