### ISSUE TITLE
Build NEW navigation for Flare

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#576]
As per [my issue in What's Cookin](https://github.com/TeamMentor/WhatsCookin), I need to build what's in those sketches.

**Comment by luchia** [comment]
Basic structure built -

![screen shot 2015-03-24 at 9 28 33 pm](https://cloud.githubusercontent.com/assets/4547737/6800726/fe42c6be-d26c-11e4-9659-0aca2a12a896.png)
![screen shot 2015-03-24 at 9 29 33 pm](https://cloud.githubusercontent.com/assets/4547737/6800725/fe28d254-d26c-11e4-86b8-ec6bb937d916.png)

**Comment by luchia** [comment]
It's starting to look good now. I need to add polish and make everything sit together better but this is going to drastically improve Flare's UX -

![flare-nav](https://cloud.githubusercontent.com/assets/4547737/6814943/90d76efa-d2cf-11e4-8c72-09e15006255f.gif)

**Comment by luchia** [comment]
Final navigation for Flare release one -

![flare-nav](https://cloud.githubusercontent.com/assets/4547737/6840182/868b1546-d3bf-11e4-9325-5df5d5213e09.gif)

You can see in the code that the User icon button still exists, but is commented out. This is because the first release of Flare won't have User pages.

![screen shot 2015-03-26 at 1 53 21 pm](https://cloud.githubusercontent.com/assets/4547737/6840180/822e111a-d3bf-11e4-906b-f1ce229391e5.png)

Assigning to Roman for QA. You can see it on the branch Issue_576.

**Comment by roman87** [comment]
![selection_163](https://cloud.githubusercontent.com/assets/1326120/6869129/036e0dcc-d468-11e4-9c04-3fdbd55f11e1.png)



Yea, so not quite :). This is FF. Here are some issues, numbered in the screenshot

1. This icon is really not intuitive. No idea what it means.
2. The logo, the search box, and these links are on 3 different lines.
3. Remind me what this Icon is for?
4. Why do I have all these scroll bars :)?
5 Logo looks very disproportional t othe rest of text.

**Comment by luchia** [comment]
### 1. Icon is not intuitive
This was the same as our navigate icon in Jade, but we changed it (and I forgot to change Flare's). I have changed it and it looks like this now -

![screen shot 2015-03-31 at 6 54 01 am](https://cloud.githubusercontent.com/assets/4547737/6906519/ba98b12a-d772-11e4-8455-137823776377.png)

### 2. Elements on different lines
I learnt something new this morning about flexbox - it's not supported in all browsers with one CSS element. You have to include different elements to target different browsers. This has been addressed and now works in all 3 major browsers perfectly -

##### Firefox 
![firefox](https://cloud.githubusercontent.com/assets/4547737/6907519/2d37932a-d77a-11e4-892e-9caf1e8560de.gif)

##### Chrome
![chrome](https://cloud.githubusercontent.com/assets/4547737/6907517/2d36fef6-d77a-11e4-987f-cd88e2580a89.gif)

##### Safari
![safari 1](https://cloud.githubusercontent.com/assets/4547737/6907518/2d373b8c-d77a-11e4-81ff-4f830118afe6.gif)

### 3. Unknown Icon
This is the icon to save the search results. The icon next to it clears the results (all filters and keywords used).

### 4. Scroll Bars
Because Flexbox wasn't working. It should be working fine now :)

### 5. Logo proportions
Fixed with the fixed flexboxes :)

**Comment by DinisCruz** [comment]
code merged into dev

**Comment by roman87** [comment]
Ok, but I still need it wired in order to test it :) https://github.com/TeamMentor/TM_4_0_Design/issues/618

**Comment by romichg** [comment]
Done, looks good.
