### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#579]
I still don't understand why this is here:

![screen shot 2015-03-17 at 11 38 24 am](https://cloud.githubusercontent.com/assets/2352439/6690990/25b824a6-cc9a-11e4-91e4-7f36ce065772.png)

"Start your free trial" seems to indicate an eCommerce product and unless things have changed, it is not.   

Is the product going to be available for trial on the public Internet?  Free trial and all the other marketing stuff might make sense from that standpoint.

**Comment by roman87** [comment]
Pete, yes, the product will be (and is available today www.teammentor.net) for a 30 day free trial. Any user can sign up. We have some customers that deploy their own instance, and we have some customers that simply use www.teammentor.net. The difference between those, is that customers that choose to modify content need to have their own instance. 
Hope this makes sense. Let me know if I can close this question.

**Comment by pjenney58** [comment]
A couple of questions come to mind.  

How do we get the software back or make sure it's destroyed at 30 days? Do we have any capability to connect to a remote instance and destroy it?  Is the free trial crippled in any way that would entice a user to buy a license?

> Cheers!
> 
> pete.;1
> 
> 
> ---)-------------------------------------
> Security Innovation, Inc.
> Peter H. Jenney
> VP, Strategic Initiatives
> Ombudsman, CCO, PMO
> 
> o:  978.694.1008 x164
> m: 603.264.3961

**Comment by roman87** [comment]
Probably I didnt make myself clear. We do not provide the software for installation. We let users register on our www.teammentor.com website that we host. At the end of 30 days the account expires and the user cant login anymore. 
Makes sense?

**Comment by pjenney58** [comment]
Hi Roman,

That makes more sense.  From the help system it looks like anyone can download it from GitHub and install, it and then do whatever they’d like.  

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Yep, I will update the docs. As this is tracked elsewhere I am closing this issue.
