### ISSUE TITLE
Suggestions for a consolidated user experience

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#582]
It seems to me that a couple of changes could allow for a single point user experience and focus the users activities while providing flexibility:

![screen shot 2015-03-17 at 11 59 15 am - phj edits](https://cloud.githubusercontent.com/assets/2352439/6691816/305f58b6-cc9f-11e4-9a27-7f2838854496.png)

**Comment by roman87** [comment]
Thanks, this is actually tracked here: https://github.com/TeamMentor/TM_4_0_Design/issues/576
I will keep this open so I can get back to you when this is complete.

**Comment by romichg** [comment]
Done in flare.
