### ISSUE TITLE
Can't multi-select filters

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#583]
I can't select multiple filters for some reason.  The standard keys one would use to do this have weird side effects like opening new tabs.   Clicking on individual items just replaces the filter,

**Comment by roman87** [comment]
This is actually a known issue https://github.com/TeamMentor/TM_4_0_Design/issues/472
and should be fixed in next beta, coming out on monday.

**Comment by pjenney58** [comment]
Yay :-)

Seriously,  you don't need to respond to every comment Roman.  I just
operate on stream of consciousness when it comes to testing.  I put myself
into DFU and savvy developer mode at random and sometimes there's value in
my comments and sometimes not.

Its enough for me to be asked to comment and contribute.  That said I'm
happy to engage in constructive dialog.

Cheers!

pete.;1


*---)--------------------------------------Security Innovation, Inc.*
Peter H. Jenney
Vice President of Strategic Initiatives
Ombudsman, FSO, CCO  & PMO

(office)   +1.978.694.1008 x164
(mobile) +1.603.264.3961
(skype)     PeteJenney

**Comment by DinisCruz** [comment]
@pjenney58 keep the comments coming, our logic is that either you are raising a new question/issue/idea that we need to take into account, or that you are touching something have covered before in another issue.

Either way the github issues becomes a nice way to have a constructive dialog between the multiple parties :)

**Comment by roman87** [comment]
I also feel its important for me to keep the loop closed with a resolution of some sorts for every issue. Otherwise we may miss an important idea, or leave some misunderstanding on the "users'" part, that will grow into an issue later on. Besides, its just good customer service :)
Anyways keep the ideas flowing.

**Comment by DinisCruz** [comment]
@pjenney58 can you try the CR.Beta.3 release just pushed to https://beta.teammentor.net (for the multiple filter selection capability)

**Comment by pjenney58** [comment]
Yup, looking now.  Its nice that the filter multi select is working.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by DinisCruz** [comment]
@pjenney58 since you opened the issue, the protocol is that it should be you to close it :)

So, if the filters are working as you originally intended, fell free to close it

**Comment by pjenney58** [comment]
OK, will do.  Where's the close button?  It doesn't seem to be available.  Is it because the issue is assigned to Roman?

**Comment by DinisCruz** [comment]
ahh.... maybe you don't have privs :)

Ok for future reference, then just ask for it to be closed and one of us will do it (like me now)
