### ISSUE TITLE
No Objective C, but there is iOS ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#584]
The default Apple (iOS/OSX) programming environment is Objective C but its missing from the filter list.

**Comment by roman87** [comment]
The technology is in fact iOS. While it is true that objective C its more specific there articles are geared for someone developing in a mobile platform.  Which makes IOS more appripriate. Anyone else agree/disagree?

**Comment by pjenney58** [comment]
I guess my issue is that there are articles fro C++, Java and a host of others, but no Objective C, which is the de-facto standard for iOS development.  To that, there’s Android and its de-facto language, Java and it would make sense to have the OC in there too.  Is it just a lack of content issue?

I also noticed and meant to drop a note on it, that there doesn’t seem to be a C filter at all.  We’ve always said that C is the weakest environment as its so old and flexible, and lets devs get into a boatload of trouble, hence one would assume that there would be a significant focus on saving people using get language.   Then it occurred to me that C might be mashed in with C++, in which case the filter tab should say C/C++, to separating them completely would make more sense to me.

  

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by DinisCruz** [comment]
from a graph point of view the query 'Objective C' should contain the 'iOS' query (or the other way around)

**Comment by roman87** [comment]
I will raise the "Objective C" content to be put on the roadmap. However, I don't think we had any specific customer requests for it. Same goes for C. I think this is more a matter of demand and we just haven't seen that much demand for C. But I will put both of them on the backlog for content.

**Comment by DinisCruz** [comment]
content issue, marking to close

**Comment by roman87** [comment]
This is tracked here: https://github.com/TMContent/Lib_UNO/issues/28
closing.
