### ISSUE TITLE
Disappearing Selection Boxes

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#585]
The index and filter selection boxes scroll away leaving the user with a narrow article selection box only.  The boxes should stay in place so the user can a) have a reference to what the list consists of and b) have the ability to do things like add another filter or otherwise change the selected set without having to go back to the top of the screen.

![screen shot 2015-03-17 at 12 23 14 pm](https://cloud.githubusercontent.com/assets/2352439/6692077/d89ad43c-cca0-11e4-8dd8-27fb178a0f69.png)

**Comment by roman87** [comment]
This is a known issue. And will be fixed in thr nect version.

**Comment by romichg** [comment]
Done in Flare.
