### ISSUE TITLE
What the heck is Cassini?

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#586]
There's a reference to something called Cassini in the DOCS section but the usual description of what it is and where to get it are missing.

![screen shot 2015-03-17 at 12 28 33 pm](https://cloud.githubusercontent.com/assets/2352439/6692145/4cd1de2c-cca1-11e4-884a-cd8fddd971d9.png)

**Comment by roman87** [comment]
Honestly, if the user does not know what it is then they will really have no need in following the dociment:) But it will be taken out in the new version of docs as it is no lnoger relevant.

**Comment by pjenney58** [comment]
Thats fine.  My point wasn’t so much the value of it, but that typically when one references a third party technology that can be used, there’s a section that points to the source site where the user can go to download  and/or get additional information.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Ah ok. Makes sense. Anyways, it will be removed.

**Comment by romichg** [comment]
This was done.
