### ISSUE TITLE
Update docs, explaining that while src code is available it is not for comercial purposes. 

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#587]
In the following document it mentions that the user can just go to GitHub and pull the latest version of TeamMentor.  If this is available only to licensed users fine, but it should NOT be an option for people doing a "Free Trial".

If it is going Open Source, we need to talk about OSS license types and terms.

![screen shot 2015-03-17 at 12 28 33 pm](https://cloud.githubusercontent.com/assets/2352439/6693216/bd9b8e36-cca7-11e4-9e67-c98266c1fa49.png)

**Comment by DinisCruz** [comment]
open source is more than just having the code available. 

As things stands TM code is available but it is covered by an commercial license so it can't be used in a commercial use without a paid license

**Comment by pjenney58** [comment]
I understand that,  You may recall that I did the whole NTRU open source initiative and wrote the commercial license for all of our software products.  My point is that from the way the text in the DOC section reads, anyone can pull the code and we have no protection, especially if it’s offered to the “Free Trial” users.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
There its a licence file that its pulled with the code. It is our generic license file. That should provide the protection you are referring to. Let me know if there its something we need to change. One option would be to reword the doc page to say something like - you can look and contribute to the code. Its comercial use is subject to proper licensing.

**Comment by pjenney58** [comment]
That would be good language to consider.  We really need to make sure that folks know that this is a real commercial product with source code available and not something they can just download and use as they please.

To that, we could also consider a checkbox at the initial login that states that logging in accepts the license agreement , and put a link to it for them to open and read.  If they don’t check the I accept box, login is disabled.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Ok I will change the language in the docs  a bit. As far as the check box, we do have a statement there

![selection_159](https://cloud.githubusercontent.com/assets/1326120/6744231/ed032ca2-ce7c-11e4-86de-acc89b59fae0.png)

Disabling the login button, I feel, will introduce too much red tape, will not really buy as anything, and will turn away potential users. We want as many people to sign up for the trial as possible.

**Comment by pjenney58** [comment]
Hi Roman,

Potential users in our current context are really individuals in
organizations that have already bought the product for the most part.  We
license the software in bulk, not per single user.  The Trial Users we
would be servicing in this model are actually evaluators from an
organization looking at the product, and probably already in touch with our
sales folk, no?

Cheers!

pete.;1


*---)--------------------------------------Security Innovation, Inc.*
Peter H. Jenney
Vice President of Strategic Initiatives
Ombudsman, FSO, CCO  & PMO

(office)   +1.978.694.1008 x164
(mobile) +1.603.264.3961
(skype)     PeteJenney

**Comment by roman87** [comment]
That is a bit the other way around. The trial users are actually users not at all in touch with our sales team. These are users that have heard of TM, were sent a link to TM, googled for TM etc, basically have somehow found out about TM and now want to see what it is. These are users that (the idea is) would fall in love with TM, and request their management to get in touch with our sales team. 

Makes sense?

**Comment by pjenney58** [comment]
The fact that there's no eComerce opportunity kind of limits things in general. As mentioned before, most users are going to be those whose company has purchased Team Acadamy and have access to TeamMentor and being offered, with the hope of being internalized.  These folks would not generally be receptive to offers or other perks unless their company decreed it. 

Just say'in. 


> Cheers!
> 
> pete.;1
> 
> 
> ---)-------------------------------------
> Security Innovation, Inc.
> Peter H. Jenney
> VP, Strategic Initiatives
> Ombudsman, CCO, PMO
> 
> o:  978.694.1008 x164
> m: 603.264.3961

**Comment by roman87** [comment]
The hope is to change that :) And bring new business in through the site.

**Comment by pjenney58** [comment]
So I need to look again, apologies for being lazy, but are there purchase options presented to the "free trial user" during the evaluation? For example, is there a footer or header on each document pointing the user to a Security Innovation Sales Person who can formalize the deal?  It's as important as providing quality evaluation content to give the evaluator someone to give their money to.

p

**Comment by pjenney58** [comment]
From Jerry Maguire:  "Show me the money, {wiggle and jump}, Show me the money!" :-)

**Comment by roman87** [comment]
Not in this version. In the future version we will have an "alert" system that will nudge the user for things.

**Comment by roman87** [comment]
@pjenney58 the page that caused the original issue (way back :) ) had been removed. Could you take a look at the docs and let us know if this issue had been resolved to your satisfaction?

**Comment by pjenney58** [comment]
It looks pretty good.  Needs a copy editor review though, for example:

Edit Article Metadata

Editing Article Metadata

Guidance Item article Metadata

Each article has the following meta-data: 

Title: The title is the title that is displayed in the article list
Technology tag: The technology tag reflects what technology the article applies to
Phase tag: The phase tag signifies which phase of the software development life-cycle the article is relevant to
Type tag: The type tag describes the type of the article
Category tag: The category tag describes what kind of security control the article is about
The values of these fields create the filters and a drop-down list items in the article editor. These values can be change in the WYSIWING editor window. Use the drop downs to change the metadata of the articles. To add a new tag, enter the tag in the drop down field and click “Save Changes”


I think we meant WYSIWYG and changed

Cheers!

Pete

---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Hahaha.. didn't you hear about this great new WYSIWING editor? 
This has actually been there for ages. Thanks for noticing. We'll miss your comments!
