### ISSUE TITLE
Update the suppprt page with proper procedure 

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#588]
The support section says - leave a message and we'll get back to you.  This is definitely not something we want to say to Charles Schwab, AIG, Symantec or any other potential TeamMentor user. What should probably be there is our SLA (available from Colin or Sandra).

![screen shot 2015-03-17 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/2352439/6693553/25fb5fc2-ccaa-11e4-8369-9b8e013e9c0e.png)

**Comment by roman87** [comment]
Yea good catch. I will follow up

**Comment by romichg** [comment]
fixed
