### ISSUE TITLE
How does someone not logged in read this message?  Missing Graphic too.

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#589]
![screen shot 2015-03-17 at 1 36 10 pm](https://cloud.githubusercontent.com/assets/2352439/6693617/a42e127c-ccaa-11e4-9a4b-ce89bb9fe9cc.png)

If they're logged in they've already done everything in the document, haven't they?

Also, there's a graphic of some sort missing from the bottom of the document.

**Comment by roman87** [comment]
These doc pages are available to non logged in users. Just hit Docs on the navbar. 
Let me know if we can close this.

**Comment by pjenney58** [comment]
OK, that makes sense but I think there should be a scrubbing exercise to make certain documents unavailable to outside viewers e.g. downloading source code, and that the stuff that talks about how to install the server should be moved to a read.me or something.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Hmm.. I really am not sure if scrubbing install documentation and how do download src code will help. It is if anything  - security by obscurity :). Also, I am not sure if I mentioned, but all of our content is not available for download. Basically the only source code someone can download is the TM engine itself. Without content it is basically useless.

**Comment by roman87** [comment]
TTL expired. (2 weeks) closing.
