### ISSUE TITLE
System needs to be installed in order to read installation requirements ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#590]
The whole Installation section doesn't make sense as the system has to be installed in order to access it.  

![screen shot 2015-03-17 at 1 39 15 pm](https://cloud.githubusercontent.com/assets/2352439/6693676/1bc72f62-ccab-11e4-96cb-59ba0699322d.png)

**Comment by roman87** [comment]
That is a good point. The info will still be available on docs.teammentor.net www.teammentor.net. We can also print it as part of thr welcome package.

**Comment by roman87** [comment]
Let me know if I can close this one.

**Comment by romichg** [comment]
Closing due to ttl
