### ISSUE TITLE
Lots of missing graphics ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#591]
The system is missing a lot of graphics, the below graphic is just a representative sample.

![screen shot 2015-03-17 at 1 41 57 pm](https://cloud.githubusercontent.com/assets/2352439/6693728/73a6a03c-ccab-11e4-983e-625314f0251e.png)

**Comment by roman87** [comment]
Yes this is a weird one. This ia the same as #593

**Comment by DinisCruz** [comment]
Roman, this on is on your side of the court, right?

**Comment by roman87** [comment]
Yes, this is a proxy issue.

**Comment by roman87** [comment]
This is fixed. @pjenney58 can you take a look and confirm?

**Comment by pjenney58** [comment]
Everything looks to be there now, can be closed IMHO.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Thanks Pete. Cheers!
