### ISSUE TITLE
Two entries for Fortify ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#592]
Shouldn't everything be under the Fortify Installation heading?

![screen shot 2015-03-17 at 1 47 29 pm](https://cloud.githubusercontent.com/assets/2352439/6693836/3741b8ba-ccac-11e4-95d5-3d45e1778835.png)

**Comment by roman87** [comment]
No since Fortify SCA and Fortify Eclipse are two different products we integrate with. 

Let me know if I can close this one.

**Comment by pjenney58** [comment]
I had no idea they were different and it makes sense.  Might it make sense to roll the two different products up under a single Fortify heading to clarify the issue?

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
That is actually a limitation on the UI of the old docs.teammentor.net. While we haven't moved it completely over to 4.0 we can't make that change, but good point I will make that change in the future.

**Comment by DinisCruz** [comment]
This is a content issue right?

**Comment by roman87** [comment]
Not really. This is a docs issue

**Comment by DinisCruz** [comment]
ok, but should it be on this repo?

**Comment by pjenney58** [comment]
My feeling is that it could be beneficial to do it now

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Moving it to backlog for Sprint 3.
