### ISSUE TITLE
Missing code samples/examples ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#594]
Wandering through the guidance collection I see a lot of documents like this:

![screen shot 2015-03-17 at 3 25 07 pm](https://cloud.githubusercontent.com/assets/2352439/6695761/0e148914-ccba-11e4-8544-9ceb7ecd6ad2.png)

To me, the article seems incomplete without at least a code snippet from a real implementation.  When looking at the additional resources links, it's pretty much the same old MSDN/JavaDoc API descriptions and no code examples.  While the descriptions of what to do are OK, it just feels incomplete without code.

One of the things that we talked about in the early days and what our competitors [specifically  Security Compass with SD Elements] talk about today, is the availability of examples that can just be cut and pasted into code and work out of the box.  This was always big with customers too who we're, and I assume still are, really implementation focused and looking for a fast leg up with security.  Having code is really helpful for these folks.

(Just found this in the intro area under features:  Stores and cross-references your security policies with out-of-the-box secure coding checklists and examples.)

**Comment by roman87** [comment]
Yes we try to add s many code samples as possible. I will follow up to out the .NeT article code sames on the road map.

**Comment by pjenney58** [comment]
Great.  I believe the more the better:-)

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney
