### ISSUE TITLE
Bug in GraphDB Service resolve_To_Ids method

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#595]
@luchia just had this bug 

```
/Users/lucybloomfield/Client/TM_4_0_QA/TM_4_0_Design/node/services/Graph-Service.coffee:81
      url = this.server + "/convert/to_ids/" + (values.url_Encode());
```

The solution is to do this

![image](https://cloud.githubusercontent.com/assets/656739/6707053/0da4c8b2-cd5b-11e4-8ff0-09acecf42416.png)

I will apply this as a patch to dev

**Comment by DinisCruz** [comment]
Here is the test that replicates the issue

```coffee
it.only 'Issue 595 - Bug in GraphDB Service resolve_To_Ids method', (done)->
    graphService.resolve_To_Ids undefined,  (data)=>
      done()
```

**Comment by DinisCruz** [comment]
@lucy does that address the issue?

**Comment by DinisCruz** [comment]
Since all QA tests are passing 
![image](https://cloud.githubusercontent.com/assets/656739/6710891/910bec92-cd7b-11e4-827b-6f7c49434630.png)

I just pushed this as a hotfix to master (fix was done on dev)

**Comment by luchia** [comment]
It has fixed the issue, but now I'm not able to see the contents on the page. I can't remember how we fixed this last time?

![screen shot 2015-03-22 at 9 38 02 pm](https://cloud.githubusercontent.com/assets/4547737/6769557/c43516d0-d0db-11e4-9a3e-8749d49a6c99.png)

**Comment by roman87** [comment]
Works fine for me :) try to hit "Index" what do you see?

**Comment by luchia** [comment]
The blank screen in my last post.

**Comment by DinisCruz** [comment]
can you update the graphdb?

**Comment by luchia** [comment]
@DinisCruz and I fixed this this morning.

**Comment by luchia** [comment]
Assigning to @DinisCruz to close.
