### ISSUE TITLE
Change default page after login to Index (Jade)

### ISSUE THREAD

**Issue by afollett** [TeamMentor/TM_4_0_Design#596]
After signing up and logging in, the landing page is the search page. This makes the site look very empty. It might be better to default to the index page which shows a lot of the content.

**Comment by roman87** [comment]
Thanks for this. We did discuss it at length before. The idea is to push users towards searching. Index is just there in case someone wants to look through our content.  In the future however, there will be a search bar on all the pages.  
I am happy do discuss this again though.

**Comment by romichg** [comment]
We got a lot of feeback and all of them request Index page to be the main page.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_Website/pull/9

**Comment by romichg** [comment]
Done. Will be this way on next production release.
