### ISSUE TITLE
Sign up Email adds a period to user name

### ISSUE THREAD

**Issue by afollett** [TeamMentor/TM_4_0_Design#597]
The signup email (Welcome to Teammentor) 

adds a  period to my username like:

- Use your username : afollett.

Would be good to leave the period out like:

- Use your username : afollett

![email](https://cloud.githubusercontent.com/assets/4615837/6717561/947fd58e-cd6a-11e4-8dc6-b78f88f7c599.jpg)

**Comment by roman87** [comment]
Good catch.   we should remove the period.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/Dev/pull/173 (which also contains changes for the email validations).

**Comment by roman87** [comment]
Bumping to P0 so @DinisCruz can see this.

**Comment by DinisCruz** [comment]
@michaelhidalgo you're still making some changes on this one, right?

**Comment by michaelhidalgo** [comment]
Yes, here is the Pull Request
https://github.com/TeamMentor/Dev/pull/174

**Comment by roman87** [comment]
This is fixed.
