### ISSUE TITLE
Article's Terms and Conditions link is broken

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#599]
If you open up this article http://beta.teammentor.net/article/2e69dab56cfa/All-Untrusted-Data-in-HTML-Contexts-Is-Escaped-in-JSF and scroll down to the footer copyright, you will see that the Terms and Conditions link is broken : It points to http://beta.teammentor.net/article/misc/terms-and-conditions

![screen shot 2015-03-18 at 4 14 20 pm](https://cloud.githubusercontent.com/assets/1732035/6720565/97abd84c-cd89-11e4-9bf1-37ec2ff16638.png)

**Comment by roman87** [comment]
Making this a P0, since its pretty bad to have broken links.

**Comment by luchia** [comment]
The way it's written in the code is correct -

![screen shot 2015-03-22 at 5 21 23 pm](https://cloud.githubusercontent.com/assets/4547737/6772647/eac2d3d4-d13d-11e4-888f-9a41078f2353.png)

Is this a routing thing @Dinis or is it something I can do?

**Comment by DinisCruz** [comment]
The solution was to use the absolute link (see https://github.com/TeamMentor/TM_4_0_Design/commit/668b60ea6e7e84e5f78421fe31e7d43982d2afbf )

**Comment by roman87** [comment]
This is fixed.

**Comment by michaelhidalgo** [comment]
I will write a unit test for it.

**Comment by michaelhidalgo** [comment]
Unit test added https://github.com/TeamMentor/TM_4_0_QA/pull/25
