### ISSUE TITLE
Inconsistency between backend and UI length checks for email address

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#607]
Currently the backend API validates that the email address is not longer than 50 characters, however, the UI allows to enter 256 characters in the textbox (maxlength), so there is an inconsistency.

Q1 : Should we limit the UI to allow entering 50 characters or should we allow the backend to support 256 characters?

Q2: Also for length, format and null checks for the email address, we are using the error message configured in the config file in the back end, should we be more specific when then the length is  exceeded or not?

![screen shot 2015-03-20 at 10 40 51 am](https://cloud.githubusercontent.com/assets/1732035/6756170/b01b9006-ceed-11e4-84fa-684a247361c7.png)

**Comment by michaelhidalgo** [comment]
@DinisCruz  what do you think :)

**Comment by DinisCruz** [comment]
Q1: if the idea to support 250 chars for email then the back end should do it (is 250 really a valid email size???)
Q2: yeah, if we can we should provide info about the size of the email being a prob

**Comment by roman87** [comment]
Q1. I thought that 250 was a system wide limit we set for everything. Lets keep it simple and set that as the global limit on the server. In flare we can actually limit it to 50 chars on the UI.  

Q2. If this is a global limit, then maybe a generic error - your input exceeds an allowed amount of characters would be better. If anyone puts more than 250 char email size, they don't deserve a friendly error message. .

**Comment by DinisCruz** [comment]
note that we can put a 50 char limit on the Jade too, but it will only be enforced on newer browsers

**Comment by michaelhidalgo** [comment]
thanks It makes sense!

**Comment by michaelhidalgo** [comment]
Closing it as the question was responded.

**Comment by roman87** [comment]
Actually for flare, it would be cool to specifically make the limit on the UI lower than system wide limit. and if system wide limit was hit, we know that someone is not using a browser. Then we can throw an error message like - nice try, use this article on how to do input validation on both server and browser side :)

**Comment by michaelhidalgo** [comment]
Yeah :) I like that approach :)

2015-03-23 9:58 GMT-06:00 RomichG <notifications@github.com>:

> Actually for flare, it would be cool to specifically make the limit on the
> UI lower than system wide limit. and if system wide limit was hit, we know
> that someone is not using a browser. Then we can throw an error message
> like - nice try, use this article on how to do input validation on both
> server and browser side :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/607#issuecomment-85064659>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*
