### ISSUE TITLE
SCRUM Stages?

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#609]
I'm not a big SCRUM fan (it takes leather balls to play rugby) but I'm thinking it might make sense to include an AGILE section to the overall content.  This would pave the way to tool recommendations etc.  At least during the "Free Trial Period."

**Comment by DinisCruz** [comment]
You mean adding content about SCRUM and how security should fit within a SCRUM/AGILE development environment?

**Comment by pjenney58** [comment]
Ya sure you betcha ...  That's Minnesotan for YES :-)

**Comment by DinisCruz** [comment]
ok, then content requests/comments should go on the https://github.com/TMContent/Lib_UNO/issues repo

this one is mainly for code and design changes/issues

**Comment by pjenney58** [comment]
Hi Dinis,

That page gives a 404.  Any other place to look?

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman, CCO, PMO

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by DinisCruz** [comment]
That means you don't have privs to access it

I just sent you an invitation

![image](https://cloud.githubusercontent.com/assets/656739/6781148/44ec0dec-d163-11e4-93ee-7fa4ece8ab4d.png)

Hopefully that will do the trick

**Comment by pjenney58** [comment]
Got it.  I'll start using it ...

**Comment by roman87** [comment]
Also Pete, now that you are adding lots of issues, which is awesome, it would really help us greatly if you structure them according to the top paragraph here: https://github.com/TeamMentor/TM_4_0_Design/wiki/GitHub-Issues-Definitions

I know its a bit of a burden, but I think it really helps to understand exactly what needs to be done and organize them accordingly.  Don't worry about priorities etc. 

Thanks!
