### ISSUE TITLE
No specific C security documentation 

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#610]
I believe I've embedded this in some other report but it deserves to be brought to the top.  Some background so you don't 'bozo' me out of the gate. I'm a trained SW engineer and primarily write device drivers in C.  I wrote the first commercial SCSI CD-R burning software on the market (Dataware Technologies CD Record) and recently wrote some ultra cool whitelisting device drivers for Windows and Linux for SI's subsidiary,Resilient Machines.  I'm also tied into the automotive specification space where MISRA as a specification and SPICE as a process are key; plus I'm directly involved with the Industrial Control System (ICS) critical infrastructure cyber defense community, again, predominantly C implementations.

To the point,  C is the loosest language from a security standpoint, hence, should be the place where we provide the most guidance.  C is used in most all "safety of life" applications including those in the automotive and medical (think MRI, PETScan, CATScan and reporting) spaces.  I believe we're doing the industry a disservice by not including C as a primary focus.  C is also the language of embedded systems and a great deal of edge connected, Linux based systems are the basis for the Internet of Things (IoT) and I believe its our responsibility to make sure they have the information they need to create secure, and generally resilient software.

Just say'n.  We need more C guidance.

**Comment by roman87** [comment]
Pete, awesome! I agree. Now C is a huge language. When we put C on the road map, should we focus on anything specific? For example should we focus on  Embedded Systems, IoT systems, automotive? Once you had a chance to answer could you open a corresponding issue (One per set of guidance) here: https://github.com/TMContent/Lib_UNO/issues
This is where we manage our content related issues.

Thanks.

**Comment by DinisCruz** [comment]
this conversation continues at https://github.com/TMContent/Lib_UNO/issues/28
