### ISSUE TITLE
C/C++ is not exclusively Windows, hence we need more real world examples

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#611]
This is a general comment regarding our eGuidance and eLearning offerings.  We seem to be overly focused on Windows code and this represents only a portion of the real C/C+ work going on out there.  I can quote usage statistics al day long but everyone knows that Linux and other RTOS environments comprise a huge share of the "real" code space in the non-desktop world.

{Open to arguments on this, prepare to be trounced thou :-)  }

**Comment by roman87** [comment]
No arguments on this one. Can you open issues on Specific items you would like to see more guidance on in https://github.com/TMContent/Lib_UNO/issues 
:) 
Thanks.

**Comment by romichg** [comment]
closing due to ttl.
