### ISSUE TITLE
eLearning SME's and eGuidance SME's Need to Sync Up

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#612]
The title says a lot.  I've been through a good deal of the available content in both areas and have found that there's not a great deal of synchronicity.  The original TM goal was to provide guidance and on-demand training, and it would be really cool if it all lined up.

**Comment by roman87** [comment]
That is a great comment. We are working on this, and I will definitely have more conversations on this with @SandraPaivaSI and @SergeTruth 

But I will close this one as it is not really actionable unit of work :)
