### ISSUE TITLE
Industry Specific Index Items

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#613]
The current index list just calls out security issues in general.  Ignoring compliance issues, there are specific areas in industry where problems are most prevalent.  Java issues for Finance/Banking, C/C++ issues for IoT/embedded, PHP issues for, well, other folk, .. etc.  It might make sense to separate the primary index, perhaps providing "Compliance or Implementation" views?

**Comment by roman87** [comment]
Basically what you are saying is that it maybe a good idea to have an 'Industry" filter. i.e. someone chooses that they are in Finance and they get articles that are only related to finance. or Embeded filter and they get articles only related to "embeded"

**Comment by romichg** [comment]
Closing due to ttl
