### ISSUE TITLE
Current search title is not wrapping

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#614]
@luchia can you take a look at the code on your **lucy** branch (I just updated it with the latest merges)

The top-right title is not wrapping

![image](https://cloud.githubusercontent.com/assets/656739/6772116/d61aad7c-d0ec-11e4-8198-62b91c569e07.png)

**Comment by roman87** [comment]
Ugh, nasty. @michaelhidalgo  do you think we can have a unit test for this one?

**Comment by DinisCruz** [comment]
I'm actually curious to find the root cause of that one,since I'm not sure how we can test it :)

**Comment by roman87** [comment]
Well actually one thing is image hashes. @michaelhidalgo we should talk about this.

**Comment by michaelhidalgo** [comment]
Yeah, I was able to reproduce it

![screen shot 2015-03-23 at 1 35 50 pm](https://cloud.githubusercontent.com/assets/1732035/6788744/4fe7d9a8-d161-11e4-8e4c-7d28c0bfa379.png)

**Comment by michaelhidalgo** [comment]
I just quickly changed the style for the h3 and the text is now displayed

![screen shot 2015-03-23 at 1 39 20 pm](https://cloud.githubusercontent.com/assets/1732035/6788849/e6e360fc-d161-11e4-9452-481641a62620.png)

**Comment by luchia** [comment]
This has been fixed now (on the Lucy branch) -

![screen shot 2015-03-24 at 8 21 34 am](https://cloud.githubusercontent.com/assets/4547737/6791950/de8df578-d1fe-11e4-8db8-97ed12ab2d18.png)

**Comment by DinisCruz** [comment]
this is done (and on dev)

**Comment by roman87** [comment]
This is fixed.
