### ISSUE TITLE
TM article redirection is not happening upon login

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#615]
If somebody shares with you a TEAM Mentor article like this http://beta.teammentor.net/article/f5a6ef898038/Prepared-Statements-Are-Used-for-Data-Access and you are not logged in ithe system, TEAM Mentor challenges you to enter the login and password which is just fine. 

However upon login, you are not redirected to the article you requested in the first place. We should be able to support that redirection upon login.

**Comment by luchia** [comment]
Good pick up :)

**Comment by roman87** [comment]
Yea good one. I will keep it at P1 for Sprint 3. We should fix it first thing after the release

**Comment by michaelhidalgo** [comment]
I just made this issue a P0 so I'll attend it shortly.

**Comment by roman87** [comment]
Great, moved it into current sprint.

**Comment by michaelhidalgo** [comment]
I'm almost here. I'm finishing to validate the Url prior to redirect the user. I created an Issue here https://github.com/TMContent/Lib_UNO/issues/43 , since I'm using TM to develop TM :)

**Comment by michaelhidalgo** [comment]
With Pull Request [https://github.com/TeamMentor/TM_4_0_Design/pull/769]

@DinisCruz  can you please code review this issue, I'm adding QA (automation) test now.

**Comment by DinisCruz** [comment]
this is merged

**Comment by roman87** [comment]
This is working great! Just as expected. Good stuff!
