### ISSUE TITLE
Split the design into it's own repo

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#617]
now that we have mature code bases on TM_Design's code and design, and we are working from branches, we need to split the code and design into its own repo  (my thinking is that we can keep the design in the current repo and I'll move the node code it a separate one)

This will help to:
-  prevent issues like this https://github.com/TeamMentor/TM_4_0_Design/commit/b35e95d733c76f177d24d9b9dbe89d6d49001162 
- help with unit testing
- help with scss generation
- improve separation of concerns between views and backend

**Comment by roman87** [comment]
Again, as we agreed, Quality type can only be used for a "Taster" issue types.  This is not a quality issue but a task, that needs to be scheduled and prioritized.

**Comment by roman87** [comment]
We should do this first thing after the release.

**Comment by DinisCruz** [comment]
ok
