### ISSUE TITLE
iOS query doesn't work on live beta (or it didn't)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#623]
![image](https://cloud.githubusercontent.com/assets/656739/6809062/c2bba31c-d24f-11e4-9f74-ef4d3b2f3a92.png)

It is only happening on index

![image](https://cloud.githubusercontent.com/assets/656739/6809092/e4c13698-d24f-11e4-8e48-dde6c004cb97.png)

UPDATE: it started working and now I can't replicate the issue 

![image](https://cloud.githubusercontent.com/assets/656739/6809201/ac07d8ce-d250-11e4-9637-f5af3e49059f.png)

Anybody else seen this kind of behaviour on beta.teammentor.net? (I also saw the prob temporarily on http://localhost:1337/show/ but not on http://localhost:1337/show)

This is why we need the real-time loogs https://github.com/TeamMentor/TM_4_0_Design/issues/550

**Comment by roman87** [comment]
Did you pull the logs from the server? Can we analyze the logs from that time? This is why we need good logging. Being real-time has nothing to do with it. Since we can't replicate it now, the logs from that point in time is the only thing we got.

**Comment by romichg** [comment]
closing as this has not happened lately
