### ISSUE TITLE
Add easy way for user to provide feedback to TM Dev team

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#624]
We should make it really easy (via a link or contact form) for TM beta users to provide feedback to us. 

This could be link on every page to this page (https://github.com/TeamMentor/TM_4_0_Design/issues/new) or a form for the user to provided (which would trigger an email to us)

**Comment by roman87** [comment]
I would prefer this to be simply instructions to send an email with screen shots. In a from we can't have screenshots (or it would make the simple form quite complex) and I would rather not encourage a flood of issues into github. Its a pain to keep it all sorted now as it is.

**Comment by luchia** [comment]
I created a new branch called Issue_624 and there are four different pages (filters-contact-one/two/three/four).

#### Contact One
I don’t particularly like this one. It just adds an extra module to an already full application interface. The alert doesn’t particularly stand out either and to me, this solution feels cumbersome.

![screen shot 2015-03-27 at 6 06 24 am](https://cloud.githubusercontent.com/assets/4547737/6856527/5bdf04c8-d44c-11e4-8cbb-18091046d129.png)

#### Contact Two
Better. I prefer the centered version. I like this one the best. I think it could stand out a little less by changing the colour to a lighter grey.

![screen shot 2015-03-27 at 6 15 49 am](https://cloud.githubusercontent.com/assets/4547737/6856528/5be3e678-d44c-11e4-80d9-a4b9ee188fa0.png)
![screen shot 2015-03-27 at 6 15 56 am](https://cloud.githubusercontent.com/assets/4547737/6856526/5bdee006-d44c-11e4-8e4f-690968c4d587.png)

#### Contact Three
This solution works well on desktop, but once this moves to mobile, it’s not a nice solution. It would appear randomly placed on mobile and it’s also past the fold on desktop on any page that has a long left-hand side navigation.

![screen shot 2015-03-27 at 6 21 31 am](https://cloud.githubusercontent.com/assets/4547737/6856530/5be8ebb4-d44c-11e4-8d89-4829ca0f42df.png)

#### Contact Four
This is the second best option, in my opinion. I think going even lighter with the grey so it doesn’t stand out as much would also work well.
![screen shot 2015-03-27 at 6 37 30 am](https://cloud.githubusercontent.com/assets/4547737/6856532/5c0b4cb8-d44c-11e4-9c5b-61b4a33376c0.png)

Let me know what you guys think about the direction of this.

**Comment by DinisCruz** [comment]
I like option four

**Comment by roman87** [comment]
I personally like the last one - Contact Four. What does everyone else think. We also need a config option for it to turn it off in production.

**Comment by luchia** [comment]
Yeah, I like option four the best now as well. I have pushed the code to branch Issue_624 and this is what it looks like -

![screen shot 2015-03-31 at 6 46 51 am](https://cloud.githubusercontent.com/assets/4547737/6906399/034b50fe-d772-11e4-856a-fa895c78466c.png)
![screen shot 2015-03-31 at 6 46 54 am](https://cloud.githubusercontent.com/assets/4547737/6906401/03776c66-d772-11e4-97f5-86d6d8c32fff.png)

Assigning to @michaelhidalgo (???) to do the config option. @michaelhidalgo, if that's not right please assign back to me.

**Comment by DinisCruz** [comment]
merged an in dev

**Comment by roman87** [comment]
So one question, how do I configure this to be removed? @DinisCruz

**Comment by roman87** [comment]
i.e. if we don't want to to show, is there an easy way to not display it?

**Comment by DinisCruz** [comment]
the easy way is to change in the jade code :)

apart from that, there is no config option to control this (just added #646 to track that)

**Comment by roman87** [comment]
haha, ok, closing this one.
