### ISSUE TITLE
Odd filter state ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#625]
When one filters down to the lowest level, it shows duplicate content. Selecting the document type reduces the set to a single item, but the fact that the duplicates appear and are obvious doesn't seem right.  I logged a similar content centric issue over in Lib_UNO.

![screen shot 2015-03-24 at 2 11 41 pm](https://cloud.githubusercontent.com/assets/2352439/6809337/06fee7b6-d230-11e4-8aed-e0faac2534fe.png)

**Comment by DinisCruz** [comment]
I agree, we need to find a much better way to deal with that kind articles that are very close in content (they are not the same, but just about)

**Comment by roman87** [comment]
I also agree. This issue is actually discussed here: https://github.com/TMContent/Lib_UNO/issues/21
@pjenney58 take a look at some of the proposed solutions and see what you think. 
I am going to close this one as duplicate.
