### ISSUE TITLE
Mouse over highlights cross-reference links but not article titles

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#626]
It feels a little inconsistent to me. I'd expect the same functionality in both cases:

Highlighted Link (Pretend the mouse is hovering ...)

![screen shot 2015-03-24 at 3 15 35 pm](https://cloud.githubusercontent.com/assets/2352439/6810690/f770344a-d238-11e4-83e7-9b84e1f04bea.png)

Title (Pretend the mouse is hovering ...)

![screen shot 2015-03-24 at 3 15 55 pm](https://cloud.githubusercontent.com/assets/2352439/6810715/2349291e-d239-11e4-9286-12ea8f6b014e.png)

**Comment by luchia** [comment]
I'll do this one.

**Comment by luchia** [comment]
This has been done on the Lucy branch, ready to be merged in the next release -

![screen shot 2015-03-25 at 1 23 27 pm](https://cloud.githubusercontent.com/assets/4547737/6817837/3126b4ca-d2f2-11e4-8f9e-f67eee215f23.png)
![screen shot 2015-03-25 at 1 23 30 pm](https://cloud.githubusercontent.com/assets/4547737/6817838/312e79a8-d2f2-11e4-802d-2a1b7a121dc5.png)

**Comment by luchia** [comment]
I have created a pull request for this. @DinisCruz, it's a very minor change in the stylesheet so will be okay to merge immediately.

**Comment by DinisCruz** [comment]
code is merged

**Comment by roman87** [comment]
This looks good on Dev. Will follow up with @pjenney58 once the code is in beta

**Comment by roman87** [comment]
@pjenney58 closing the loop on this, could you check the latest beta and let us know if this issue had been resolved to your satisfaction?

**Comment by pjenney58** [comment]
Yup.  Looks fine.

Cheers!

Pete

---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Great, closing.
