### ISSUE TITLE
Is eGuidance still in play?

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#628]
In the initial plan [as I recall] eKnowledge was a combination of training and guidance.  We had coined the term eGuidance to refer to TeamMentor to differentiate it.  I just noticed that the TM Logo doesn't reflect the original concept. No biggie,  just an observation, but in the original layout the logo would say TEAM Academy eGuidance.

![screen shot 2015-03-24 at 4 22 22 pm](https://cloud.githubusercontent.com/assets/2352439/6811943/fbad39aa-d241-11e4-87d3-0c17af8094be.png)

**Comment by roman87** [comment]
Hmm... interesting. I don't think we will change it now but doesn't hurt to ask :)
@tlaloc75 do you remember why eGudance was no longer used?

**Comment by romichg** [comment]
closing due to TTL
