### ISSUE TITLE
I'm Clueless, how prevalent is Scala Play?  I've never heard of it ... :-)

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#630]
It seems to me that there are a lot of system critical programming languages in use, but this one is not one I'm familiar with it.  Do we have market analysis' supporting it?

![screen shot 2015-03-24 at 4 34 10 pm](https://cloud.githubusercontent.com/assets/2352439/6812215/c32af03e-d243-11e4-859f-1bc8fe6c8f67.png)

**Comment by tlaloc75** [comment]
This was requested and paid for by Sony. It's unique!

Jason



On Mar 24, 2015, at 2:38 PM, Pete Jenney <notifications@github.com> wrote:

It seems to me that there are a lot of system critical programming
languages in use, but this one is not one I'm familiar with it. Do we have
market analysis' supporting it?

[image: screen shot 2015-03-24 at 4 34 10 pm]
<https://cloud.githubusercontent.com/assets/2352439/6812215/c32af03e-d243-11e4-859f-1bc8fe6c8f67.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/TeamMentor/TM_4_0_Design/issues/630>.

**Comment by pjenney58** [comment]
Doah!  Sony!

OK Guys,  could someone close this one?

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by DinisCruz** [comment]
It's actually quite popular. Scala is an evolutionary step for Java developers (these days if you are doing hard core Java dev, most likely you would be using scala) and Scala Play is a web framework (like Spring MVC or struts)

see more details at https://playframework.com/
