### ISSUE TITLE
On GraphDB add metadata mappings to articles

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#631]
Originally the GraphDB did not contain a direct mapping to the article's metadata. The metadata mappings were inside a 'Technology' query which contained (for example) an 'iOS' query which is the one that contained the articles.

This worked fine until we needed to have a full mapping of the articles 'phase', 'technology' and 'type' on the search results (for example for https://github.com/TeamMentor/TM_4_0_Design/issues/574 and https://github.com/TeamMentor/TM_4_0_Design/issues/577).

The solution is to add an extra mapping during the db import stage, which will map an article to its metadata. For example

```json
  {
    "subject": "article-0422dbfbdbaa",
    "predicate": "phase",
    "object": "Design"
  }
```

**Comment by DinisCruz** [comment]
This is done with the mapped commit

now an article has 3 extra mappings (phase, technology and type)

![image](https://cloud.githubusercontent.com/assets/656739/6833297/e417f982-d323-11e4-93d9-5b5f937f40f7.png)

this information is also exposed to the query data (used by the ui)

![image](https://cloud.githubusercontent.com/assets/656739/6833326/09e9a2d2-d324-11e4-9d20-bb6db2814ba5.png)

![image](https://cloud.githubusercontent.com/assets/656739/6833348/32af2868-d324-11e4-8821-24d5db5ebfda.png)

**Comment by DinisCruz** [comment]
Build is [failing on travis](https://travis-ci.org/TeamMentor/TM_4_0_GraphDB/builds/55847000) (so need some further tests, before its ready for QA)

**Comment by DinisCruz** [comment]
fixed test, moving this to master https://travis-ci.org/TeamMentor/TM_4_0_GraphDB/builds/56038168

**Comment by roman87** [comment]
Lets discuss this. I am not sure this is the right aproach. We should have added an xref to the already existing query. iOS for example. So the end result should be that  article -> xref -> iOS and iOS -> xref -> article
This approach duplicates nodes.

**Comment by DinisCruz** [comment]
article -> xref -> iOS is already what was happening, but I would still need to a further query to resolve iOS to technology.

I don't think having those extra nodes in there are a problem. In fact that is part of the beauty of a GraphDB., we can add nodes/relationships based on the way the data will be consumed (or created/populated)

**Comment by roman87** [comment]
yes, you would need an extra query :) I would rather take a hit on doing an extra query (which should not be that expensive) than duplicate data. Data duplication is bad, nasty and ugly, and will come to bite us in the future when we no longer use the current import mechanism for articles, but write directly to the database. Check this out, so lets say our new editor interface writes directly to the graphDB. Then when you create a new article, you will have to create the xref to technology and then another triplet for the article itself. Now, we are planning on allowing an article to have multiple technologies (because all they are is just keywords). You see how quickly it grows to be a problem?

**Comment by DinisCruz** [comment]
I don't think that that is such a big problem, and in fact this kind of 'evolve the graph as we go along' is part of the beauty of having a graphdb.

And it is quite expensive to do the extra query since since you need to do it for all articles on the query (at least until we add paginations for the results). In your example it wouldn't be that hard to take this extra mapping into consideration when editing (vs adding something that will impact all queries).

What we really need is to bring back the visualisation of the data that is in the graph, which will allow for better understanding of how the data is stored and used.

note that at the moment the GraphDB schema is still created programatically on DB Rebuild/Reload (which only takes a couple secs), so we are not really making any long terms decisions with how the data is being stored. And we still need to have the conversation/research if the current GraphDB (and levegraph/levelup) is the one that we should be using in the medium term

**Comment by roman87** [comment]
Alright, lets talk about it tomorrow. We should start formalizing the schema a bit. Since while graphDB is organic, we dont want to duplicate data. 
I do agree we need the visualizations. Though I think we can use some of the existing tools out there instead of spending time on our own. How hard would it be to dump the db into dot notation?

And yes, if we feel leveldb is not the right one we should be changing it sonner rather than later.

**Comment by DinisCruz** [comment]
> How hard would it be to dump the db into dot notation

My understanding is that dot notation is good to map 'A to B' relationships, but our current graph architecture is based on triplets (A to B to C')

**Comment by roman87** [comment]
So wouldn't tripliets in DOT notation look like
A to B
B to C 
:)?

**Comment by DinisCruz** [comment]
that wouldn't work because we need to capture the relationship between A and C

For example we have 

'article-000000032948' 'is' 'Article'
'article-000000032948' 'title' 'Access Control Checks Are Performed for All Filesystem Access'

which is something that can't be easily done in dot since we couldn't do

'article-000000032948' -> 'is' 
'is' -> 'Article'
or 
'article-000000032948' -> 'Article'

see what I mean?

for reference here are a couple triplets from http://localhost:1332/graph-db/predicate/title

```
  {
    "subject": "article-000000032948",
    "predicate": "title",
    "object": " Access Control Checks Are Performed for All Filesystem Access"
  },
  {
    "subject": "query-f8e4c9926792",
    "predicate": "title",
    "object": "(Web) Encoding"
  }
```

**Comment by roman87** [comment]
article-000000032948 -- "Access Control Checks Are Performed for All Filesystem Access"  [label="title"]
:)

**Comment by DinisCruz** [comment]
that might work. 

ok open an issue if you want to get a flat file with an export of the graphDB data in the format shown above

**Comment by roman87** [comment]
This is done, closing.
