### ISSUE TITLE
After DB lock, double check if data is available on cache

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#641]
To make the app more robust to race conditions and DoS (see https://github.com/TeamMentor/TM_4_0_Design/issues/604 ) for the cases when GraphDB cannot be opened, add a check to see if the data is available on the cache (at the moment the cache check happens before the request to open the GraphDB)

**Comment by DinisCruz** [comment]
done with code pushed to GraphDB master (with [tests passing](https://travis-ci.org/TeamMentor/TM_4_0_GraphDB/builds/56368329). This code change should have no side effects on the rest apis consumed by TM_Design 

@roman87  I'm closing this since there is no easy way for you to manually test this. For reference the unit-test that tests this behaviour is at https://github.com/TeamMentor/TM_4_0_GraphDB/blob/master/test/api/base-classes/Swagger-GraphDB.test.coffee#L135-L180

**Comment by roman87** [comment]
Cool, that should help for simultaneous searches. I still think that queuing is a better approach.

**Comment by DinisCruz** [comment]
what is implemented is kinda a queue, but it is one that has an expiry setting on it (i.e it will try 20 at 250ms intervals, before kicking out). I currently not keeping track of how many items are in the queue, but that wouldn't be too hard

**Comment by roman87** [comment]
ok.. thats cool. I would be curious to see what happens when there is a request that exceeds the 5 second time out.
