### ISSUE TITLE
Extract article abstracts based on the "Why" paragraph. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#643]
This is what we talked to a couple of days ago. Basically parse the HTML and extract the why section.  (note this is sprint 3)

**Comment by romichg** [comment]
We don't need this anymore besides what is done already. We have a good method of extracting summaries based on first 200 characters of items in <p>. We need an EDITOR support for summaries to make them more robust at this point. 
Related to #903
