### ISSUE TITLE
[Q] write test that confirms and detects changes to icons used on technology and type

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#644]
The objective is to pick up issues like this https://github.com/TeamMentor/TM_4_0_Design/issues/574#issuecomment-87876223

@tekgirl77 do you want to have a go at writing this one?

**Comment by tekgirl77** [comment]
[PR submitted here](https://github.com/TeamMentor/TM_4_0_QA/pull/32)

**Comment by tekgirl77** [comment]
@DinisCruz  TravisCI is failing on this one - here is the library I am pointing at, is this correct for the QA environment also?

  "tm_3_5_Server": "https://tmdev01-uno.teammentor.net",
  "content_Folder": "./.tmCache/_TM_3_5_Content",
  "default_Repo": "git@github.com:TMContent/Lib_UNO.git",
  "current_Library": "Lib_UNO"

**Comment by tekgirl77** [comment]
I think this can be closed, the PR was merged into Dev branch.

**Comment by DinisCruz** [comment]
@tekgirl77 the travis runs on Lib_Vulnerabilities library (https://github.com/TMContent/Lib_Vulnerabilities)

**Comment by tekgirl77** [comment]
Thanks @DinisCruz 

Hm, okay... I updated my library to the Lib_Vulnerabilities and the test is still passing for me locally.  The icons are all in the same place and order.  Can you help me understand what else may be causing the failure in QA env?

Based on the failure, it appears that PHP is the first technology listed in QA at the index page ('/show').

**Comment by tekgirl77** [comment]
@DinisCruz nevermind, I cleared my .tmCache and updated it; now I am seeing the change in libraries.

There is no '/show' page and no articles.

Shouldn't our QA env be pointing to the same library as production?  

Let me know if there is something more you want me to do with this test, or if we need to make a change to the library QA is using, or if I am missing something else?  :)

**Comment by DinisCruz** [comment]
@tekgirl77 ok, I just pushed an refactored of this test, and now looks like this:

```coffee
  it 'Issue 644 - Validate icon for each Technology or Type', (done)->
    mappings =
      "Web Application" : { title : "Web Application" , class : "technology-icon web-app"     }
      "All"             : { title : "Any Technology"  , class : "fi-flag"                     }
      "C++"             : { title : "C++"             , class : "technology-icon c-plus-plus" }
      "iOS"             : { title : "iOS"             , class : "technology-icon ios"         }
      "Android"         : { title : "Android"         , class : "technology-icon android"     }
      ".NET 3.5"        : { title : "ASP.Net"         , class : "technology-icon asp"         }
      "Java"            : { title : "Java"            , class : "technology-icon java"        }
      ".NET"            : { title : "ASP.Net"         , class : "technology-icon asp"         }
      "Scala Play"      : { title : "Scala"           , class : "technology-icon scala"       }
      "PHP"             : { title : "PHP"             , class : "technology-icon php"         }
      "HTML5"           : { title : "HTML5"           , class : "fi-html5"                    }
      "Guideline"       : { title : "Guideline"       , class : "fi-book"                     }
      "Checklist Item"  : { title : "Checklist"       , class : "fi-checkbox"                 }
      "How To"          : { title : "How To"          , class : "fi-list-bullet"              }
      "Code Example"    : { title : "Code Sample"     , class : "fi-puzzle"                   }

    jade.login_As_User ()->
      jade.page_User_Index (html,$)->

        technology = $('#filter-Technology')
        phase      = $('#filter-Phase')
        type       = $('#filter-Type')

        # Technology
        $(technology.find('h4')).html().assert_Is 'Technology'        # checking Technology values and icons

        technology.find('td').each (index, td)->
          using $(td),->
            text = $(@.find('span').eq(1)).html()
            mappings[text].assert_Is_Object()
            if mappings[text].class.starts_With('fi')
              $(@.find('i')).attr().assert_Is mappings[text]
            else
              $(@.find('div')).attr().assert_Is mappings[text]

        # Phase
        $(phase.find('h4')).html().assert_Is 'Phase'                # checking Phase value (no icons for phase)

        # Type
        $(type.find('h4')).html().assert_Is 'Type'                  # checking Type values and icons

        type.find('td').each (index, td)->
          using $(td),->
            text = $(@.find('span').eq(1)).html()
            mappings[text].assert_Is_Object()
            $(@.find('i')).attr().assert_Is mappings[text]

        done()
```

can you study it and see what I did?

**Comment by DinisCruz** [comment]
@tekgirl77 can you fix the test?

![image](https://cloud.githubusercontent.com/assets/656739/7091964/e48a5b08-df7b-11e4-8f0e-f1929e83e7cb.png)

this is caused by the fact that there are some  diff Technology mapping in the Lib_Vulnerabilities lib

> Shouldn't our QA env be pointing to the same library as production?

the main reason was to not publish our entire lib to travis (and to deal with giving it access to our private Lib_Uno repo)

It also runs faster and it is nice to run tests on different libraries

**Comment by tekgirl77** [comment]
Oh thank you!!  I did play around with some of that, like the .each method... but wasn't sure how to tie them together ... let me take another look.

**Comment by tekgirl77** [comment]
@DinisCruz the issue is a difference b/n the text in the 2nd span tag for "Any Technology" in QA ("Any") versus the local and beta environments ("All").

- Here is QA:


  ![screen shot 2015-04-10 at 4 54 53 pm](https://cloud.githubusercontent.com/assets/6649463/7098758/98195360-dfa2-11e4-9f93-df39557064d4.png)

- And here is the beta environment (same as my local):

  ![screen shot 2015-04-10 at 4 58 45 pm](https://cloud.githubusercontent.com/assets/6649463/7098770/e3a472f6-dfa2-11e4-8688-58b55682b5cf.png)

Can you help me understand where it is picking up this value from?

**Comment by DinisCruz** [comment]
That value comes from the graph search

**Comment by tekgirl77** [comment]
Thanks that is what I thought... so these get categorized and populated manually, correct?


![screen shot 2015-04-11 at 10 25 42 am](https://cloud.githubusercontent.com/assets/6649463/7102202/489e4c34-e036-11e4-899c-f5e0e26b2a43.png)

**Comment by roman87** [comment]
@tekgirl77 don't forget to assign the issue to the appropriate person, in this case its @DinisCruz

**Comment by DinisCruz** [comment]
Well not really manually, the TM article editor is used to change those values

**Comment by tekgirl77** [comment]
@roman87 I don't think I have the rights to assign issues yet

**Comment by DinisCruz** [comment]
ok, I just fixed the small issue that happened due to Lib_Vulnerabilities

![image](https://cloud.githubusercontent.com/assets/656739/7107657/d5014b1c-e163-11e4-84c8-4f5fa5e46168.png)

**Comment by DinisCruz** [comment]
closing it
