### ISSUE TITLE
Add config option to show/hide user feedback link

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#646]
Which was the feature added at https://github.com/TeamMentor/TM_4_0_Design/issues/624

**Comment by roman87** [comment]
I would argue this is a bug :) Its great that it can be turned off in the code, but remember there are 10 kinds of people. The ones that understand binary, and the ones that don't :)

**Comment by romichg** [comment]
This is no longer needed. There is no requirement to disable feedback at the moment.
