### ISSUE TITLE
Docs pages are not resizing properly

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#649]
![screen shot 2015-04-01 at 8 17 30 am](https://cloud.githubusercontent.com/assets/4547737/6930544/9377996e-d847-11e4-8e43-9fa7ff9573a2.png)
![screen shot 2015-04-01 at 8 17 33 am](https://cloud.githubusercontent.com/assets/4547737/6930545/93a1b8c0-d847-11e4-962f-9545448ecc53.png)

**Comment by luchia** [comment]
I've just added a fix for this. I have created a PR @DinisCruz.

**Comment by DinisCruz** [comment]
merged into dev https://github.com/TeamMentor/TM_4_0_Design/pull/650

**Comment by roman87** [comment]
looks good.
