### ISSUE TITLE
Is the TeamCity Hook for this repo still being used?

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#655]
Just found this webhook in this repo

![image](https://cloud.githubusercontent.com/assets/656739/6957539/7c2816ac-d8ca-11e4-87a1-8e247575b232.png)

I think is a legacy from past experiments with TeamCity and it doesn't seem to be working

![image](https://cloud.githubusercontent.com/assets/656739/6957545/b0128222-d8ca-11e4-9eaa-529a4f03028e.png)

@michaelhidalgo are you still using this?

**Comment by DinisCruz** [comment]
The waffle webhook is also not succeeding

![image](https://cloud.githubusercontent.com/assets/656739/6964190/c856bea8-d914-11e4-885e-a00e176a8d51.png)

**Comment by michaelhidalgo** [comment]
Hmm, I don't think we are using it.

**Comment by roman87** [comment]
I don't think we need the waffle hook ether.

**Comment by romichg** [comment]
Closing due to TTL
