### ISSUE TITLE
Remove unwanted HTTP headers from https://beta.teammentor.net

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#660]
As depicted below, an HTTP HEAD to https://beta.teammentor.net reveals sensitive/unwated headers.

![screen shot 2015-04-03 at 5 26 00 pm](https://cloud.githubusercontent.com/assets/1732035/6990275/5af67a2a-da26-11e4-92e4-1e5600923e03.png)

**Comment by romichg** [comment]
done.
