### ISSUE TITLE
Should we mark TM session as secure too?

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#661]
TM session is set to be ReadOnly, should we also enforce Secure so that way it will be only transmitted over a secure channel? I think we should :)

![screen shot 2015-04-03 at 5 29 23 pm](https://cloud.githubusercontent.com/assets/1732035/6990302/cbb852e2-da26-11e4-82ba-3c10c69b5bef.png)

**Comment by roman87** [comment]
I am not sure we can do it with the reverse proxy.

**Comment by michaelhidalgo** [comment]
I think is doable from Node Express perspective as described in this
article
http://scottksmith.com/blog/2014/09/04/simple-steps-to-secure-your-express-node-application/

However, setting this flag means that the cookie will only be transmitted
over a secure channel, which might not work on our local environment

2015-04-04 17:53 GMT-06:00 RomichG <notifications@github.com>:

> I am not sure we can do it with the reverse proxy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/661#issuecomment-89690251>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
we should try it, I also would like to see if we can start running our own dev environments in SSL (as per the @tekgirl77 work done at https://github.com/TeamMentor/TM_4_0_Design/issues/147)

**Comment by roman87** [comment]
Well, there is actually no point in doing that (at the moment) while we are behind reverse proxy. Basically this would mean that IIS needs to establish an SSL connection to express over the loopback port, which is a waste of resources. 
So I would suggest we leave it until the time we move away from IIS. Objections?

**Comment by romichg** [comment]
Closing due to TTL
