### ISSUE TITLE
Docs pages need to be installed on and served from the local cache, including images

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#664]
As described in #593 currently the Docs pages are beeing cached when they are first used from Github. However the images are not cached. 
We need:
1. To download the whole docs library at install time, similar to what we do with Lib_Uno. 
2 Serve all the docs content, including images from  read it from .tmCache directory in TM_Design

**Comment by roman87** [comment]
Bumping this as we need this for the release

**Comment by DinisCruz** [comment]
code merged

**Comment by roman87** [comment]
This is fixed.
