### ISSUE TITLE
Work on the Jade footer

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#668]
Per #658, the alignment is slightly off on the footer.
![screen shot 2015-04-07 at 9 17 22 am](https://cloud.githubusercontent.com/assets/4547737/7014336/094dd34c-dd07-11e4-9fb4-072708831256.png)
![screen shot 2015-04-07 at 9 19 04 am](https://cloud.githubusercontent.com/assets/4547737/7014344/2a3f7fe2-dd07-11e4-95d9-acf756610d47.png)

**Comment by luchia** [comment]
This is what I currently have on Flare and I think it looks really good (ignore the clients div, still working on something.) -

![screen shot 2015-04-08 at 5 36 10 pm](https://cloud.githubusercontent.com/assets/4547737/7040769/dd14f6f6-de15-11e4-863c-de07333b29b4.png)

I thought stripping back some of the information that really wasn't relevant to TM was important and the footer is now a lot cleaner and looks 100% better.

**Comment by roman87** [comment]
Yep, definitely. We still need the version number there somewhere.

**Comment by luchia** [comment]
Why do we need the version number? Could it be a part of our docs instead?

**Comment by roman87** [comment]
Its good to know the version number at a glance. Docs would not necessary change between versions. It is mainly for support/troubleshooting and installation purposes.

**Comment by luchia** [comment]
Sure, that makes sense. See below for what I have now. I just created a PR for @DinisCruz as well -

![screen shot 2015-04-14 at 12 44 15 pm](https://cloud.githubusercontent.com/assets/4547737/7129461/1a494918-e2a4-11e4-81bd-01eb233dfc29.png)
![screen shot 2015-04-14 at 12 44 26 pm](https://cloud.githubusercontent.com/assets/4547737/7129462/1a49cbcc-e2a4-11e4-9e0d-8525cb017ca5.png)
![screen shot 2015-04-14 at 12 44 30 pm](https://cloud.githubusercontent.com/assets/4547737/7129463/1a4d7272-e2a4-11e4-9665-4795639e8cec.png)
![screen shot 2015-04-14 at 12 44 34 pm](https://cloud.githubusercontent.com/assets/4547737/7129460/1a493220-e2a4-11e4-8fd3-166e4f25cd7d.png)

**Comment by luchia** [comment]
This solution flows a lot better on Flare thanks to flexbox but I think this is okay for legacy browsers.

**Comment by roman87** [comment]
Looks good.
