### ISSUE TITLE
Run Node sites directly on node and not via IIS

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#678]
We keep having a number of IIS issues caused by the fact that node is being proxied by IIS (latest one is https://github.com/TeamMentor/TM_4_0_Design/issues/677). I think that the time has come to actually support running node as it is supposed to be run (directly). If anything we should do the reverse, proxy the 3.5 TM on a node module, or run 3.5 on a different port

At the moment, we already have an complex IIS set-up, so we might as well make it more explicit that the node site should be run natively using node.

**Comment by roman87** [comment]
That is a good idea.  However, does node support multiple sites on the same port? Is there a reverse proxy module for node?

**Comment by romichg** [comment]
closing due to TTL
