### ISSUE TITLE
[Q] use isnt instead on != when setting the loggedIn value

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#680]
Which follows our [Coding Standard](https://github.com/TeamMentor/TM_4_0_Design/wiki/Development-Style-Guide)

![image](https://cloud.githubusercontent.com/assets/656739/7051267/14fc975c-ddf5-11e4-97dc-2419b161e2db.png)

**Comment by DinisCruz** [comment]
@michaelhidalgo can you take a look at this issue and the fix, and then close the issue?

**Comment by michaelhidalgo** [comment]
Nice, it looks more verbose. Closing it.
