### ISSUE TITLE
Searching for ASP.NET produces only 3 articles in result list. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#685]

**Comment by DinisCruz** [comment]
Making P1 since this depends on #704

**Comment by roman87** [comment]
This is now fixed,

**Comment by roman87** [comment]
This is now again an issue

**Comment by DinisCruz** [comment]
This is content Issue

You guys removed the ASP.NET tag

https://github.com/TMContent/Lib_UNO/blame/510f66de56838aa2f354e8fbfcb73b59541eed43/Guideline/96059535-1543-458e-afb7-e40360b9dcd2.xml#L10

That is where those search results where coming from

**Comment by DinisCruz** [comment]
more specifically you removed the asp.net technology which is currently used as the default value for the Tag

**Comment by roman87** [comment]
Yes I know that :) but the tags don't work for me ad in #704. I am putting the tags back now into the content. But if they don't work we can't use them :)

**Comment by roman87** [comment]
I've added ASP.NET tags to most of the articles so they should work, once tagging is working again.

**Comment by DinisCruz** [comment]
This should be working now

![image](https://cloud.githubusercontent.com/assets/656739/7594428/73309564-f8d8-11e4-99f1-0f2ba0894142.png)

**Comment by roman87** [comment]
Issue is covered in #704 closing
