### ISSUE TITLE
It is possible to create hundreds of temporary articles in the server using TM.

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#697]
It seems like when we provide a non-existing article, GraphDB creates a temporary file in the /.tmCache/data_cache folder.

Someone might run a script and full the disk with files : 

Here is the folder empty : 

![screen shot 2015-04-14 at 9 42 14 am](https://cloud.githubusercontent.com/assets/1732035/7141056/579cfbf6-e28c-11e4-8ebf-9ea3a93e6e1c.png)

Creating a script to target TM 

```coffeescript
  runTest = (articleUrl) ->
    testName = articleUrl
    it testName, (done) ->
      jade.login_As_User ()->
        page.open articleUrl, (html,$)->
          page.wait_For_Complete (html, $)=>
          done()

  x =0
  while x < 500
    url = "/article/query-".add_5_Letters()
    runTest(url)
    x++
```

and this is the result 

![screen shot 2015-04-14 at 9 51 49 am](https://cloud.githubusercontent.com/assets/1732035/7141080/83b0c2c2-e28c-11e4-81fe-947ec416de0b.png)

**Comment by michaelhidalgo** [comment]
As a reference, here are the lines where the file is saved to disk

https://github.com/TeamMentor/TM_4_0_GraphDB/blob/master/src/api/Data-API.coffee#L15
https://github.com/TeamMentor/TM_4_0_GraphDB/blob/master/src/api/base-classes/Swagger-GraphDB.coffee#L16

**Comment by DinisCruz** [comment]
that is a bug, in fact that is most likely the reason for the https://github.com/TeamMentor/TM_4_0_Design/issues/682 prob

we need to fix it here https://github.com/TeamMentor/TM_4_0_GraphDB/blob/master/src/api/Data-API.coffee#L17

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_GraphDB/pull/3/files

**Comment by DinisCruz** [comment]
I just merged https://github.com/TeamMentor/TM_4_0_GraphDB/pull/5

@michaelhidalgo can you run your script again and confirm that the temp files are not created

**Comment by DinisCruz** [comment]
added to #703

**Comment by michaelhidalgo** [comment]
Thanks Dinis, sure let me give it a test.

El martes, 21 de abril de 2015, Dinis Cruz <notifications@github.com>
escribió:

> added to #703 <https://github.com/TeamMentor/TM_4_0_Design/issues/703>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/697#issuecomment-94777643>
> .
>


-- 
Sent from Gmail Mobile

**Comment by michaelhidalgo** [comment]
This issue seems to be fixed : 
I ran simultaneous request (with Fiddler by incrementing by 1 the id of the URL using the # feature).
![screen shot 2015-04-22 at 09 48 34](https://cloud.githubusercontent.com/assets/1732035/7278865/4939ab50-e8d5-11e4-8927-033ea9206827.png)

Then I checked the temp folder and no articles were created 

![screen shot 2015-04-22 at 09 50 27](https://cloud.githubusercontent.com/assets/1732035/7278901/83fcd906-e8d5-11e4-8c28-10a561dc465b.png)

**Comment by michaelhidalgo** [comment]
closing this.

**Comment by DinisCruz** [comment]
nice, thanks
