### ISSUE TITLE
Search box too big in latest Dev (in mobile mode)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#699]
@luchia can you take a look at the Search box on the latest dev

it looks like this

![image](https://cloud.githubusercontent.com/assets/656739/7143387/1efb7624-e2d7-11e4-8571-dc843a697d69.png)

looks ok when in full width mode:

![image](https://cloud.githubusercontent.com/assets/656739/7143405/4c4fffd2-e2d7-11e4-8b41-12b82eefec22.png)

**Comment by luchia** [comment]
Got it, about to create a PR.

![screen shot 2015-04-15 at 5 43 14 am](https://cloud.githubusercontent.com/assets/4547737/7145871/92dd0aca-e332-11e4-8c75-dd91d5a7d78e.png)

**Comment by DinisCruz** [comment]
this was fixed on latest commit

**Comment by roman87** [comment]
This one was fixed, however now we have https://github.com/TeamMentor/TM_4_0_Design/issues/732
