### ISSUE TITLE
Flare UI is not working very well on latest Dev

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#702]
This is what I get

http://localhost:1337/flare/all#

![image](https://cloud.githubusercontent.com/assets/656739/7170236/2b058368-e3c4-11e4-97bc-657d808cd1bd.png)

http://localhost:1337/flare/articles/alert-article-new-window-view#

![image](https://cloud.githubusercontent.com/assets/656739/7170255/49710a0c-e3c4-11e4-9f5c-502177f3d977.png)

http://localhost:1337/flare/help/index
![image](https://cloud.githubusercontent.com/assets/656739/7170221/13714dcc-e3c4-11e4-8c29-d30953317e00.png)

**Comment by luchia** [comment]
@DinisCruz here's the production ready folder we discussed in our meeting this morning -

![screen shot 2015-04-16 at 10 36 15 am](https://cloud.githubusercontent.com/assets/4547737/7172044/7dc25fee-e424-11e4-83ed-3f77cff8c931.png)
![screen shot 2015-04-16 at 10 37 12 am](https://cloud.githubusercontent.com/assets/4547737/7172049/9a58dd0e-e424-11e4-8686-5cf0744f371b.png)
![screen shot 2015-04-16 at 10 37 14 am](https://cloud.githubusercontent.com/assets/4547737/7172051/9a5a2542-e424-11e4-925d-331295f21bc5.png)
![screen shot 2015-04-16 at 10 37 16 am](https://cloud.githubusercontent.com/assets/4547737/7172050/9a598542-e424-11e4-90dd-5cf2cc2f3250.png)
![screen shot 2015-04-16 at 10 37 23 am](https://cloud.githubusercontent.com/assets/4547737/7172052/9a5aa2ec-e424-11e4-9738-ef49e4f85e48.png)
![screen shot 2015-04-16 at 10 37 43 am](https://cloud.githubusercontent.com/assets/4547737/7172054/a49bdde8-e424-11e4-8861-8193c27bf0de.png)

This is the three pages that are needed to create a beta of Flare:
* [ X ] Main App View (when you first log in)
* [ X ] Search Results (after using the search)
* [ X ] Article View

**Comment by luchia** [comment]
Buttons still need work.

**Comment by luchia** [comment]
@DinisCruz, I've done some more work on this to tidy up the button styles. We now have a little more cohesiveness throughout the application. All my work is on the Lucy branch.

![screen shot 2015-04-21 at 11 19 41 am](https://cloud.githubusercontent.com/assets/4547737/7244001/6e078fb4-e818-11e4-8068-70f86d33e509.png)
![screen shot 2015-04-21 at 11 19 45 am](https://cloud.githubusercontent.com/assets/4547737/7244002/6e107a98-e818-11e4-89f5-c3c0816a2b7c.png)
![screen shot 2015-04-21 at 11 19 51 am](https://cloud.githubusercontent.com/assets/4547737/7244003/6e17c1a4-e818-11e4-96fb-926b2c4aefa6.png)
![screen shot 2015-04-21 at 11 19 54 am](https://cloud.githubusercontent.com/assets/4547737/7244004/6e1df1a0-e818-11e4-8bdc-fcd82b303a4c.png)

**Comment by DinisCruz** [comment]
closing since flare is behaving ok, and the wire of the 'production' pages is now at #724
