### ISSUE TITLE
Add support for using 3.5 Article Tags in search results weights

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#704]
The idea is to use the Tag values as an extra weight on the search results

This will also solve https://github.com/TeamMentor/TM_4_0_Design/issues/686 and https://github.com/TeamMentor/TM_4_0_Design/issues/685

**Comment by roman87** [comment]
All of WCF 3.5 articles now have the tag field populated with <Tag>WCF 3.5</Tag>

**Comment by DinisCruz** [comment]
done on latest commit

![image](https://cloud.githubusercontent.com/assets/656739/7241340/39b49bc0-e7b0-11e4-988d-7070ef9f77e0.png)

**Comment by DinisCruz** [comment]
added to https://github.com/TeamMentor/TM_4_0_Design/issues/703

**Comment by roman87** [comment]
It looks pretty good, however  something is not right:
Searching for "scala play" (lowercase) I get 4th or so result down
```
  {
    "id": "article-470d382c5b36",
    "score": 48,
    "why": {
      "scala": {
        "h2": 4,
        "em": 3,
        "p": 1,
        "title": 10
      },
      "play": {
        "tag": 30
      }
    }
  },
```
 how is it possible that "scala" did not match the tag, but "play" did? Also I think that if an article matches on a tag we should not text search the same article for the same tag.

**Comment by roman87** [comment]
When I search for "Java" I get
```
  {
    "id": "article-9c3c3ec448fe",
    "score": 54,
    "why": {
      "p": 18,
      "ol": 11,
      "li": 16,
      "ul": 5,
      "em": 3,
      "pre": 1
    }
  },
```
As first article. However that article does not exist "http://localhost:1337/article/9c3c3ec448fe"
In fact, the first article I get when searching with the UI is:
http://localhost:1337/article/000000065b72/Validate-Logged-User-Data
Which has a score of 2
```    "id": "article-000000065b72",
    "score": 2,
    "why": {
      "ul": 1,
      "li": 1
    }
  },
```

So the question is - huh? ?

**Comment by DinisCruz** [comment]
That is a weird result, here is what I get when searching for Java

![image](https://cloud.githubusercontent.com/assets/656739/7399779/1fbefc72-eeb0-11e4-95a3-1d693cf80bdd.png)

Which points to the article

![image](https://cloud.githubusercontent.com/assets/656739/7399841/8e66bebc-eeb0-11e4-8112-9e81d43e0db5.png)

**Comment by michaelhidalgo** [comment]
in fact, the first two occurrences do not exist

{ "id": "article-9c3c3ec448fe", "score": 54, "why": { "p": 18, "ol": 11, "li":
16, "ul": 5, "em": 3, "pre": 1 } }, { "id": "article-25871e535933", "score":
43, "why": { "p": 17, "ol": 9, "li": 13, "ul": 4 } },


http://localhost:1337/article/25871e535933

http://localhost:1337/article/9c3c3ec448fe

2015-04-29 14:10 GMT-06:00 Michael Hidalgo <michaelfallas@gmail.com>:

> I'm experiencing the same as Roman :
>
>
> ​
>
> 2015-04-29 13:44 GMT-06:00 Dinis Cruz <notifications@github.com>:
>
> That is a weird result, here is what I get when searching for Java
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/656739/7399779/1fbefc72-eeb0-11e4-95a3-1d693cf80bdd.png>
>>
>> Which points to the article
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/656739/7399841/8e66bebc-eeb0-11e4-8112-9e81d43e0db5.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TeamMentor/TM_4_0_Design/issues/704#issuecomment-97557752>
>> .
>>
>
>
>
> --
> Michael Hidalgo
> http://michaelhidalgocr.blogspot.com
>
> *The future has many names: For the weak, it means the unattainable. For
> the fearful, it means the unknown. For the courageous, it means
> opportunity. (1802-1885) French Poet, Dramatist, Writer*
>
>


-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by michaelhidalgo** [comment]
I'm experiencing the same as Roman :


​

2015-04-29 13:44 GMT-06:00 Dinis Cruz <notifications@github.com>:

> That is a weird result, here is what I get when searching for Java
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/656739/7399779/1fbefc72-eeb0-11e4-95a3-1d693cf80bdd.png>
>
> Which points to the article
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/656739/7399841/8e66bebc-eeb0-11e4-8112-9e81d43e0db5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/704#issuecomment-97557752>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
This is what I get when I search for 'scala play'

![image](https://cloud.githubusercontent.com/assets/656739/7401685/f3cc5ad4-eebd-11e4-87da-88fdeb8a205d.png)

**Comment by roman87** [comment]
We need to figure out why this is happening for me and @michaelhidalgo but not for @DinisCruz

**Comment by DinisCruz** [comment]
based on the fix for #742 can you you still replicate this issue?

**Comment by roman87** [comment]
Tags don't work at all now. 
![selection_228](https://cloud.githubusercontent.com/assets/1326120/7580548/1cac6cce-f845-11e4-8dc6-45ac3b4e5720.png)

**Comment by roman87** [comment]
Bumping this since we need this stuff to work for the release.

**Comment by DinisCruz** [comment]
Hum they are working here 

![image](https://cloud.githubusercontent.com/assets/656739/7582379/d4aa785e-f884-11e4-9d76-8fd373a30e02.png)

**Comment by michaelhidalgo** [comment]
They also works for me 

![screen shot 2015-05-12 at 06 43 44](https://cloud.githubusercontent.com/assets/1732035/7587276/4f1d822e-f872-11e4-8c5e-1759fe05b6ab.png)

**Comment by roman87** [comment]
Weird. Let me try to reload the lib

**Comment by roman87** [comment]
Nope, does not work. And my json does have WCF 3.5 object.
```
"object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
    "object": "WCF 3.5"
```

**Comment by roman87** [comment]
Precisely 78 of them. Which is the number of search hits you both got
```
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB/.tmCache/Lib_UNO-json/Graph_Data$ grep "WCF 3.5" lib-uno-triplets.json | wc -l
78
```

**Comment by roman87** [comment]
Is there a timeout that is being hit?

**Comment by michaelhidalgo** [comment]
Interesting, but you are right, I also got 78 results

Michael:Graph_Data Michael$  grep "WCF 3.5" lib-uno-triplets.json | wc -l

      78

Which is the value in the search.


Do you get 78 results when you go here
http://localhost:1332/search/word_score/WCF%203.5

I used this JSON parser http://jsonviewer.stack.hu/ to collapse the items.



2015-05-12 7:55 GMT-06:00 RomichG <notifications@github.com>:

> Is there a timeout that is being hit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/704#issuecomment-101291512>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by roman87** [comment]
I get [ ]  when I go to that URL :)

**Comment by DinisCruz** [comment]
ok, found the prob, working on a fix

**Comment by DinisCruz** [comment]
OK, can you guys try with the latest code?

Now I get these results:

**WCF 3.5**
![image](https://cloud.githubusercontent.com/assets/656739/7594390/3f14121a-f8d8-11e4-80db-9bbf326d093d.png)

**asp.net** 

![image](https://cloud.githubusercontent.com/assets/656739/7594410/59b894ba-f8d8-11e4-9dc2-9811fadbcf05.png)

**Asp.NET 3.5**
![image](https://cloud.githubusercontent.com/assets/656739/7594370/106d37de-f8d8-11e4-925d-e8dbcc87c391.png)

**Asp.net 4.0**
![image](https://cloud.githubusercontent.com/assets/656739/7594357/f6624bb8-f8d7-11e4-811a-7a8e4a13873b.png)

**Comment by michaelhidalgo** [comment]
Yeah, it works fine, I get the same results.

**Comment by roman87** [comment]
Not working right.
There are 179 articles tagged as WCF 3.5, 508 as ASP.NET, 316 as ASP.NET 3.5, 208 as ASP.NET 4.0


```
rom@TITI08:~/Dev/roman87/Lib_Uno$ grep -r "<Tag>WCF 3.5"  | wc -l
179
rom@TITI08:~/Dev/roman87/Lib_Uno$ grep -r "<Tag>ASP.NET"  | wc -l
508
rom@TITI08:~/Dev/roman87/Lib_Uno$ grep -r "<Tag>ASP.NET" | grep "3.5" | wc -l
316
rom@TITI08:~/Dev/roman87/Lib_Uno$ grep -r "<Tag>ASP.NET" | grep "4.0" | wc -l
258
rom@TITI08:~/Dev/roman87/Lib_Uno$
```

**Comment by roman87** [comment]
I am not going to make it dependent for the release, but we need to fix it right the way after.  I think the reason we have the issue is because we are not storing the Tag as a query (keyword)

**Comment by roman87** [comment]
Just checked this again and it is working correctly. The searches match the file system counts.  The check needed to make sure that the GUID is also part of the view

This is how to check for ASP.NET 4.0 for example:
```
grep -r "<Tag>ASP.NET" | grep "ASP.NET 4.0"  | awk -F\/ '{print $2}' | awk -F\. '{print $1}' | while read LINE; do grep "$LINE" UNO.xml > /dev/null; if [ $? -eq 0 ]; then  echo $LINE; fi; done | sort | uniq | wc -l
```
