### ISSUE TITLE
Pre populate Recent Articles, Top Articles, and Resent searches with something meaninfull on first install

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#709]

**Comment by DinisCruz** [comment]
ok so what should that be?

I need the ids of the articles to show and the default search queries

**Comment by roman87** [comment]
I am discussing the need for Recent articles with @tlaloc75  
For the rest:


Popular search items:
prevent sql injection
xss
secure connection string

Top Articles:
article/1d72228392bf/Decrypt-a-String-via-a-Block-Cipher-Using-AES
article/22ed784143ee/Using-Parameterized-Queries-for-Secure-Database-Access
article/17f790dedf10/Constrain,-Reject,-And-Sanitize-Input

**Comment by DinisCruz** [comment]
First part is done

Here are the default searches

![image](https://cloud.githubusercontent.com/assets/656739/7578442/f554a8fa-f84c-11e4-9a9e-c6c2440a2875.png)

**Comment by DinisCruz** [comment]
Here is what it looks like (on clean server load, and before any user interaction)

![image](https://cloud.githubusercontent.com/assets/656739/7592816/998f7c4e-f8cd-11e4-8965-13e93370ef09.png)
