### ISSUE TITLE
Need to have an Icon for "Vulnerability" Type articles

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#710]
As can be seen in https://tmdev01-beta.teammentor.net/show/ 

Vulnerability type articles do not have an Icon.

**Comment by luchia** [comment]
I couldn't recreate this locally, but I added the icon anyway. Let me know if it fixes the issues -

![screen shot 2015-04-21 at 9 09 30 am](https://cloud.githubusercontent.com/assets/4547737/7242488/458c1bca-e806-11e4-8fea-69437bf4bc7a.png)
![screen shot 2015-04-21 at 9 09 51 am](https://cloud.githubusercontent.com/assets/4547737/7242489/45f260b0-e806-11e4-929c-21341382fbe4.png)

I have created a PR for this and #687 for @DinisCruz.

**Comment by DinisCruz** [comment]
Merged and code is there

![image](https://cloud.githubusercontent.com/assets/656739/7250338/4c97b1f0-e819-11e4-84f6-c479559e2ddf.png)

**Comment by DinisCruz** [comment]
Added to Need to have an Icon for "Vulnerability" Type articles #710

**Comment by roman87** [comment]
Looks good closing
