### ISSUE TITLE
Search icon is mis-aligned on search page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#716]
See http://localhost:1337/search?text=xss
![image](https://cloud.githubusercontent.com/assets/656739/7250386/cef48074-e819-11e4-93f3-213b27a42a85.png)

I believe this was caused by https://github.com/TeamMentor/TM_4_0_Design/issues/687

**Comment by DinisCruz** [comment]
I just pushed a small hack to make it look good 

![image](https://cloud.githubusercontent.com/assets/656739/7254135/0982404a-e839-11e4-9dfc-f6debcce133c.png)

**Comment by luchia** [comment]
I just added a fix for it that works in Chrome, Safari and Firefox. I won't create a PR as I think it can be merged with next week's release (your fix works well for the moment).

**Comment by luchia** [comment]
Assigning to you for QA and closing.

**Comment by DinisCruz** [comment]
done
