### ISSUE TITLE
Add new icons to Getting Started summary element

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#722]
![screen shot 2015-04-22 at 10 56 51 am](https://cloud.githubusercontent.com/assets/4547737/7265504/54e8941c-e8de-11e4-8af2-506dea3c789a.png)

We still have the old icons in here.

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-04-22 at 11 11 02 am](https://cloud.githubusercontent.com/assets/4547737/7265640/4c59ef92-e8e0-11e4-8fc2-f44dc2c13c2c.png)
![screen shot 2015-04-22 at 11 11 06 am](https://cloud.githubusercontent.com/assets/4547737/7265641/4c5d939a-e8e0-11e4-8042-14549d3107b3.png)
![screen shot 2015-04-22 at 11 11 09 am](https://cloud.githubusercontent.com/assets/4547737/7265642/4c625592-e8e0-11e4-8d6b-373ce36d9c7e.png)

**Comment by luchia** [comment]
I'll create a PR on my last day this week with this included.

**Comment by luchia** [comment]
Created a PR. Assigning to @roman87 for QA.

**Comment by DinisCruz** [comment]
Added to https://github.com/TeamMentor/TM_4_0_Design/issues/719

**Comment by roman87** [comment]
Icons are well received. Closing.
