### ISSUE TITLE
Wire up the Flare production pages

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#724]
As seen here https://github.com/TeamMentor/TM_4_0_Design/issues/702#issuecomment-93606853

@luchia I'm opening this here since it's more focused than #702 (which I'm about to close)

**Comment by roman87** [comment]
This is a dupe of #618 no :)?

**Comment by DinisCruz** [comment]
Yeah we can use #618

**Comment by roman87** [comment]
Closing as dupe of #618
