### ISSUE TITLE
Refactor ArticleHTML and Search Artifacts creation out of the GraphDB

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#727]
This is something needs to happen since the article html and search artifacts are dependent on the Lib_UNO changes, and not on the GraphDB

This will also improve the current deployment process and help to test https://github.com/TeamMentor/TM_4_0_Design/issues/180 and https://github.com/TeamMentor/TM_4_0_Design/issues/705

**Comment by DinisCruz** [comment]
Done with latest push to GraphDB 

Code that does the transformation is at https://github.com/TeamMentor/TM_4_0_JSON_Data

**Comment by DinisCruz** [comment]
Added to https://github.com/TeamMentor/TM_4_0_Design/issues/719

**Comment by roman87** [comment]
This works quite well, even locally. closing.
