### ISSUE TITLE
Seaching for "java" (lowercase) causes a browser failure. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#729]
Searching for:
http://localhost:1337/search?text=java

Causes:

![selection_181](https://cloud.githubusercontent.com/assets/1326120/7351706/e0c298e4-ecd4-11e4-8ddb-5534c8f2dd5c.png)

**Comment by DinisCruz** [comment]
Humm, I can't replicate this locally 

![image](https://cloud.githubusercontent.com/assets/656739/7370745/35b46a8c-edb4-11e4-8610-62d66b970ea8.png)

Were there any errors in the logs?

@michaelhidalgo can you reproduce?

**Comment by roman87** [comment]
really weird, I can't reproduce it anymore. There were no errors and it was only happening on lowercase "java" not on "Java" @michaelhidalgo give it a shot, if you can't reproduce it then lets close it, but lets keep an eye on something like this.

**Comment by michaelhidalgo** [comment]
Hey, I was not able to reproduce it either. I searched for several words and I stopped and started the instances again.

I think we can close it and keep an eye on that if it happens again.
