### ISSUE TITLE
Create a release version of 3.6

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#731]

**Comment by michaelhidalgo** [comment]
I've generated a release version, once merged, we will need to merge it from TM 3.6_Dev into TM 3.6_Release

https://github.com/TeamMentor/Dev/pull/177

**Comment by DinisCruz** [comment]
merged

**Comment by roman87** [comment]
Great, @michaelhidalgo can you merge it into 3.6_Release and into master?

**Comment by michaelhidalgo** [comment]
I sent a PR to merge it into master https://github.com/TeamMentor/Dev/pull/178.

I think that 3.6_Release is quite behind the current version and there will be issues merging it.

**Comment by michaelhidalgo** [comment]
This is done. https://github.com/TeamMentor/Dev/pull/178

**Comment by roman87** [comment]
Done. Closing
