### ISSUE TITLE
Formatting issue on the search bar

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#732]
As you can see when searching on the search results page, the search bar doesn't seem to have enough room for the text.

![selection_182](https://cloud.githubusercontent.com/assets/1326120/7352793/96b6ab52-ecdc-11e4-8e1a-1192680f5271.png)

**Comment by luchia** [comment]
I think I got it (I couldn't recreate it on my machine) -

![screen shot 2015-04-28 at 12 08 48 pm](https://cloud.githubusercontent.com/assets/4547737/7361636/5bef5640-ed9f-11e4-8d34-02704a9b7218.png)

**Comment by DinisCruz** [comment]
Added to https://github.com/TeamMentor/TM_4_0_Design/issues/719

**Comment by roman87** [comment]
Yep, Looks good now.
![selection_183](https://cloud.githubusercontent.com/assets/1326120/7375341/dbd4ea5e-eda5-11e4-922f-3353d16dd1ca.png)
