### ISSUE TITLE
Add support for simple /a/{ref} article navigation

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#738]
Since I've seen this done on multiple websites and it took me less than 5m to add, I just added the ability to link to article using a simple */a* prefix

* http://localhost:1337/a/1fbc926e6752
* http://localhost:1337/a/How-to-Test-for-Cross-Site-Scripting-Vulnerabilities
* http://localhost:1337/a/article-1fbc926e6752

![image](https://cloud.githubusercontent.com/assets/656739/7402106/36af06c8-eec1-11e4-8708-a8b019f52650.png)

Here is the code that represent all mappings currently possible for articles

```coffee
  app.get "/a/:ref"             , checkAuth, articleController('article')
  app.get "/article/:ref/:title", checkAuth, articleController('article')
  app.get "/article/:ref"       , checkAuth, articleController('article')
  app.get "/articles"           , checkAuth, articleController('articles')
```

**Comment by DinisCruz** [comment]
@tekgirl77 can you add this case to the existing **article** unit tests

**Comment by michaelhidalgo** [comment]
that's a cool feature.

**Comment by roman87** [comment]
I thought we were not going to support the 2nd example?

**Comment by DinisCruz** [comment]
ok done

Removed the ability to resolve an article using its title (dashed or not)

The actual code that was doing it was:

![image](https://cloud.githubusercontent.com/assets/656739/7572318/1c621140-f815-11e4-8828-dc396c0416a0.png)

and

![image](https://cloud.githubusercontent.com/assets/656739/7572321/222a7478-f815-11e4-86ac-17d577521940.png)

**Comment by roman87** [comment]
Works as expected.
