### ISSUE TITLE
CSS prob with List items in article view

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#741]
@luchia there is an alignment prob with the css in the articles, where the bullet list items are showing too much to the left, see for example

https://beta.teammentor.net/article/764f120e3972/Using-Stored-Procedures-for-Secure-Database-Access

![image](https://cloud.githubusercontent.com/assets/656739/7446940/d96db626-f1e0-11e4-875a-f295da970d8c.png)

https://beta.teammentor.net/article/1fbc926e6752/How-to-Test-for-Cross-Site-Scripting-Vulnerabilities

![image](https://cloud.githubusercontent.com/assets/656739/7446942/e85ece90-f1e0-11e4-81a8-da4816776045.png)

**Comment by roman87** [comment]
Good catch.

**Comment by luchia** [comment]
Yup, I already caught it on my branch - 

![screen shot 2015-05-05 at 5 13 28 am](https://cloud.githubusercontent.com/assets/4547737/7460323/7cef53d6-f2e5-11e4-8e67-8087d96be1b6.png)
![screen shot 2015-05-05 at 5 13 30 am](https://cloud.githubusercontent.com/assets/4547737/7460322/7ceefeb8-f2e5-11e4-9322-5090426c2524.png)

Will create a PR shortly.

**Comment by luchia** [comment]
This has been fixed in my PR. Marking QA and assigning to Roman.

**Comment by DinisCruz** [comment]
@luchia I was merging and noticed a that the **ol** (ordered list) also need fixing .See for example on http://localhost:1337/article/000000010f15/URLs-Passed-to-the-EventSource-Constructor-are-Validated

![image](https://cloud.githubusercontent.com/assets/656739/7490278/c81c6348-f3d6-11e4-9625-994fcd46ea91.png)

So I added an extra  css mapping for it 

```css
#article ul {
  padding: 10px;
  margin: 20px;
}
#article ol {
  padding: 10px;
  margin: 20px;
}
```

and it looks better now (can you double check)

![image](https://cloud.githubusercontent.com/assets/656739/7490398/e105e162-f3d7-11e4-8ff9-0a9200e8dd13.png)

**Comment by DinisCruz** [comment]
Code (and latest Lucy branch) is on dev

**Comment by roman87** [comment]
This looks good. Closing.
