### ISSUE TITLE
Minor alignment issue on search page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#747]
Doesn't happen on all icons. See Web App logo below:
![image](https://cloud.githubusercontent.com/assets/656739/7464020/ae409cf8-f2b6-11e4-99e4-461b8f066965.png)

**Comment by roman87** [comment]
This also happens on the index page

**Comment by luchia** [comment]
This doesn't happen with the new icons -

![screen shot 2015-05-06 at 8 50 14 am](https://cloud.githubusercontent.com/assets/4547737/7484516/f44bdb10-f3cc-11e4-92dc-9bf6d1837ca9.png)

**Comment by roman87** [comment]
I'll take this to QA

**Comment by roman87** [comment]
Fixed.
