### ISSUE TITLE
Create Icons for "Phase" as well

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#750]
With latest feedback, we should create icons for "Phase" in the same way we do technology and type.
How long will this take?

**Comment by luchia** [comment]
Another week I would imagine. I'll add it to #634, I still have a heap of Flare icons to do.

**Comment by luchia** [comment]
Are we going to add these to the articles? Because if so then I think I need to revisit where the icons are positioned.

**Comment by luchia** [comment]
Here we are -

![screen shot 2015-05-06 at 7 09 09 am](https://cloud.githubusercontent.com/assets/4547737/7483000/d7fb3ea0-f3be-11e4-9aec-7bb15189b674.png)

@roman87, can you please let me know if you want these displayed on the article (both in the article view and the list view) because I will need to re-position the icons I think.

**Comment by luchia** [comment]
I've added them to the list view and the article itself. I needed to update the design as the way it was looked unbalanced -
![screen shot 2015-05-06 at 9 49 29 am](https://cloud.githubusercontent.com/assets/4547737/7485452/5f905d36-f3d9-11e4-8f20-5d5ebfd7f102.png)
![screen shot 2015-05-06 at 9 49 17 am](https://cloud.githubusercontent.com/assets/4547737/7485457/6734070e-f3d9-11e4-806a-a5294e571c56.png)

This is the list view which is very similar to Flare - this is important as we want them to look alike as much as possible.
![screen shot 2015-05-06 at 10 16 32 am](https://cloud.githubusercontent.com/assets/4547737/7485446/4b8787b0-f3d9-11e4-92b1-40382b2730a0.png)
![screen shot 2015-05-06 at 10 17 43 am](https://cloud.githubusercontent.com/assets/4547737/7485447/4b893ff6-f3d9-11e4-97d4-ebe0218e25df.png)

Then the article view has a minor change for better readability -
![screen shot 2015-05-06 at 10 21 24 am](https://cloud.githubusercontent.com/assets/4547737/7485477/b0a22394-f3d9-11e4-8375-47b6df929a4f.png)

**Comment by luchia** [comment]
Marking as QA and I will create a PR at the end of my week.

**Comment by roman87** [comment]
Ok I am not getting why we added the green titles to the article list?

**Comment by luchia** [comment]
Removing the styling, it was brought over from Flare -

![screen shot 2015-05-07 at 8 49 02 am](https://cloud.githubusercontent.com/assets/4547737/7505458/eef6589c-f495-11e4-859a-a6f07b37f1c7.png)
![screen shot 2015-05-07 at 8 49 06 am](https://cloud.githubusercontent.com/assets/4547737/7505459/ef02ae4e-f495-11e4-9cfc-f33980c5bcad.png)

I did still have to change the design slightly to allow for the extra icon, it couldn't be avoided.

**Comment by DinisCruz** [comment]
Added to https://github.com/TeamMentor/TM_4_0_Design/issues/739

**Comment by roman87** [comment]
This is done.
