### ISSUE TITLE
Font size issue on the about page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#751]
The first paragraph of the about page is in a font larger than the rest of the paragraphs. 
![selection_209](https://cloud.githubusercontent.com/assets/1326120/7479538/56cdc368-f330-11e4-9d1e-32856bace842.png)

Is that on purpose?

**Comment by luchia** [comment]
Yes, one's a h5, the other a paragraph. To make the distinction clearer, I have changed the first part of the text to a h4 -

![screen shot 2015-05-06 at 7 12 39 am](https://cloud.githubusercontent.com/assets/4547737/7483075/5eeb54d6-f3bf-11e4-90f2-02db5e422856.png)
![screen shot 2015-05-06 at 7 12 41 am](https://cloud.githubusercontent.com/assets/4547737/7483076/5f19a1e2-f3bf-11e4-83bb-ac6bd59b4aab.png)
