### ISSUE TITLE
Refactor TM library import from TM_Graph into TM_Json_Data

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#755]
Following on the last refactoring where the Lib_UNO to Lib_Uno-json was moved into the TM_4_0_JSON_Data repo, the next step is to actually move the creation of the GraphDB triplets into that repo to.

This will have tons of good side effects, specially the fact that there will be no need to run the GraphDB unit tests to load the data (it will also allow for the much faster reload/reset of the TM_Graph data)

This is needed for https://github.com/TeamMentor/TM_4_0_Design/issues/746

**Comment by DinisCruz** [comment]
opps this is not fully done

(it was the commit reference to 'fix' that closed this issue)

**Comment by roman87** [comment]
@DinisCruz I assume this is done now and can be closed?
