### ISSUE TITLE
How to connect to Slack

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#761]
Step 1) go to https://securityinnovation.slack.com/

![image](https://cloud.githubusercontent.com/assets/656739/7524639/4c22b41a-f4fb-11e4-9b92-e08a3da236f1.png)

.... (can somebody paste other steps below)

**Comment by tkrpata** [comment]
![image](https://cloud.githubusercontent.com/assets/1203492/7526708/ee956478-f4c8-11e4-80e1-13f85b4c9511.png)

![image](https://cloud.githubusercontent.com/assets/1203492/7526713/f90a5170-f4c8-11e4-9a60-dd6b92f28a9a.png)

**Comment by tkrpata** [comment]
![image](https://cloud.githubusercontent.com/assets/1203492/7526724/2347e5b0-f4c9-11e4-974a-939da8534ff3.png)

**Comment by tkrpata** [comment]
I'm in. Very straightforward.

**Comment by luchia** [comment]
That's how easy it should be to sign up for TM.

**Comment by roman87** [comment]
Awesome! Thanks @tkrpata

**Comment by roman87** [comment]
This was made into a wiki page https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-sign-up-and-use-Slack-for-colaboration
Closing.
