### ISSUE TITLE
Set up Analytics goals

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#763]
For testing and user acquisition purposes.

**Comment by roman87** [comment]
https://support.google.com/analytics/answer/1012040?hl=en

**Comment by luchia** [comment]
So we currently have 2 goals -

![screen shot 2015-05-17 at 11 20 29 am](https://cloud.githubusercontent.com/assets/4547737/7668634/c50f3e1a-fc86-11e4-8b0d-08e4ac94746f.png)

If anyone can think of any others, please let me know.

**Comment by romichg** [comment]
- [x] Time on reading an article
- [x] Time on the search results page
- [x] number of search result page hits (i.e number of searches)
- [x] search strings (if we can get them)
- [ ] function of search string + time on search result page 
- [ ] function of search string + time on search page + number of open articles + time on each one :)
- [ ] number of failed login attempts (per user would be nice)
- [x] time on the index page
- [x] filter selections (if we can get them)
- [ ] function of filter selections + time on index page per selection

Edited by Lucy - formatting.

**Comment by luchia** [comment]
Some of these are more things to track rather than goals -

* Time reading an article
* Time on search results page
* Number of search result page hits
* Search strings
* Filter selections
* Time on Landing Page Index

Some of them can't be tracked by Analytics - 

* Failed login attempts (needs to be tracked by us)
* The ones relating to comparing a search string to time spent on pages

What I've done is created a dashboard for with all of these, as well as set up all the goals that I could. I have also set up an auto-email that is sent to TM-dev once every week with these stats for everyone to see. This will hopefully drive ideas for improving the application and it's numbers over time.

**Comment by roman87** [comment]
awesome!

**Comment by roman87** [comment]
This is closely related to #534  
Looking at the data it doesn't correlate well with what we know. For example there is no way we had over 100 new users. 
As discussed in https://github.com/TeamMentor/TM_4_0_Design/issues/534#issuecomment-104474108 we should closely correlate our acquisition methods to what we want and able to collect.

**Comment by luchia** [comment]
As per #534, we've decided collectively to use another service for analytics over GA. Reasons were discussed in last weeks meeting (I wasn't in attendance) but relate specifically to getting the data from client-side instances of TM. GA isn't a nice solution for collecting this data.

Close?

**Comment by michaelhidalgo** [comment]
@luchia  we are using Piwik Analytics for tracking data. On top of Piwik, we can set up goals too.

Here is a video about goals http://piwik.org/docs/video-tracking-goals/

**Comment by luchia** [comment]
@michaelhidalgo How do I set up the goals? Or are we not at that stage yet?

**Comment by luchia** [comment]
I've managed to get this somewhat working. Piwik is a PITA for some things. This is our custom dashboard -

![screen shot 2015-06-09 at 4 42 42 am](https://cloud.githubusercontent.com/assets/4547737/8042349/11e95314-0e62-11e5-9f43-976f3fea1d69.png)
![screen shot 2015-06-09 at 4 42 49 am](https://cloud.githubusercontent.com/assets/4547737/8042348/11e69fac-0e62-11e5-8cab-fc07ee9b95fa.png)

Email reports have been set up to send out but they're not pretty or particularly easy to read -

![screen shot 2015-06-09 at 4 44 14 am](https://cloud.githubusercontent.com/assets/4547737/8042370/3928ce0a-0e62-11e5-8e4c-a629339ec0d8.png)
![screen shot 2015-06-09 at 4 44 19 am](https://cloud.githubusercontent.com/assets/4547737/8042371/392a6b2a-0e62-11e5-9c73-c6b231af57da.png)
![screen shot 2015-06-09 at 4 44 22 am](https://cloud.githubusercontent.com/assets/4547737/8042372/392abae4-0e62-11e5-974a-b9f161074561.png)
![screen shot 2015-06-09 at 4 44 25 am](https://cloud.githubusercontent.com/assets/4547737/8042373/392b40d6-0e62-11e5-8a4b-896eb849687e.png)

I also had a lot of issues trying to set up basic goals, like times spent on pages. This is because Piwik doesn't have that feature built in yet (the FR has been sitting in their issues list for over 4 years).

**Comment by romichg** [comment]
Done in Piwik,  Related to: #934
