### ISSUE TITLE
Icon for Android is not looking good

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#777]
![selection_225](https://cloud.githubusercontent.com/assets/1326120/7578108/4ddbe8be-f81e-11e4-84ad-0509880d00db.png)

**Comment by luchia** [comment]
There was a bug but I had already pushed and fixed this with my PR. This shouldn't be an issue anymore.

**Comment by luchia** [comment]
May need to clear your cache as I had to redo the font file when I made the icons colours.

**Comment by roman87** [comment]
Fixed as well
