### ISSUE TITLE
HTML5 icon does not look right

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#778]
![selection_225](https://cloud.githubusercontent.com/assets/1326120/7578133/dbd957b4-f81e-11e4-9fc0-5016e6eeb153.png)

**Comment by DinisCruz** [comment]
Mine look good

![image](https://cloud.githubusercontent.com/assets/656739/7578212/09c5a58a-f84a-11e4-9818-896059dd12c8.png)

**Comment by luchia** [comment]
There was a bug but I had already pushed and fixed this with my PR. This shouldn't be an issue anymore.

**Comment by luchia** [comment]
May need to clear your cache as I had to redo the font file when I made the icons colours.

**Comment by roman87** [comment]
Yep this one is fixed.
