### ISSUE TITLE
Library import is not handling folders inside folders

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#779]
The prob is here https://github.com/TeamMentor/TM_4_0_JSON_Data/blob/master/src/graph/TM-Guidance.coffee#L115-L117 which is not loading child folders.

This is now a prob since we have those folders-inside-folders structure in the latest version of Lib_Uno:

https://github.com/TMContent/Lib_UNO/blob/master/UNO.xml#L3048-L3050

**Comment by DinisCruz** [comment]
I just pushed to Lib_UNO-json and update , can you take a look at it?

**Comment by DinisCruz** [comment]
actually , wait a sec

**Comment by DinisCruz** [comment]
ok, try now

**Comment by michaelhidalgo** [comment]
Ok :)

**Comment by DinisCruz** [comment]
Just merged content https://github.com/TMContent/Lib_UNO-json/pull/9

**Comment by DinisCruz** [comment]
Check this out, we have Standards

![image](https://cloud.githubusercontent.com/assets/656739/7597513/f1c27e7a-f8eb-11e4-86de-a2f873b1eaf0.png)

![image](https://cloud.githubusercontent.com/assets/656739/7597519/fad1a0ea-f8eb-11e4-9f42-5e677a6bf74f.png)

![image](https://cloud.githubusercontent.com/assets/656739/7597536/133691c2-f8ec-11e4-8a66-b6fe3765bc10.png)

![image](https://cloud.githubusercontent.com/assets/656739/7597543/1ea1a7fe-f8ec-11e4-8423-5286e73e78c0.png)

**Comment by michaelhidalgo** [comment]
It seems like there might be an issue when searching for PCI DSS lower and upper case:

![screen shot 2015-05-12 at 14 27 04](https://cloud.githubusercontent.com/assets/1732035/7597827/653c8f46-f8b3-11e4-83c4-eece2a76f884.png)

Vrs : 

![screen shot 2015-05-12 at 14 26 48](https://cloud.githubusercontent.com/assets/1732035/7597828/653e36d4-f8b3-11e4-92e6-cc60dc30ab0e.png)

**Comment by roman87** [comment]
Yep, that is because tagging is case sensitive. Same reason why Java and java produce different results. Should we make it case insensitive?

**Comment by DinisCruz** [comment]
can we open a different issue for that , since that is a different problem and I need to hunt that bug separately (I also noticed that the .NET and .net also had different results)

**Comment by DinisCruz** [comment]
but loading data from folders within folders is working one (to one level deep, so at the moment folders within folders within folders are not supported)

**Comment by roman87** [comment]
Another related issue  #787 
However this specific issue is fixed now.
