### ISSUE TITLE
Technology Independent and WCF icons are the same.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#780]
![selection_226](https://cloud.githubusercontent.com/assets/1326120/7580104/6acfe7d6-f83c-11e4-9720-f5e935d560b6.png)

**Comment by luchia** [comment]
What branch are you on? On Dev, this isn't showing? -

![screen shot 2015-05-13 at 7 36 21 am](https://cloud.githubusercontent.com/assets/4547737/7599105/ce6e2b84-f942-11e4-8db5-90b28f265adb.png)

**Comment by luchia** [comment]
And the code is correct -

![screen shot 2015-05-13 at 7 42 43 am](https://cloud.githubusercontent.com/assets/4547737/7599229/aad43960-f943-11e4-986d-281db935d291.png)

**Comment by DinisCruz** [comment]
This is fixed with https://github.com/TeamMentor/TM_4_0_Design/commit/01b7a88b3456e8975f4846e53f338f0e020fc44b

![image](https://cloud.githubusercontent.com/assets/656739/7600175/cb75c320-f900-11e4-82a3-8ea722055ffd.png)

**Comment by luchia** [comment]
Thank you, Dinis!

**Comment by roman87** [comment]
This is fixed.
