### ISSUE TITLE
Automatically log in the user upon sign-up (Jade)

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#781]
I don't really see a reason why the user should enter his credentials again, after he/she signed up.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/819

**Comment by DinisCruz** [comment]
Added to https://github.com/TeamMentor/TM_4_0_Design/issues/842

**Comment by romichg** [comment]
done.
