### ISSUE TITLE
Bunch of files are missing the <Tag> metafield

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#782]
There is a bunch of files (emailed separately) that are missing the <Tag> metafield.
How hard it would be to add the metafield with the script. The field for all those files should read
```<Tag>ASP.NET,ASP.NET 4.0,ASP</Tag>```

All the are in the clone of tm-sme/Lib_Uno

**Comment by DinisCruz** [comment]
nice, we needed those changes

but, you actually also hit on a bug with the tags, which I'm working on the fix now

**Comment by michaelhidalgo** [comment]
Fixed in referenced commit

https://github.com/tm-sme/Lib_UNO/pull/7

**Comment by roman87** [comment]
Fixed.
