### ISSUE TITLE
Expose the <Tag> field in the 3.6 editor interface

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#783]
Right now it is not exposed so it is hard to tag articles.

**Comment by michaelhidalgo** [comment]
Fixed in referenced Pull Request 
https://github.com/tm-sme/Lib_UNO/pull/7

**Comment by roman87** [comment]
This is not actually the issue :). The issue to expose in the TM3.5 editor interface the Tag metadata field. And it can wait until 4.1

**Comment by michaelhidalgo** [comment]
Yeah that's true :), I confuse the issue.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/Dev/pull/179

**Comment by DinisCruz** [comment]
merged

**Comment by romichg** [comment]
Done
