### ISSUE TITLE
Support legacy link format in 4.0

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#784]
Turns out we do need to support the legacy format in 4.0

```
https://teammentor.net/teamMentor/open/c57eaf7a-f02e-4172-8221-38fb47dbf402#load:47a10a30-15ad-4cfd-bf82-00e9bb2037f6&showFilters:false&showTree:false&centerGuidanceItems:true
```

Since we don't really have the "view" layout anymore, we should just show the article. This is needed because we have given TP courses to customers and cannot change the links on those.

**Comment by DinisCruz** [comment]
@michaelhidalgo can you do this one

**Comment by DinisCruz** [comment]
take a look at the solution at https://github.com/TeamMentor/TM_4_0_Design/commit/01b7a88b3456e8975f4846e53f338f0e020fc44b

**Comment by michaelhidalgo** [comment]
@DinisCruz I think you referenced the wrong site in the previous link!

**Comment by DinisCruz** [comment]
Yeah :)

**Comment by DinisCruz** [comment]
this is the one https://cloud.githubusercontent.com/assets/656739/7600548/3051a180-f904-11e4-9497-8fc90ede884b.png

**Comment by DinisCruz** [comment]
done

now http://localhost:1337/teamMentor/open/c57eaf7a-f02e-4172-8221-38fb47dbf402#load:47a10a30-15ad-4cfd-bf82-00e9bb2037f6&showFilters:false&showTree:false&centerGuidanceItems:true

will redirect to

http://localhost:1337/article/c57eaf7a-f02e-4172-8221-38fb47dbf402#load:47a10a30-15ad-4cfd-bf82-00e9bb2037f6&showFilters:false&showTree:false&centerGuidanceItems:true

**Comment by roman87** [comment]
Perfect. Works great.
