### ISSUE TITLE
Need an icon for "Principle"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#786]
![selection_229](https://cloud.githubusercontent.com/assets/1326120/7599289/c212567c-f8ce-11e4-8b91-8c021c1ba2eb.png)

**Comment by luchia** [comment]
### Principle

> a fundamental truth or proposition that serves as the foundation for a system of belief or behaviour or for a chain of reasoning.

![screen shot 2015-05-13 at 8 46 25 am](https://cloud.githubusercontent.com/assets/4547737/7600217/93aa00e0-f94c-11e4-8a53-ac5b4b0147a9.png)
![screen shot 2015-05-13 at 8 46 34 am](https://cloud.githubusercontent.com/assets/4547737/7600218/93d60370-f94c-11e4-8182-84bb029dd6fe.png)

**Comment by DinisCruz** [comment]
its there now 

![](https://cloud.githubusercontent.com/assets/656739/7600793/ef66247c-f906-11e4-978a-6192456a2b90.png)

**Comment by roman87** [comment]
This is done.
