### ISSUE TITLE
Standards articles are not part of the total count and principle type is not shown. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#787]

**Comment by roman87** [comment]
Updating this issue as Standards articles (part of folder inside a folder) are not shown in search results.

Article exists in index.

![selection_288](https://cloud.githubusercontent.com/assets/1326120/7664773/a76f8c38-fb65-11e4-8027-c2d971c0593f.png)

Searching for partial title of the article does not produce the article on the list of search results. 

![selection_289](https://cloud.githubusercontent.com/assets/1326120/7664774/c0fa8b1c-fb65-11e4-91df-82d25d038802.png)

**Comment by DinisCruz** [comment]
Still hunting for the source of the bug, but here is a test that contains a bad result

```coffee
  it.only '#787 - Standards articles are not part of the total count and principle type is not shown.', (done)->
    using query_Mappings, ->
      @.get_Queries_Mappings (mappings)=>
        mappings['query-6234f2d47eb7'].articles.assert_Size_Is 1751 # Index
        mappings['query-ca4b67378adb'].articles.assert_Size_Is 329  # Standards
        mappings['query-b53e272fa197'].articles.assert_Size_Is 106  # CWE

        # In the results above the first one is wrong (it should be above 2000)
        done()
```

**Comment by DinisCruz** [comment]
OK, I think the prob is here https://github.com/TeamMentor/TM_4_0_JSON_Data/blob/aead8d9d4fb7e6ab585ee8166035bfe6d826d034/src/graph/TM-Guidance.coffee#L90 where the 'contains-article' graph mapping is only happening to views-inside-folders (not and not to views-inside-folders-inside-folders)

I spotted this because I noticed that the **Standards** child queries (like **CWE** or **PCI-DSS**) did not had any **contains-article** values:

![image](https://cloud.githubusercontent.com/assets/656739/7668393/085827f8-fc2e-11e4-8fd1-f715333ea200.png)

**Comment by roman87** [comment]
Cool, got catch.

**Comment by DinisCruz** [comment]
OK, I think I finally found the place to fix this, can you take it for a test drive?

Once the GraphDB is updated (that is where the fix is) you don't need to rebuild the db, but you will need to delete the **data_cache** folder (since that contains the cached json for the index/queries).

**Comment by roman87** [comment]
Still not working right. They are not showing up in search. Searching for "Least Privilege" does not produce the article "Use the Principle of Least Privilege' from CWE in search results
![selection_300](https://cloud.githubusercontent.com/assets/1326120/7683518/ab0b1fda-fd4d-11e4-9b4e-86c3ae1eedcb.png)
![selection_301](https://cloud.githubusercontent.com/assets/1326120/7683520/adecb9ac-fd4d-11e4-82a4-c87e43b30cd3.png)

**Comment by DinisCruz** [comment]
That is a separate prob, I've just opened https://github.com/TeamMentor/TM_4_0_Design/issues/813 to track it

**Comment by roman87** [comment]
Ok makes sense.  Then this one is fixed.
