### ISSUE TITLE
Create a default icon as a fallback for new filter types

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#789]

**Comment by luchia** [comment]
I also need these icons (for Flare) -

* [ ] Fallback filter icon
* [ ] Design icon
* [ ] X (Close)
* [ ] Tick

**Comment by luchia** [comment]
Fallback filter -
![screen shot 2015-05-21 at 5 22 23 am](https://cloud.githubusercontent.com/assets/4547737/7734448/65524a1c-ff79-11e4-92bf-a1de53d98426.png)

Design -
![screen shot 2015-05-21 at 5 22 19 am](https://cloud.githubusercontent.com/assets/4547737/7734446/654f6054-ff79-11e4-8ae6-3cf1ee28ff08.png)

X (Close) -
![screen shot 2015-05-21 at 5 22 26 am](https://cloud.githubusercontent.com/assets/4547737/7734449/6552c726-ff79-11e4-9100-8ede82b44d79.png)

Tick -
![screen shot 2015-05-21 at 5 22 15 am](https://cloud.githubusercontent.com/assets/4547737/7734447/6551b0b6-ff79-11e4-9807-f6a43dc31745.png)

**Comment by luchia** [comment]
PR created.

**Comment by luchia** [comment]
Taking it back, I need a user icon for Flare.

**Comment by luchia** [comment]
User icon -

![screen shot 2015-05-21 at 10 18 33 am](https://cloud.githubusercontent.com/assets/4547737/7739366/c590f56c-ffa2-11e4-9742-3f75cc7e676c.png)

PR created (again).

**Comment by roman87** [comment]
I think the inktip is still a bit off. 
![inktip](https://cloud.githubusercontent.com/assets/1326120/7750856/9c2044a6-ffa4-11e4-8ff8-1badf1cf3bb5.jpeg)

**Comment by luchia** [comment]
Maybe the pen tip isn't working at all. Other ideas -

![image](https://cloud.githubusercontent.com/assets/4547737/7922418/7b42c64c-08ef-11e5-827e-42fd9d396b5f.png)
![image](https://cloud.githubusercontent.com/assets/4547737/7922423/83b769ea-08ef-11e5-96df-596a8895c176.png)
![image](https://cloud.githubusercontent.com/assets/4547737/7922426/89637ff0-08ef-11e5-9434-3be8caeb30e7.png)
![image](https://cloud.githubusercontent.com/assets/4547737/7922431/90a430ac-08ef-11e5-9d18-fe7b17b5175d.png)

**Comment by luchia** [comment]
@roman87, can you please let me know what you think about this one -

![screen shot 2015-06-04 at 1 44 34 pm](https://cloud.githubusercontent.com/assets/4547737/7976550/efba9212-0abf-11e5-9ac9-596939c05ff8.png)
![screen shot 2015-06-04 at 1 44 43 pm](https://cloud.githubusercontent.com/assets/4547737/7976551/efbb5896-0abf-11e5-904d-e565c2dcc480.png)

**Comment by luchia** [comment]
I also needed a curated content icon for Flare, so I made this -

![screen shot 2015-06-11 at 3 25 25 pm](https://cloud.githubusercontent.com/assets/4547737/8100373/5ad3a2d0-104e-11e5-99d8-6321e4507d59.png)
![screen shot 2015-06-11 at 3 25 32 pm](https://cloud.githubusercontent.com/assets/4547737/8100372/5ad339d0-104e-11e5-9233-659d8e8dc3c1.png)

**Comment by luchia** [comment]
I've just added all the files to the seperate repos as well as to the TM_4_0_Design. I had to build it on the old one because I can't see what i'm working on in the new ones. Assigning to Roman for QA.
