### ISSUE TITLE
removing button transition (from scss)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#79]
Hi Lucy, can you remove the button transitions from the SCSS files

Here is what it looks like when it is done on the CSS: https://github.com/TeamMentor/TM_4_0_Design/commit/fa523072b15e74600664532241909b5f29275ed3

**Comment by roman87** [comment]
@luchia  can you check this again?

**Comment by DinisCruz** [comment]
yeah, latest version does have this behaviour (i.e it is fixed)
