### ISSUE TITLE
Search for 'SQL Injection' returns LDAP result first

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#790]
I just noticed this

![image](https://cloud.githubusercontent.com/assets/656739/7601074/e2241e6a-f909-11e4-8d1a-1f974fa457d5.png)

so I make a couple minor changes to the word scores and it is much better (I made the **title** to have **30** and the **span** to have 0)

It is not perfect, but it is much better

![image](https://cloud.githubusercontent.com/assets/656739/7601087/0c0b2552-f90a-11e4-9f2f-4dcc75771d78.png)

**Comment by DinisCruz** [comment]
For reference here is the current formula (before the tags mappings are applied)

```coffee
              for tag in data.where
                score = 1
                switch tag
                  when 'title'
                    score = 30
                  when 'h1'
                    score = 5
                  when 'h2'
                    score = 4
                  when 'em'
                    score = 3
                  when 'b'
                    score = 3
                  when 'a'
                    score = -4
                  when 'span'
                    score = 0

                result.score += score
```

**Comment by roman87** [comment]
This looks much better. I still think we need to revisit the formula and add coefficients to the weight. For example if only one word matches a title then its a "30" but if 2 words match a title then it should not be "60" but a bit more.
