### ISSUE TITLE
When I search for exact title of the article, the article does not always come up first

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#792]
For example, searching for "structured exception handling is used" brings up the actual article 3d or so. 
I think we need to multiply the the title score by some coefficient of the number of words found in the title.

**Comment by DinisCruz** [comment]
I think this is fixed now with the minor fix I pushed yesterday https://github.com/TeamMentor/TM_4_0_Design/issues/790

![image](https://cloud.githubusercontent.com/assets/656739/7609789/a44b32f8-f96e-11e4-9402-987b788b277b.png)

**Comment by DinisCruz** [comment]
I basically increased the points given to the title

**Comment by DinisCruz** [comment]
which now gives that article these scores

```json
  {
    "id": "article-66ba69662d18",
    "score": 238,
    "why": {
      "structured": {
        "p": 2,
        "ul": 1,
        "li": 1,
        "a": -4,
        "title": 30
      },
      "exception": {
        "p": 23,
        "ol": 13,
        "li": 14,
        "strong": 1,
        "pre": 2,
        "ul": 1,
        "a": -4,
        "title": 30
      },
      "handling": {
        "p": 5,
        "pre": 3,
        "ol": 3,
        "li": 4,
        "ul": 1,
        "a": -4,
        "title": 30
      },
      "is": {
        "p": 11,
        "ol": 7,
        "li": 7,
        "title": 30
      },
      "used": {
        "p": 1,
        "title": 30
      }
    }
  },
```

**Comment by roman87** [comment]
This works now.
