### ISSUE TITLE
Add a new route to '/help/article/:guid' to access Documentation links

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#801]
We need to support the route '/help/article/:guide' to be able to serve links from the documentation library.

**Comment by michaelhidalgo** [comment]
Fixed in the referenced Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/802

@DinisCruz , @roman87  can you guys please comment in this fix.

![screen shot 2015-05-15 at 17 58 22](https://cloud.githubusercontent.com/assets/1732035/7663710/da2ba41a-fb2c-11e4-84f9-733e559b3f70.png)

**Comment by DinisCruz** [comment]
Fix looked great :)

merged

**Comment by roman87** [comment]
Doesn't seem to be working. I used the JSON conversion too to get the Docs in place. However the links are still pointing to /article/GUID

![menu_293](https://cloud.githubusercontent.com/assets/1326120/7668331/932bbd96-fc00-11e4-930f-f7f7d5a0e473.png)

**Comment by michaelhidalgo** [comment]
Yes I can see the problem : 
This article http://localhost:1337/**help/article/738f8545-5818-45fb-9494-92ea795af257** contains a link inside : 

![screen shot 2015-05-17 at 06 24 43](https://cloud.githubusercontent.com/assets/1732035/7670320/86a0c424-fc5d-11e4-8ba3-aa92e97c9bea.png)

That link goes to **/article/323dae88-b74b-465c-a949-d48c33f4ac85"**

Which becomes 

![screen shot 2015-05-17 at 06 32 16](https://cloud.githubusercontent.com/assets/1732035/7670343/814278c8-fc5e-11e4-8488-20fa7f44c75a.png)

This happens because we have a route in place for the articles (except for the documentation library) that uses the format **/article/323dae88-b74b-465c-a949-d48c33f4ac85**

I believe this can easily fixed by : 

Modify 4 of the Documentation articles (those brand new that references another article) to link to the guid directly (without the /article/) : 

From :
![screen shot 2015-05-17 at 06 3545](https://cloud.githubusercontent.com/assets/1732035/7670380/4d7809e4-fc5f-11e4-8842-0d4344e73570.png)
To : 
![screen shot 2015-05-17 at 06 36 00](https://cloud.githubusercontent.com/assets/1732035/7670379/4d75c120-fc5f-11e4-8e3b-8be6e7892810.png)

Note that it does not disrupt the TEAM Mentor 3.5 editing capabilities (i.e it does not generate broken links)

![screen shot 2015-05-17 at 06 36 44](https://cloud.githubusercontent.com/assets/1732035/7670378/4d734d78-fc5f-11e4-9bf9-19489fb26502.png)

So back in TM 4.0, the link will be resolved as  : 
![screen shot 2015-05-17 at 06 42 29](https://cloud.githubusercontent.com/assets/1732035/7670396/068172d6-fc60-11e4-95de-61674e3e54b6.png)


@roman87 I can send a pull request with this change, it should be something really easy to do and it continue working on TM 3.5 so if we still need to modify the documentation it should not be an issue.

Please let m know what do you think!

**Comment by roman87** [comment]
@michaelhidalgo as discussed on slack, lets do it the way you suggest.

**Comment by michaelhidalgo** [comment]
Alright with Pull Request https://github.com/roman87/Lib_Docs/pull/3

**Comment by michaelhidalgo** [comment]
I've generated a release version for the Documentation Library https://github.com/TMContent/Lib_Docs-json
You should be able to clone this remo into ./.tmCache.

Make sure you remove the folder ./.tmCache and then create it again to avoid any cache issue.

**Comment by roman87** [comment]
Ok merged. Let me try the JSON

**Comment by roman87** [comment]
Ok this is working now. Good stuff.
