### ISSUE TITLE
Make TAGs case insenstive

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#803]
As explained in https://github.com/TeamMentor/TM_4_0_Design/issues/779#issuecomment-101429926
Tags in searches are currently case sensitive. That is why searching for "Java" produces different results than for "java" 
We should make it case insensitive.

**Comment by roman87** [comment]
As outlined in https://github.com/TMContent/Lib_UNO/issues/38#issuecomment-104724128
Users expect searches to be case insensitive. Lets bump this up. This should be an easy fix.

**Comment by DinisCruz** [comment]
done

**Comment by romichg** [comment]
fixed
