### ISSUE TITLE
Should we make URL case insensitive? 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#804]
As described https://github.com/TeamMentor/TM_4_0_Design/issues/726#issuecomment-102711425 and below, the URL, and specifically URL variables are case sensitive.  Should we make them case insensitive, so that /article and /Article and /artiCle are the same thing

**Comment by DinisCruz** [comment]
I don't think so (at least not for all params)

we might do it for specific cases, but it is good practice to keep these case-sensitive

**Comment by romichg** [comment]
closing due to TTL
