### ISSUE TITLE
Get rid of the first Docs page

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#805]
It is confusing and uneditable. Lets make the "Introduction to TM"  page the first page"

![selection_295](https://cloud.githubusercontent.com/assets/1326120/7668487/d620183c-fc09-11e4-9574-fa3be1777d8c.png)

**Comment by luchia** [comment]
I need someone to help me with the routing on this. @michaelhidalgo @DinisCruz, I have deleted the help-page and moved that pages contents into help-index. The branch I used is Issue_508.

**Comment by roman87** [comment]
I think @luchia means branch Issue_805 and not Issue_508 :)  there is no branch Issue_508 :)

**Comment by michaelhidalgo** [comment]
Yeah @roman87 is correct. Should we redirect the user to What is new in this release? as a start page in the docs now that the index is not longer there?


![screen shot 2015-05-17 at 11 23 54](https://cloud.githubusercontent.com/assets/1732035/7671312/58177574-fc87-11e4-8024-e8428ede37d4.png)

**Comment by roman87** [comment]
No, lets redirect the user to "Introduction to TEAM Mentor" I think this is more valuable for someone to see the first time they click on Docs link.

**Comment by michaelhidalgo** [comment]
Shouldn't we then switch items in the navigation too? It is just a thought :) 

![screen shot 2015-05-17 at 11 41 35](https://cloud.githubusercontent.com/assets/1732035/7671366/ea8ff500-fc89-11e4-804e-72ad29c87326.png)

**Comment by roman87** [comment]
Yea, good idea, lets do that.

**Comment by roman87** [comment]
Add done.. Great!!!
