### ISSUE TITLE
Alignment issue in docs

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#806]
Seems like lists are aligned incorrectly:
![selection_296](https://cloud.githubusercontent.com/assets/1326120/7668496/26c92c42-fc0a-11e4-9272-9647ec57f785.png)

**Comment by luchia** [comment]
This has been fixed on Issue_806 branch -

![screen shot 2015-05-17 at 10 58 14 am](https://cloud.githubusercontent.com/assets/4547737/7668586/b77921c4-fc83-11e4-835c-17c2f1005acb.png)

I created a PR.

**Comment by roman87** [comment]
The fix looks good. @DinisCruz it seems like its failing QA. I don't see why, can you take a look and merge?

**Comment by roman87** [comment]
This is fixed in Dev. Closing.
