### ISSUE TITLE
Links are not highlighted in Docs

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#807]
Quick Start Guide is a link. 
![selection_297](https://cloud.githubusercontent.com/assets/1326120/7668502/69e64e9c-fc0a-11e4-8c90-b742b5fd1bac.png)

**Comment by luchia** [comment]
This has been fixed on branch Issue_807 -

![screen shot 2015-05-17 at 11 02 33 am](https://cloud.githubusercontent.com/assets/4547737/7668595/3faab4fe-fc84-11e4-9d61-0ce0cc5ff5eb.png)

I have created a PR.

**Comment by roman87** [comment]
Fix looks good. @DinisCruz can you take a look at why the QA is failing and merge the PR. 
Thanks.

**Comment by roman87** [comment]
Fixed.
