### ISSUE TITLE
Go through CSS and tidy up

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#811]
https://validator.w3.org/
http://csslint.net/
Tidy up CSS (http://24ways.org/2014/naming-things/)
[CSS](https://en.bem.info/)
http://devilo.us/

* Alignment issue on all pages with #application div caused by margin-top.

**Comment by roman87** [comment]
Good idea.

**Comment by luchia** [comment]
Tidy up CSS (http://24ways.org/2014/naming-things/)

**Comment by luchia** [comment]
Started doing this for Flare while I wait for everyone else to catch up. Started with ~2k lines of code and we have 1600 atm. We'll also be able to reduce bloat when we move from CSS to SCSS.

**Comment by luchia** [comment]
This has been done for Jade. I will complete this once I have checked Flare relating to #874.

**Comment by luchia** [comment]
This has been finished for Flare.
