### ISSUE TITLE
Numbered list is still missaligned in Docs. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#812]
![selection_298](https://cloud.githubusercontent.com/assets/1326120/7682384/b9d1582a-fd45-11e4-83cb-f888258afc7b.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-05-19 at 7 54 56 am](https://cloud.githubusercontent.com/assets/4547737/7691246/6158ae0c-fdfc-11e4-926a-a4d2ba63f276.png)

And a PR created.

**Comment by michaelhidalgo** [comment]
This is how it looks like after updating it : 

![screen shot 2015-05-18 at 16 22 07](https://cloud.githubusercontent.com/assets/1732035/7691723/14c12b1e-fd7a-11e4-904f-94917fc33830.png)

**Comment by roman87** [comment]
Works well, great stuff!
