### ISSUE TITLE
Search for 'Least Privilege' does not produce the expected results

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#813]
See comment https://github.com/TeamMentor/TM_4_0_Design/issues/787#issuecomment-103088574

**Comment by DinisCruz** [comment]
This was a content issue, with the lasted data from Lib_UNO-json the search results

![image](https://cloud.githubusercontent.com/assets/656739/7687311/37066fda-fd94-11e4-821a-49e05eea511f.png)

with the expected principle to be there

![image](https://cloud.githubusercontent.com/assets/656739/7687328/4b4c6314-fd94-11e4-90e7-0c1c8aaf8713.png)

**Comment by roman87** [comment]
This is fixed.
