### ISSUE TITLE
Work with Brandon / Serge to replace 70715a36-8511-4cc5-b35f-e180a7ec2411

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#820]
Article 70715a36-8511-4cc5-b35f-e180a7ec2411 is linked from COD 213 course page 32
Since this article is obsolete and there are better articles that relate to the subject of the page, we need to replace the link in the TP course. Some candidates are

https://beta.teammentor.net/article/130b822d9611/Encrypt-Communication-Links
https://beta.teammentor.net/article/0ad910267202/Reduce-Application-Fingerprints
https://beta.teammentor.net/article/b983a9b0aee9/Partition-the-Application-Between-Public-And-Private-Domains
https://beta.teammentor.net/article/99c540427a22/Deny-All-Access-by-Default 

@SergeTruth  Can you pick the best one that relates to the subject of the page on the cours.e

**Comment by roman87** [comment]
We will use  c875eb4b-cb91-4c02-b51f-9f5b6dbd6db1  Know Your Binding Options 
for the link.

**Comment by romichg** [comment]
We will use  c875eb4b-cb91-4c02-b51f-9f5b6dbd6db1  Know Your Binding Options 
for the link.
