### ISSUE TITLE
Remove Express x-powered-by response header

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#823]
There are few approaches to disable this response header checkout http://expressjs.com/api.html

![screen shot 2015-05-20 at 15 42 52](https://cloud.githubusercontent.com/assets/1732035/7737245/e627a628-ff06-11e4-843c-92450a01ec89.png)

**Comment by michaelhidalgo** [comment]
app.disable('x-powered-by');

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/832

**Comment by DinisCruz** [comment]
merged

**Comment by roman87** [comment]
@michaelhidalgo can I take this for QA?

**Comment by michaelhidalgo** [comment]
Hi Roman, yes it is

El lunes, 25 de mayo de 2015, RomichG <notifications@github.com> escribió:

> @michaelhidalgo <https://github.com/michaelhidalgo> can I take this for
> QA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/823#issuecomment-105365588>
> .
>


-- 
Sent from Gmail Mobile

**Comment by roman87** [comment]
This is done
