### ISSUE TITLE
Redirect /teammentor to /

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#826]
In a month from now, make it the fix added to https://github.com/TeamMentor/TM_4_0_Design/issues/825 to actually redirect to the /

This is something that should be ok in about 1 month once we don't have users with the / to /teammentor value cache

**Comment by romichg** [comment]
Month has passed.. We should be carefull with this so we don't break @michaelhidalgo customizaiton for the portal page.

**Comment by DinisCruz** [comment]
With the new redirection to /jade or /flare this issue is not relevant anymore since there will be no redirect to /

**Comment by romichg** [comment]
We still need to make sure that original issue - https://github.com/TeamMentor/TM_4_0_Design/issues/825 is addressed by our redirect jade/flare. i.e. we need to make sure that /teammentor works exactly the same as /

**Comment by DinisCruz** [comment]
I think we should leave it as it is

**Comment by romichg** [comment]
Substentiate :)? We still need to make sure that https://teammentor.net/teamMentor/open/c57eaf7a-f02e-4172-8221-38fb47dbf402#load:47a10a30-15ad-4cfd-bf82-00e9bb2037f6&showFilters:false&showTree:false&centerGuidanceItems:true

Works as described in issue: #784

**Comment by michaelhidalgo** [comment]
With Pull Request : 

1.[TM_Angular] -Issue 826 redirect TeamMentor/TM_Angular#24
2.[TM_Website]-Issue 826 redirect TeamMentor/TM_Website#28
3.[TM]-Issue 826 redirect TeamMentor/TM#42

**Comment by romichg** [comment]
This is fixed.
