### ISSUE TITLE
Article 'Do Not Use Dangerous APIs' has no summary on search items

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#827]
See
![image](https://cloud.githubusercontent.com/assets/656739/7738772/1cd85cdc-ff50-11e4-85d2-d97bb8bb1439.png)

The article is this one
http://localhost:1337/article/133cd5912c91/Do-Not-Use-Dangerous-APIs

I was going to open this on TMContent/Lib_UNO but I think this might also be parsing issue

**Comment by DinisCruz** [comment]
@roman87 can you map the priority on this one?

**Comment by DinisCruz** [comment]
This is caused by the fact that the article doesn't have the content inside a paragraph

![image](https://cloud.githubusercontent.com/assets/656739/7738881/65726bf8-ff51-11e4-82a2-eae56b8c72c4.png)

**Comment by roman87** [comment]
@michaelhidalgo is looking into this. Lets see if this is only a content issue. Regardless, lets fix it ASAP.

**Comment by michaelhidalgo** [comment]
Yeah, I'm looking into this issue right now!.

2015-05-21 8:13 GMT-06:00 RomichG <notifications@github.com>:

> Assigned #827 <https://github.com/TeamMentor/TM_4_0_Design/issues/827> to
> @michaelhidalgo <https://github.com/michaelhidalgo>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/827#event-310672461>.
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_JSON_Data/pull/1

**Comment by DinisCruz** [comment]
merged

**Comment by roman87** [comment]
Taking for QA
