### ISSUE TITLE
Minor alignment issue on TnC bullet points

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#835]
![image](https://cloud.githubusercontent.com/assets/656739/7803118/6e9773e4-033f-11e5-98f9-80b9c9c48ea6.png)

**Comment by luchia** [comment]
This has been fixed and a PR submitted -

![screen shot 2015-06-02 at 6 08 40 am](https://cloud.githubusercontent.com/assets/4547737/7922246/5632162e-08ee-11e5-9cea-96b58279a873.png)

**Comment by DinisCruz** [comment]
Code merged

**Comment by romichg** [comment]
fixed
