### ISSUE TITLE
[Q] find root cause and provide fix for 'Transformers.md is deprecated' alert

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#858]
With the latest version of Jade we are now getting the error 

```
Transformers.md is deprecated, you must replace the :md jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0.
```

There doesn't seem to be any issue with it (at the moment), but we need to upgrade so that we don't get caught in the future

**Comment by michaelhidalgo** [comment]
Looking at this issue now : 
I found this log entry from the documentation

Now supports jstransformers, which allows improved handling of embedded languages such as Coffee-Script, and deprecated Transformers support in filters - to be removed in 2.0.0 
http://jade-lang.com/history/

**Comment by michaelhidalgo** [comment]
Fixed.

**Comment by DinisCruz** [comment]
this is done, closing
