### ISSUE TITLE
Update Config files to take into account new TM_4 repo structure

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#859]
As seen at https://github.com/TMClients/SiteData_TM_4 and below:

![image](https://cloud.githubusercontent.com/assets/656739/8034951/a5537310-0de4-11e5-88a0-36b62155ffcb.png)

(note that I had two extra 'SiteData' repos on my local version)

This is needed for #818, #746, #721, #618

**Comment by roman87** [comment]
can we move config outside of the git repo.

**Comment by DinisCruz** [comment]
they are already on separate repos

**Comment by DinisCruz** [comment]
TM Design is now fully working , GraphDB is almost there

**Comment by DinisCruz** [comment]
This is now done and looks like fully working 

![image](https://cloud.githubusercontent.com/assets/656739/8154987/7705e4f4-1337-11e5-87de-921a7684506c.png)

**Comment by DinisCruz** [comment]
all QA tests are passing

![image](https://cloud.githubusercontent.com/assets/656739/8159207/4af71642-135c-11e5-9c49-ae02f0d81dad.png)

**Comment by romichg** [comment]
This is done.
