### ISSUE TITLE
Refactor Jade, Flare and Static files

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#862]
Into these repos

* https://github.com/TeamMentor/TM_4_Jade
* https://github.com/TeamMentor/TM_4_Flare
* https://github.com/TeamMentor/TM_4_Static

@luchia as discussed on Slack please remove the files from TM_4_0_Design in the Issue_862_Design_Refactor branch

**Comment by luchia** [comment]
This has been completed and all repos are up to date. Assigning to @DinisCruz to finish the refactoring.

**Comment by DinisCruz** [comment]
yap add done and working on https://github.com/TeamMentor/TM
