### ISSUE TITLE
Curated Content Interface

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#863]

**Comment by luchia** [comment]
I have a basic wireframe for this (excuse mess in top navigation bar, working on it) -

![screen shot 2015-06-11 at 4 10 27 pm](https://cloud.githubusercontent.com/assets/4547737/8100871/7ce94ee6-1054-11e5-947f-1f0980feb7d2.png)
![screen shot 2015-06-11 at 4 11 00 pm](https://cloud.githubusercontent.com/assets/4547737/8100876/7d0f55e6-1054-11e5-98c1-d927aaa5383d.png)

But now I need to work out how the hell I'm going to do the map. I have no idea. I think we'll have to use JS but that's all I know.

**Comment by luchia** [comment]
The original storyboards had the map looking like this -

![screen shot 2015-07-06 at 11 49 48 am](https://cloud.githubusercontent.com/assets/4547737/8518685/30dcd466-23d5-11e5-96a1-6793a88cc6b8.png)

Which is cool, but not necessarily useable or even possible to dev for our current deadline. This would definitely be cool to have but I think we need to stick with really simple to begin with so we can get the app out. 

Thus, I spent time revisiting the concept and came up with something similar (shown here on Navigate as CC isn't wired up) -

![screen shot 2015-07-06 at 11 40 43 am](https://cloud.githubusercontent.com/assets/4547737/8518693/53400a28-23d5-11e5-9299-748d980ac47f.png)

So if instead of Index, it said Curated Content and the items below it were the 'Gateways', this is how it would work. If the user clicks on Gateway 1, they are shown content relating to this to the right-hand side of the application (as it is in Flare). Then, they can delve further into the rabbit hole by selecting items beneath it or go back/up a level by using the toggle button.

I think this is a simpler solution and a lot easier for people to use. I got creative with the original but I don't think it's good UX. The more you know, the more you realise you don't know etc.  This is also a neat solution because it can work for the Index (instead of breadcrumbs) and for the docs.

**Comment by luchia** [comment]
Here's a screenshot of the article view (minus the navigation due to some bugs relating to #869.) This design also ties in with what I have planned for Editor Interface, which means there won't be much to change when it's time to dev that.

The metadata for the article is to the left so the natural eye scanning flow (left-to-right) isn't disrupted by secondary information). The metadata will also say whether an article belongs to Curated Content and gives the user a link to access it.

I am assigning to @DinisCruz because I need the sub-navigation wired up for Flare, not just for CC (but it relates). 

![screen shot 2015-07-11 at 12 26 29 pm](https://cloud.githubusercontent.com/assets/4547737/8633270/45f88ea2-27c8-11e5-820b-4c3b677ae86e.png)

**Comment by luchia** [comment]
And here's the most recent version, with the navigation fixed:

![screen shot 2015-07-13 at 1 45 24 pm](https://cloud.githubusercontent.com/assets/4547737/8647993/925e9716-2965-11e5-9e63-107fbaa69831.png)

**Comment by romichg** [comment]
Can we add "Back"  or "UP" button for the CC interface to go back to the previous article.   

This is from @SergeTruth  here https://github.com/TMContent/Lib_UNO/issues/76

**Comment by luchia** [comment]
Added -

![screen shot 2015-08-06 at 12 19 47 pm](https://cloud.githubusercontent.com/assets/4547737/9104343/95f1fc78-3c35-11e5-9a6c-191c0dce6ea2.png)

[NOTE: we've got some editor interface stuff in there]

**Comment by romichg** [comment]
Good stuff!!!

**Comment by SergeTruth** [comment]
The back/up button should be present in the regular articles as well to be able to go back to the cc from the guidance.

**Comment by romichg** [comment]
@SergeTruth we've been discussing this and I think it comes to personal preference. I prefer for example to use the browsers back button, and additional back button is confusing to me. This is something we can discuss later when we have a fully working site and everyone had a chance to play with it.

**Comment by luchia** [comment]
I will push this stuff a little later today, but it is finished for now. Assigning to Dinis to finish.

**Comment by michaelhidalgo** [comment]
Assigning it to Michael

**Comment by romichg** [comment]
So based on latest comments, once the user is in Guides, they should remain in the Guide's interface, no matter what the article type is. 
When the user selects a "guide" article from the search, they should also be taken to the guide interface and then stay in the guide interface.

**Comment by romichg** [comment]
This is done.
