### ISSUE TITLE
Logged out view

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#869]
- Docs
- Terms and Conditions
- [x] Docs do not work on the logged out view. 
- [x] See for yourself" and "Start your free trial today" links do not work
- [x] Links are not underlined " TEAM Professor eLearning courses, extending developers’ knowledge in combination with training." 
- [x] Extra scroll bar on the right
- [x] Clicking on terms and conditions brings up Jade nav menu. 
- [x] Get password link does not work. 
- [x] Images are too large https://github.com/TeamMentor/TM_4_0_Design/issues/869#issuecomment-130415884
- [x] The menu should not scroll with text.

**Comment by luchia** [comment]
PR submitted. Assigning to @DinisCruz to write the logic.

Dinis, the landing_page layout and the application layout are the only two layouts to be used. We need to write the same logic that Jade has, where if the user is logged in it shows one layout and if the user isn't, it shows the other. I have revised the templates so they will all work correctly.

**Comment by DinisCruz** [comment]
Docs are now done

![image](https://cloud.githubusercontent.com/assets/656739/8579600/762fec04-25ad-11e5-8aa6-f8c9b2a41185.png)

![image](https://cloud.githubusercontent.com/assets/656739/8579613/8431be72-25ad-11e5-9110-94a989de75bd.png)

menu depends on logged status

![image](https://cloud.githubusercontent.com/assets/656739/8580594/6035bbe4-25b3-11e5-8f97-7bf9ec9dfe9c.png)

**Comment by luchia** [comment]
Taking back to make some small style changes.

**Comment by luchia** [comment]
Hey @DinisCruz, I added the fixes for this. 

![screen shot 2015-07-10 at 10 35 34 am](https://cloud.githubusercontent.com/assets/4547737/8614189/b96d1256-26ef-11e5-934b-ad404617651c.png)

The other thing I did was add the page.jade to the layouts directory in Flare (the same as we have in Jade). I did this because we should serve either page_logged_in or page_logged_out. Having done this though, it seems that part of the logic is broken as I am definitely logged in, but the navigation is not changing. Would you mind taking a look? Thank you.

![screen shot 2015-07-10 at 10 35 17 am](https://cloud.githubusercontent.com/assets/4547737/8614188/b96c98b2-26ef-11e5-8ea1-8142df93cee0.png)

Here's the [code](https://github.com/TeamMentor/TM_Flare/blob/Dev_Lucy/_layouts/page.jade#L1-L4).

**Comment by luchia** [comment]
Dinis and I have completed this with Angular and it is ready for QA.

**Comment by romichg** [comment]
moved this comment (logged out view issues) to the top, so it can easily be seen and added to..

**Comment by luchia** [comment]
@roman87, can you show me a screenshot of the extra scroll bar.

One, five and six I will need help from @DinisCruz. To discuss with him later today or on the meeting tomorrow morning.

**Comment by romichg** [comment]
Scrolbar

![selection_376](https://cloud.githubusercontent.com/assets/1326120/9120764/3d750538-3c4c-11e5-997e-1229261a46bd.png)

**Comment by luchia** [comment]
Five and six are done. Still have not found a way to fix the docs and cannot see the double scroll bar.

**Comment by romichg** [comment]
@luchia catch me on skype, I will show you on the join me.

**Comment by luchia** [comment]
Need help from Dinis, Michael or Salle on to fix the docs.

**Comment by romichg** [comment]
Images on the Docs pages (logged out view) are too large.

![selection_416](https://cloud.githubusercontent.com/assets/1326120/9234088/bccf0c5e-4104-11e5-9e69-81db63384665.png)

**Comment by luchia** [comment]
This has been completed. PR submitted today.

**Comment by romichg** [comment]
All fixed
