### ISSUE TITLE
Filters in the nav bar

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#872]

**Comment by luchia** [comment]
Made good progress on this today. May still be some bugs but a first verison is in the PR I submitted. Will spend more time on this a little alter.

**Comment by luchia** [comment]
![screen shot 2015-06-26 at 7 59 29 am](https://cloud.githubusercontent.com/assets/4547737/8366581/6f88cac0-1bd9-11e5-8a28-4f674723535a.png)
![screen shot 2015-06-26 at 7 59 32 am](https://cloud.githubusercontent.com/assets/4547737/8366582/6f8cb1d0-1bd9-11e5-992c-5b0968de815e.png)

I'm submitting my PR with these changes. Assigning to @roman87 for QA and feedback.

**Comment by luchia** [comment]
![screen shot 2015-06-26 at 1 29 42 pm](https://cloud.githubusercontent.com/assets/4547737/8370175/7a278f10-1c07-11e5-8e07-7f2cec968486.png)
![screen shot 2015-06-26 at 1 29 45 pm](https://cloud.githubusercontent.com/assets/4547737/8370173/79ab7aec-1c07-11e5-922a-ba970103045d.png)
![screen shot 2015-06-26 at 1 29 49 pm](https://cloud.githubusercontent.com/assets/4547737/8370174/7a25d300-1c07-11e5-82c6-55f677562295.png)

This has been fixed. I would like JS to do a little work for us so we can move the X button to the filters button. For example, it would be great if the filters icon toggles to the X button so the user can use it toggle the filters div always. This is especially a good solution for mobile, where the basic navigation is at the base of the screen (easy access for thumbs). Is it possible for Angular to do the swap on the button @DinisCruz @michaelhidalgo?

**Comment by romichg** [comment]
@luchia looking at the screenshots, this is not exactly what we had in mind. 
![selection_318](https://cloud.githubusercontent.com/assets/1326120/8398127/6f3e1eba-1db1-11e5-8478-11127649e37b.png)
![selection_317](https://cloud.githubusercontent.com/assets/1326120/8398128/71d90928-1db1-11e5-9af9-b38b429c6e72.png)

**Comment by luchia** [comment]
Okay, so it's more a JS dropdown component that you want.

**Comment by luchia** [comment]
I've just finished deving and cross-browser testing this solution. @DinisCruz said a select was a better option (over a hack button/unordered list), but the only downfall with that is that it cannot display the icons for technologies. 

![screen shot 2015-07-06 at 11 36 29 am](https://cloud.githubusercontent.com/assets/4547737/8518538/bcc4ea24-23d3-11e5-83b7-f0f0102979bb.png)
![screen shot 2015-07-06 at 11 37 38 am](https://cloud.githubusercontent.com/assets/4547737/8518540/bcccb5ce-23d3-11e5-8d13-1b9802514a11.png)
![screen shot 2015-07-06 at 11 37 41 am](https://cloud.githubusercontent.com/assets/4547737/8518541/bccd2982-23d3-11e5-9b2b-118cb67beebe.png)

But you can still see all the filters and the icons when you toggle the filters div.

**Comment by romichg** [comment]
This is done.
