### ISSUE TITLE
Remove Flare styles applied via html element ids (vs via classes)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#875]
Hi @luchia as mentioned on https://github.com/TeamMentor/TM_Static/commit/43745756fc01e601c14fa405644ba1aa8fe4fd4e we need to avoid applying styles using ids

We tend to add a lot of ids to make unit testing easier and it will create issues if there are a number of css mappings that are applied when a particular id is added 

There seems to be a number of them still left:
![image](https://cloud.githubusercontent.com/assets/656739/8337471/3532ddc0-1aa3-11e5-95b8-697bda5a94ec.png)

Can you take a look and start removing them?

**Comment by luchia** [comment]
This has been fixed as much as possible for the time being. We have 3 selectors that only relate to toggling the filters div on and off screen. My code has been submitted in my PR request.
