### ISSUE TITLE
Safari is a mess on Flare

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#876]
![screen shot 2015-06-26 at 7 57 18 am](https://cloud.githubusercontent.com/assets/4547737/8366530/021e77d2-1bd9-11e5-8944-9b6b5b0156dd.png)
![screen shot 2015-06-26 at 7 57 25 am](https://cloud.githubusercontent.com/assets/4547737/8366531/0247a670-1bd9-11e5-842d-a2e996f76a53.png)

**Comment by luchia** [comment]
This has been fixed on all pages.

![screen shot 2015-06-30 at 7 49 38 am](https://cloud.githubusercontent.com/assets/4547737/8424060/a99b4276-1efc-11e5-9dc0-8047840d95e0.png)

And it's in my newest PR.

**Comment by romichg** [comment]
Fixed.
