### ISSUE TITLE
Remove Lib_UNO from submodules

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#880]

**Comment by romichg** [comment]
This actually won't work. Lib_UNO should not be part of submodules for the same reason as reason number 1 here https://github.com/TeamMentor/TM_4_0_Design/issues/882
I should be able to pull in the latest changes to all of the app without loosing my content changes

**Comment by DinisCruz** [comment]
> I should be able to pull in the latest changes to all of the app without loosing my content changes

actually you will not lose any content changes, since if:
a) they are committed, you can easily go back to those commits (using git checkout)
b) they are not committed, the submodule update will not work

**Comment by romichg** [comment]
a) I will need to go and do a git checkout every time I do a submodule update, that is an extra step 

I want to be able to track a different branch and maybe even a different remote.  (tm-sme/Dev for uno.teammentor.net  tm-sme/Beta for tmdev01 and if I am a customer, perhaps some other repo. So I have to change the remote, do a checkout every time I want to pull in latest app changes. Seems 
cumbersome
.

**Comment by DinisCruz** [comment]
actually that extra step (to have the commit pinned) is actually very important, since it allows us to be able to load up an version of Lib_UNO that is compatible with the current code base.

If you do what you did (remove both Lib_UNO and Lib_UNO-json) then we lose that abiity

**Comment by romichg** [comment]
Um.. At any point in time, ever, any (current or older) version of Lib_UNO must load with TM. Sorry but the Library is not coupled with the code. This is content, content had different dynamics than the code. These can't be coupled for reasons I already outlined above.

**Comment by romichg** [comment]
Done on master
