### ISSUE TITLE
Reload  shell script (bash) does not work in windows git shell

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#884]
The reason is coffee is not in global path
Fixing by adding full path to coffee module location

**Comment by DinisCruz** [comment]
yeah, @michaelhidalgo hit on that one too. I though @michaelhidalgo had added the full path to the windows bat file

**Comment by romichg** [comment]
just pushed a fix. https://github.com/TeamMentor/TM/pull/6
