### ISSUE TITLE
New articles are not picked up by the reload

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#888]
When new articles are created:

```

ntracked files:
 (use "git add <file>..." to include in what will be committed)

       Articles/9c2d5029-97a6-4c72-9739-25b25efb02ce.xml

o changes added to commit (use "git add" and/or "git commit -a")
```

They are not picked up by the reload.

**Comment by DinisCruz** [comment]
As discussed on the call let's go with the option that requires a delete of the data with the virtual-articles.json added to Lib_UNO. See https://github.com/tm-sme/Lib_UNO/commit/7d00b19dc4cc327fc3822a99793137102751187e

note that the bin/reload_data.bat will need to be updated to the changes made to bin/reload_data.sh See https://github.com/TeamMentor/TM/commit/728059ff358bd50347b3f04c82c022419997b119

**Comment by michaelhidalgo** [comment]
Cool I'm doing the same to the bin/reload_data.bat file.

2015-07-15 12:29 GMT-06:00 Dinis Cruz notifications@github.com:

> As discussed on the call let's go with the option that requires a delete
> of the data with the virtual-articles.json added to Lib_UNO. See
> tm-sme/Lib_UNO@7d00b19
> https://github.com/tm-sme/Lib_UNO/commit/7d00b19dc4cc327fc3822a99793137102751187e
> 
> note that the bin/reload_data.bat will need to be updated to the changes
> made to bin/reload_data.sh See TeamMentor/TM@728059f
> https://github.com/TeamMentor/TM/commit/728059ff358bd50347b3f04c82c022419997b119
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamMentor/TM_4_0_Design/issues/888#issuecomment-121705217
> .

## 

Michael Hidalgo
http://michaelhidalgocr.blogspot.com

_The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer_
