### ISSUE TITLE
View under root of the library (view not in any folder) does not get picked up by transform to 4.0

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#889]
Current tm-sme/Lib_UNO/Beta has that issue.

**Comment by DinisCruz** [comment]
This is a specific problem with the 'Gateways' view recently added

**Comment by DinisCruz** [comment]
done

![image](https://cloud.githubusercontent.com/assets/656739/8679809/dbb4152c-2a54-11e5-8f8c-fdecd41aed2c.png)

![image](https://cloud.githubusercontent.com/assets/656739/8679803/cef8eb50-2a54-11e5-9d60-4911ea99ba6e.png)
