### ISSUE TITLE
New Technology does not pick up the generic icon, but pick up tech independent icon

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#891]
![selection_320](https://cloud.githubusercontent.com/assets/1326120/8424150/e593fe32-1ec3-11e5-8d18-11c67d30db93.png)

**Comment by luchia** [comment]
I fixed this already but I don't know where the changes went. I have just pushed a fix and submitted a [PR](https://github.com/TeamMentor/TM_Jade/pull/3).
