### ISSUE TITLE
Technology "Independant' missspelling is still there on hover

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#892]
![desktop due_333](https://cloud.githubusercontent.com/assets/1326120/8424216/143cc434-1ec5-11e5-8224-7520df6672e6.png)
![desktop due_332](https://cloud.githubusercontent.com/assets/1326120/8424218/15ac3002-1ec5-11e5-86d7-b34a7154fb96.png)

**Comment by luchia** [comment]
I fixed this already but I don't know where the changes went. I have just pushed a fix and submitted a [PR](https://github.com/TeamMentor/TM_Jade/pull/3).
