### ISSUE TITLE
The reload button on TM3.6 doesn't work

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#893]
The functionality doesn't seem to work. The bat file does not run on its own (seems like issue related to #884 
The paths in the bat file are also in unix format ".../../" as opposed to windows "...."

**Comment by michaelhidalgo** [comment]
Hi @roman87.
There is a configuration setting in place that tells where is the bat file located. Make sure to use double backslash when setting up the config value (\) just like this one : 

"TMReloadDataScriptPath": "C:\Users\Mike\Desktop\TM\bin\reload_data.bat",

![screen shot 2015-06-30 at 05 54 50](https://cloud.githubusercontent.com/assets/1732035/8430223/c48e70fe-1eec-11e5-9231-5b4068c2af2d.png)

The reason why I set it up as a configuration value is just in case the folder structure is different between environments.

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM/pull/13/files
