### ISSUE TITLE
Allow anonymous users to hit 5 TEAMMentor articles

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#896]
In order to reach potential TEAM Mentor users/buyers, we should allow anonymous user to access 5 articles before being challenged to create an account.

Every time an article is fetched, the number of 'free" articles should be decreased.

**Comment by tekgirl77** [comment]
HI @luchia we need your help!  :) 
- While testing the "5 free articles" for anonymous visitors, we noticed the view rendering funny on the Android - the body was no longer flush with the navbar when the visitor is in "logged out" status.  
  - <img width="953" alt="screen shot 2015-08-04 at 1 36 16 pm" src="https://cloud.githubusercontent.com/assets/6649463/9071210/5213c192-3ab1-11e5-8042-4d11ae6d9d4a.png">
- Here is what it looks like when the user is logged in:
  -  <img width="1035" alt="screen shot 2015-08-04 at 1 38 38 pm" src="https://cloud.githubusercontent.com/assets/6649463/9071279/aaf56360-3ab1-11e5-8545-2f246e29fd10.png">
- We have tried tweaking the article.jade code a bit, but it still is not flush w/ the navbar.
  - From [this](https://github.com/TeamMentor/TM_Jade/blob/Issue_896_view_free_articles/user/article.jade#L14-L25) to this: 
  - `````` bash
       else
              .col-1
                .lge-container
              .col-10
                .lge-container
                  .alert.alert-ok(role='alert')
                  #message
                    span.alert-icon !
                    if welcomeMessage
                      span.alert-text=welcomeMessage
                  +article
                  +copyright ```
    ``````
  -  Which resulted in this:
  - <img width="1040" alt="screen shot 2015-08-04 at 1 45 31 pm" src="https://cloud.githubusercontent.com/assets/6649463/9071258/89bc87dc-3ab1-11e5-8bb6-5257dfc41250.png">
- Can you please help us identify where / how it is best to make necessary changes so this "logged out" article view renders nicely?  We have an [Issue_896 branch](https://github.com/TeamMentor/TM/tree/Issue_896_view_free_articles) on the main /TM repo that you can check out and do a `git submodule update` to get the other submodule branches in place for testing.

**Comment by luchia** [comment]
Hey @tekgirl77, I worked with @michaelhidalgo this morning to fix this. It should be right to go now.

**Comment by tekgirl77** [comment]
Thanks @luchia!

**Comment by DinisCruz** [comment]
this is now merged
although there is something not 100% right

Here is what It looks to me as a logged in user

![image](https://cloud.githubusercontent.com/assets/656739/9210276/39e19fdc-4073-11e5-8c34-924f526e4d3d.png)

**Comment by romichg** [comment]
@tekgirl77 this is ready for QA right?

**Comment by tekgirl77** [comment]
hey @roman87 yes, @DinisCruz merged it into Dev yesterday... unless he is still testing or making any changes, it should be ready.

**Comment by romichg** [comment]
This is done, though some issues still remain:
#938 #939
