### ISSUE TITLE
NodeTM should connect to TM 3.5 backend over SSL and authenticate itself through ether SSO or session cookie

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#90]
At the moment no authentication is required to the TM 3.5 backend.

**Comment by roman87** [comment]
This does not work. When I switch not to show library structure to anonymous, which is really the only information that is being fetched. Loading of data fails.  Moreover, switching it back does not fix this.
![selection_033](https://cloud.githubusercontent.com/assets/1326120/5616720/4d95811e-94d5-11e4-9b65-73a50b067f3b.png)

**Comment by roman87** [comment]
Additional info:
When changing the auth-key to something invalid. The GraphDB still shows that the data was loaded.
However, there is no data in the UI
![selection_034](https://cloud.githubusercontent.com/assets/1326120/5616909/d5c873f6-94d6-11e4-8261-06d7ee84a123.png)
![selection_035](https://cloud.githubusercontent.com/assets/1326120/5616916/df937868-94d6-11e4-90e0-a1974c8fcf50.png)

And this seems to certainly cause the database to crash after a few attempts of clicking on keywords. Which seems like this issue: https://github.com/TeamMentor/TM_4_0_Design/issues/191

![selection_036](https://cloud.githubusercontent.com/assets/1326120/5617046/4163be80-94d8-11e4-8974-c62f93bd3c39.png)

**Comment by roman87** [comment]
I am making this a P1 to be inline with priorities we need to work on.

**Comment by DinisCruz** [comment]
Ahh yeah, at the moment the option to consume data from a TM library that is setup with 'not to show library structure to anonymous,' is not supported (only the default TM/Uno case where the library structure is shown, but article content require login)

**Comment by romichg** [comment]
no longer necessary.
