### ISSUE TITLE
Add validations for the Signup form fields

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#900]
1. State place holder must be "State" instead of "state".
2. Validations should follow the UI workflow.

**Comment by michaelhidalgo** [comment]
With Pull Request [https://github.com/TeamMentor/TM_Website/pull/6]
With Pull Request [https://github.com/TeamMentor/TM_Jade/pulls]

**Comment by michaelhidalgo** [comment]
Merged.

**Comment by romichg** [comment]
Done.
