### ISSUE TITLE
Top articles need to be changed

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#901]
Initial top articles should be:

article/e2f97ef0-6ced-4f3d-bdce-7a72e359eb7b Programming Best Practices
article/b9c18634-7d10-4edf-b7ef-20d72f7c1650 Platform-specific Guidance
article/e2f97ef0-6ced-4f3d-bdce-7a72e359eb7b Vulnerabilities

**Comment by romichg** [comment]
This is the fist article  bcbbe5c7-95c3-468d-9371-6eb42f9b93e6 Programming Best Practices
Cut and paste error in the issue

**Comment by DinisCruz** [comment]
Done 

Note that the id for the Programming Best Practices is 6eb42f9b93e6 (and not  7a72e359eb7b)

**Comment by romichg** [comment]
Done
