### ISSUE TITLE
Error on the error page

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#904]
![selection_349](https://cloud.githubusercontent.com/assets/1326120/8888682/9480c1b2-3285-11e5-93d7-556144ab4161.png)

**Comment by luchia** [comment]
Fixed and submitted a PR. Edit: PR merged.

![screen shot 2015-07-26 at 8 58 24 pm](https://cloud.githubusercontent.com/assets/4547737/8895177/14b52022-33d9-11e5-8433-9e7fb4061a3f.png)

**Comment by romichg** [comment]
Fixed in latest Dev
