### ISSUE TITLE
Missing stylesheet from Jade

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#905]
I found a really strange bug on jade where the stylus generated stylesheet (jade-stylesheet.css) is no longer attached to the head in the browser. However, when checking the head.jade file in the TM_Jade repo, the correct stylesheet is present.

Stuck on this one, I need help please @DinisCruz.

**Comment by luchia** [comment]
This seems to be working now. The only big changes I made this morning was turning Jade compilation cache off in tm.config.json. Not urgent anymore, but you might want to see if you can recreate it.

**Comment by DinisCruz** [comment]
this could be caused by jade-compilation cache

**Comment by luchia** [comment]
Yup, my thoughts exactly.

**Comment by romichg** [comment]
@luchia  Can we close this?

**Comment by luchia** [comment]
I haven't seen it again, so let's close it.
