### ISSUE TITLE
Cross browser testing (Flare)

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#906]
Needs to be completed using Saucelabs

BROKEN
- [x] Mac iPad 8.4
  ![screen shot 2015-07-26 at 9 33 58 pm](https://cloud.githubusercontent.com/assets/4547737/8895306/0c971dd2-33de-11e5-80a1-dea41fa6d7b0.png)
- [x] Win XP FF9
  ![screen shot 2015-07-26 at 9 30 49 pm](https://cloud.githubusercontent.com/assets/4547737/8895297/9ac1aa06-33dd-11e5-8fbb-212ee319b2f0.png)

GOOD 
- [x] Win 8 IE11
- [x] Win 8 Chrome 26
- [x] Win XP FF9

This would be a lot quicker if I could automate it. Is there any way we can do this @michaelhidalgo?

**Comment by luchia** [comment]
So I've done as much as I can on my machine but it's going to take forever to do SauceLabs manually. Is there a way to automate this so I can save some time? Probably not a P0 but we'll need to do this at some point.

**Comment by romichg** [comment]
Sounds good, great stuff, assigning to @michaelhidalgo as a p1. Related to #82

**Comment by romichg** [comment]
Done.
