### ISSUE TITLE
login form should show on the top in mobile view

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#913]
Here is the login page (http://localhost:12345/angular/user/index)

**in wide view**

![image](https://cloud.githubusercontent.com/assets/656739/9072626/2ef50c96-3af4-11e5-8442-56164d7adce2.png)

**in mobile view**

![image](https://cloud.githubusercontent.com/assets/656739/9072643/469ae848-3af4-11e5-86e3-b3e3dfac99fb.png)

I think the form in mobile should be at the top

**Comment by luchia** [comment]
This has been fixed and submitted with my PR today.
