### ISSUE TITLE
Trem(n) de carga  of Flare issues (Lucy)

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#916]
@luchia these ones are yours 
- [x] Login and signup form shows the required fields as RED right the way. 
  ![selection_372](https://cloud.githubusercontent.com/assets/1326120/9090920/4428ea8e-3b6b-11e5-9aea-0903885b396b.png)
- [x] I think the login and password boxes are to big 
- [x] I think, get password link should be right justified. Text should be changed to "Forgot your password"
- [x] images are blown up to fit the page
  ![selection_375](https://cloud.githubusercontent.com/assets/1326120/9092584/043df356-3b75-11e5-92ee-57d54dbde6a1.png)

**Comment by luchia** [comment]
Hi @roman87, can you please take a look at Dev for me? I submitted a large PR yesterday with these fixes.

**Comment by romichg** [comment]
Fixed.
