### ISSUE TITLE
Trem(n) de carga  of Flare issues. (Dinis)

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#917]
@DinisCruz and these are yours.
- [x] no logged in user should be redirected to login if she is not authenticated.
- [x] not logged in user going to the login protected page, user is not redirected to the login page..
- [x] after logging in (and otherwise when clicking on home button) screen is blank
- [x] Flare articles like http://localhost:12345/article/c4914e51-2609-4edc-8133-31491f1b03c0 redirect to Jade
  ![selection_373](https://cloud.githubusercontent.com/assets/1326120/9092536/c262ca1a-3b74-11e5-98e0-daea29a7b0a5.png)
- [x] the back button does not work from the full article view
- [ ] Search should always search the existing result set and not reset the filters (#948)
- [x] changing the dropdown should always clear the search box. Probably it should do nothing with respect to the results unless search is performed. Otherwise the behavior is exactly the same as selecting a tech filter. In which case we should remove the tech filter. 
- [x] After signup the page displayed is not the "index" page
  ![selection_421](https://cloud.githubusercontent.com/assets/1326120/9335896/b61fe5dc-45a4-11e5-9cc9-c2c1a84ed252.png)
- [x] docs don't work in both logged in and logged out mode
- [ ] hitting the index button should clear the search box _(Decided not a good idea)_
- [x] Back button does not work from any query/filter selection
  the home page is empty.
- [x] selecting a filter and then selecting lefhand side nav clears all the filters

**Comment by michaelhidalgo** [comment]
Ok I'm going to work on this

**Comment by romichg** [comment]
Some more:
- [x] Terms and conditions link on the signup form goes to the jade version of T&C
- [ ] Error Page is a jade page, with the jade menu. Needs to have flare menu (#995)
- [x] Going to the index page via a URL (typing https://tmdev01-beta.teammentor.net/angular/user/index in the URL window) SOMETIMES does not load the full page.
  ![selection_381](https://cloud.githubusercontent.com/assets/1326120/9143660/a1e7678a-3d15-11e5-9dce-5d2f4a64819d.png)

**Comment by romichg** [comment]
Done/ Decided not to do, or tracked elsewhere.
