### ISSUE TITLE
Login/Signup text alignment. 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#921]
- [ ] Signup /login page. The test on the right seems to be too far off to the right. Can we make it a bit closer to the sign-up fields?
  ![selection_380](https://cloud.githubusercontent.com/assets/1326120/9143516/02037f10-3d15-11e5-99d7-76861a750636.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-08-18 at 10 16 58 pm](https://cloud.githubusercontent.com/assets/4547737/9329676/19f09938-45f7-11e5-9d64-82f50d895855.png)
![screen shot 2015-08-18 at 10 17 31 pm](https://cloud.githubusercontent.com/assets/4547737/9329677/1a26c738-45f7-11e5-91c1-188a3d739730.png)

**Comment by romichg** [comment]
fixed
