### ISSUE TITLE
Make the selection of hierarchical filter look more intuitive in Jade

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#93]
Right now we show selection with Italics

![image](https://cloud.githubusercontent.com/assets/1326120/5255809/efabbcec-798d-11e4-96e7-4fe0ddd16d2d.png)

Maybe we can  do something more user friendly?

**Comment by DinisCruz** [comment]
The solution for https://github.com/TeamMentor/TM_4_0_Design/issues/94 addresses this issue. And for the Jade beta there will only be one active filter on the right
