### ISSUE TITLE
Signup page: Terms and conds link points to a Jade page

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#937]

**Comment by luchia** [comment]
This has been fixed and PR submitted today.

**Comment by romichg** [comment]
Not working yet, related to #977

**Comment by luchia** [comment]
This issue is actually fixed because it doesn't redirect to the Jade TOC page anymore.

**Comment by romichg** [comment]
Agreed, just keeping it open until the whole thing works.

**Comment by romichg** [comment]
This is fixed.
