### ISSUE TITLE
Left hand (hierarchical) and right hand filters should be select-able together, ANDing the result set. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#94]

**Comment by DinisCruz** [comment]
Finally, here are the right-hand side scripts filters working (examples below are using the **Vulnerabilities** library)

**top level (library)**

![image](https://cloud.githubusercontent.com/assets/656739/5902757/16b5e67e-a575-11e4-8ce7-5a44c3d9e059.png)

**2nd level (folder)**

![image](https://cloud.githubusercontent.com/assets/656739/5902792/5044306c-a575-11e4-937c-48638865fedd.png)

**3rd level (view) ** 

![image](https://cloud.githubusercontent.com/assets/656739/5902774/349467ba-a575-11e4-8ed8-9563e7dd142b.png)

**Comment by DinisCruz** [comment]
This is now working :)

Here is the **Authorization** query 


![image](https://cloud.githubusercontent.com/assets/656739/5907558/c9f65ad0-a597-11e4-8907-e6bfda170d5e.png)

and after clicking on **Java** we get this:

![image](https://cloud.githubusercontent.com/assets/656739/5907581/f5761d30-a597-11e4-9b7b-60b1a20bf902.png)

Here are the links used above
 * http://localhost:1337/graph/Guidance,query-2416c5861783
 * http://localhost:1337/graph/Guidance,query-2416c5861783/query-3a752bb7462b

Note that you can also use the title on the left-hand-side-query: http://localhost:1337/graph/Guidance,Authorization

**Comment by roman87** [comment]
Yep All done.
