### ISSUE TITLE
Multiple UI issues in non-logged in pages (FF)

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#941]
- [x] "our clients love us" is not centered, like in Jade
  ![selection_424](https://cloud.githubusercontent.com/assets/1326120/9413367/7cfaa8de-47ff-11e5-80df-f16c7a840b26.png)
- [x] The font for the navbar is smaller than in Jade. And logo is bigger.  Probably should be consistent here. 

![selection_427](https://cloud.githubusercontent.com/assets/1326120/9413399/a47bd932-47ff-11e5-9b30-1542c95ced75.png)
![selection_428](https://cloud.githubusercontent.com/assets/1326120/9413402/a6ccca52-47ff-11e5-9547-6a895f0b5358.png)
- [x]  Icons are wrong on the bottom

![selection_432](https://cloud.githubusercontent.com/assets/1326120/9413406/b32bd1e4-47ff-11e5-8c49-f90c64bee6e7.png)
- [x] bottom header is missing on Docs, singup and login pages
- [x] double scroll bar on the about and features page

![selection_433](https://cloud.githubusercontent.com/assets/1326120/9413433/d1429dd4-47ff-11e5-89d2-99263437f8cc.png)
- [x] Double scroll bar, when mouse over an article on the docs page
  ![selection_434](https://cloud.githubusercontent.com/assets/1326120/9413455/ecf5a9f4-47ff-11e5-93ff-b2bb2839282b.png)
- [x] the word "Login" looks much better in Jade than in Flare
  ![selection_435](https://cloud.githubusercontent.com/assets/1326120/9413537/660a43a4-4800-11e5-93ba-0c51ee54ea79.png)
  ![selection_436](https://cloud.githubusercontent.com/assets/1326120/9413542/7381550e-4800-11e5-976e-082c70527847.png)

**Comment by luchia** [comment]
The second checkpoint hasn't been addressed in my PR, I still need to do that.

**Comment by luchia** [comment]
Submitted in PR today. Will merge shortly.

**Comment by romichg** [comment]
All fixed!
