### ISSUE TITLE
Consolidate the style requests in a smaller number of requests

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#942]
@luchia is it possible to reduce the number of css/style/font requests made to server

look at the requests currently made (when the angular caches are enabled)

![image](https://cloud.githubusercontent.com/assets/656739/9415750/524c2394-4839-11e5-92d6-cd12fabd8ec3.png)

Ideally we should have one requests per content type: css, font, images (or even one with both css and font data on it)

**Comment by luchia** [comment]
I managed to remove one (the github syntax stylesheet) as I added it into the Flare stylus files. The others I don't think we can compress, unless we drop fonts. The page still loads really fast regardless, so I don't think it's a big issue.

**Comment by romichg** [comment]
Agreed. I don't think we have a performance issue on page loading.
