### ISSUE TITLE
2nd Level navigation  should only  reflect navigation in hierachical filters, from higher rank to lower rank, and from left to right

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#95]
Kingdom->Phylum->Class->Order->Family->Genus->Species
Index->Data Validation->Validate All Input

![image](https://cloud.githubusercontent.com/assets/1326120/5255929/b8293aae-798f-11e4-8610-effdedb74ceb.png)

**Comment by roman87** [comment]
Related to #199 
Moving to p0

**Comment by DinisCruz** [comment]
Shouldn't we rename this issue to '2nd-level-Navigation' , since these are not breadcrumbs any more

**Comment by roman87** [comment]
Yea we can rename it.

**Comment by DinisCruz** [comment]
https://github.com/TeamMentor/TM_4_0_Design/issues/199 addresses this issue

**Comment by roman87** [comment]
All done. Great stuff!!!
