### ISSUE TITLE
Move angular site as main site and use Jade site as the back up

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#952]
Which is swap the current behaviour

The idea is to use Flare as the main site, with auto-redirection happening for Jade

**Comment by DinisCruz** [comment]
this is now done

**Comment by romichg** [comment]
This is mostly done. As part of this we need to rename /angular to /flare and also have a full list of user-agents to switch on. I am keeping in your court for now @DinisCruz

**Comment by DinisCruz** [comment]
renaming /angular to /flare is not a simple change and we will need to have better code coverage before we do it

**Comment by romichg** [comment]
Quite poor planing here. We knew we were going to name it like this a long time ago. I don't understand why we cant simply do a search and replace of /angular to /flare

**Comment by romichg** [comment]
This is done except for #1047
