### ISSUE TITLE
Bring back the "UP" Arrow on the left handside filters

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#955]

**Comment by luchia** [comment]
![screen shot 2015-09-02 at 10 57 49 am](https://cloud.githubusercontent.com/assets/4547737/9620722/78e8e5d8-5161-11e5-9d65-b8478232eb83.png)

Done, will push later today.

**Comment by romichg** [comment]
@luchia is this pushed? I don't see it.

**Comment by luchia** [comment]
Some reason it didn't merged, it's in my PR today.

**Comment by luchia** [comment]
PR submitted. Need Dinis/Michael to rewire this because it doesn't work.

**Comment by romichg** [comment]
After discussion it was decided to not to do this. Breadcrumbs should solve the navigation need.
