### ISSUE TITLE
Scrolling does not go all the way down

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#957]
![selection_010](https://cloud.githubusercontent.com/assets/1326120/9613740/4d36e148-50bb-11e5-9ecd-9b51ffa4733f.png)

**Comment by luchia** [comment]
Yup, this is an issue that has to be addressed by my comments on #943 

>  Can we make JS change the height of .scrolling-results from the defined height to 75% when active-filters are present on the page? And change it back to the original height (in the css) when active-filters are not present?

I can't do this with CSS alone unfortunately, it has do with the page not reloading (so I can't apply a class that will change the height). We have this issue in Chrome and Safari too -

![screen shot 2015-09-02 at 11 00 44 am](https://cloud.githubusercontent.com/assets/4547737/9620746/ea2fa68c-5161-11e5-87a4-c81c474dff42.png)

**Comment by romichg** [comment]
Assigning to @michaelhidalgo

**Comment by romichg** [comment]
Also an issue with Top Articles, 
![selection_013](https://cloud.githubusercontent.com/assets/1326120/9668833/d5431fd8-5251-11e5-8409-f8fc17543198.png)

**Comment by romichg** [comment]
And here is another sshot
![selection_016](https://cloud.githubusercontent.com/assets/1326120/9668849/f1e2d2d2-5251-11e5-8a4e-5743607f1625.png)

**Comment by michaelhidalgo** [comment]
Working on this.

**Comment by michaelhidalgo** [comment]
Hi @luchia , I have dynamically changed the height of the .scrolling-results  : 

I changed it to 70% when there are filters : This is a Firefox screenshot with more zoom 

However, I think we need to add some padding bottom or something similar since I think that depending on the browser, the bottom cuts  without selecting any filter :

![screen shot 2015-09-07 at 12 55 01](https://cloud.githubusercontent.com/assets/1732035/9721803/47c7c5e4-555f-11e5-9759-703434f6b434.png)

**Comment by luchia** [comment]
Cool, that looks good. Thanks for doing that for me Michael :) I will work on this today.

**Comment by luchia** [comment]
Padding added and PR submitted. Did you finish your stuff on this Michael?

**Comment by romichg** [comment]
It seems like we could use some extra padding not only in FF. As you can see both the lefhand and righthand filters scroll all the way to the bottom without any indication that you've reached the end. This is chrome btw. 
![selection_062](https://cloud.githubusercontent.com/assets/1326120/9887986/7c5a3848-5bc0-11e5-9ebe-ef8cb5856ee1.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-09-17 at 7 09 29 am](https://cloud.githubusercontent.com/assets/4547737/9918593/14e0c186-5d0b-11e5-8f7a-98ff2d20eb4e.png)

**Comment by romichg** [comment]
Looks good.
