### ISSUE TITLE
"Contact support" link in Flare

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#961]
Just like we have it in jade, we need a similar thing in flare.
![selection_020](https://cloud.githubusercontent.com/assets/1326120/9669509/b6edc106-5255-11e5-8ed3-77a43cc2f46c.png)

**Comment by luchia** [comment]
I've done this already, and given it to Michael to wire up.

**Comment by michaelhidalgo** [comment]
Hi Lucy, it seems like the class you are assigning to it is sending the component to the bottom of the page : 
Note that I removed the class and I added it to the right hand side div, so it is consistent with Jade 

![screen shot 2015-09-04 at 11 42 08](https://cloud.githubusercontent.com/assets/1732035/9690483/ded53c72-52f9-11e5-8e3d-a3528b321397.png)

**Comment by luchia** [comment]
When we talked about this in the meeting, Roman said it didn't have to be exactly like Jade. I wanted it to be in the bottom left hand corner.

**Comment by michaelhidalgo** [comment]
Ok, I also think it is not fixed at the bottom. If you move the scroll, it moves too, as a result, this button is hidden when moving the scroll.

**Comment by luchia** [comment]
Yeah, I think because you removed the class in your comment above ^^. I'll fix it now.

**Comment by luchia** [comment]
Fixed and PR submitted. Re-assigning to Michael.

**Comment by romichg** [comment]
Not sure how it is supposed to look like, but it does look quite weird where it is here, almost to the point of blocking usability.
![selection_028](https://cloud.githubusercontent.com/assets/1326120/9742670/b497885a-562f-11e5-8353-c0907b44a4bc.png)

**Comment by luchia** [comment]
Fixed, I need Michael to make this toggle-able when you click the ! in the navigation. It should be hidden by default. PR waiting to be merged.

![screen shot 2015-09-09 at 9 23 22 am](https://cloud.githubusercontent.com/assets/4547737/9750258/7bdbf3fc-56d4-11e5-8ae1-a3bd67bbf363.png)

**Comment by romichg** [comment]
I can't say I am in love with the solution. I think making the user hit "!" to bring this up is not the best idea. The main nav menu is for primary functions. This is really a secondary, feedback function. I am not sure it belongs in the main nav. Also it needs an icon. "!" means nothing to me. We also lost our progress wheel as a result.  I think we need more brainpower on this one :)

**Comment by luchia** [comment]
It don't think it matters that we lost the wheel because we are having a loading bar anyway. What about something more simple, that doesn't involve toggling?

![screen shot 2015-09-10 at 8 22 34 pm](https://cloud.githubusercontent.com/assets/4547737/9786510/b351863c-57f9-11e5-9fc3-0ccbab7982d9.png)

**Comment by romichg** [comment]
Looks much better. once the double scroll is fixed should be good.

**Comment by luchia** [comment]
Yeah, I'm waiting for Dinis to get back to me so I can finish this.

**Comment by romichg** [comment]
Has this happened?

**Comment by luchia** [comment]
Yup, he got back to me late last night. This is fixed.

**Comment by romichg** [comment]
Ok, the only thing is that the lines are misaligned when it breaks into to lines. 
![selection_050](https://cloud.githubusercontent.com/assets/1326120/9837162/68b78aba-5a04-11e5-94ef-1feb43aa58c6.png)

**Comment by luchia** [comment]
I fixed this one -

![screen shot 2015-09-15 at 8 45 14 am](https://cloud.githubusercontent.com/assets/4547737/9863768/3a1f2c52-5b86-11e5-9cd0-64ab627cf405.png)

**Comment by romichg** [comment]
Yep done.
