### ISSUE TITLE
Metadata text is misalligned 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#963]
![selection_015](https://cloud.githubusercontent.com/assets/1326120/9669600/432a1f52-5256-11e5-9315-0964f31aa06a.png)

**Comment by luchia** [comment]
PR submitted

**Comment by romichg** [comment]
Needs more TLC. The top one is off by one char.  Also perhaps we should move it closer to the icons.

![selection_037](https://cloud.githubusercontent.com/assets/1326120/9773029/e5466ef6-570d-11e5-9714-b8a312c72323.png)

**Comment by luchia** [comment]
Hmm, I'm not sure why yours is out of line? Are you still seeing it with the new stuff I pushed?

![screen shot 2015-09-10 at 1 20 37 pm](https://cloud.githubusercontent.com/assets/4547737/9783972/65b3c79e-57e7-11e5-9654-fd1ac74ac313.png)

**Comment by romichg** [comment]
Looks good now actually. Closing.
