### ISSUE TITLE
Share badge seems like its using a different font

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#964]
![selection_014](https://cloud.githubusercontent.com/assets/1326120/9669614/54f3d4bc-5256-11e5-819d-de1cd9466276.png)

**Comment by luchia** [comment]
Hmmm...

**Comment by luchia** [comment]
![screen shot 2015-09-04 at 11 07 33 am](https://cloud.githubusercontent.com/assets/4547737/9674507/2bfaa190-52f5-11e5-9f94-2025f5a1dbbc.png)

Fixed.

**Comment by luchia** [comment]
PR submitted

**Comment by romichg** [comment]
Text is still misaligned to the symbol. This needs some more TLC.
![selection_036](https://cloud.githubusercontent.com/assets/1326120/9772990/9b5bcb10-570d-11e5-8b3a-0e379aacc64f.png)

**Comment by luchia** [comment]
![screen shot 2015-09-10 at 6 10 03 pm](https://cloud.githubusercontent.com/assets/4547737/9783942/2ee09d82-57e7-11e5-9746-c51277eb6ce6.png)

I think I fixed the issue :)

**Comment by romichg** [comment]
I am gonna get really picky here, but now it seems like its not centered.

**Comment by luchia** [comment]
I hacked this to fix it. Padding is all uneven to make the button appear even -

![screen shot 2015-09-11 at 7 47 05 pm](https://cloud.githubusercontent.com/assets/4547737/9812696/2b9b388a-58be-11e5-9da7-5281af7068c9.png)

**Comment by romichg** [comment]
Is that merged?  I don't see it?

**Comment by luchia** [comment]
Yup -

![screen shot 2015-09-12 at 10 32 54 am](https://cloud.githubusercontent.com/assets/4547737/9829189/a7322c94-5939-11e5-83ed-71126f84614a.png)

**Comment by romichg** [comment]
Something still seems off.. .can you please put your 100% designer attention to it?

**Comment by luchia** [comment]
> seems like text is too far to the right form the < sign and also that the < sign is aligned with the bottom of the text.

I think I've fixed this -

![screen shot 2015-09-15 at 10 44 09 am](https://cloud.githubusercontent.com/assets/4547737/9865254/089b8a5c-5b97-11e5-8dd4-ebb040625982.png)
![screen shot 2015-09-15 at 10 44 14 am](https://cloud.githubusercontent.com/assets/4547737/9865255/089e0c32-5b97-11e5-901f-63e54c323ef3.png)

**Comment by romichg** [comment]
Alright looks good. now we just need it to do something :)
