### ISSUE TITLE
Make sure customizations and SSO  still work with flare/jade switch

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#970]

**Comment by romichg** [comment]
Related to #974

**Comment by DinisCruz** [comment]
this is not that simple

**Comment by romichg** [comment]
Um..this one I kinda think should fall under the 3 year unconditional warranty :). SSO has been part of TM for  a long time. Let me know what needs to be done to make this work and the level of effort on your part.

**Comment by DinisCruz** [comment]
ok, we need more detail on this one:

What exactly needs to be working? 

Are the SSO and customisations working as expected for Jade?

What are the SSO urls that we need to support?

Do we have the design for the user's customisation needed?

**Comment by romichg** [comment]
This issue was to make sure that if a user logs in with SSO, they are properly redirected to jade or flare based on their browser. This is working. The rest of this issue is covered in #974. @DinisCruz please give @michaelhidalgo a hand when he is working on that issue.
