### ISSUE TITLE
TM Logo shrinks with browser size

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#973]
When you make the browser size smaller, The logo shrinks. 

![selection_032](https://cloud.githubusercontent.com/assets/1326120/9774050/15070de8-5714-11e5-896c-8e455d69eddd.png)

**Comment by luchia** [comment]
![screen shot 2015-09-10 at 6 14 04 pm](https://cloud.githubusercontent.com/assets/4547737/9784030/be2a5078-57e7-11e5-9549-f4635e91034f.png)
![screen shot 2015-09-10 at 6 14 07 pm](https://cloud.githubusercontent.com/assets/4547737/9784032/be58a716-57e7-11e5-9f97-14eee882452f.png)

Hey, I made it a fixed width (pixels) instead. It was initially a % based width so it was responsive.

**Comment by romichg** [comment]
Ok so this seems to now have an effect that logo is fixed up until a certain browser size and then gets bigger after about 1960 pixels of the browser. Is that on purpose? I think its fine. Why is @DinisCruz assigned for this one?

**Comment by luchia** [comment]
Yes because otherwise it needs to be percentage-based and we have the problem of the original issue. Assigned Dinis by mistake.

**Comment by romichg** [comment]
ok cool closing
