### ISSUE TITLE
Terms and conditions link does not work 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#977]
Both on the bottom footer, signup and on the article view page.

**Comment by DinisCruz** [comment]
link on bottom of the articles is now fixed (In Flare)

![image](https://cloud.githubusercontent.com/assets/656739/9819631/0dea4004-58a7-11e5-933f-c1d66af8cbf2.png)

it opens

![image](https://cloud.githubusercontent.com/assets/656739/9819639/199c4b9a-58a7-11e5-88ac-855a68a9c3e0.png)

Link on non-logged in page 

![image](https://cloud.githubusercontent.com/assets/656739/9819742/baa43480-58a7-11e5-8181-71f8df133a90.png)

goes to 

![image](https://cloud.githubusercontent.com/assets/656739/9819769/d834f200-58a7-11e5-8195-76ca863c5660.png)

**Comment by luchia** [comment]
Thank you Dinis.

**Comment by romichg** [comment]
Looks good, thanks!
