### ISSUE TITLE
Cross-Site Scripting not shown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#978]
https://tmdev01-beta.teammentor.net/angular/user/index?query=search-cross-site&filters=query-5119877f960f,query-132f0cf22c47

would be expected to show cross-site scripting along with cross-site request forgery, but it is not shown.

**Comment by DinisCruz** [comment]
can you try now, it looks like those results are there (just not showing up enough in the searches)

![image](https://cloud.githubusercontent.com/assets/656739/10058631/6c2ff24e-623e-11e5-869b-a8907e68537e.png)

![image](https://cloud.githubusercontent.com/assets/656739/10058647/87ce11de-623e-11e5-8a98-3353c6ee18bc.png)

**Comment by romichg** [comment]
Still a problem. 
Search for cross-site, select Vulnerability as a filter. Only CSRF articles are shown. 

![selection_001](https://cloud.githubusercontent.com/assets/1326120/10077720/85d30120-62af-11e5-9c24-363f17fa5b65.png)

However I can easily Navigate to XSS articles. Select Vulnerabilities on the right, select vulnerabilities on the left, scroll down to cross site scripting

![selection_002](https://cloud.githubusercontent.com/assets/1326120/10077748/a05614c4-62af-11e5-96e3-02804bd35976.png)

**Comment by DinisCruz** [comment]
this is what you get now with the 'cross-site' search

![image](https://cloud.githubusercontent.com/assets/656739/10683170/e892b984-7936-11e5-9ef1-440088591a03.png)

**Comment by romichg** [comment]
Still missing the "Cross-Site Scripting" article
![selection_005](https://cloud.githubusercontent.com/assets/1326120/10684945/3ffe2c28-7921-11e5-8286-641b5bf97262.png)

This article is feeling left out of the whole "cross-site" thing.

![selection_006](https://cloud.githubusercontent.com/assets/1326120/10684951/558d3f20-7921-11e5-9f4f-d0cf45cc72ea.png)

**Comment by romichg** [comment]
This is fixed.
