### ISSUE TITLE
Icon for AWS Technology

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#979]
We need an Icon for AWS (Amazon Web Services)

**Comment by luchia** [comment]
I think we should use the box from the AWS logo. What does everyone think?

![screen shot 2015-09-15 at 11 34 33 am](https://cloud.githubusercontent.com/assets/4547737/9865763/d3232982-5b9d-11e5-92fc-10038b9e77c9.png)

**Comment by romichg** [comment]
Looks good. I like it.

**Comment by luchia** [comment]
Cool, this is in Flare now but needs to be wired.

**Comment by romichg** [comment]
There is no AWS content yet, but it should pick it up once there is right?

**Comment by luchia** [comment]
Should do, I think Dinis wired it so it reads the name of the icon and matches it to the filter name.

**Comment by romichg** [comment]
Ok cool.. Then closing this one.

**Comment by romichg** [comment]
Looks like AWS icon is not working. @michaelhidalgo can you double check, icon should be in there.

**Comment by michaelhidalgo** [comment]
This one was fixed here https://github.com/TeamMentor/TM_4_0_Design/issues/1108

**Comment by romichg** [comment]
This is done.
