### ISSUE TITLE
Flicker on Jade Features page 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#98]
Is happening on Chrome OSX with the landing page currently at /landing-pages/features.html

Here is an animated gif showing the prob (created using QuickTime screen recorder and ```ffmpeg -i TM-Features-bug.mov -t 20 TM.gif```)

![tm](https://cloud.githubusercontent.com/assets/656739/5363282/a9448388-7fd2-11e4-8fd7-282a14b7b51b.gif)

**Comment by roman87** [comment]
This one was not assigned to anyone ether. It seems that it is fixed. I don't see it anymore. @DinisCruz can you reproduce it?

**Comment by DinisCruz** [comment]
Yeah, this is fixed on the latest version , so closing it
