### ISSUE TITLE
Mobile seems to break on a shorter browser

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#980]
![selection_052](https://cloud.githubusercontent.com/assets/1326120/9837340/6f7c75cc-5a09-11e5-8de2-ab55b8c19598.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-09-15 at 11 06 49 am](https://cloud.githubusercontent.com/assets/4547737/9865498/a18ef192-5b9a-11e5-9187-33629e87c7f5.png)

**Comment by romichg** [comment]
Related to #981 will close them together when done.

**Comment by luchia** [comment]
Related issue has been fixed, assigning to you.

**Comment by romichg** [comment]
Fixed. looks good.
