### ISSUE TITLE
Empty white space on the mobile browser when nothing on the lefthand side menu

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#981]
Can we collapse the white space?
![selection_051](https://cloud.githubusercontent.com/assets/1326120/9837346/9ac37f14-5a09-11e5-91b0-1b606955a14e.png)

**Comment by luchia** [comment]
This has been fixed -

![screen shot 2015-09-15 at 8 26 07 am](https://cloud.githubusercontent.com/assets/4547737/9863465/910278f6-5b83-11e5-88ea-e8f1954b67be.png)
![screen shot 2015-09-15 at 8 26 20 am](https://cloud.githubusercontent.com/assets/4547737/9863466/9106938c-5b83-11e5-889e-916dc696c519.png)

**Comment by romichg** [comment]
Seems like its not working the way it is in sshots above.  The top is missing from the lefhandside filters.

![selection_060](https://cloud.githubusercontent.com/assets/1326120/9886868/8b76c536-5bba-11e5-83a4-ef3114c38d6b.png)

Also, is it possible, in mobile view, to move "found and issue" and breadcrumbs all the way up top, just below the search bar?

**Comment by romichg** [comment]
Also, I think as a result of this, the full article view in mobile is messed up. So check that when you fix this.

**Comment by luchia** [comment]
I don't see any issues on the article view -

![screen shot 2015-09-17 at 7 10 51 am](https://cloud.githubusercontent.com/assets/4547737/9918641/4921ff0a-5d0b-11e5-892d-ce687b2d83c4.png)
![screen shot 2015-09-17 at 7 10 54 am](https://cloud.githubusercontent.com/assets/4547737/9918642/4956d32e-5d0b-11e5-8ad9-63005ef9d825.png)

And I fixed the ordering too -

![screen shot 2015-09-17 at 8 00 58 am](https://cloud.githubusercontent.com/assets/4547737/9919761/49900fc0-5d12-11e5-89ff-46b99263163f.png)

**Comment by romichg** [comment]
Looks good, closing this one.
