### ISSUE TITLE
Guides View Issues

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#982]
- [x] Share button is different between the guides and full article view
  ![selection_057](https://cloud.githubusercontent.com/assets/1326120/9837459/81cd0b5c-5a0d-11e5-9121-d1c11aa6e5b7.png)
  ![selection_055](https://cloud.githubusercontent.com/assets/1326120/9837461/83f896c6-5a0d-11e5-99fa-66752b6dfaac.png)
- [x] Should we make the Gray line a bit narrower, both for Guides and full article view? what do you think?
- [x] Guide articles should have the "Guide" Badge, remember how we originally though it should look like?

**Comment by luchia** [comment]
The first one should be fixed, that was an error with the code from when Michael and I were working on CC (before I had fixed the Share button issue). 

The second can be done, but I wanted to show how uneven it does make the screen -

![screen shot 2015-09-15 at 8 48 56 am](https://cloud.githubusercontent.com/assets/4547737/9863813/d623aee8-5b86-11e5-98bf-46750dadecf3.png)
![screen shot 2015-09-15 at 8 50 26 am](https://cloud.githubusercontent.com/assets/4547737/9863814/d626b9ee-5b86-11e5-8fa5-bfee53ca6992.png)

It looks okay, but I'd prefer if we stick to the grid. At least it looks uniform then. I think on CC it could be smaller but then again, we run into problems when the screen gets smaller -

##### CC view

![screen shot 2015-09-15 at 8 51 49 am](https://cloud.githubusercontent.com/assets/4547737/9863841/0e0fb914-5b87-11e5-85f4-48e9d7f08256.png)

##### Usual view

![screen shot 2015-09-15 at 8 51 57 am](https://cloud.githubusercontent.com/assets/4547737/9863842/0e13921e-5b87-11e5-981d-065172ca8ae9.png)

If you can live with that, then I can change it. But I think it looks messy and like we added the bar in as an afterthought.

The third point has been fixed/added into the template. But I will need Dinis/Michael to wire up whether the icon shows or not.

![screen shot 2015-09-15 at 8 57 04 am](https://cloud.githubusercontent.com/assets/4547737/9863920/c155b334-5b87-11e5-91ab-6d2e299e106c.png)

**Comment by romichg** [comment]
Yea I am not sure about the narrow line.. @michaelhidalgo what do you think? @luchia can you merge it so we can see how it looks on our browsers, with an understanding that we might want to bring it back to how it is now.

**Comment by luchia** [comment]
Sure, it's in my PR today.

**Comment by luchia** [comment]
Finished for the moment, as per our call this morning.

**Comment by romichg** [comment]
Looks good. See my comments on #1005  closing this one.
