### ISSUE TITLE
Wire Share Button popup

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#985]
#

**Comment by DinisCruz** [comment]
what should happen when the user click on it?

**Comment by DinisCruz** [comment]
@luchia can you put a reference to here on the location of the flare component

**Comment by luchia** [comment]
What it should look like -
![screen shot 2015-09-24 at 8 49 42 am](https://cloud.githubusercontent.com/assets/4547737/10061130/85862bb8-6299-11e5-8918-5d8e9de6081c.png)

And you can find it in Flare/components/user/modal.jade
![screen shot 2015-09-24 at 8 50 09 am](https://cloud.githubusercontent.com/assets/4547737/10061131/8588e10a-6299-11e5-91a6-b22de19600ff.png)

**Comment by romichg** [comment]
@DinisCruz can you make the share button work as specified

**Comment by romichg** [comment]
assigning to @michaelhidalgo

**Comment by michaelhidalgo** [comment]
With Pull Request, branch Issue_1063_LoginMessage

**Comment by romichg** [comment]
You mean this branch :) Issue_985_ShareButton

**Comment by romichg** [comment]
Ok looks and works good. One major point:
- [ ] It needs to work in the guides as well :)

And couple of smaller points. If they are easy lets fix them if not lets leave them for later:
- [ ] Can we make the gray box a big thinner. It feels like it occupies too much space. 
- [ ] Can we get rid of the little share icon to the right of "SHARE THIS ARTICLE" it just seems redundant
  ![selection_001](https://cloud.githubusercontent.com/assets/1326120/10679306/c87e4c2c-78e5-11e5-833d-fe6416f9a34d.png)
- [ ] Can we make it so that when the green label pops up and says that "Article link copied to clipboard" it doesn't make the gray box bigger
  ![selection_002](https://cloud.githubusercontent.com/assets/1326120/10679324/e451643e-78e5-11e5-9213-b42ce0ebf1fe.png)

**Comment by romichg** [comment]
There is also an interesting issue in IE:
- [ ] - 

![selection_001](https://cloud.githubusercontent.com/assets/1326120/10680369/10800748-78ed-11e5-9ae0-2f71205236c7.png)
I wonder if there are special perms we need to pass. Like we only want to write to the clipboard and not read. Anyways. this can also be fixed later.

**Comment by michaelhidalgo** [comment]
Pull Request https://github.com/TeamMentor/TM_Static/pull/95

**Comment by romichg** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/1326120/10707321/c77be472-79be-11e5-93f9-9500cfac93b0.png)

**Comment by romichg** [comment]
This is done. There is a small follow up UI issue which is tracked here #1083
