### ISSUE TITLE
The heart icon isn’t intuitive for the guide. Maybe an open book?

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#986]
this needs to change both on the nav and the badge on the gray line in guides.

**Comment by luchia** [comment]
This has been changed. It's in my PR today -

![screen shot 2015-09-16 at 8 58 47 am](https://cloud.githubusercontent.com/assets/4547737/9892338/31860798-5c51-11e5-88ab-d08709c9c3af.png)
![screen shot 2015-09-16 at 8 59 11 am](https://cloud.githubusercontent.com/assets/4547737/9892340/3a553c7c-5c51-11e5-99a2-c751dba78c4c.png)

**Comment by romichg** [comment]
Looks good. I like it.
