### ISSUE TITLE
The profile icons isn’t intuitive

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#989]
The profile icons isn’t intuitive, since you don’t have any profile features in place yet. Probably a search icon (e.g. magnifying glass) would make more sense at the momen

**Comment by luchia** [comment]
Changed to a bookmark (there are stored/saved searches in there, so I thought it made sense). I don't think it's a good idea to have two search icons in the same place. In my PR today -

![screen shot 2015-09-16 at 8 58 47 am](https://cloud.githubusercontent.com/assets/4547737/9892354/5b10f74e-5c51-11e5-8996-b3a66cd3b59f.png)

**Comment by romichg** [comment]
Good stuff, I like this one as well.
