### ISSUE TITLE
The i icon doesn’t scream help to me and since the UI is so much like the guide 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#990]
had to click both a few times to tell the difference - oh yeah that’s the docs! I think the this could be made more intuitive. Maybe a question mark?

**Comment by luchia** [comment]
Changed to a question mark. In my PR today -

![screen shot 2015-09-16 at 8 58 47 am](https://cloud.githubusercontent.com/assets/4547737/9892357/64b250d6-5c51-11e5-80a4-e5c139121c53.png)

**Comment by romichg** [comment]
Looks good!!!
