### ISSUE TITLE
Can you add popups for the icons? For instance I clicked the ‘power’ icon on far right and was surprised to be logged out. 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#992]

**Comment by luchia** [comment]
Yup, these are tooltips and need to be added by Dinis/Michael with JS. This is a duplicate of #1002.

**Comment by luchia** [comment]
So we have title tags on the nav at the moment and most icons -

![screen shot 2015-09-17 at 9 07 21 am](https://cloud.githubusercontent.com/assets/4547737/9920909/96cf4e6e-5d1b-11e5-8b64-0f237cb7e0e7.png)
![screen shot 2015-09-17 at 9 07 24 am](https://cloud.githubusercontent.com/assets/4547737/9920910/96d61938-5d1b-11e5-880e-bd26700b29e5.png)
![screen shot 2015-09-17 at 9 07 26 am](https://cloud.githubusercontent.com/assets/4547737/9920911/96d702c6-5d1b-11e5-89ff-908fca1abd69.png)
![screen shot 2015-09-17 at 9 07 29 am](https://cloud.githubusercontent.com/assets/4547737/9920912/96da7c26-5d1b-11e5-8671-1bfd230c20b9.png)
![screen shot 2015-09-17 at 9 07 31 am](https://cloud.githubusercontent.com/assets/4547737/9920913/96dde99c-5d1b-11e5-9546-65adc5b844b9.png)

But we really do need Michael/Dinis to do them properly with JS so they come up quicker.

**Comment by romichg** [comment]
I don't see tags working on nav icons though.. make sure they are there then assign to @DinisCruz along with #1001

**Comment by DinisCruz** [comment]
this will be solved by https://github.com/TeamMentor/TM_4_0_Design/issues/1001, I think we should close this issue and track it on #1001

**Comment by romichg** [comment]
Agreed closing as dupe.
