### ISSUE TITLE
Angular version of the error page

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#995]
when redirecting to the error page, jade version is automatically selected. There should be an angular version of the error page, with appropriate menu

**Comment by luchia** [comment]
Hey Michael, I added a page for you in views/user/ called error.jade. It has the alert mixins in there already. It's in my PR today.

**Comment by DinisCruz** [comment]
I just pushed a number of fixes for this.

Now there is browser detection for '/error' and normal angular errors will be shown this page

![image](https://cloud.githubusercontent.com/assets/656739/10499429/38d7154a-72c8-11e5-9b5e-ac0aa0ece2ca.png)

**Comment by romichg** [comment]
This is done. Thank you!
