### ISSUE TITLE
gray column next to article box changes size with single/double column of boxes

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#996]
This has been an issue for a while...

**Comment by luchia** [comment]
The width is fixed so it shouldn't be doing this anymore. Can you show me a photo? This is what the single column and grid look like for me (they're the same width) -

![screen shot 2015-09-16 at 8 30 18 am](https://cloud.githubusercontent.com/assets/4547737/9891923/64e72846-5c4d-11e5-87e2-bf816e0e54c5.png)

**Comment by romichg** [comment]
This is fixed! d
