### ISSUE TITLE
When URL has a guid that doesn't exist, blank page is shown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#997]
https://tmdev01-beta.teammentor.net/angular/user/article/c4914e51-2609-4edc-8133-31491f1b03c1

For example.

**Comment by DinisCruz** [comment]
ok, here is what is now shown when the article cannot be resolved from the provided ID

![image](https://cloud.githubusercontent.com/assets/656739/10001952/4c9d0672-609c-11e5-9f0b-cb3156fee7e4.png)

Is that text ok, if not, put here the desired text

**Comment by romichg** [comment]
Well, we shouldn't really have a share button there nor a comment button :). In fact we should have a generic "Page not found" instead of article not found. As I think this is shown for any page that is not found. like https://tmdev01-beta.teammentor.net/angular/user/searchblah

**Comment by DinisCruz** [comment]
I don't think we should change the link, since that will be confusing for the user, and in fact the comment button is very relevant (the share is not  :)  )

**Comment by romichg** [comment]
Nothing to do with changing the link. This page is shows not only when the article cannot be found, but when any error condition is met. For example a search page  with querries cannot be found. Thats why the "Article Not Found" is not always appropriate. As well as "Have a comment about this article" is not appropriate ether.

**Comment by romichg** [comment]
Related to #995

**Comment by DinisCruz** [comment]
I believe this is now addressed with the fix for https://github.com/TeamMentor/TM_4_0_Design/issues/995

**Comment by DinisCruz** [comment]
http://localhost:12345/angular/user/article/c4914e51-2609-4edc-8133-31491f1b03c1 will now redirect to http://localhost:12345/angular/user/error

**Comment by romichg** [comment]
This is done!
