### ISSUE TITLE
"Guide" Icon/Badge should be shown in the Guide view as well and should only be showin if the article is a "Guide"

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#998]

**Comment by luchia** [comment]
Cool, can we assign this one to Dinis or Michael? I'm going to need them to wire it so that it shows only on articles in the Security Guide. I've added the icon to the article-info column.

**Comment by luchia** [comment]
As per our meeting this morning, I have commented out this line of writing so it doesn't affect all articles. Michael/Dinis need to wire this so it shows only on articles that are a part of the guide. 

For reference, you can find this line in mixins/articles-mixins.jade. Then, you'll need look at the mixin article-metadata.

**Comment by romichg** [comment]
Still is shown on all articles...

**Comment by luchia** [comment]
It's hidden now, assigning to Dinis.

**Comment by romichg** [comment]
This is fixed.
